### ISSUE TITLE
FTB backups ignoring max backups to keep

### ISSUE THREAD

**Issue by Ll0m0** [FTBTeam/FTB-Mods-Issues#1]
I am currently running a mineshafts and monsters server for my friends, and I notice that FTB backups is ignoring the max backups to keep line in the config. Despite it being set to = 1, it keeps creating new backups and not clearing older backups. I edited the config while the server was offline and saved it before starting the server and the changes were still ignored.

**Comment by MichaelHillcox** [comment]
Mod version please :+1:

**Comment by Ll0m0** [comment]
FTB backups 2.1.1.6

**Comment by MichaelHillcox** [comment]
Should be fixed now
