### ISSUE TITLE
[Bug]: Manual Pump Texture Wrong at 4 Minutes Wound

### ISSUE THREAD

**Issue by Jkosio23** [FTBTeam/FTB-Mods-Issues#100]
### Mod

FTB Sluice

### Mod version

ftb-sluice-forge-1.0.6-build.20

### Forge / Fabric version

1.16.5 36.2.8

### Modpack & version

FTB OceanBlock 1.5.0

### What issue are you having?

The bar that shows winding progress on the face that the water is pumped out of through ticks up each minute until 3:59 and when going to 4:00 it goes blank instead of filling in the 5th tick on the charge bar.

### Steps to reproduce

1. Place Manual pump above infinite water source.
2. Start winding it
3. Watch the charge bar.

**Comment by MichaelHillcox** [comment]
Interesting, I'll look into this, sluice will be having an update soon anyway

**Comment by MichaelHillcox** [comment]
Fixed this and it should show in the next pack release
