### ISSUE TITLE
[Bug]: Tooltip is still slightly rendered when right-clicking Item.

### ISSUE THREAD

**Issue by FooterMan15** [FTBTeam/FTB-Mods-Issues#1001]
### Mod

FTBQ

### Mod version

1902.5.6-build.304

### Forge / Fabric version

Forge - 43.2.21

### What issue are you having?

Right clicking on Items in a Quest still renders part of the Tooltip.
This might just be an issue with whatever mod adds the part that is showing, but I don't know. Seems weird to have the tooltip still working while a different menu is open in the first place.

https://github.com/FTBTeam/FTB-Mods-Issues/assets/71946346/83fc520a-5084-4fad-b656-1537b7cf1f63

### Steps to reproduce

Make a Quest with an item.
Right click on item.

**Comment by FooterMan15** [comment]
Alright, I'll figure out what mod is doing that. If I found it, should I go to it's dev or here?

**Comment by desht** [comment]
It might need a little cross-mod communication, so probably best to mention it in both places.

**Comment by FooterMan15** [comment]
I have found the mod, it is Quark ^^
