### ISSUE TITLE
[Bug]: Crash when inserting a quest

### ISSUE THREAD

**Issue by MrHimera** [FTBTeam/FTB-Mods-Issues#1004]
### Mod

FTB Quests

### Mod version

ftb-quests-forge-2001.1.7

### Forge / Fabric version

Forge 1.20.1 47.2.1

### What issue are you having?

If any text line was copied to the clipboard before pressing paste quest (Ctrl + V), the game crashes. There is no such problem with any copied file. Below I attached an error when there was a text string "Test".

### Crashlogs

https://hastebin.com/share/tecacuhefu.css

### Steps to reproduce

1. Copy any text string
2. Enter the quest field
3. Press Ctrl + V

**Comment by desht** [comment]
Fixed in 2001.2.0 release
