### ISSUE TITLE
[Bug]: FTB Essentials non-deterministically ignores settings in FTB Ranks

### ISSUE THREAD

**Issue by ChristopherJTrent** [FTBTeam/FTB-Mods-Issues#1009]
### Mod

FTB Ranks / FTB Essentials

### Mod version

ftb-ranks-forge-2001.1.4, ftb-essentials-forge-2001.2.1

### Forge / Fabric version

Forge 47.1.3 MC 1.20.1

### Modpack & version

All the Mods 9 0.2.19

### What issue are you having?

I have a server running for me and a couple friends, so I wanted to disable the cooldown for the various FTBEssentials commands.
I did so by adding the following to my world/serverconfig/ftbranks/ranks.snbt:
```
{
	member: {
		name: "Member"
		power: 1
		condition: "always_active"
		ftbessentials.home.cooldown: 0
		ftbessentials.home.max: 10
		ftbessentials.back.max: 4
		ftbessentials.spawn.cooldown: 0
		ftbessentials.tpa.cooldown: 0
		ftbessentials.rtp.cooldown: 0
		ftbessentials.back.cooldown: 0
		command.ftbteams: true
	}
	vip: {
		name: "VIP"
		power: 50
		ftbranks.name_format: "&bVIP {name}"
		ftbessentials.home.cooldown: 0
		ftbessentials.home.max: 10
		ftbessentials.back.max: 4
		ftbessentials.spawn.cooldown: 0
		ftbessentials.tpa.cooldown: 0
		ftbessentials.rtp.cooldown: 0
		ftbessentials.back.cooldown: 0
	}
	admin: {
		name: "Admin"
		power: 1000
		condition: "op"
		ftbranks.name_format: "&2{name}"
		ftbessentials.home.cooldown: 0
		ftbessentials.home.max: 10
		ftbessentials.back.max: 4
		ftbessentials.spawn.cooldown: 0
		ftbessentials.tpa.cooldown: 0
		ftbessentials.rtp.cooldown: 0
		ftbessentials.back.cooldown: 0
	}
}
```

Now I occasionally see the cooldown message for /home without any rhyme or reason to the timing of it, even though I have redundantly disabled said cooldown.

### Steps to reproduce

I use /home
I use /home again
Sometimes it complains about a cooldown, sometimes it doesn't, but if it complains once, I have to wait out the cooldown regardless, even if I restart the server.
It happens more often (but not exclusively) if I use /home immediately after logging in.

**Comment by desht** [comment]
I'm not able to reproduce this problem, I'm afraid. I've configured FTB Ranks with the same setup as you have above, and tested with both an op and non-op player, and I never see the cooldown message.
