### ISSUE TITLE
[Feature Request]: Command to create/remove waypoints for players

### ISSUE THREAD

**Issue by TheonlyTazz** [FTBTeam/FTB-Mods-Issues#1010]
### Mod

FTB Chunks

### Description

Make it possible for players to use a command to place down waypoints (and also remove them)

this would allow clickEvents in text to be able to place down waypoints (usable for quests) as they can only run commands.
this needs to have permission(0) as clickEvents respect the players permission

### Describe the solution you'd like

I created a mockup version of this for FTB Genesis with KubeJS which works on Singleplayer, but not on Server

### Describe alternatives you've considered

I'd fix my issue in KubeJS, but i got told to request a proper implementation

**Comment by desht** [comment]
Which modpacks (or more importantly Minecraft versions) will this be needed for?

**Comment by UnRealDinnerbone** [comment]
This feature has been added https://github.com/FTBTeam/FTB-Chunks/commit/7bde1b41ff826f6a604dac4b71308936b94ed19f
