### ISSUE TITLE
[Feature Request]: Quest Chapter Center

### ISSUE THREAD

**Issue by MrHimera** [FTBTeam/FTB-Mods-Issues#1012]
### Mod

FTB Quests

### Description

Is it possible to make sure that when opening a quest chapter, the center of the quest field is directed to a specific quest specified in the settings of this chapter?

**Comment by desht** [comment]
So when you change the selected chapter via the gui, you want the display centered on a specific quest in that chapter?

Just centered, not actually opening the quest view panel?

**Comment by MrHimera** [comment]
> So when you change the selected chapter via the gui, you want the display centered on a specific quest in that chapter?

Yes
