### ISSUE TITLE
[Bug]: quest not detecting planks correctly tagged

### ISSUE THREAD

**Issue by Abalieno** [FTBTeam/FTB-Mods-Issues#1015]
### Mod

FTB Quests

### Mod version

ftb-quests-fabric-1902.5.6-build.304

### Forge / Fabric version

1.19.2 fabric 14.24

### Modpack & version

Gregorian Nightmares

### What issue are you having?

![yikluilou](https://github.com/FTBTeam/FTB-Mods-Issues/assets/4656436/98cd3aa3-500f-4993-857c-d37746df63c7)

![iloul66](https://github.com/FTBTeam/FTB-Mods-Issues/assets/4656436/08729987-c721-4e2a-9196-ab4f2aa6c694)

I have tried multiple times, even exiting and relogging.

I can't complete that quest asking for any plank. Despite the plank being tagged correctly.

It works with vanilla planks. The tag is being ignored for some reason.

### Steps to reproduce

1- Craft planks for the plank quest.
2- Quest not getting completed as it should.

**Comment by Abalieno** [comment]
![yukuilou](https://github.com/FTBTeam/FTB-Mods-Issues/assets/4656436/83802af9-3f8f-4ee3-80ab-2c87c002c0e1)

I have no idea how this happened.

I didn't write the title. So maybe it's worth looking into, even if I figured it out.

**Comment by Emkave** [comment]
> ![yukuilou](https://private-user-images.githubusercontent.com/4656436/285579028-83802af9-3f8f-4ee3-80ab-2c87c002c0e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU2NzA4MjYsIm5iZiI6MTczNTY3MDUyNiwicGF0aCI6Ii80NjU2NDM2LzI4NTU3OTAyOC04MzgwMmFmOS0zZjhmLTRlZTMtODBhYi0yYzg3YzAwMmMwZTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIzMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMzFUMTg0MjA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWE1OGVkMmExMjE0MTU4YmIzZjY0OTMwODI1YWMzM2Y4ZGFiYTE2MmIxZGVkZDczMThlZmEwYWU5MDFkM2YzMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.4xM1RwjBAjhfbt81AErHJcY1hVqEKpkA5XSrs3o_WbM)
> 
> I have no idea how this happened.
> 
> I didn't write the title. So maybe it's worth looking into, even if I figured it out.


How did you figure it out? How did you solve the issue?

**Comment by Abalieno** [comment]
It's just a mismatch, whatever is written in the title is arbitrary, it doesn't mean much.

You just needs to make sure the item requested in the quest IS a tag, rather than a specific item.
