### ISSUE TITLE
[Feature Request]: Update to 1.20.1

### ISSUE THREAD

**Issue by auroraanna** [FTBTeam/FTB-Mods-Issues#1017]
### Mod

FTB Industrial Contraptions

### Description

FTB Industrial Contraptions does not run on the latest major version of Minecraft (1.20) but I would like to play it on that version.

### Describe the solution you'd like

Release an update of the mod so that it works on Minecraft 1.20.1 e.g.

### Describe alternatives you've considered

Restarting my world in 1.19 (the current supported version by this mod)

**Comment by MichaelHillcox** [comment]
It has not yet been ported but I think there are some plans to do so, either way, gunna close this as it's not an issue.
