### ISSUE TITLE
[Bug]: FTB Chunks not force loading when on dedicated server

### ISSUE THREAD

**Issue by ElderBarrySirUp** [FTBTeam/FTB-Mods-Issues#1018]
### Mod

FTB Chunks

### Mod version

ftb-chunks-forge-2001.2.3

### Forge / Fabric version

1.20

### Modpack & version

FTB DW20 1.20 1.7.0

### What issue are you having?

FTB Chunks not force loading when on dedicated server. 

### Steps to reproduce

Claim Chunks. Force Load Chunks. Leave area or disconnect from server. Return to find no progress continued.

**Comment by MichaelHillcox** [comment]
Do you have chunk loading set to enabled for when no one on the team is online / the leader of the party isn't online?

**Comment by Urhas** [comment]
I am having this issue as well with ftb-chunks-forge-2001.2.3 on FTB DW20 1.20 1.8.0. 
On my side I set force_load_mode to always in world\serverconfig\ftbchunks-world.snbt but when the server launches it changes the config setting back to default.

**Comment by MichaelHillcox** [comment]
Are you on a modpack?

**Comment by Urhas** [comment]
Yes it was the Direwolf20 1.20 pack version 1.8.0. Any time I edit the  world\serverconfig\ftbchunks-world.snbt file and launch the server, that config file resets back to default during the preparing world part of the server startup. I am not sure if it is caused by the mod or the pack configuration but I did figure out a workaround for it. 

I deleted world\serverconfig\ftbchunks-world.snbt then edited ftbchunks-world.snbt in defaultconigs/ftbchunks to add {force_load_mode: "always"}. On server launch it recreated the config but created with the always value.

**Comment by MichaelHillcox** [comment]
Oh, very interesting, thanks for letting us know, we'll look into this as this is likely effecting a good few modpacks. Likely some issue with the defaultconfigs system

**Comment by desht** [comment]
Just installed a DW20 1.20.1 pack via serverinstaller (https://api.modpacks.ch/public/modpack/119/11393/server/linux) 
* Changed `force_load_mode` to "always" in world/serverconfig/ftbchunks-world.snbt
* Verified offline forceloading is working (set up a furnace, logged out, logged back later and furnace had processed items in the meantime)
* Restarted server
* Verified `force_load_mode` is still "always" 
* Verified offline forceloading still working as expected

So this is not reproducible in a default DW20 pack install.

**Comment by Urhas** [comment]
I have went through and redone my setup on a completely different computer and not having the same issue on that install. I am thinking there must be something on my side thats doing this then

**Comment by NoHaxJustCat** [comment]
I have the same issue. Is there a workaround?

**Comment by NoHaxJustCat** [comment]
Alright, I'm gonna upload a video of my issue, maybe is not the same. Otherwise I'll try to reinstall everything

https://github.com/FTBTeam/FTB-Mods-Issues/assets/78616044/896bc172-2e20-41c8-9c7e-485c219f090d

**Comment by desht** [comment]
Why are you using `/forceload add` there?

**Comment by NoHaxJustCat** [comment]
to show that it isnt a ftb issue I think, I tried with several chunk loading methods

**Comment by desht** [comment]
Did a little research - command blocks don't tick as normal block entities do, but rely on scheduled block ticks. So no command blocks won't work in force-loaded chunks, sorry. Not something we support.

**Comment by NoHaxJustCat** [comment]
> Did a little research - command blocks don't tick as normal block entities do, but rely on scheduled block ticks. So no command blocks won't work in force-loaded chunks, sorry. Not something we support.
Alright thank you anyway. I'll check if other things work too

**Comment by KrustyCheese42** [comment]
For anyone reading this after closure. I had same issue on ATM10 modpack -force load: always not working offline. For me the solution was to give me FTB rank: admin. Seems like even when I was OP on the server the FTB rank permission had higher priority. So set urself FTBrank admin or configure other ranks for players to enable offline force loading.

**Comment by PilaScat** [comment]
> For anyone reading this after closure. I had same issue on ATM10 modpack -force load: always not working offline. For me the solution was to give me FTB rank: admin. Seems like even when I was OP on the server the FTB rank permission had higher priority. So set urself FTBrank admin or configure other ranks for players to enable offline force loading.

Tell me more pls, why I need the admin rank if I configured via config to always? When I have that what I need to change?
I'm going insane this needs to be fixed

**Comment by dot-mike** [comment]
For anyone coming here, you can directly modify permissions of the `member` group so all users who has access to server can chunk load offline. Command ``/ftbranks node add member ftbchunks.chunk_load_offline true`
