### ISSUE TITLE
[Bug]: FTB XMod Compat causes crashes with Universal Shops if FTBChunks is not present

### ISSUE THREAD

**Issue by jmadarg** [FTBTeam/FTB-Mods-Issues#1019]
### Mod

FTB XMod Compat

### Mod version

ftb-xmod-compat-fabric-2.0.1

### Forge / Fabric version

Fabric 1.20.1 0.14.24

### Modpack & version

Fantasy MC Fabric 1.3.0

### What issue are you having?

The modpack has the FTB XMod Compat but uses OPAC instead of FTBChunks for the claims.
When interacting with a [Universal Shop](https://www.curseforge.com/minecraft/mc-mods/universal-shops) FTB XMod Compat causes the server to crash https://github.com/Patbox/UniversalShops/issues/23

### Crashlogs

https://paste.feed-the-beast.com/view/3f726325

### Steps to reproduce

1. Place an Universal Shop
2. Claim the place using OPAC
3. Interact with the block

**Comment by desht** [comment]
Fixed in 2.0.3 release
