### ISSUE TITLE
[Bug]: Chunkloading compatibility crash with Minecolonies

### ISSUE THREAD

**Issue by AnishaZonose** [FTBTeam/FTB-Mods-Issues#1020]
### Mod

FTB Chunks

### Mod version

ftb-chunks-forge-2001.2.3.jar

### Forge / Fabric version

forge-47.2.6 

### Modpack & version

Medieval MC [FORGE 1.20.1 v22.zip  (MMC4+personally altered to fix minecolonies)

### What issue are you having?

This is a mod incompatibility problem, we're playing a modpack on a server with a few friends, Medieval Minecraft, a forge version, MMC4. Ordinarily the mods it has will run the game, but when trying to use a builder wand for minecolonies, the game will crash, as this is a known issue to them, they walked me through fixing it by having the correct versions of the mod and its dependencies, this now works correctly when loading into singleplayer, now onto the FTB part, when playing minecolonies as normal, there is a border with a fence around the colony, when you close the game when standing outside of this border, there is no problem loading back into the game, however when closing the game from inside the colony border, and reopening it, the game crashes and supplies the following crash, essentially locking the world. This means we cannot risk updating the minecolony mods in the server modpack to make them work, and the only solution is to just avoid using the minecolonies mod to avoid problems. 

I have a few screenshots from my conversation with support for minecolonies that could add context into what could be causing the confliction, particularly chunkloading.
![supportchat1](https://github.com/FTBTeam/FTB-Mods-Issues/assets/91922328/765a11b6-f18e-4c33-92a7-af99cf759a0b)
![supportchat2](https://github.com/FTBTeam/FTB-Mods-Issues/assets/91922328/00faf24f-2b1e-4692-a380-93aed2e7ea37)

### Crashlogs

logs: https://paste.feed-the-beast.com/view/22a3fb62
crash logs: https://paste.feed-the-beast.com/view/f1cd2282

### Steps to reproduce

1: download Medieval MC Forge MMC4 1.20.1 v22 on curseforge launcher
2: replace minecolonies 1.20.1-1.1.240-RELEASE.jar with minecolonies-1.20.1-1.1.328-BETA.jar
3: replace blockui-1.20.1-0.0.98-ALPHA.jar with blockui-1.20.1-1.0.119-BETA.jar
4: run game, make new world, *creative or survival, same problem, creative is easier*
5: obtain builder wand
6: right click a block with builder wand in hand
7: click the house icon labeled "fundamentals"
8: click "town hall" 
9: click schematic paste
10: find the "Town Hall" block (with a green book on a desk) in the center of the build.
11: click "create colony"
12: close the game from within the colony border (the fence)
13: re open the game, rejoin the same world.

### Anything else to note?

inability to rejoin the world anymore, locking it, Minecolonies support noted chunkloading mods cause this.

**Comment by desht** [comment]
Should be fixed in 2001.2.4 release
