### ISSUE TITLE
[Bug]: Big lag spike when clicking custom chapters that include tags? as a quest.

### ISSUE THREAD

**Issue by Gbergz** [FTBTeam/FTB-Mods-Issues#1021]
### Mod

FTB Quests

### Mod version

ftb-quests-forge-2001.2.0.jar

### Forge / Fabric version

47.2.14 & 47.1.3 (current version in latest Limitless 7).

### Modpack & version

TNP Limitless 7 v0.30.0

### What issue are you having?

Game freezes and gets a big lag spike when clicking certain chapters. This only happens once in this instance then you'll need to restart for it to occur.

### Crashlogs

No crash log.

### Steps to reproduce

Download modpack TNP Limitless 7, v0.30.0.
Click the Ad Astra, Botania or Industrial Foregoing chapter.

Game freeezes.
Goes on for atleast 15 seconds.

### Anything else to note?

Spark profiler: https://spark.lucko.me/AeUXWSVGqN

**Comment by Gbergz** [comment]
Thanks for the answer!

Just wanna add that it wasn't an issue in 1.19.2, and started in 1.20.1 only.

**Comment by desht** [comment]
1.20 did make some big changes to how creative item tags work, which item filters scans for matching items.
