### ISSUE TITLE
[Bug]: game stage not unlock from stage reward

### ISSUE THREAD

**Issue by khazenor** [FTBTeam/FTB-Mods-Issues#1023]
### Mod

FTB Quests

### Mod version

ftb-quests-forge-2001.2.0

### Forge / Fabric version

47.2.0

### What issue are you having?

Game stage reward doesn't seem to be working in the latest version of FTBQuest for 1.20.1

Steps to replicate:
- join world
- make checkpoint quest with stage reward with stage "test"
- complete the check quest
- Problem: stage "test" is not claimed by the active player
- What should happen: stage "test" is claimed by the active player

Mods installed:
`architectury-9.1.10-forge.jar
Bookshelf-Forge-1.20.1-20.1.6.jar
ftb-library-forge-2001.1.4.jar
ftb-quests-forge-2001.2.0.jar
ftb-teams-forge-2001.1.4.jar
GameStages-Forge-1.20.1-15.0.1.jar
item-filters-forge-2001.1.0-build.59.jar
jei-1.20.1-forge-15.2.0.27.jar
RecipeStages-8.0.0.1.jar`

### Steps to reproduce

Steps to replicate:
- join world
- make checkpoint quest with stage reward with stage "test"
- complete the check quest
- Problem: stage "test" is not claimed by the active player
- What should happen: stage "test" is claimed by the active player

**Comment by desht** [comment]
You also need to install FTB XMod Compat. Please try with this and let us know.
