### ISSUE TITLE
[Bug]: crash report

### ISSUE THREAD

**Issue by Fartsalot** [FTBTeam/FTB-Mods-Issues#1025]
### Mod

ATM9

### Mod version

All the mods 9-0.2.25 (current)

### Forge / Fabric version

202311222052-2901a2bd31 i think thats the latest version

### Modpack & version

ATM9 latest version

### What issue are you having?

Hi I was playing a playthrough of all the mods 9 and I saved and exited yesterday and last night when I tried to log back in it kept crashing and I'm not sure why.

### Crashlogs

https://pste.ch/ezufesojuj.pl

### Steps to reproduce

I load up the FTB app click on ATM9 then click play and then it crashes i have not done anything different since first downloading the game.

**Comment by desht** [comment]
I see nothing here to indicate anything to with FTB mods, and ATM9 is not an FTB modpack.

**Comment by Fartsalot** [comment]
Hi so what could the issue be? My pc can more than handle the game

Brendon Holton
0836420106

**Comment by desht** [comment]
No, it is not.  Once more: ATM9 is not an FTB modpack. Just because the FTB app is able to download modpacks from Curseforge doesn't mean that FTB support those modpacks.

In this case, I would suggest you raise an issue with the ATM9 developers.

**Comment by Fartsalot** [comment]
Hi again how can I raise the issue with the developers I've never done
something like this before so if by any chance you could help me I would
really appreciate it

Brendon Holton
0836420106
