### ISSUE TITLE
FTB Ultimine and FTB Lib do not recognise Arcitectuary version 6.8.85 in 1.19.2

### ISSUE THREAD

**Issue by Paddyspud420** [FTBTeam/FTB-Mods-Issues#1027]
### Modpack

Other...

### Modpack version

N/A

### Log Files

[2023-11-23-3.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13452965/2023-11-23-3.log)

### Describe the bug

FTB Ultimine and FTB Lib do not recognise Arcitectuary version 6.8.85 in 1.19.2

### Steps to reproduce

1. load minecraft with FTB Ultimine running the latest version of Architectuary

### Expected behaviour

crash during loading

**Comment by desht** [comment]
I have a 1.19.2 instance here with arch 6.5.85 and up-to-date versions of FTB Lib and FTB Ultimine, and there is no dependency issue. Maybe try re-downloading the Arch 6.5.85 jar, since you seem to have some problem with your local instance.
