### ISSUE TITLE
[Feature] (FTB Chunks): Ability to allow interaction from non team members on specific blocks.

### ISSUE THREAD

**Issue by Micaxs** [FTBTeam/FTB-Mods-Issues#1028]
### Modpack

Other...

### Is your suggestion related to a problem? Please describe.

Just curious if it would be possible to allow certain blocks to be accessed from non-team-members (anyone) within a claim maybe specified from within the config file?
Something like a `whitelist = ['minecraft:furnace', ...]` if possible?

**Comment by desht** [comment]
It's already possible. Add the blocks for which you want general access to one or both of the following block tags, as appropriate:

* `ftbchunks:edit_whitelist` - allows the block to placed/broken
* `ftbchunks:interact_whitelist` - allows the block to interacted with (right clicked)#

**Comment by TheOnlyExxxception** [comment]
> It's already possible. Add the blocks for which you want general access to one or both of the following block tags, as appropriate:
> 
> * `ftbchunks:edit_whitelist` - allows the block to placed/broken
> * `ftbchunks:interact_whitelist` - allows the block to interacted with (right clicked)#

Hello! I am very new to modifying mod files; what file/where would I add these whitelist block tags to if I would like to use them for FTBChunks? Thank you :)

**Comment by desht** [comment]
You create a datapack, which is a standard vanilla concept: https://minecraft.fandom.com/wiki/Data_pack

Or you can use a tool like KubeJS to add tags.

**Comment by WaffleDevs** [comment]
I am unable to get this working with Vs_eureka ship helms. 
1.18.2 
ftb-chunks-forge-1802.3.17-build.265.jar
eureka-1.4.0-beta.1.jar
