### ISSUE TITLE
[Bug]: Selecting an image using Ctrl+LMB

### ISSUE THREAD

**Issue by MrHimera** [FTBTeam/FTB-Mods-Issues#1029]
### Mod

FTB Quests

### Mod version

ftb-quests-forge-2001.2.1

### Forge / Fabric version

Forge 1.20.1 47.2.1

### What issue are you having?

It is impossible to select or deselect an image using Ctrl+LMB. Selecting with the wheel or Ctrl+A and deselecting with Ctrl+D works fine.

### Steps to reproduce

1. Go to the quest panel
2. Press Ctrl+LMB on another image

**Comment by desht** [comment]
Confirmed, will fix for next release.

As a workaround for now, you can select the image by dragging a box round the image with the middle mouse button.

**Comment by desht** [comment]
Fixed in latest releases for 1.19.2/1.20.1
