### ISSUE TITLE
[Bug]: FTB Sluice crafts even if low fluid requirement is not met

### ISSUE THREAD

**Issue by Raidobw2** [FTBTeam/FTB-Mods-Issues#103]
### Mod

FTB Sluice

### Mod version

ftb-sluice-forge-1.0.6-build.20.jar

### Forge / Fabric version

1.16.5 36.2.8

### Modpack & version

FTB OceanBlock 1.5.0

### What issue are you having?

In the Sluices that use less than 1000mB per craft it only checks to ensure the correct fluid is there, not that there is sufficient fluid.

I.e a Iron sluice with 1000mB can proccess two pieces, when it should only proccess one, and then be missing 200mB to do the next one.

### Steps to reproduce

1. Place down Iron Sluice with any Mesh.
2. Add Hopper to the side of Sluice.
3. Add 1000mB of water.
4. Place two pieces of gravel in hopper.
5. See both pieces be sluiced.
6. Profit and look at the error.

### Anything else to note?

Expected behavior: I'd Expect the first pieve to go throught just fine, but the next be waiting on another 200mB of water.

IMPORTANT
Relayed from FTBTeam/FTB-Modpack-Issues#238 which originated from Modpack Issues

**Comment by MichaelHillcox** [comment]
Fixed in dev :+1:

**Comment by Raidobw2** [comment]
Fixed in `ftb-sluice-forge-1.0.9-build.34.jar`, available now
