### ISSUE TITLE
[Bug]: Item task set crashes game completly

### ISSUE THREAD

**Issue by ReeCodes** [FTBTeam/FTB-Mods-Issues#1030]
### Mod

FTB Quests

### Mod version

ftb-quests-forge-2001.2.1

### Forge / Fabric version

1.20.1

### What issue are you having?

Getting a crash when searching for the using the word cam whilst in the GUI to set the Item task.

### Crashlogs

https://mclo.gs/2B9QREz (crash)

https://mclo.gs/BtbKTzn (latest.log)

### Steps to reproduce

See description

**Comment by desht** [comment]
Bug in SecurityCraft, not FTB Quests.

Although FTB Library passes a null level to `ItemRenderer#getModel` in `GuiHelper#drawItem`, the `level` parameter is annotated as `@Nullable` and SecurityCraft isn't checking nullability in its item model overrides.
