### ISSUE TITLE
[Bug]: Incorrect display with a large number of tasks/rewards

### ISSUE THREAD

**Issue by MrHimera** [FTBTeam/FTB-Mods-Issues#1033]
### Mod

FTB Quests

### Mod version

ftb-quests-forge-2001.3.0

### Forge / Fabric version

Forge 1.20.1 47.2.1

### What issue are you having?

If there are a large number of tasks/rewards (17+) in one quest, the top line of tasks/rewards is displayed in half (it moves up too much).

### Steps to reproduce

1. Create a quest with at least 17 tasks/rewards
2. View display of the top line of tasks/rewards

**Comment by desht** [comment]
To be honest, this would need a fairly significant rework of how the quest view panel is displayed. In the short term, you're much better off splitting the quest into a couple of quests, one of which depends on the other. If there's only one objective, the second quest could be just be a checkmark task or similar.

**Comment by desht** [comment]
Going to close this since implementing #1034 would fix it.
