### ISSUE TITLE
[Bug / Question]: How to remove generated recipes

### ISSUE THREAD

**Issue by MundM2007** [FTBTeam/FTB-Mods-Issues#1038]
### Mod

FTB Industrial Contraptions

### Mod version

 ftb-industrial-contraptions-1605.1.3-build.122.jar /  ftb-industrial-contraptions-1802.1.6-build.197.jar

### Forge / Fabric version

1.16.5 36.2.39 / 1.18.2 40.2.14

### What issue are you having?

How exactly should a generated recipe like iron plates or some of the canning recipes be removed.

Trying with kubejs doesn't work and I don't know what else to try

### Steps to reproduce

install kubejs and ftbic and get the recipe id of a generated recipe use this code to remove the recipe
```js
onEvent('recipes', event => {
	event.remove({id: "ftbic:reprocessing/generated/scrap_jei"})
})
```
and paste your recipe id, it doesn't remove

### Anything else to note?

Wierdly, when trying to add a recipe with the same id as a generated one adds both and they have the same id. I thought recipe ids are unique and can't be duplicated. What's the error here?
this may also effect 1.19

**Comment by MundM2007** [comment]
anybody got an idea?

**Comment by MundM2007** [comment]
If anybody else is searchingnfor a solution for this, there's a Tag that allows to disable the Auto Gen for that Item, it's `ftbic:no_auto_recipe`

**Comment by MichaelHillcox** [comment]
There is also a config option but I can't remember if it's hardcoded is 1.16. Sorry, i've only just seen this issue

**Comment by MundM2007** [comment]
Yeah, it seems pretty hardcoded, there's No config File generated and only located in the Java File FTBICConfig.

**Comment by MichaelHillcox** [comment]
It's all a bit weird back in 1.16. If you have KubeJS installed and it's a public field, you could technically flip any of the values in FTBICConfig but it's kinda an all off or all on system

**Comment by MundM2007** [comment]
that's not a problem, how would I do this?

**Comment by MichaelHillcox** [comment]
```
const FTBICConfig = java("dev.ftb.mods.ftbic.FTBICConfig")

FTBICConfig.ADD_DUST_FROM_ORE_RECIPES = true;
FTBICConfig.ADD_DUST_FROM_MATERIAL_RECIPES = true;
FTBICConfig.ADD_GEM_FROM_ORE_RECIPES = true;
FTBICConfig.ADD_ROD_RECIPES = true;
FTBICConfig.ADD_PLATE_RECIPES = true;
FTBICConfig.ADD_GEAR_RECIPES = true;
FTBICConfig.ADD_CANNED_FOOD_RECIPES = true;
```

All the above values are default in the mod. If you do not intend on changing this behaviour. I'd recommend removing the entries you do not change.

Setting to false will disable those recipes from being generated.

It's recommended you do this in the startup_scripts of kubejs

**Comment by MundM2007** [comment]
Thanks for the Info.
