### ISSUE TITLE
[Feature Request]: FTB Auxilium doesn't disclose launcher type data collection in opt-out screen

### ISSUE THREAD

**Issue by NepNep21** [FTBTeam/FTB-Mods-Issues#104]
### Mod

FTB Auxilium

### Description

From looking at the code, ftb auxilium sends more data than is disclosed in the opt-out screen, i don't think the collection itself is big deal but i believe everything should be disclosed, all i could find so far that isn't disclosed is the launcher the player is using

### Describe the solution you'd like

Disclose the launcher type data collection in the opt-out screen

**Comment by lachian** [comment]
Also probably important to disclose exactly what is sent to be clear that it's in compliance with GDPR.

**Comment by MichaelHillcox** [comment]
The system is complete GDPR compliant but you are right, we should have everything listed, I will look into this and get the wording sorted, the mod needs an update anyway. The mod is by no means invasive, it takes very basic telemetry completely anonymously with an opt-out button that truly Yeets all of the stored data :) helps us plan effectively for new packs :)
