### ISSUE TITLE
[Bug]: Game crashes when i hover over an item

### ISSUE THREAD

**Issue by loopel** [FTBTeam/FTB-Mods-Issues#1042]
### Mod

FTB Library

### Mod version

ftb-library-forge-2001.1.4.jar

### Forge / Fabric version

1.20.1, 47.2.16

### What issue are you having?

So I use ftb mods with a modpack I use and whenever I hover over silent gear items like blueprints, my game crashes every time.

### Crashlogs

https://pastebin.com/Vc7TbMFu

### Steps to reproduce

1. Launch mc with mods
2. hover over silent gear blueprint item
3. crash

**Comment by desht** [comment]
Just tested with a small instance including Silent Gear/Silent Lib/FTB Library and I cannot reproduce the crash when hovering over SG blueprints, which leads me to believe that some other mod in your pack is interfering.

Which GUI are you in when you get the crash? And is it _all_ SG items, or just specific ones?

**Comment by loopel** [comment]
I'm in the creative menu or JEI or any UI with certain SG items like bluprint, blueprint pakcage, and blueprint book. It's not always ftb library but sometimes the crash log says the suspected mod is JEI or it says (none)
