### ISSUE TITLE
[Bug]: Unable to remove certain waypoints

### ISSUE THREAD

**Issue by connormatt** [FTBTeam/FTB-Mods-Issues#1043]
### Mod

FTB Chunks (Forge)

### Mod version

ftb-chunks-forge-2001.2.4

### Forge / Fabric version

1.20.1

### What issue are you having?

I accidentally pressed the plus on my numpad and it added a quick waypoint (that looks like a beacon) in the world where i was standing. it doesnt show up in the waypoint manager and i have found no way to remove it
![Screenshot 2023-12-13 105955](https://github.com/FTBTeam/FTB-Mods-Issues/assets/45466883/4f9eaa37-30d5-4853-be09-8dd9a298e2bb)
![Screenshot 2023-12-13 110032](https://github.com/FTBTeam/FTB-Mods-Issues/assets/45466883/2615a519-6d77-429c-bb44-d81258e7f776)

### Steps to reproduce

press num pad plus while out in the world and then try to use waypoint manager to remove it

**Comment by desht** [comment]
That's not an FTB Chunks waypoint.  Check your key bindings and find out what which mod has the numpad-plus bound.
