### ISSUE TITLE
Question: How do I change permissions of chunks?

### ISSUE THREAD

**Issue by Aceplante2** [FTBTeam/FTB-Mods-Issues#1044]
### Mod

Chunks

### Mod version

latest

### Forge / Fabric version

1.19.2

### What issue are you having?

I want to let people use waystones but thats it

### Steps to reproduce

claim chunks,
idk?

**Comment by desht** [comment]
This question is much to vague, sorry.  Can you please explain exactly what you're trying to do, and what you need from FTB Chunks to help you?

**Comment by Aceplante2** [comment]
I do not remember exactly, But I think I was trying to allow people to edit certain chunks but not all of mine in the form of teams
