### ISSUE TITLE
[Feature Request]: Custom Dependency Lines in FTB Quests

### ISSUE THREAD

**Issue by firemaster1294** [FTBTeam/FTB-Mods-Issues#1045]
### Mod

FTB Quests

### Description

It would be nice to have the option to custom define dependency lines. Specifically, when I am building questlines with many quests originating at a single source, they can appear quite cluttered. Allowing the option to overlay the lines and then split them later (similar to vanilla advancements) could help alleviate this.

### Describe the solution you'd like

The ability to either click and drag to draw dependency lines, or to add vertices to the existing dependency lines that I could then drag to reposition the lines.

### Describe alternatives you've considered

Invisible dependencies with background images of the dependency lines can work but it's rather time consuming to custom build this sort of thing.

**Comment by desht** [comment]
Pretty much covered by #503 so closing this one.

I agree it would be nice to have this, just a matter of priorities unfortunately.
