### ISSUE TITLE
[Bug]: Can't Edit/Add Quests in Singleplayer Worlds

### ISSUE THREAD

**Issue by MysteryGhost21** [FTBTeam/FTB-Mods-Issues#1046]
### Mod

FTB Quests

### Mod version

ftb-quests-forge-2001.3.0.jar

### Forge / Fabric version

1.20.1 47.2.0

### What issue are you having?

On the wiki, it states that FTB Quests can be used in a singleplayer world by running the "/ftbquests editing_mode true" command. However, running this command has no effect and no quest editing/creation icons show up. Opening the world to LAN and allowing cheats does cause an icon in the lower right to show up, stating that "editing mode for Player is enabled", but again, there is no editing/creation functionality available.

Note: I have just discovered a workaround as of writing this bug report. If you open to LAN with cheats on then run "/ftbquests reload", then editing functionality will be granted. Creating a world in creative and making quests there is the other workaround that I know of.

### Steps to reproduce

1. Create a world in Survival 
2. Open the quest book, noticing that you do not have the ability to edit (as expected)
3. Run the "/ftbquests editing_mode true"
4. Open the quest book again, noticing that you still don't have editing privileges (which according to the wiki, you should)

**Comment by desht** [comment]
I'll take a look at this, but in general if you're developing a quest book (as part of general modpack development), it's a very good idea to be an admin-level user in your dev world - it's hard to test mods and mod integration without admin permissions...

In SSP, create the world with "Allow Cheats: On", and on a dedicated server, ensure you're a server op (`/op <player-name>`).

**Comment by itsdinkd** [comment]
I also am having this issue.

**Comment by desht** [comment]
I'm not seeing this behaviour at all. As long as my player has admin rights, there is no issue in enabling edit mode (and if this were a general problem, _every_ quest writer would be complaining to us).

Please provide a very precise set of steps you took (from starting the client onward), to reproduce the issue.

**Comment by desht** [comment]
I can confirm though that creating an SSP world with cheats off and opening to LAN doesn't function correctly right now.

**Comment by desht** [comment]
Fixed in 2001.3.1
