### ISSUE TITLE
[Bug]: Chunks are bugs

### ISSUE THREAD

**Issue by AlfreDGR** [FTBTeam/FTB-Mods-Issues#1047]
### Mod

FTB Chunks

### Mod version

ftb-chunks-forge-2001.2.4.jar

### Forge / Fabric version

Forge 1.20.1 47.2.17

### What issue are you having?

I have set a maximum of 4 chunks per player in the config. When a player claims his zone and a player invites him to his team. (Having the config in sum) They are put together and their claims are 8 chunks in total. But if I remove that user from the party, I still have those 8 chunks already claimed and the other user cannot claim anything and cannot build on his old chunk either.

Another problem also occurs, which is that sometimes when the server restarts the protected fragments get bugs and I cannot remove them. Screenshot of Dejo. Just as it doesn't let me remove it, it lets me protect more pieces.
![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/62883576/ea3cb87a-3926-4f7e-a5a7-d83cb857ff64)

### Steps to reproduce

I create a party, i protect the chunks and after I invite someone to my party. I expand with his chunks and i kick of the party. I have the 8 chunks and he cant claim

**Comment by desht** [comment]
I'll take a look today and see if I can reproduce this. If you could attach a copy of your server config (`world/serverconfig/ftbchunks-world.snbt`), that would be very helpful, to ensure I have an identical setup to yours.

**Comment by AlfreDGR** [comment]
{
	# Forced modes won't let players change their ally settings
	# Default: "default"
	# Valid values: "default", "forced_all", "forced_none"
	ally_mode: "default"
	
	# Dimension ID's where chunks may not be claimed. Add "minecraft:the_end" to this list if you want to disable chunk claiming in The End, or "othermod:*" to disable chunk claiming in *all* dimensions added by "othermod"
	# Default: []
	claim_dimension_blacklist: [ ]
	
	# Dimension ID's where chunks may be claimed. If non-empty, chunks may be claimed *only* in these dimensions (and the dimension is not in "claim_dimension_blacklist"). Same syntax as for "claim_dimension_blacklist".
	# Default: []
	claim_dimension_whitelist: [
		"minecraft"
		":overworld"
	]
	
	# Disables all land protection. Useful for private servers where everyone is trusted and claims are only used for force-loading
	# Default: false
	disable_protection: false
	
	# Override to disable/enable fake players like miners and auto-clickers globally.
	# Default will check this setting for each team
	# Default: "check"
	# Valid values: "check", "deny", "allow"
	fake_players: "check"
	
	# Minimap for clients connecting to this server will be disabled
	# Default: false
	force_disable_minimap: false
	
	# Control how force-loaded chunks work.
	# NEVER: only allow chunk force-loading if the owning team has at least one online player.
	# ALWAYS: always allow force-loading, even if no players are online.
	# DEFAULT: allow force-loading IF the team has at least one player with the 'ftbchunks.chunk_load_offline' FTB Ranks permission.
	# Default: "default"
	# Valid values: "default", "always", "never"
	force_load_mode: "default"
	
	# Hard limit for the number of chunks a team can claim, regardless of how many members. Default of 0 means no hard limit.
	# Default: 0
	# Range: 0 ~ 2147483647
	hard_team_claim_limit: 0
	
	# Hard limit for the number of chunks a team can force-load, regardless of how many members. Default of 0 means no hard limit.
	# Default: 0
	# Range: 0 ~ 2147483647
	hard_team_force_limit: 0
	
	# If true, "Location Visibility" team settings are ignored, and all players can see each other anywhere on the map.
	# Default: false
	location_mode_override: false
	
	# Interval in ticks to send updates to clients with long-range player tracking data.
	# Lower values mean more frequent updates but more server load and network traffic; be careful with this, especially on busy servers.
	# Setting this to 0 disables long-range tracking.
	# Default: 20
	# Range: 0 ~ 2147483647
	long_range_tracker_interval: 20
	
	# Max claimed chunks.
	# You can override this with FTB Ranks 'ftbchunks.max_claimed' permission
	# Default: 500
	# Range: -∞ ~ +∞
	max_claimed_chunks: 4
	
	# Max force loaded chunks.
	# You can override this with FTB Ranks 'ftbchunks.max_force_loaded' permission
	# Default: 25
	# Range: -∞ ~ +∞
	max_force_loaded_chunks: 6
	
	# Maximum time (in real-world days) where if no player in a team logs in, the team automatically loses their claims.
	# Prevents chunks being claimed indefinitely by teams who no longer play.
	# Default of 0 means no automatic loss of claims.
	# Default: 0.0
	# Range: 0.0 ~ 3650.0
	max_idle_days_before_unclaim: 0.0d
	
	# Maximum time (in real-world days) where if no player in a team logs in, any forceloaded chunks owned by the team are no longer forceloaded.
	# Prevents chunks being forceloaded indefinitely by teams who no longer play.
	# Default of 0 means no automatic loss of forceloading.
	# Default: 0.0
	# Range: 0.0 ~ 3650.0
	max_idle_days_before_unforce: 0.0d
	
	# Maximum time in days to keep logs of prevented fakeplayer access to a team's claims.
	# Default: 7
	# Range: 1 ~ 2147483647
	max_prevented_log_age: 7
	
	# Requires you to claim chunks in order to edit and interact with blocks
	# Default: false
	no_wilderness: false
	
	# Dimension ID's where the no_wilderness rule is enforced - building is only allowed in claimed chunks. If this is non-empty, it overrides the 'no_wilderness' setting.
	# Default: []
	no_wilderness_dimensions: [ ]
	
	# Method by which party claim & force-load limits are calculated.
	# LARGEST: use the limits of the member with the largest limits
	# SUM: add up all the members' limits
	# OWNER: use the party owner's limits only
	# AVERAGE: use the average of all members' limits.
	# Default: "largest"
	# Valid values: "largest", "owner", "sum", "average"
	party_limit_mode: "sum"
	
	# When true, standard FTB Chunk explosion protection is applied in protected chunks when the source of the explosion cannot be determined
	# (Ghast fireballs are a common case - vanilla supplies a null entity source)
	# Default: true
	protect_unknown_explosions: true
	
	# Should PvP combat be allowed in claimed chunks? Default is ALWAYS; NEVER prevents it in all claimed chunks; PER_TEAM allows teams to decide if PvP is allowed in their claims
	# Default: "always"
	# Valid values: "always", "never", "per_team"
	pvp_mode: "never"
	
	# If true, the player must have the 'ftbchunks_mapping' Game stage to be able to use the map and minimap.
	# Requires KubeJS and/or Gamestages to be installed.
	# Default: false
	require_game_stage: false
}

**Comment by desht** [comment]
Thanks.  Also checking - do you use FTB Ranks (claim limits can be overridden with ranks) ?

**Comment by AlfreDGR** [comment]
No i dont use ftb ranks , i use luckperms. But i dont have overriden limits

**Comment by AlfreDGR** [comment]
Hi?

**Comment by desht** [comment]
I've been away, sorry. There should be a new release next week with some fixes for this.

**Comment by desht** [comment]
Should be fixed in FTB Chunks 2002.2.5 released today
