### ISSUE TITLE
[Bug]: RFTools builder bypass FTB Chunk

### ISSUE THREAD

**Issue by Sayaniku** [FTBTeam/FTB-Mods-Issues#1048]
### Mod

FTB Chunks

### Mod version

ftb-chunks-forge-1802.3.17-build.265.jar

### Forge / Fabric version

1.18.2-40.2.9

### Modpack & version

Ragnamod VII

### What issue are you having?

The builder of rftools isn't blacklist and can mine on every claimed chunk, causing griefing on some base, the video of the proof : https://cdn.discordapp.com/attachments/1180817668010410055/1187356185330974731/2023-12-21_12-27-04.mp4
The destruction on claimed chunk : https://media.discordapp.net/attachments/1180211580017836144/1187053739798966333/image.png

### Steps to reproduce

Claim an chunk, place an builder with an shaped card on a certain zone, and run the builder, the video with everything tried : https://cdn.discordapp.com/attachments/1180817668010410055/1187356185330974731/2023-12-21_12-27-04.mp4

### Anything else to note?

Already talked with the dev of rftools builder : https://github.com/McJtyMods/RFToolsBuilder/issues/120

**Comment by desht** [comment]
The RFTools builder doesn't just bypass FTB Chunks, but you need to configure things correctly.  You have these options:

* Set "Allow All Fake Players" to true in your team settings. This will allow the builder, but also anyone else's builder and anyone else's fake players from _any_ mod (not recommended).
* Add "rftools_builder" to "Allow Fake Player Names". This will also allow your builder and anyone else's.
* Ask McJty to add support for using the UUID of the player who placed the builder as the fake player's UUID. This will allow only your builder (as long as you have "Allow Fake Players by Player ID" enabled), but it needs support from RFTools.

These are your only options. If McJty is not prepared to implement the third option, then you're out of luck, sorry.

I've also added a comment to the original issue.

**Comment by Sayaniku** [comment]
Did you check the video, because I tried without and with that, and for the
fake player idk for the builder (at this time I'm not on my pc)

**Comment by desht** [comment]
Yes, I've watched the video.  No there's nothing I can do about it.  Please read my comment in the other issue.

**Comment by Sayaniku** [comment]
i just maked without bypass protection and without op with one of my player on a claimed chunk with the default config on ftb chunk, the quarry can mine in every case

**Comment by desht** [comment]
What's "Allow All Fake Players" set to in your server config?

**Comment by Sayaniku** [comment]
I didn't touch the serverconfig file
Absolutely never touched that
And i just check that on allow

**Comment by desht** [comment]
Well, someone's touched it, because "check" is the default.  And on a multiplayer server where you don't trust everyone, you really don't want it set to "allow".  So there's your problem.

**Comment by Sayaniku** [comment]
The only person had acces to the pterodactyl is me, and i never touched that, idk if they was from the server pack or not, but i think that from the server pack because i didn't touch that
