### ISSUE TITLE
[Bug]: FTB Chunks - Large Fireball Ticking Entity Error on EntityMobGriefingEvent

### ISSUE THREAD

**Issue by janlout** [FTBTeam/FTB-Mods-Issues#1049]
### Mod

FTB Chunks

### Mod version

ftb-chunks-forge-1902.4.3-build.321

### Forge / Fabric version

Forge 43.3.5

### What issue are you having?

**What is happening?**
When travelling around the nether, our server randomly crashes, while players are near claimed chunks. It throws an Ticking Entity Error for a minecraft:fireball while trying to get the entity for an EntityMobGriefingEvent. After that, the entity needs to be removed via NBT Explorer. This happend twice already.

**What should be happening?**
The Server shouldn't crash. The Error with the fireball should be handeld by FTB Chunks, or ideally, shouldnt happen.

### Crashlogs

[https://pste.ch/ipivineqac.pl](https://pste.ch/ipivineqac.pl)

### Steps to reproduce

1. Claim a chunk in the nether.
2. Have a Ghast fire at you while you are in the claimed chunk
3. Profit (Server Crash)

### Anything else to note?

We just updated FTB Chunks and a few other mods, and also added a few more, but this seems to be caused by the vanilla fireball.

**Comment by desht** [comment]
Fixed in latest FTB Chunks for 1.19.2
