### ISSUE TITLE
[Bug]: FTB Sluice AutoHammer directional issue on placement

### ISSUE THREAD

**Issue by Raidobw2** [FTBTeam/FTB-Mods-Issues#105]
### Mod

FTB Sluice

### Mod version

ftb-sluice-forge-1.0.8-build.30.jar

### Forge / Fabric version

1.16.5 36.2.8

### Modpack & version

FTB OceanBlock 1.6.0

### What issue are you having?

The auto hammer has a directional issue when place from east or west. The inputs and outputs will be reversed.

Also, although minor, but when I looked at the model the arrows seem to point in the opposite direction (input arrow points like an output for example, items going "out" of the input). Maybe that's unintended, but it's what I thought when I looked at it the first time.

See original issue FTBTeam/FTB-Modpack-Issues#245 and gif:
![auto_hammer](https://user-images.githubusercontent.com/17010632/140440772-514fbfe1-a003-4800-914f-5539d7f051d8.gif)

### Steps to reproduce

See gif, place from East or West. Latches point North or South, the latches will be reversed.

**Comment by MichaelHillcox** [comment]
I'll look into this thanks

**Comment by MichaelHillcox** [comment]
Fixed in dev, will be released soon

**Comment by Raidobw2** [comment]
Thank you
