### ISSUE TITLE
[FTBUltimine | Question ]: How do I include the Raw Block variant in the veinmining

### ISSUE THREAD

**Issue by ArsiTheFox** [FTBTeam/FTB-Mods-Issues#1050]
### Mod

FTB Ultimine

### Description

I am trying to add the funtionality to also break the raw ore blocks while veinmining along with the different ore types.
Example: 
  - I mine a minecraft:iron_ore and it mines the raw block variant and deepslate varient next to it

**Comment by desht** [comment]
First off, I assume we're talking about using the shapeless mining mode here.  There is a config entry `merge_tags` which controls how block equivalence is decided when a shapeless ultimine operation is done. Its default value lists the following block tags (wildcarding is supported):

```
"minecraft:base_stone_overworld",
"c:*_ores",
"forge:ores/*"
```

(`c:*_ores` and `forge:ores/*` are the Fabric and Forge equivalents for all known ore blocks, respectively)

When a block is ultimined, the `merge_tags` tag is checked: if the block just mined is in one of the tags, then any adjacent blocks also in that matched tag are candidates for being broken too.  So in the case of Iron Ore, both Iron Ore and Deepslate Iron Ore are in the `forge:iron_ores` block tag, so are considered equivalent for ultimining. Raw Iron blocks are not in that tag, so would not be considered equivalent.

If you really want raw iron to be considered equivalent, I'd suggest adding a custom block (use a data pack, or maybe KubeJS) containing iron ore, deepslate iron ore and raw iron blocks, and add that custom tag to the `merge_tags` config entry.

(You could add raw iron blocks to `forge:iron_ores` but I would not recommend it - it's not really an ore, and adding it there could have unintended consequences elsewhere).

Does that help?

**Comment by ArsiTheFox** [comment]
It does help, thank you <3
Sorry for the wait

I will look at matching tags to add into the system
