### ISSUE TITLE
[Bug]: Crashes Game/Server When Fake Player Tries to Break Block

### ISSUE THREAD

**Issue by jzells09** [FTBTeam/FTB-Mods-Issues#1051]
### Mod

FTB Quests

### Mod version

ftb-quests-forge-2001.3.0.jar

### Forge / Fabric version

1.20.1

### Modpack & version

Earth Inc 4 1.0.6-1.20.1

### What issue are you having?

Whenever a fake player is used to break a block (modular routers, integrated tunnels, etc.), the game crashes.

### Crashlogs

https://pste.ch/efubucaxed.pl

### Steps to reproduce

1. Use modular router block breaker, or integrated tunnels player simulator to try and break a block
2. Game crash

**Comment by desht** [comment]
This crash is in FTB Quests Additions, which is a third party addon, and not an FTB mod.
