### ISSUE TITLE
[Feature Request]: Mod addon

### ISSUE THREAD

**Issue by Globox1997** [FTBTeam/FTB-Mods-Issues#1054]
### Mod

FTB Quests

### Description

I am working on an addon mod for the ftb quests mod which is called VillagerQuests.
As the name suggests, villagers will give out quests. 

This is quite intrusive if I want to get this done based on the ftb quests mod cause the visibility of these villager quests changes, new data has to get stored in quests, those villager quest rewards can be only given out by the villager and syncing the quest mark onto the villager needs a couple places to get synced.

In a conversion with Mikey and desht, they basically said I could mixin but it is really not appreciated cause it will lead to github issues, when ftb quests gets updated , villagerquest mod not and update incompats come by.
There is no official statement that mixins are allowed/not allowed for the ftb ARR mods, by default ARR does not allow mixins tho since the byte code get changed as a side not.

I've checked other mod addons by non ftb members and some mix into the ftb mods too.

My solution for using mixins into the ftb quests mod is (if I get permission), I can hard depend on a specific version and when a user tries to use non incompatible versions (for example a new ftb quest version), a pop up will show up saying these versions are incompatible and I would need to update my addon before it works again.

This popup is native build in to fabric and my mod is exclusively for fabric. 

Side note:
I am also adding a new task type but that does not require a mixin of course.
The quest creator will be able to set quests to specific villagers with the small villager head icon.
![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/55102939/884a4cc4-c952-4c7d-80d8-e50d847e3efe)

### Describe the solution you'd like

As I wrote in the description, my solution is to hard depend on specific versions of the mod.

### Describe alternatives you've considered

My alternative solution would be to list all places I have to mix into but those places might require a cancelable callback.

**Comment by Globox1997** [comment]
And there might be an open github issue already about it but dropping mipmap level should always be avoided.
`Texture ftblibrary:icons/nbt/int with size 8x8 limits mip level from 4 to 3`

**Comment by desht** [comment]
Just to be clear: we won't stop you from using a mixin, but as I mentioned previously it's not the best idea, due to the increased chance of breakage. But if you're locking your addon to a specific version of FTB Quests, that becomes less of a problem.

So if you really need to mix in, and you understand the risks, and understand how to do it, that's fine. However, if you have any suggestions for API improvement or non-mixin hooks that we can add to FTB Quests, I'm very much open to suggestions.

(Can the villager type not just be a task property in the example you provide above?)

**Comment by desht** [comment]
> And there might be an open github issue already about it but dropping mipmap level should always be avoided.

That looks like a simple fix; the PNG is only 8x8 right now, but can be increased to 16x16. A separate issue would good so it doesn't get forgotten about :stuck_out_tongue:

**Comment by Globox1997** [comment]
Thank you for your answer.
So I will add hard dependency.
When I figure out an API improvement I will reopen this issue here.
The villager quests repo: [https://github.com/Globox1997/VillagerQuests](https://github.com/Globox1997/VillagerQuests)

The link to the new issue about the mipmap level can be found here: [https://github.com/FTBTeam/FTB-Mods-Issues/issues/1055](https://github.com/FTBTeam/FTB-Mods-Issues/issues/1055)
