### ISSUE TITLE
[Feedback]: Dependencies

### ISSUE THREAD

**Issue by Globox1997** [FTBTeam/FTB-Mods-Issues#1056]
### Mod

FTB Quests

### Description

While going through the fabric side of ftb quests I've seen it is hard depending on the reborn core mod here:
[https://github.com/FTBTeam/FTB-Quests/blob/main/fabric/src/main/java/dev/ftb/mods/ftbquests/fabric/FTBQuestsFabric.java#L47](https://github.com/FTBTeam/FTB-Quests/blob/main/fabric/src/main/java/dev/ftb/mods/ftbquests/fabric/FTBQuestsFabric.java#L47)

In the fabric.mod.json it is missing this reference here: [https://github.com/FTBTeam/FTB-Quests/blob/main/fabric/src/main/resources/fabric.mod.json#L25](https://github.com/FTBTeam/FTB-Quests/blob/main/fabric/src/main/resources/fabric.mod.json#L25) and it is missing on the curseforge page of the fabric ftb quests.

### Describe the solution you'd like

Not sure if it is intended to hard depend on it, if not put a bracket around with the `if(FabricLoader.getInstance().isModLoaded("reborncore"))` statement. There is also a task which should get disabled when it is not loaded.

If this dependency is intended, I expect to have a notice disclaimer somewhere, either in the fabric.mod.json or the curseforge page itself.

**Comment by desht** [comment]
It is intended, and it's not a hard dependency on reborncore.  It will load and run just fine without reborncore installed.  The dependency is on `team_reborn_energy` 3.0.0, which is included with FTB Quests here: https://github.com/FTBTeam/FTB-Quests/blob/main/fabric/build.gradle#L31C54-L31C54

Not sure why you think a disclaimer is needed?
