### ISSUE TITLE
[Bug]: Autofocus Quest ID

### ISSUE THREAD

**Issue by MrHimera** [FTBTeam/FTB-Mods-Issues#1057]
### Mod

FTB Quests

### Mod version

ftb-quests-forge-2001.3.0

### Forge / Fabric version

Forge 1.20.1 47.2.1

### What issue are you having?

Autofocus Quest ID does not work when entering quests for the first time (if Autofocus Quest ID has already been installed on the quest before). Can this be fixed?

### Steps to reproduce

1. Install Autofocus Quest ID on the quest
2. Exit to the game menu
3. Login and go to quests

**Comment by desht** [comment]
Fixed in 2001.3.1
