### ISSUE TITLE
[Bug]: Dependency Requirement

### ISSUE THREAD

**Issue by MrHimera** [FTBTeam/FTB-Mods-Issues#1058]
### Mod

FTB Quests

### Mod version

ftb-quests-forge-2001.3.0

### Forge / Fabric version

Forge 1.20.1 47.2.1

### What issue are you having?

All my quests are hidden and Progression Mode is set to Flexible. Quests must be completed and unlocked one by one. 1 quest is visible, but not completed. Quest 2 costs obtaining items and "Dependency Requirement" to "All Completed". After it comes quest 3 from “Dependency Requirement” to “All Started” and it was completed and you could get a reward, although quest 2 before it was also completed, but it is hidden. Was this intended or is it a bug?

### Steps to reproduce

1. Create 3 quests with dependencies "1-2-3"
2. Set each "Hide Quests Until Dependencies Visible" to True
3. Set each "Progression Mode" on Flexible
4. Set on quest 3 "Dependency Requirement" on All Started
5. Set on quest 1 & 2 "Dependency Requirement" on All Completed
6. Get quest items 2 in the game
7. See how quest 3 is visible on the quest field (although it should be hidden)

**Comment by MrHimera** [comment]
![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/29342708/0efa2948-8f15-4982-bc8c-b14159323a8c)

**Comment by desht** [comment]
Flexible progression mode isn't really compatible with hiding quests until their dependencies are visible - the two concepts aren't intended to be used together.  Flexible mode is intended to allow a bunch of quests in a chapter (or even the whole quest book) to be progressed in parallel, while still maintaining a dependency tree for progression (i.e. quests can be progressed in any order but must be completed in the order you define).

So, as intended... some options just don't go together.
