### ISSUE TITLE
[Bug]: Severe server lag when crafting due to FTB Quests

### ISSUE THREAD

**Issue by dacarmart** [FTBTeam/FTB-Mods-Issues#1063]
### Mod

FTB Quests

### Mod version

ftb-quests-forge:2001.3.0

### Forge / Fabric version

1.20.1 47.2.19

### Modpack & version

All The Mods 9 - 0.2.36

### What issue are you having?

Whenever an item is crafted and shift clicked into the inventory there is a lag spike. This duration/severity increases with more items being crafted (crafting a stack of logs into planks is bad, crafting a stack of iron blocks into iron ingots is even worse). I've created new worlds to ensure that this isn't a problem in a single one but it persists in each. The ATM discord help channel pointed me towards this github page to create an issue for the mod. I've provided a spark link to demonstrate the lag caused when crafting. https://spark.lucko.me/eXLN0DBlLm

### Steps to reproduce

1. Craft a stack of items
2. Lag

**Comment by LilDyl8** [comment]
Also having the same issue with AE2 terminal, see linked spark log.

https://spark.lucko.me/VjUh84hp7X

Weird thing is that it doesnt happen in a refined grid?

**Comment by desht** [comment]
Yep, there's definitely potential for some lag in the way things are done right now. I'm looking into ways of mitigating this now, will keep you posted. A proper fix is likely to be non-trivial (in particular to avoid situations where valid tasks get missed due to careless optimisation...)

**Comment by mazunki** [comment]
Could clients have an option to disable all/crafting checks, as a temporary fix?

**Comment by LilDyl8** [comment]
> Could clients (or server?, not sure who does the checks exactly) have an option to disable all/crafting checks, as a temporary fix?

There is a progression mode option in the config, problem being it doesn't seem to make a difference wether I have it on Flexi Default or Linear!

**Comment by mazunki** [comment]
`/ftbquests locked true` seems to help!

**Comment by desht** [comment]
Locking the quest book will prevent any lag, but it will also prevent all quest progression, so not really a solution...

I've just pushed a change which should help a lot here, especially if the quest book is very large but only has a small number of tasks that require the item to be crafted (as opposed to just picked up).

If you're prepared to try a dev build, you can download this build of quests: https://maven.ftb.dev/snapshots/dev/ftb/mods/ftb-quests-forge/2001.3.1-SNAPSHOT/ftb-quests-forge-2001.3.1-20240115.153238-3.jar

Would be interested to hear if this helps...

**Comment by dacarmart** [comment]
Tested the build you linked and experienced no lag when crafting with other people as well, thanks for the fix!

**Comment by desht** [comment]
Fixed in 2001.3.1
