### ISSUE TITLE
[Feature Request]: Could I release an addon to any FTB mods?

### ISSUE THREAD

**Issue by KatatsumuriPan** [FTBTeam/FTB-Mods-Issues#1065]
### Mod

Any FTB mods

### Description

Could I release an addon to any FTB mods on Curse Forge or Modrinth?

**Comment by desht** [comment]
Yes, you are allowed to release addons for FTB mods, but we ask that you don't use "FTB" in the mod name.

As an example of a published addon mod, see the [Quests Additions](https://www.curseforge.com/minecraft/mc-mods/quests-additions) mod.

**Comment by KatatsumuriPan** [comment]
OK, thanks a lot!
