### ISSUE TITLE
[Bug]: FTB Quests crashed when clicking "Control+D To Deselect Quests"

### ISSUE THREAD

**Issue by nthxny** [FTBTeam/FTB-Mods-Issues#107]
### Mod

FTB Quests

### Mod version

ftb-quests-forge-1605.3.5-build.72

### Forge / Fabric version

1.16.5

### Modpack & version

Custom, lots of mods.

### What issue are you having?

Crash.

### Crashlogs

[crash-2021-11-06_02.49.47-client.txt](https://github.com/FTBTeam/FTB-Mods-Issues/files/7490003/crash-2021-11-06_02.49.47-client.txt)

### Steps to reproduce

No idea. Just clicked a button.

**Comment by desht** [comment]
Fixed in 1.18/1.19.  Keeping open until next 1.16.5 FTB Library release.
