### ISSUE TITLE
[Bug]: Rendering Layer Crash

### ISSUE THREAD

**Issue by Flabblegast** [FTBTeam/FTB-Mods-Issues#1070]
### Mod

FTB Chunks

### Mod version

ftb-chunks-forge-1802.3.17-build.265

### Forge / Fabric version

1.18.2 40.2.17

### What issue are you having?

I believe this crash is due to what the title says, but it's honestly an educated guess at best. All I really know is that FTB Chunks is crashing my game on launch.

### Crashlogs

Crash Log: https://pste.ch/apafuvepem.pl

### Steps to reproduce

1. Install the modpack attached in the notes
2. Attempt to launch the game

### Anything else to note?

[Initia Nova-FTBRep.zip](https://github.com/FTBTeam/FTB-Mods-Issues/files/13929703/Initia.Nova-FTBRep.zip)

**Comment by Flabblegast** [comment]
Fixed by deleting "forge-client.toml" in config and letting it regenerate itself. Still not sure what was causing it, however.

**Comment by desht** [comment]
There is absolutely nothing here to suggest that FTB Chunks is in any way involved in this crash.
