### ISSUE TITLE
[Bug]: crash in FTB Quests

### ISSUE THREAD

**Issue by Squidistry** [FTBTeam/FTB-Mods-Issues#1072]
### Mod

FTB Quests

### Mod version

ftbquests-forge-2001.3.0

### Forge / Fabric version

1.20.1 47.2.16

### Modpack & version

Ruinous Horizons 

### What issue are you having?

Our server is crashing due to this mod and I'm not quite sure why. It will just randomly do it. 

### Crashlogs

https://mclo.gs/Mrkvutb

### Steps to reproduce

It just happens randomly it seems, hopefully the crash report helps.

**Comment by desht** [comment]
The only way this is likely to be possible is another mod messing with the `DeferredInventoryDetection.playerMap` field from another thread.  FTB Quests (or any other FTB mods) never does this, so I would suggest looking through the mods in your pack for other third party mods which are in any way related to, or addons for, FTB Quests.
