### ISSUE TITLE
[Feature Request]: Expand Availability of FTB Mods to Modrinth

### ISSUE THREAD

**Issue by sauramel** [FTBTeam/FTB-Mods-Issues#1074]
### Mod

FTB Suite of Mods

### Description

The FTB suite of mods, a cornerstone in the Minecraft modding community, is currently exclusive to CurseForge. This exclusivity limits access for a significant portion of the community, especially those who prefer or use only Modrinth for their mod downloads. In light of recent concerns regarding malware on CurseForge, many users are becoming increasingly cautious and are looking for safer, alternative platforms to download their favorite mods. The availability of FTB mods on Modrinth would not only expand their reach and accessibility but also contribute significantly to the health and diversity of the Minecraft modding ecosystem. Offering these mods on Modrinth would provide a safer alternative for users concerned about security and give players more options in how they engage with these mods.

### Describe the solution you'd like

I propose that the FTB suite of mods be made available on Modrinth in addition to their current availability on CurseForge. This move would cater to a broader audience and provide more options for Minecraft players and modders who prefer using different platforms. The inclusion of FTB mods on Modrinth would enhance the platform's offerings and ensure that a wider community can enjoy these high-quality mods.

### Describe alternatives you've considered

While we have considered using alternative mods available on Modrinth, the FTB suite stands out due to its quality, comprehensiveness, and popularity within the Minecraft community. These mods offer unique features and experiences that are hard to replicate with other available mods. Thus, the availability of the FTB suite on Modrinth would be highly beneficial.

**Comment by Don77b** [comment]
+1

**Comment by nvb-uy** [comment]
I think this will benefit both FTB and the whole modding community altogether. Most Modrinth modpacks are using alternatives such as the Odyssey Project (Argonauts, Cadmus, Heracles, etc), which aren't as good as some mods of the FTB suite, but people still will use them for the simple fact that due to the licensing of the mods you cannot include them as overrides.

This would be a huge step considering how popular Modrinth has become, and is growing consistently.

**Comment by DizzXat** [comment]
+1

**Comment by chorbintime** [comment]
+1

**Comment by Xplodin** [comment]
+1 as this would ease lots of developers on modrinth and help them too. Being opposed to this would basically keep curseforge in a somewhat monopoly when it comes to Minecraft modding.
And that wouldnt look good.

**Comment by Jake-E** [comment]
We have publicly stated that we will not be uploading to Modrinth (at least for now) in previous issues and on our Discord, so I'm going to lock this.
