### ISSUE TITLE
[Bug]: FTB Quests Flag "Always Invisible" not hiding chapters outside of edit mode.

### ISSUE THREAD

**Issue by Ghostipedia** [FTBTeam/FTB-Mods-Issues#1075]
### Mod

FTB Quests

### Mod version

ftb-quests-forge-2001.3.0

### Forge / Fabric version

Forge 47.2.16

### What issue are you having?

While working on a questbook for a modpack, I attempted to make a quest chapter 'always invisible' - which I would assume hides the chapter entirely outside of edit mode. 
However, this was not the case. Making it very cumbersome to create hidden logic quests as there is no way to hide the internal page needed.

I have tried in an isolated environment with just the following mods

architectury-9.1.12-forge
ftb-library-forge-2001.1.4
ftb-quests-forge-2001.3.0
ftb-teams-forge-2001.1.4
item-filters-forge-2001.1.0-build.59

I apologize if this is a skill issue on my part, but as far as I understand, the whole chapter is meant to be hidden unless in edit mode.

### Steps to reproduce

To reproduce
Open quest book
Make two chapters, one with the flag "Always Invisible" enabled and one without
Place a quest (Identical or otherwise) in both chapters.
Disable Editing mode
The Chapter flagged to be 'always invisible' is still visible with editing mode disabled.

### Anything else to note?

Images have been attached for clarity
 ![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/46772882/078a54b9-dc87-49b5-9ec8-d12cc788d18c)
![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/46772882/6ae4600d-eaf8-4d12-97bb-27573a819eb5)
![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/46772882/834c3453-75e0-41ce-82f3-014e275fa269)

**Comment by desht** [comment]
Fixed in 2001.3.1
