### ISSUE TITLE
[Bug]: Opening FTB Quests GUI on 1.20.1 0.15.6 Fabric results in crash

### ISSUE THREAD

**Issue by True-Lan** [FTBTeam/FTB-Mods-Issues#1077]
### Mod

FTB Quests

### Mod version

ftb-quests-fabric:2001.3.1

### Forge / Fabric version

1.20.1 0.15.6

### What issue are you having?

Whenever you open the Quests UI it causes a game crash on 1.20.1 Fabric Loader 0.15.6. 
The mods I am running: `Architectury, Fabric API, FTB Quests, FTB Teams, FTB Library, FTB XMod Compact`

### Crashlogs

https://paste.feed-the-beast.com/view/c29047fc

### Steps to reproduce

1. Launch minecraft 1.20.1 with fabric launcher version 0.15.6
2. Get a quest book and open it, or open quests using the icon in the inventory
3. Crash

**Comment by zagdrath** [comment]
Having the same exact issue on NeoForge currently.

**Comment by desht** [comment]
#1080
