### ISSUE TITLE
Textures from this mod have been reproduced in another mod without permission!

### ISSUE THREAD

**Issue by erialsan** [FTBTeam/FTB-Mods-Issues#1079]
### Mod

FTB Industrial Contraptions

### Description

https://www.curseforge.com/minecraft/mc-mods/rtech
This mod
Please respond promptly.
WIRE Texture
Looks like unauthorized use from Mekanism and GregTech as well!

### Describe the solution you'd like

Please bring it up in the forum and advise them to quit using it without permission.

**Comment by desht** [comment]
Looks like the mod in question has no public files to download right now, so I'm guessing they were already taken down? We'll keep an eye on the mod in any case for unauthorised copying.
