### ISSUE TITLE
[Bug]: Opening inventory from quest tab crashes game

### ISSUE THREAD

**Issue by gregoriousbig** [FTBTeam/FTB-Mods-Issues#108]
### Mod

FTB Quests

### Mod version

ftb-quests-forge-1605.3.5-build.72.jar

### Forge / Fabric version

Forge 1.16.5 36.2.4

### Modpack & version

Exigence

### What issue are you having?

Issue: Game crashes when opening inventory from quest tab.

What should be happening: Probably close the quest tab.

### Crashlogs

https://paste.feed-the-beast.com/view/4ebc8396

### Steps to reproduce

1. Open quest tab
2. Press E (or inventory keybind)
3. Crash

### Anything else to note?

Saw this issue on github memory but couldnt find the issue here so I'm posting it again.

**Comment by Raidobw2** [comment]
Hello, your stacktrace shows WorldEditClientUI being the problem. Can you check your keybinds and validate that world edit does not have a keybinding to the "E" letter? Remove it if it does, and try to replicate the crash.

I unfortunately do not have any FTB mod in that stacktrace either, if you have another one containing an error related to FTB mods please post it here.

I'll mark this as "not our fault" until we get a stacktrace that shows FTB mods failing, I hope that's understandable (the dev cannot do anything for now with that log).

Examples contained in your log:

WorldEditCUI:
`at com.github.hexomod.worldeditcuife3.aN.a(KeyBinderManager.java:122) ~[?:3.0.9] {re:classloading}`
Forge hooks:
`at net.minecraftforge.client.ForgeHooksClient.onGuiKeyPressedPost`
Light Weight Java Game Library:
`at org.lwjgl.glfw.GLFWKeyCallback$Container.invoke`
Carry On mod (can pick up chests and carry them around, place them after):
`tschipp.carryon.common.helper.KeyboardCallbackWrapper.keyCallback`
MC Java render engine:
`at com.mojang.blaze3d.systems.RenderSystem.flipFrame`
etc. but no reference to FTB. Those typically start with "dev.ftb.mods" or something similar.

P.S.: When carrying a chest with Carry On, you normally are not supposed to be able to open your inventory. You haven't mentioned anything about that so I'm just adding the info in case you were carrying a chest and if that's the only way to replicate this issue.

**Comment by gregoriousbig** [comment]
Well, luckily there's people who understands crashlogs! Couldnt find a E keybind for worldedit but when disabling the mod the issue was solved. Definitely not your fault.
