### ISSUE TITLE
[Bug]: FTB Quest Crashes ( Ticking Screen ) on version 1.20.1, Forge 47.2.20

### ISSUE THREAD

**Issue by Dracu0** [FTBTeam/FTB-Mods-Issues#1080]
### Mod

FTB Quests

### Mod version

ftb-quests-forge-2001.3.1.jar

### Forge / Fabric version

1.20.1 - 47.2.20

### What issue are you having?

Game instantly crashes when using the button to open the quests menu for FTB Quests, tried with a 200+ mod modpack, and it crashed so i figured I would try with just 4 mods installed in totalm, 4 FTB mods, Library, Quests, Teams and XMod Compat, with just those 4 mods, it's still crashing the same way. The versions used:

ftb-library-forge-2001.1.4.jar
ftb-quests-forge-2001.3.1.jar
ftb-teams-forge-2001.1.4.jar
ftb-xmod-compat-forge-2.1.0.jar

### Crashlogs

Crash log:  https://pste.ch/xinetanaqe.pl
debug.log:  https://pste.ch/qiwufinefo.md

### Steps to reproduce

Open Quests menu.

**Comment by Le-noirrateur** [comment]
I have the same problem :
https://youtu.be/5QSYJuOtBQQ

**Comment by desht** [comment]
Fixed in 2001.3.2
