### ISSUE TITLE
[Bug]: FTB Quests after version 2001.2.1 doesn't have ability to convert item filters w/ tags into items

### ISSUE THREAD

**Issue by muggleorwizard** [FTBTeam/FTB-Mods-Issues#1081]
### Mod

FTB Quests

### Mod version

ftb-quests-forge-2001.3.2

### Forge / Fabric version

1.20.1 47.2.20

### What issue are you having?

FTB Quests after version 2001.2.1 doesn't have ability to convert item filters w/ tags into items. For example, when adding an "OR Filter" with two items in it as an item quest, it uses the filter as the required item, not a choice between the two items in the filter. It works as intended on version 2001.2.1, but does not work on the newest version, 2001.3.2.

### Steps to reproduce

1. Launch forge with FTB Quests ftb-quests-forge-2001.3.2
2. Select an "Or Filter", add two items in it.
3. Select "Or Filter" as item for item quest

**Comment by desht** [comment]
Do you have FTB XMod Compat installed?

**Comment by muggleorwizard** [comment]
yes, and it is up to date.

**Comment by burknado** [comment]
Hey, I found this while googling - I have the exact same issue, and can replicate it from changing versions between 2001.2.1 and 2001.3.2. I'll look into it more tomorrow to see if I can narrow down if there's an incompatibility, as I only ran into it while creating a fairly large modpack.

**Comment by desht** [comment]
> yes, and it is up to date.

By "up to date", I hope you mean 2.1.0?  Explicit version numbers are important here.

**Comment by burknado** [comment]
That ended up fixing it for me at least - Curseforge downloads the old version of XMod by default (v2.0.4) instead of v2.1, and was causing the issue.

**Comment by Rodrigo816** [comment]
I have ftb-xmod-compact-forge-2.10 installed and didn't fix for me
![tag](https://github.com/FTBTeam/FTB-Mods-Issues/assets/12116265/0e557fa6-2724-41cc-a162-9b06fd26bb50)

**Forge / Fabric version**
1.20.1 47.2.18

**Comment by muggleorwizard** [comment]
> > yes, and it is up to date.
> 
> By "up to date", I hope you mean 2.1.0? Explicit version numbers are important here.

I have the latest release version 2.0.4. I can try it with the beta version 2.1.0

**Comment by muggleorwizard** [comment]
Can confirm problem does not exist when using ftb-quests-forge-2001.3.2 and the FTB XMod Compat beta 2.1.0. Forge 47.2.20. Why is FTB XMod Compat beta 2.1.0 in beta? Curseforge won't show an update available unless it is a release.

**Comment by desht** [comment]
I'll get this version promoted to release.  It was marked as beta on upload since it included significant new functionality, but since then release versions of Quests etc. need it, so it should be release now.

**Comment by desht** [comment]
Done now.  FTB XMod Compat 2.1.0 is marked as release.

**Comment by muggleorwizard** [comment]
Thank you so much!
