### ISSUE TITLE
[Bug]: quests in hidden chapters show in search GUI

### ISSUE THREAD

**Issue by Saereth** [FTBTeam/FTB-Mods-Issues#1084]
### Mod

FTB Quests

### Mod version

ftb-quests-forge-1902.5.7-build.326

### Forge / Fabric version

1.12.2

### Modpack & version

FTB Skies

### What issue are you having?

Search for a quest using control+f will allow people to find/navigate to quest chapters that are hidden/should be inaccessible

### Steps to reproduce

make a questline and put some quests on it, hide the questline. goto a visible quest chapter and control+f to search, you'll see the quests in the hidden chapters and can navigate to them.

**Comment by desht** [comment]
Fixed in 1902.5.8
