### ISSUE TITLE
[Bug]: FTBFilteringSystem cause massive (2-3sec) lag on RenderThread when EMI installed (when opening the quest gui)

### ISSUE THREAD

**Issue by SpeeeDCraft** [FTBTeam/FTB-Mods-Issues#1086]
### Mod

FTB Filtering System

### Mod version

FTB Filtering System 1.0.2

### Forge / Fabric version

1.20.1 - 47.2.20

### Modpack & version

TerraFirmaGreg 1.20.1 (v.0.7.0 - unreleased for now)

### What issue are you having?

If 1 or more quests use a filter, then when opening the quest menu with JEI+EMI installed, it will hang for a few seconds, checked with Spark. This problem does not occur with REI and has not been tested with a single JEI.

![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/52341158/ca9ab232-937f-458d-ade2-7cc388881775)

### Steps to reproduce

1. Install our modpack (TerraFirmaGreg on 1.20.1 (v0.6.6) or 0.7.0 if present (then you dont need to do 2, 3 steps))
2. Remove REI and REIPluginCompatibles
3. Install JEI + EMI
4. Enter the game and after EMI initialization try to open quests
5. 2-3sec lag

### Anything else to note?

I do not know if this is due to the number of quests with this filter or something else, I am sure that when deleting ftbfilteringmod everything works fine and there are no freezes, maybe this is a problem with caching, but I do not have time to thoroughly check it right now

**Comment by desht** [comment]
Does this 2-second delay happen every time you open the quest window, or the first time only?

**Comment by SpeeeDCraft** [comment]
First time only.

For example:
1. Starting the game
2. Enter world
3. Wait for EMI init
4. Open quests (game freezes (2-3sec))
5. Close quests or try to open recipe of any quest item (game freezes (2-3sec))
6. Open inventory (game freezes (2-3sec)), but if you before open recipe of any quests item - no freeze
7. After maybe 10-20 minutes, this proccess can be repeat again, randomly

**Comment by SpeeeDCraft** [comment]
I also checked, 1 quest using a filter with an item by tag is enough to check the freeze

**Comment by SpeeeDCraft** [comment]
And with mod called Item Filters, I'm get the same result, I think it's EMI bug, or idk

**Comment by desht** [comment]
The method taking the time is `DisplayStacksCache.getCachedDisplayStacks()`, and I'm not surprised that there's a pause. This method needs to build a client-side cache of all the items in the creative search tabs which would be matched by the filters in use in the quest book (and this is true for both FTB Filter System and Item Filters).

There isn't really a way around this, although trying to do this on a separate thread might be possible if it can be done in a thread-safe way.  I would guess your pack adds a particularly large number of items (looks like Gregtech is in there, so probably yes?)

However the delay should only appear the first time you open the quest book, and not again. The point of building a cache is so this expensive computation needs to be done only once per client startup. If it's occurring frequently, that could be a problem.

**Comment by SpeeeDCraft** [comment]
Yes, we have GregTech. And I understand what a cache is, but there is no problem if use REI, maybe need to add something to EMI? In any case, I have already written to the EMI developer about that on git

**Comment by desht** [comment]
I'm surprised this behaviour differs here between REI and EMI, and I honestly don't believe there's anything EMI can or should be doing to change it.  So I doubt reporting this to the EMI dev will help much. The issue (as the Spark report fairly clearly shows) is the `getCachedDisplayStacks()` call in FTB Quests.

I am investigating a few ways to hopefully mitigate the CPU load here at the moment.

**Comment by SpeeeDCraft** [comment]
to make plugins from other mods work, otherwise the recipes of other mods (which did not make EMI support) do not work. Although it is possible that this somehow fixes emi, but I will assume that it does not

**Comment by SpeeeDCraft** [comment]
Tested 2001.3.3 build for now, the massive lags are gone, it's just a huge job, thank you very much! I think, I can close that, and again thanks a lot :3

One more question, when this fix will be released on curseforge?

**Comment by desht** [comment]
Awesome!  Hoping to get a release out in the next day or two (one other unrelated issue to resolve before a release).
