### ISSUE TITLE
[Feature Request]: Rendering paths for visible quests only

### ISSUE THREAD

**Issue by MrHimera** [FTBTeam/FTB-Mods-Issues#1087]
### Mod

FTB Quests

### Description

We have 3 hidden quests with a dependency on one to complete. If 1 quest is completed, then a hidden quest appears and a path leads from it to others. Is it possible to prevent the quest from rendering paths to still hidden quests? Example on screenshot.
![Quests](https://github.com/FTBTeam/FTB-Mods-Issues/assets/29342708/0587b9d5-b67c-41ce-99bd-2a35ba4fa08b)
![Render](https://github.com/FTBTeam/FTB-Mods-Issues/assets/29342708/034d16fb-6519-4a8e-8f01-0083f64535da)

**Comment by desht** [comment]
I need to see your quests configuration for this so I can reproduce the issue. Can you paste (or attach here), the SNBT file for that chapter please?  i.e. the contents of `config/ftbquests/quests/chapters/<chapter_name>.snbt`

**Comment by MrHimera** [comment]
> I need to see your quests configuration for this so I can reproduce the issue. Can you paste (or attach here), the SNBT file for that chapter please? i.e. the contents of `config/ftbquests/quests/chapters/<chapter_name>.snbt`

https://drive.google.com/file/d/1Z_IeXvD2LUN_u1wCoeKEoqnOmYCUaMgB/view?usp=sharing

**Comment by desht** [comment]
Fixed in 2001.3.3 release
