### ISSUE TITLE
[Bug]: Forced chunks not persisting?

### ISSUE THREAD

**Issue by Affe36963** [FTBTeam/FTB-Mods-Issues#1088]
### Mod

FTB Chunks

### Mod version

ftb-chunks-forge-2001.2.5

### Forge / Fabric version

1.20.1

### Modpack & version

All the mods 9

### What issue are you having?

chunkloading resets on restart

### Steps to reproduce

1. start world
2. claim chunks
3. force load chunks
4. leave world
5. join world
6. open claim manager
7. observe no chunks force loaded

### Anything else to note?

seems to only be a problem if you are not in a team

**Comment by desht** [comment]
Is this in a SSP world or on a dedicated server?

**Comment by Affe36963** [comment]
SSP

**Comment by desht** [comment]
I've tested across a few SSP worlds, and I'm seeing no problems with saved chunk data being persisted across games.  Any chunks I claim and/or forceload stay that after restarting the game, in all cases.

Can you check your `latest.log` for any errors, both when stopping the game, and when starting it again?

**Comment by Affe36963** [comment]
nothing in latest.log but it works now that I createad a team guess it is in the previus logs but i cant open them. Hope you can.
[2024-01-26-6.log.gz](https://github.com/FTBTeam/FTB-Mods-Issues/files/14087064/2024-01-26-6.log.gz)
[latest.log](https://github.com/FTBTeam/FTB-Mods-Issues/files/14087073/latest.log)

**Comment by desht** [comment]
I suspect what happened here is that you connected offline on one of the occasions, maybe due to a network glitch (if the launcher can't reach Mojang's auth servers, you end up offline, with a blank player UUID, and Teams/Chunks see you as a different player).

**Comment by Affe36963** [comment]
It happend again and now i have the current log and i dont think there are any connection problems
[latest.log](https://github.com/FTBTeam/FTB-Mods-Issues/files/14157679/latest.log)

**Comment by desht** [comment]
I can this in your log:
```
[18:21:27] [Server thread/INFO]: all forceloads for team cb03b471-7ea9-4ff6-b50e-9bf549ee2786 have expired due to team inactivity; unforcing 20 chunks
```
Looks like you have an inactivity timeout set in your server config?  What is `max_idle_days_before_unforce` set to in `serverconfig/ftbchunks-world.snbt` ?
