### ISSUE TITLE
[Feature Request]: Popup list on hover

### ISSUE THREAD

**Issue by MrHimera** [FTBTeam/FTB-Mods-Issues#1090]
### Mod

FTB Quests

### Description

Is it possible to somehow remove the pop-up list when hovering over a quest parameter (names of achievements, mobs, structures, biomes), otherwise with a large number of mods this causes a strong drop in FPS?

![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/29342708/18b7050b-2df6-4211-8c77-4457b15ff484)

**Comment by MrHimera** [comment]
Thank you

**Comment by desht** [comment]
Fixed in FTB Library 2001.2.0
