### ISSUE TITLE
[Bug]: Old-style Scroll Wheel Behavior is not loaded correctly on local world

### ISSUE THREAD

**Issue by drakray** [FTBTeam/FTB-Mods-Issues#1091]
### Mod

FTB Quests

### Mod version

ftb-quests-forge:2001.3.3

### Forge / Fabric version

NeoForge 47.1.96 for 1.20.1

### What issue are you having?

Trying to set `Old-style Scroll Wheel Behavior` to `TRUE`, work after being set, but config return to `FALSE` after restarting
Didn't test on server, only local play
Quitting and reopening the world without closing the game, the config is still `TRUE`
`old_scroll_wheel: true` is set in `"local\ftbquests\client-config.snbt"` even before starting the game, but config is still `FALSE` when opening the world unless changed at least once after launching the game, which imply FTBQuest is not checking the config on load, but remember if modified?

Also, the config is client-wide, not world specific(which is probably intended which is ok)

### Steps to reproduce

1. Set the config to TRUE in `Player Preferences`
2. Restart client
3. Repeat 1, because it didn't load properly

**Comment by drakray** [comment]
Also, the `Player Preferences` UI doesn't respect the `pause_game` setting

**Comment by desht** [comment]
Both issue will be fixed in next release (also yes it is intentional that player preferences are global to the client, and not per-world).

**Comment by drakray** [comment]
hi @desht ,sorry to bother you, but is there an ETA for the next 1.20.1 version of FTB Quest with the fix for this?
Thank you for your good work :D

**Comment by desht** [comment]
Should be able to get something out this week.

**Comment by desht** [comment]
Fixed in 2001.3.5 release
