### ISSUE TITLE
[Feature Request]: Allow the trash can to be disabled

### ISSUE THREAD

**Issue by StardustPassingBy** [FTBTeam/FTB-Mods-Issues#1092]
### Mod

FTB Essentials

### Description

I'm not fond of inventory trash and would like players to have to craft actual in world trash cans instead, but am unable to find any option to do so.

### Describe the solution you'd like

A config option or command to disable the trash can.

### Describe alternatives you've considered

Deleting sidebar_buttons.json in the mod file seems to accomplish the job but is obviously a very hacky workaround.

**Comment by desht** [comment]
Trash functionality is actually in two places, and can be disabled without requiring any updates to mod:

1. Server-side: disable the trashcan in `serverconfig/ftbessentials.snbt` with:
```
 # Enables usage of a trash can inventory, which can be used to void unneeded items
                trashcan: {
                        # Default: true
                        enabled: false
                }
```

That will disable the `/trash` command. This can be done in `defaultconfigs/ftbessentials.snbt` if you're developing a modpack.

2. Client-side: you can get rid of the trash icon with a custom resource pack.  Override `assets/ftbessentials/sidebar_buttons.json` with a blank JSON document:
```json
{
}
```
