### ISSUE TITLE
[Bug]: FTB Teams Claim bypass with modded Item

### ISSUE THREAD

**Issue by bookerthegeek** [FTBTeam/FTB-Mods-Issues#1094]
### Mod

FTB Teams

### Mod version

ftb-teams-forge-2001.1.4

### Forge / Fabric version

forge-1.20.1-47.2.20

### Modpack & version

ATM9 0.2.43

### What issue are you having?

The following items from the mod Blood Magic bypass the claim protection.

Items:
```
Name: Shaped Charge
ID: bloodmagic:shaped_charge

Name: Augmented Shaped Charge
ID: bloddmagic:aug_shaped_charge

Name: Tunneling Shaped Charge
ID: bloodmagic:shaped_charge_deep

Name: Deforester Charge
ID: bloodmagic:deforester_charge

Name: Controlled Charge
ID: bloodmagic:veinmine_charge

Name: Fungal Charge
ID: bloodmagic:fungal_charge

Name: Deforester Charger II
ID: bloodmagic:deforester_charge_2

Name: Controlled Charge II
ID: bloodmagic:veinminer_charge_2

Name: Fungal Charge II
ID: bloodmagic:fungal_charge_2
```

### Steps to reproduce

Testing Methodology:

- 1st Test

    - Look at a block that is inside a claim while being close enough to interact with the block
    - Your location inside or outside the claim does not matter
    - Right click while holding any of the above items while looking at the block
    - Claim protections block placement of item
- 2nd Test
    - Look at a block that is inside the claim while being far enough away to not interact with it
    - Your location inside or outside the claim does not matter
    - Right click while holding any above item
    - This causes a mod feature of being able to throw the item causing it to fly to the block you are looking at
    - Claim protections do not block placement of item
    - The item (now a block placed in the world) functions as if not in a claim at all.

**Comment by stellanera98** [comment]
On tick method of the entity spawned by these items when not being able to interact with a block.
https://github.com/WayofTime/BloodMagic/blob/1.20.1/src/main/java/wayoftime/bloodmagic/entity/projectile/EntityShapedCharge.java#L70

**Comment by desht** [comment]
Not an FTB Chunks problem.  The entity is setting blockstates without firing any block place events so there's absolutely nothing FTB Chunks can do about it.  Ask the author of Blood Magic to fire the appropriate event.
