### ISSUE TITLE
[Bug]: ftbchunks:interact_whitelist doesnt work on lootr chests

### ISSUE THREAD

**Issue by sprocketaudio** [FTBTeam/FTB-Mods-Issues#1097]
### Mod

FTBChunks

### Mod version

ftb-chunks-forge-1902.4.4-build.326

### Forge / Fabric version

Forge 43.3.7

### What issue are you having?

I have added the tag ftbchunks:interact_whitelist to lootr chests and barrels using kubeJS and although I can give myself a lootr chest/barrel using the /give command and can see the tag on it, if I place one down in a claimed area (using /ftbchunks admin bypass_protection), then remove the bypass, I then can not open that lootr chest/barrel.

![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/13222732/352db2b0-a255-4819-9bce-598089bf2086)

### Steps to reproduce

Added above.

**Comment by kirarcangell** [comment]
also with fabric

**Comment by desht** [comment]
Please show exactly what kubejs config you've used to add the tags.

**Comment by kirarcangell** [comment]
here's mine,
![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/157147879/710823b8-97d0-4d8d-9996-065e64eadf75)

**Comment by desht** [comment]
Right, the _item_ tag doesn't work for _blocks_.

You need to add the `#lootr:containers` tag to the `ftbchunks:interact_whitelist` block tag.

The item tag is `ftbchunks:right_click_whitelist`, for reference.  See https://github.com/FTBTeam/FTB-Chunks/blob/main/common/src/main/java/dev/ftb/mods/ftbchunks/api/FTBChunksTags.java

**Comment by sprocketaudio** [comment]
Sorry yes for clarity here is mine

![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/13222732/674ea015-9cb7-444c-a31f-1011b1f5e4c7)

So you are saying I need to use block tag ?  like this?

ServerEvents.tags('block', event => {

  event.add('ftbchunks:interact_whitelist', 'lootr:lootr_chest')
})

**Comment by kirarcangell** [comment]
> Sorry yes for clarity here is mine
> 
> ![image](https://private-user-images.githubusercontent.com/13222732/333829394-674ea015-9cb7-444c-a31f-1011b1f5e4c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3MDA5OTEsIm5iZiI6MTcxNjcwMDY5MSwicGF0aCI6Ii8xMzIyMjczMi8zMzM4MjkzOTQtNjc0ZWEwMTUtOWNiNy00NDRjLWEzMWYtMTAxMWIxZjVlNGM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI2VDA1MTgxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlYTE5ZjRmMjBmNTM0ODhmOGNhNDJmZWMzZDc0YjE1YzVhZWY1ZWRjNWQ5ZTI4OTg4MWI3NWExMGIyYTYyMmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.j2Xdj7oGgyY-QetsknVdKB3z8zweozbxI0U9RMjhnS4)
> 
> So you are saying I need to use block tag ? like this?
> 
> ServerEvents.tags('block', event => {
> 
> event.add('ftbchunks:interact_whitelist', 'lootr:lootr_chest') })

Yes its working now that i changed *item* for *block*
