### ISSUE TITLE
[Bug]: Build Gadgets (all tools from mod) bypass claims

### ISSUE THREAD

**Issue by bookerthegeek** [FTBTeam/FTB-Mods-Issues#1099]
### Mod

FTB Teams & FTB Chunks

### Mod version

ftb-teams-forge-2001.1.4
ftb-chunks-forge-2001.2.5

### Forge version

47.2.20

### Modpack & version

ATM9 2.48

### What issue are you having?

The items from DW20 Building Gadgets ignore the claim

### Crashlogs

No Crash

### Steps to reproduce

- Claim chunks
- Have someone not trusted use items on blocks inside your claim

This also happens with ONLY FTB Mods and Building gadgets installed on a Forge server instance.

### Anything else to note?

A poorly written report was made on the Building Gadgets GitHub [HERE](https://github.com/Direwolf20-MC/BuildingGadgets2/issues/66)

**Comment by desht** [comment]
Not a FTB Chunks issue. Building Gadgets needs to be firing the appropriate block place/break events.
