### ISSUE TITLE
[Bug]: FTB Library crashes 1.17.1 when needed by JEI

### ISSUE THREAD

**Issue by Agamemnon128** [FTBTeam/FTB-Mods-Issues#11]
### Mod

FTB Library

### Mod version

ftb-library-forge-1605.3.3-build.74

### Forge / Fabric version

1.17.1 37.0.68

### What issue are you having?

FTB Library is crashing the game, I have all the needed mods and its having an issue.

### Crashlogs

https://paste.feed-the-beast.com/view/19acc11e

### Steps to reproduce

If I delete FTB Library and Architectury, the issue goes away, however, I cannot configure JEI then.

**Comment by Raidobw2** [comment]
Would it be possible to have the crash mentioned at `Twitch\Minecraft\Instances\Better Minecraft [FORGE] - 1.17.1\crash-reports\crash-2021-10-04_22.42.18-fml.txt`? The latest.log does contain some info but having the crash in its original format would be appreciated (to get the full stacktrace for example).

For the mod dev:
Failed to create mod instance. ModID: ftblibrary, class dev.ftb.mods.ftblibrary.forge.FTBLibraryForge
java version 16.0.1
java.lang.reflect.InvocationTargetException: null
Minecraft 1.17+ now uses Java 16 by default, so this indeed looks like a bug

**Comment by Raidobw2** [comment]
Actually, my mistake. Ignore the crash report request. There is currently no file for FTB Library that supports Minecraft 1.17.1 -- please report this to Better Minecraft instead or ask for support on their Discord. They might be using another version of Java, as Java 16 will make it crash 100% of the time, currently, as it was not ported to 1.17.1 yet.

Please take a look at https://www.curseforge.com/minecraft/mc-mods/ftb-library-forge/files, where the last file is still mentioned as supporting 1.16.5, not 1.17.1. Looking through recent commits also show no sign of releases/version changes for 1.17.1.
Sorry but it's not ported yet!
