### ISSUE TITLE
[Bug]: Item Select menu always defaults to JEI mode, rather than the mode it was on before

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-Mods-Issues#110]
### Mod

FTB Quests

### Mod version

ftb-quests-forge-1605.3.5-build.72

### Forge / Fabric version

1.16.5 36.2.4

### What issue are you having?

Before, whatever item search mode you were using would stay persistent. If you switched over to inventory mode, it would stay in inventory mode every time you opened the menu again. Now, it opens in JEI mode every time. If I want to grab a Filter out of my inventory (which I have to do a *lot*), I have to click this button twice. Every time.
![image](https://user-images.githubusercontent.com/15698722/140640482-6e60d74e-f863-4f17-ae1b-e93a7ef47951.png)

### Steps to reproduce

N/A

**Comment by desht** [comment]
Fixed in latest quests releases
