### ISSUE TITLE
[Feature Request]: Allow exclusion from claim all

### ISSUE THREAD

**Issue by ceejayvee523** [FTBTeam/FTB-Mods-Issues#1100]
### Mod

FTB Quests

### Description

I have a few different quests that teleport the player, therefore I have to warn them not to click claim all. It would be very nice if there were quests that could be excluded from being hit by claim all rewards.

### Describe the solution you'd like

A simple toggle like, Is Secret or Always Invisible but for Disable Claim All Rewards

**Comment by desht** [comment]
That's already a thing.  Just set "Exclude from Claim All" to true for the rewards you don't want claimed.

![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/736831/e1bdb5c1-6dae-4e05-be21-f51c52accf2a)

**Comment by ceejayvee523** [comment]
I'm sorry. I should have been more clear. I am running this with Pixelmon, so I am using the 1.16 version. Does this feature exist in that version because I do not see it.
