### ISSUE TITLE
[Bug]: Quests Theme does not effect flexible quest's dependency lines

### ISSUE THREAD

**Issue by ThePansmith** [FTBTeam/FTB-Mods-Issues#1106]
### Mod

FTB Quests

### Mod version

latest

### Forge / Fabric version

1.20.1

### What issue are you having?

The color of the dependency lines is not effected by your questbook theme if it is using the flexible quest type.
![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/70342772/167bc399-a2a3-40a6-847a-41d413fc0e50)

### Steps to reproduce

1. Make a quest with a flexible dependency
2. Try to make a custom theme
3. Notice that it does not work as intended

**Comment by desht** [comment]
Dependency line colouring has nothing to do with flexible quest progression.  That pale washed-out red tint is always used for uncompleted dependency lines.

Having said that, this colour should really be configurable, so I will add an theming entry for them.
