### ISSUE TITLE
[Bug]: FTBRanks=An unexpected error occurred while trying to execute the command

### ISSUE THREAD

**Issue by QianMuu** [FTBTeam/FTB-Mods-Issues#1108]
### Mod

FTBranks

### Mod version

ftb-ranks-forge-1902.1.16-build.98

### Forge / Fabric version

1.19.2-1902.1.16

### What issue are you having?

An unexpected error occurred while trying to execute the command
![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/50398180/a8a1351d-b634-4827-a495-f5a463058c79)

### Crashlogs

My log：.https://pste.ch/oginofikop.md

### Steps to reproduce

All commands I type regarding "ftbranks" fail.
An unexpected error occurred while trying to execute the command

**Comment by desht** [comment]
From your server log:

```
[04Mar2024 23:22:13.791] [Server thread/ERROR] [FTB Library/]: Failed to read .\world\serverconfig\ftbranks\players.snbt: Unexpected end of file!
```

Your `players.snbt` file is corrupt. Please fix this problem and see if you have still have issues with FTB Ranks.

(If you're not sure how to fix it, you can paste a copy somewhere and I will take a look)
