### ISSUE TITLE
[Bug]: Cannot reset progress of a command reward

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-Mods-Issues#111]
### Mod

FTB Quests

### Mod version

ftb-quests-forge-1605.3.5-build.72

### Forge / Fabric version

1.16.5 36.2.4

### What issue are you having?

I'm trying to basically fake a repeatable quest, since those don't exist anymore.

![image](https://user-images.githubusercontent.com/15698722/140647903-ebc7a287-e44a-47e5-b716-5dab606b0241.png)
This quest reward resets the quest when claimed, resetting the progress of the quest and the other 2 rewards. It does not reset itself, though.

I thought you just couldn't have rewards reset *themselves*, but I also can't reset it from the context menu.
![image](https://user-images.githubusercontent.com/15698722/140647927-821ea856-43e4-4f91-91de-bf85582641b7.png)
Clicking this does nothing.

### Steps to reproduce

N/A

**Comment by aaronhowser1** [comment]
![image](https://user-images.githubusercontent.com/15698722/140647954-43c2b6c3-b678-4d74-9842-a5f2ab3a12f8.png)
Resetting progress from here also doesn't reset that specific reward.

**Comment by aaronhowser1** [comment]
![image](https://user-images.githubusercontent.com/15698722/140648841-8cf6a2ac-d2f6-4988-b6d8-7b4331a5bfe1.png)
Fascinating, leaving and joining the world shows the reward as being unclaimed again.

**Comment by desht** [comment]
Fixed in latest 1.16.5 release
