### ISSUE TITLE
Controller mod

### ISSUE THREAD

**Issue by xMariaGariax** [FTBTeam/FTB-Mods-Issues#1116]
### Mod

FTB 

### Description

Not much of a keyboard girlie and I've been doing some research but is there anyway to add a controller mod to play the FTB servers with

### Describe the solution you'd like

.

### Describe alternatives you've considered

.

**Comment by desht** [comment]
We don't explicitly support any controller mods, but we also don't do anything to prevent their use with our mods.

You could try a mod such as Controllable: https://www.curseforge.com/minecraft/mc-mods/controllable

Note: I've not tried this myself, so can provide no guarantees on whether it'll work. FTB don't provide support for Controllable, but it looks like the mod author has a Discord server if you need to ask them any questions.
