### ISSUE TITLE
[Bug]: I can't paste the ID of a quest.

### ISSUE THREAD

**Issue by Dreavurus** [FTBTeam/FTB-Mods-Issues#1117]
### Mod

FTB QUEST

### Mod version

ftb-quest-forge-1605.3.7-build.165.jar

### Forge / Fabric version

1.16.5 Forge 36.2.34

### Modpack & version

My own modpack

### What issue are you having?

I'm creating a Pixelmon modpack with quests, and while I was working on the quests, I realized that a very important and valuable feature was missing, which is the ability to copy a quest by copying its ID and pasting it in the desired area. I can't find a button, function, command, or setting that allows me to paste a quest. I've searched everywhere and can't find a solution to this.

### Steps to reproduce

1.open the quest menu in-game.
2.enter the chapter where I want to edit the quests.
3.right-click on a quest.
4.copy the ID of that quest.
5.try to paste it using Ctrl+V, but it doesn't work.

### Anything else to note?

I'm using PixelTweaks a side mod for Pixelmon, which bridges between Pixelmon and FTBQuest.

**Comment by desht** [comment]
The 1.16.5 version is very old and not receiving new features, sorry. Update to 1.19/1.20 if you want to be able to paste quest id's.
