### ISSUE TITLE
[Bug]: Dependency Lines are drawn underneath Images in 2001.3.4

### ISSUE THREAD

**Issue by katubug** [FTBTeam/FTB-Mods-Issues#1119]
### Mod

FTB Quests

### Mod version

ftb-quests-forge-2001.3.4.jar

### Forge / Fabric version

1.20.1 47.2.20

### What issue are you having?

My quest dependency lines have all disappeared beneath the images I am using as backgrounds. I have attempted to use the "image ordering" to set them lower, but they're all at 0 and negative numbers don't seem to have an effect. Then I thought, maybe I read it wrong, so I tried higher numbers, and that didn't work either.

Example:
https://i.imgur.com/UkQn3nv.png

### Steps to reproduce

1. Place an image behind 2 dependent quests
2. Watch the dependency lines go poof

**Comment by desht** [comment]
Confirmed, sorry about that. Will fix for the next release.

**Comment by katubug** [comment]
Thanks so much!

**Comment by desht** [comment]
Fixed in 2001.3.5 release
