### ISSUE TITLE
[Bug]: Map crash when entering certain chunks on ATM6

### ISSUE THREAD

**Issue by SithKillerAlpha** [FTBTeam/FTB-Mods-Issues#112]
### Mod

FTB Chunks

### Mod version

ftb-chunks-forge-1605.3.2-build.69.jar

### Forge / Fabric version

1.16.5 36.2.8

### Modpack & version

ATM6

### What issue are you having?

Entering certain chunks on a server running ATM6 would crash the server and output a error on the client. 

### Crashlogs

https://pastebin.com/raDJS4r2

### Steps to reproduce

1. Chunk load chunks that have tile entities ticking
2. Move to chunks outside of the load distance of the previous chunks
3. Leave the server
4. Load server and enter chunks
5. Crash

### Anything else to note?

This issues seems hard to replicate and may just be simple mod incompatibility.

**Comment by desht** [comment]
There's nothing at all of use in the "crash log" attached to this ticket.  Need a valid crash log, including stack trace, to investigate this.
