### ISSUE TITLE
[Feature Request]: FTB Quests 1.20.2 port finished

### ISSUE THREAD

**Issue by wop0911** [FTBTeam/FTB-Mods-Issues#1120]
### Mod

FTB Quests

### Description

I have noticed that the move to 1.20.2 has been on indefinite pause for at least three months that I have seen.

### Describe the solution you'd like

Mods like Pixelmon have some integrations created, and are waiting for this update to finish so we can continue on with adventure/story projects. If at all possible could we get some clarification on what is happening with the 1.20.2 update?

### Describe alternatives you've considered

Honestly, there really isn't. Custom NPCs are still stuck on 1.18. Citizens is a learning curve, and our own Pixelmon quest system is currently under heavy rework with no indication of when it will be done/usable.

**Comment by desht** [comment]
There will never be a 1.20.2 release.  The next version supported will be for 1.20.4, which is happening very soon.
