### ISSUE TITLE
[Bug]: Problems with taskscreens using schematics (.nbt and .schem)

### ISSUE THREAD

**Issue by dotdotdotdotdotdot** [FTBTeam/FTB-Mods-Issues#1122]
### Mod

FTB Quests

### Mod version

ftb-quests-fabric-2001.2.0.jar

### Forge / Fabric version

1.20.1 0.15.7

### What issue are you having?

Problem arises when you have a task screen in your build and paste the schematic, the task screen stop working and prints error in console.

### Crashlogs

There is none

### Steps to reproduce

1. Place a Task Screen from FTB Quests
2. right click the task screen to check if it works
3. create a schematic using create mod or worldedit
4. paste the schematic next to the working task screen
5. see that the new tast screen doesnt work.

**Comment by Samme20** [comment]
I have the same issue. Would be very useful for datapacks with quests.

**Comment by desht** [comment]
This isn't supportable, no.

One of the critical fields of the Task Screen block entity is the team UUID to which it's connected (so it knows whose progress to update when items/fluids/energy is inserted).

Pasting a saved Task Screen will paste whatever team it was created with, which (if you're pasting from a datapack into another instance) won't be a valid UUID for a team on that server.

Sorry, not possible.
