### ISSUE TITLE
[Bug]: FTB utilities, command permissions

### ISSUE THREAD

**Issue by somebush** [FTBTeam/FTB-Mods-Issues#1124]
### Mod

FTB utilities

### Mod version

FTBUtilities-5.4.1.131.jar

### Forge / Fabric version

Minecraft: 1.12.2, Forge: 14.23.5.2859

### What issue are you having?

I want players to have access to a specific two-part command, such as `/srpevolution getphase`, but not to have access to other commands that begin (in the case of my example) with `/srpevolution`. I couldn't get the mod to work as I described.

### Steps to reproduce

1. In the file `.minecraft\local\ftbutilities\ranks.txt` write
```
[player]
default_player_rank: true
power: 1
command.srpevolution.getphase: true
command.seed: false
command.weather: true
```

2. Create a single player world in survival mode with cheats turned off.

3. You cannot use the `/seed` command, you can use the `/weather` command. Corresponds to what is written in the file. But you can't use `/srpevolution getphase` even though this command is allowed.

**Comment by MichaelHillcox** [comment]
The `1.12` version of our mods are no longer supported. The issue you have mentioned is most likely an issue with the mods implementation of their command and not with our mod.
