### ISSUE TITLE
[Bug]: FTB Chunks - Long Range Tracker Interval server crash.

### ISSUE THREAD

**Issue by Gbergz** [FTBTeam/FTB-Mods-Issues#1125]
### Mod

FTB Chunks x FTB Teams

### Mod version

ftb-chunks-forge-2001.2.6.jar

### Forge / Fabric version

47.2.17

### Modpack & version

TNP Limitless 7 - v1.0.0

### What issue are you having?

There seems to be some issues with the Long Range Tracker within FTB Chunks.
Getting crashes randomly on our public servers.

```java.lang.NullPointerException: Cannot invoke "dev.ftb.mods.ftbchunks.data.ChunkTeamDataImpl.canPlayerUse(net.minecraft.server.level.ServerPlayer, dev.ftb.mods.ftbteams.api.property.PrivacyProperty)" because "p2Team" is null```

### Crashlogs

https://gist.githubusercontent.com/Gbergz/c92667499694171a18c0f4b0c9346739/raw/89de56073f98a48e785ae492ef007eb0663cfca8/gistfile1.txt

### Steps to reproduce

I am currently not sure how to reproduce the issue as it seemed pretty random.
But what I gathered from the crash report is that it's tied to the ``long_range_tracker_interval`` option in the serverconfig.
As when it's turned to 0 it doesn't happen.

### Anything else to note?

None.

**Comment by desht** [comment]
Looking at the code, this is one of those "should never happen" issues (and I've never seen it happen - no idea how to reproduce it).

I can add some code to prevent the crash, but the fundamental problem is FTB Teams not having a record of the target player, which should never be the case, and I'm not sure what circumstances could cause that.

**Comment by desht** [comment]
Fixed in 2004.2.7 release
