### ISSUE TITLE
[Bug]: Quests on server don't render quest requirement options when FFS is used.

### ISSUE THREAD

**Issue by DragonS0u1623** [FTBTeam/FTB-Mods-Issues#1127]
### Mod

FTB Filter System 

### Mod version

ftb-filter-system-forge-1.0.2

### Forge / Fabric version

Forge 1.20.1 47.2.20

### What issue are you having?

When creating quests I used FFS to select tags or multiple items as it was quick and relatively simple. But when I went to test on server what quests looked like all the quests that I used FFS to select the items just rendered the Filter tool instead of the items matching the tag.
Client quest view:
![2024-03-24_14 31 11](https://github.com/FTBTeam/FTB-Mods-Issues/assets/24501666/20c87367-d923-4c67-a89a-da1c47d3c25e)

Server quest view:
![2024-03-24_14 29 28](https://github.com/FTBTeam/FTB-Mods-Issues/assets/24501666/5cfd9d5c-0c81-460c-98dc-b69568a5e7ce)

### Steps to reproduce

1. Select a tag or multiple items using FFS Filter tool in single player
2. Create a quest that uses the filter tool as the requirement item
3. Copy the quests config over to a server (as every quest modpack does in their server pack)
4. View the quests as a client on the server

**Comment by desht** [comment]
This would happen if the filters you created don't match any items in the client's creative search tab.  FTB Quests & FFS evaluate (and cache, of course) each filter to check what items in the creative list are actually matched by the filters in use.

The client you created the quests on clearly does have matching items in its creative list, so is there any difference between that client and the client you use to connect to the server?

**Comment by DragonS0u1623** [comment]
No obvious change in the client between loading the single player world and the server. I didn't change any tags, add or remove any mods or anything. The only difference is loading a single player world and connecting to a server. It even happens in the same game instance, so it's not just a strange first load interaction.

**Comment by desht** [comment]
I think I'll need see your quest book data to have a chance of debugging this...

**Comment by DragonS0u1623** [comment]
Okay where can I find that information? Is it the ftbquests config folder, or something else?

**Comment by desht** [comment]
Yep, `config/ftbquests/`

**Comment by DragonS0u1623** [comment]
Alright this is the quests folder from right inside the `config/ftbquests` directory
[quests.zip](https://github.com/FTBTeam/FTB-Mods-Issues/files/14779793/quests.zip)

**Comment by desht** [comment]
I've just loaded your "Basic Storage" chapter into my test dedicated server, which has Sophisticated Storage/Sophisticated Core/Functional Storage installed, and it worked fine (the "Any of" filters all cycle through the options as expected):

![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/736831/eb3d9bf7-b415-47b2-83e6-ea838a733ac3)

(The missing items there are from Ender Chests, which I don't have installed right now)

So I'm honestly not sure what's happening for you. My client has no trouble finding the matching items...

Do you have any errors in your client or server log?

**Comment by DragonS0u1623** [comment]
So in single player the issue doesn't appear. Everything loads and renders fine.
It's only on server that the icons don't render.
This is the logs for the server start, but looking over it I personally don't see anything that's out of the ordinary for a modpack with over 100 mods, especially one that is comparable in size to ATM9
https://mclo.gs/qA9QTqb

**Comment by desht** [comment]
Sorry for the delay, but I have a dev build which might help?  (hard to know for sure without some testing)

Are you in a position to try this build and see if it helps: https://maven.ftb.dev/snapshots/dev/ftb/mods/ftb-quests-forge/2001.4.7-SNAPSHOT/ftb-quests-forge-2001.4.7-20240703.105648-1.jar
