### ISSUE TITLE
[Feature Request]: Chest Privacy

### ISSUE THREAD

**Issue by KeenanVH-AS** [FTBTeam/FTB-Mods-Issues#1128]
### Mod

FTB Chunks

### Description

I've noticed that players keep complaining that items from other mods bypass the FTB chunk claim privacy when it comes to chests have had multiple complaints of people using the RFTools storage scanner to scan for chests that are in other players claimed chunks and steal the items from those chests using the storage scanner to see the inventories.

### Describe the solution you'd like

Could there be a way to lock chests to the player who has claimed the chunk almost like the effect that the ender chest has? Could it be that there is a setting in the FTB chunks menu that needs to be enabled on servers that help with this issue?

### Describe alternatives you've considered

have tried using plugins and mods to monitor chest activity and they simply do not work. Mekanism has personal chests. Security craft has a locking function. None of these matter as the chests are still discoverable via the storage scanner.

**Comment by desht** [comment]
This is something that would have to be added to RFTools, not FTB Chunks. The Storage Scanner just scans nearby chests; it doesn't currently care about what protection other mods impose on their inventories, or indeed vanilla inventories, so there's nothing FTB Chunks can do here to stop it.

A good solution would be to request from McJty (RFTools author) that the mod fires an event of some kind when it's about to scan an inventory. Then mods like FTB Chunks would be able to listen to this event and prevent the interaction. (Note: I don't know if that's feasible from an RFTools point of view, but it's the right way to do it).
