### ISSUE TITLE
[Bug]: Server side: Mod loading error has occurred.

### ISSUE THREAD

**Issue by Gbergz** [FTBTeam/FTB-Mods-Issues#1129]
### Mod

FTB XMod Compat x FTB Quests

### Mod version

ftb-xmod-compat-forge-2.1.0.jar

### Forge / Fabric version

Forge 47.2.17

### Modpack & version

https://legacy.curseforge.com/minecraft/modpacks/tnp-limitless-7

### What issue are you having?

Sometimes (rarely) when the server starts it results in a crash (Mod loading error has occurred).

### Crashlogs

https://gist.githubusercontent.com/Gbergz/ebfff882294afab8f1dfcb6c081fa4a8/raw/3dd08757c1e0c352d33b973299cae7c18c689d27/gistfile1.txt

### Steps to reproduce

Since it's not always its:

1. Start server.
2. Wait.
3. Modloading error.
profit.

### Anything else to note?

None.

**Comment by Gbergz** [comment]
Scratch that it's rare. This happens way too often. Atleast 3-4+ times a day when the server restarts.

**Comment by desht** [comment]
Are you in a position to test a dev build?  If so: https://maven.ftb.dev/snapshots/dev/ftb/mods/ftb-xmod-compat-forge/2.1.1-SNAPSHOT/ftb-xmod-compat-forge-2.1.1-20240328.155215-1.jar

This isn't a problem I've been able to reproduce myself, but I think the fix I've added will solve the crash you're seeing.

**Comment by Gbergz** [comment]
Is this a fix that can be deployed on a server without the clients needing the new jar file aswell ? If so I can test for awhile.

**Comment by desht** [comment]
Yes, it should be compatible. No network protcol changes or anything like that.

**Comment by Gbergz** [comment]
Alright, sweet. 👍 
Will test for a bit then

**Comment by Gbergz** [comment]
So far, no issues. 
So probably fixed, but if it happens again I'll write here.

**Comment by desht** [comment]
Sorry for the delay, been out of town. There will be a new release today.
