### ISSUE TITLE
[Bug]: Color Picker 

### ISSUE THREAD

**Issue by UnRealDinnerbone** [FTBTeam/FTB-Mods-Issues#1130]
### Mod

FTB Library

### Mod version

2004.2.1

### Forge / Fabric version

20.4.212

### What issue are you having?

Color Picker GUI jumps around when changing brightness
https://github.com/FTBTeam/FTB-Mods-Issues/assets/8102498/68ca904c-49a5-468b-9a6b-6a8f350b8d6b

### Steps to reproduce

1. Change color brightness in Color Picker GUI

**Comment by desht** [comment]
Fixed in FTB Library 2004.2.2 (also now backported to latest 2001.2.0 release :partying_face: )
