### ISSUE TITLE
[Bug]: Couple of commands not working anymore in 1.20.4

### ISSUE THREAD

**Issue by AutumnGamer** [FTBTeam/FTB-Mods-Issues#1131]
### Mod

FTB Essentials

### Mod version

FTB Essentials Fabric v2004.1.1

### Forge / Fabric version

Fabric Loader 0.15.7 1.20.4

### What issue are you having?

In the version for 1.20.4 I noticed some commands aren't working:

- /anvil
- /crafting or /workbench
- /smithing
- /stonecutter
- /tpl (not sure if this would work with more then 1 player, but other multiplayer commands did exist)

I have also tested this in a separate new and clean minecraft version with only the necessary mods to exclude incompatibility issues. These are the versions used in the test modpack:

- Fabric API v0.96.11
- Architectury v11.1.17
- FTB Library v2004.2.1
- FTB Essentials v2004.1.1

### Steps to reproduce

 - Open up any world in MC 1.20.4 with Fabric Loader 0.15.7 with the 4 mods listed above.
 - Try to use any of the listed commands
 - Minecraft will tell you it is an unknown command.

**Comment by MichaelHillcox** [comment]
Hey! Thanks for reaching out. I've just pushed a fix to resolve the `/anvil` etc commands now showing up.

Please note, they have now been moved under the `/open` namespace making `/anvil` be `/open anvil`

`/tpl` is now `/teleport_last`

I've updated the changelog to reflect these changes

https://github.com/FTBTeam/FTB-Essentials/releases/tag/v2004.1.2-beta

This should be on curseforge soon :+1:
