### ISSUE TITLE
[Feature Request]: Faster way to make dependency lines

### ISSUE THREAD

**Issue by wolfieboy09** [FTBTeam/FTB-Mods-Issues#1133]
### Mod

FTB Quest

### Description

Making a dependency from quest A to quest B is just WAY too long, and it's hard to find the exact quest with other quests as well in the list.

### Describe the solution you'd like

Dragging dependencies lines instead of having to go the long way (lots of clicking!!)
To right-click a quest, press "make dependency line", and it will follow your mouse until you click another quest to finish the line.
Only takes three clicks for this feature!

**Comment by desht** [comment]
You can already select one or more quests (ctrl-click it, or middle-click to drag a box), and then right-click another quest and select "Add selected as dependencies" or "Add as dependency to selected".  Which is pretty much what you're asking for in a slightly different form.

Editing quests via the quest properties screen (and adding quest id's to the dependency list) is not the intended primary method of setting up dependencies.
