### ISSUE TITLE
[Feature Request]: Compatibility with ReplayMod

### ISSUE THREAD

**Issue by SwooshyGang** [FTBTeam/FTB-Mods-Issues#1135]
### Mod

FTB Quests

### Description

Per the ReplayMod Discord this is the issue the mods have together "FTB Quests - Minecraft crashes if you load a recording when this mod is present (it cannot handle the fake player used by ReplayMod): i have tried removing the FTB quest mod when using the Replay Mod features but that doesn't fix the issue.

**Comment by Slenah** [comment]
Im having the exact same isssue I have the crash report if needed.

**Comment by desht** [comment]
A crash report might be helpful...

**Comment by Slenah** [comment]
My apologies, when I posted it I did post a crash report with it, but I
ended up figuring out the problem so I closed it!

**Comment by Poopooracoocoo** [comment]
How did you solve this?

**Comment by ShpionLV** [comment]
I also would like to know
