### ISSUE TITLE
[Feature Request]: make the chunk security level setting easier to find

### ISSUE THREAD

**Issue by hacker-on-steroids** [FTBTeam/FTB-Mods-Issues#1141]
### Mod

FTB utilities

### Description

to get to the security settings, you have to open the friendsGUI(and not the client settings), click your name, then "settings" where your name used to be, and then modify them
or do `/lmplayer_settings block_security ` and the only way to figure that out is listing out all possible commands and searching through em

### Describe the solution you'd like

i suggest adding the settings to the chunk claiming screen like so
![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/159179330/b54c7563-4f42-4308-9ca8-5e7ec417eb3a)

### Describe alternatives you've considered

briefly considered playing a minecraft version that isn't 10 years old

**Comment by desht** [comment]
Sorry, 1.12 is no longer supported and hasn't been for some time.

**Comment by hacker-on-steroids** [comment]
but what about 1.7.10?
