### ISSUE TITLE
[Bug]: FTB Quests version 2001.3.5 crashes with FTB Library 2001.2.0

### ISSUE THREAD

**Issue by katubug** [FTBTeam/FTB-Mods-Issues#1142]
### Mod

FTB Quests

### Mod version

ftb quests forge-2001.3.5

### Forge / Fabric version

1.20.1 47.2.20

### Modpack & version

custom, in development

### What issue are you having?

When I attempt to load up the game with the listed mod versions, it crashes, and this is in the latest.log:
```
[13:20:06] [main/ERROR]: Missing or unsupported mandatory dependencies:
	Mod ID: 'ftblibrary', Requested by: 'ftbquests', Expected range: '[2001.1.4,2001.2.0)', Actual version: '2001.2.0'
```
I'm not sure why it's erroring, given the version numbers requested.

### Crashlogs

Full latest.log https://pste.ch/vejebetedi.md

### Steps to reproduce

Install the listed versions of these two mods and attempt to launch the game.

**Comment by katubug** [comment]
Actually, I am still experiencing startup errors even with the FTB suite downgraded to my last working version. I will close this for now until I figure out if this is actually caused by something else.

**Comment by katubug** [comment]
Okay, I can confirm this is definitely an issue, all other problems notwithstanding.

**Comment by katubug** [comment]
Here is my updated latest.log: https://pste.ch/ahuwonawan.md

**Comment by desht** [comment]
Quest 2001.3.5 is not compatible with FTB Lib 2001.2.0 and never will be. That got missed in the mods.toml, sorry.

There will be a 2001.4.0 release of Quests today.

**Comment by desht** [comment]
FTB Quests 2001.4.0 is now released.
