### ISSUE TITLE
[Bug]: Crash On Startup

### ISSUE THREAD

**Issue by xbon60** [FTBTeam/FTB-Mods-Issues#1145]
### Mod

FTB Chunks

### Mod version

ftb-chunk-forge:2001.2.7

### Forge / Fabric version

1.20.1-47.2.20

### Modpack & version

ValHelsia 6

### What issue are you having?

hello, the game crash on the startup if a add FTB Chunk

### Crashlogs

the Crash Log : https://pste.ch/opamoselox.pl

### Steps to reproduce

Install The ValHelsia 6 Modpack, add FTB Chunk And FTB library

**Comment by desht** [comment]
This crash is in Valhelsia Structures, not FTB Chunks.  Chunks is just using vanilla calls to check the block's map color for rendering purposes; for some reason this is triggering a crash in Valhelsia Structures.

I would suggest contacting the authors of that mod.
