### ISSUE TITLE
[Bug]: FTBQuest "StringIndexOutOfBoundsException" error

### ISSUE THREAD

**Issue by LetterN** [FTBTeam/FTB-Mods-Issues#1149]
### Mod

FTBQuest, ftblibrary

### Mod version

FTBQuest: 2001.3.0, FTBLibrary: 2001.2.0

### Forge / Fabric version

1.20.1, 47.2.21

### What issue are you having?

Double clicking description text on ftbquest while on edit mode crashes the game

### Crashlogs

https://mclo.gs/poXrEON

### Steps to reproduce

1. Enable ftbquest edit mode
2. Double-click any description text

**Comment by desht** [comment]
Confirmed, but doesn't happen for all text contents.  Will try to track it down.

As a workaround in the short term, you can still edit quest text by either pressing 'D', or use the "Edit" dropdown menu and selecting one of the options there.

**Comment by desht** [comment]
Fixed in 2001.4.1 (FTB Library 2001.2.1 also required)
