### ISSUE TITLE
[Bug]: FTB Quests Checkmark menu not rendering

### ISSUE THREAD

**Issue by Leclowndu93150** [FTBTeam/FTB-Mods-Issues#1151]
### Mod

FTB Quests

### Mod version

4.0

### Forge / Fabric version

1.20.1 47.2.23

### What issue are you having?

https://github.com/FTBTeam/FTB-Mods-Issues/assets/73310949/795d6ee8-289f-4da5-a0d5-004bcdaaf30e

### Steps to reproduce

https://github.com/FTBTeam/FTB-Mods-Issues/assets/73310949/17e48128-a684-4b56-9392-f0cdd5e9c5ef

**Comment by desht** [comment]
Confirmed

**Comment by desht** [comment]
Fixed in 2001.4.1 (FTB Library 2001.2.1 also required)

**Comment by Leclowndu93150** [comment]
ty
