### ISSUE TITLE
[Feature Request]: FTB Ultimine allowed only the proper tools to be effective.

### ISSUE THREAD

**Issue by syano-u** [FTBTeam/FTB-Mods-Issues#1155]
### Mod

FTB Ultimine(1.19.2)

### Description

Hello to all developers.
This mod is great.

However, players have to work hard when using it in multiplayer.

I want to disable the batch destruction when they break the soil with their hands or a nickel!

(This text was prepared using DeepL. Sorry if the text is weird.)

### Describe the solution you'd like

Config needs to have
“Activate FTB Ultimine only with proper tools” and “Disable FTB Ultimine with bare hands”

### Describe alternatives you've considered

Of course, some people do not need this. But some people need it.

**Comment by desht** [comment]
> I want to disable the batch destruction when they break the soil with their hands or a nickel!

I have no idea what you mean by "nickel", but there is already a config setting to require a tool.  In the server configuration (found in `<world>/serverconfig/ftbultimine-server.snbt`), set "require_tool" to true.

**Comment by syano-u** [comment]
Oops, I found that item. Thanks.I have one more suggestion, can I make a thread

**Comment by desht** [comment]
Just create a new issue for that please
