### ISSUE TITLE
[Bug]: Clicking on air item in quest GUI causes crash 

### ISSUE THREAD

**Issue by Qwerty97475** [FTBTeam/FTB-Mods-Issues#1157]
### Mod

FTB Quests

### Mod version

FTB quests Forge 2001.3.5

### Forge / Fabric version

Forge 1.20.1 47.2.0

### What issue are you having?

When you click on an air item in a quest interface, it crashes the game.

### Steps to reproduce

1. Create a new world and enable FTB quests editing mode
2. Make a new quest in a chapter, to obtain an item
3. Leave the item blank and click "Accept", this adds an air item to the quest interface
4. Disable FTB quests editing mode, and click on the icon for the air item in the quest interface (Looks like a purple square with white question mark inside)
5. Game should crash

**Comment by desht** [comment]
How are you even doing that?  The item selection screen has no option to select a blank item, and clicking "Accept" without selecting an item doesn't create a quest, it just dismisses the selection screen.

![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/736831/086f64a7-3800-4563-be17-156fa245d267)

**Comment by desht** [comment]
Ah wait, you're on an older version.  Latest FTB Quests does not have this problem.
