### ISSUE TITLE
[Bug]: Dupe bug with output buffer on Auto hammers

### ISSUE THREAD

**Issue by braingkk** [FTBTeam/FTB-Mods-Issues#116]
### Mod

FTB Sluice

### Mod version

ftb-sluice-forge-1.0.8-build.30

### Forge / Fabric version

1.16.5  36.2.8

### Modpack & version

FTB Oceanblock 1.6.0

### What issue are you having?

the auto hammer from FTB sluice mod seems to dupe all items in its output buffer when outputting to a storage drawer.

video evidence provided.
https://youtu.be/NNTq79ckp-c

### Steps to reproduce

1) let an auto hammer build up items in its output buffer.
2) place a storage drawer by the output slot
3) infinitely dupe the buffer leading to much more than you initially put into the hammer

**Comment by MichaelHillcox** [comment]
Ugh

**Comment by MichaelHillcox** [comment]
@MaxNeedsSnacks this is likely a really small fix / logic issue in the tile handler on a method called pushPull or something like that, I'm snowed under atm, could you see if you can spot the issue?

**Comment by braingkk** [comment]
looking at it some more, it seems to decrement the buffer by 64 each time, but the drawer increases by the total buffer

**Comment by MichaelHillcox** [comment]
Ugh! This is already fixed... Update your pack or sluice! :D
