### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by reformedpipa** [FTBTeam/FTB-Mods-Issues#1164]
### Mod

FTB Library

### Mod version

ftb-library-forge-2001.2.0.jar

### Forge / Fabric version

47.2.0

### Modpack & version

Create Perfect world

### What issue are you having?

![image_2024-05-04_162100716](https://github.com/FTBTeam/FTB-Mods-Issues/assets/168916425/f191fdf4-2a3b-4150-9f9c-e221a3a37571)

### Crashlogs

https://pste.ch/raw/eyegisemem

### Steps to reproduce

Just play modded minecraft after some time

**Comment by GAMINGCHATS** [comment]
Yep that same mismatch, although instead of this showing up in the minecraft program it crashed alltogether. 
This is from the `latest.log`:
![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/90594728/99583029-f815-4641-9205-f381d8c05082)

**Comment by desht** [comment]
@reformedpipa the error message is clear: you need to install FTB Library 2001.2.1 and FTB Teams 2001.3.0

@GAMINGCHATS your problem is unrelated; please open a separate issue with full details of your environment (mod loader version and versions of all relevant mods).

**Comment by reformedpipa** [comment]
> @reformedpipa the error message is clear: you need to install FTB Library 2001.2.1 and FTB Teams 2001.3.0
> 
> @GAMINGCHATS your problem is unrelated; please open a separate issue with full details of your environment (mod loader version and versions of all relevant mods).

Hey, after i updated by your help it´s crashing, Exit Code:1
