### ISSUE TITLE
[Bug]: Datapack function (mcfunction)

### ISSUE THREAD

**Issue by KevzCz** [FTBTeam/FTB-Mods-Issues#1165]
### Mod

FTB Quests

### Mod version

 ftb-quests-fabric-2001.4.2 (older version still has the same issue)

### Forge / Fabric version

1.20.1 (Fabric Modloader 0.15.10)

### What issue are you having?

This is the logs. Functions that have ftbquests change_progress @p complete/reset ________ always seem to fail to load ONLY ON THE FIRST LOADING INTO THE WORLD after that FUNCTIONS LOAD FINE (AFTER EXITING THE GAME AND LOADING INTO THE WORLD AGAIN, THE PROBLEM CONTINUES AND ONLY FIXES WHEN YOU RELOG). I can't really release an update since its a huge hassle to log out and login, servers might have to reload, etc (haven't tested on servers)
![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/130611225/9c714ce9-31f8-428e-8309-c29fc04ff9fe)
![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/130611225/4936075f-7e3e-41e5-b472-6dc63d632550)
![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/130611225/1898e7e2-26ac-4b6b-b482-b9008f1f6f5f)
![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/130611225/8725d2a7-4d9c-4065-bc31-2fbe7e64fdf8)
![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/130611225/729a6d78-399b-4301-90ca-941a170f0879)
![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/130611225/18d0c7c7-ccbd-47f1-a77d-d7239520d45f)
![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/130611225/a243d96e-1e02-4340-b8b3-f5eaf7c1f10a)
![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/130611225/bda3cf71-f04e-4620-b5bf-f5f0f76adce4)
![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/130611225/25e1dcf9-253d-4c6e-bbde-a20f812210d2)
![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/130611225/32a581f4-8fa2-452d-9b05-50dddcec43e9)
![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/130611225/05641c94-b303-4a7a-bc2c-5e273ee18466)
![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/130611225/8ffc870c-183f-49a1-96ef-45008a3ba55b)

### Crashlogs

Didn't crash https://pste.ch/icapohiqiv.md

### Steps to reproduce

1. Make functions contains ftbquests change_progress comands
2. Load into the world for the first time
Fix:
1. Log out after loading in

### Anything else to note?

FTBQuests, FTBLibrary are on the latest version.

**Comment by desht** [comment]
It might be helpful if you actually showed your `.mcfunction` file(s)...

What's most likely happening here is (and the Minecraft Wiki confirms this) is that the very first function tick runs before the world is loaded and the server is properly started.  So, you cannot use any `/ftbquests` command from a function tick, because the quest book is not yet available.

**Comment by KevzCz** [comment]
![28C477BE-2698-4477-A4BB-30C1B28C3A44](https://github.com/FTBTeam/FTB-Mods-Issues/assets/130611225/6da1013f-609d-4cc1-93dd-f5902957bbcd)
I did show the .mcfunction files. I see that explains it a lot.
Though i did think of making a system that auto reloads if a function fails to load up. Should i close this issue now?

**Comment by desht** [comment]
Yeah, I don't think there's much else that can be done here. Tick functions just won't work on the very first tick for FTB Quests commands.
