### ISSUE TITLE
Crash with FTB backups mod (1.16.1 original)

### ISSUE THREAD

**Issue by Fireworkstars46** [FTBTeam/FTB-Mods-Issues#1170]
### Mod

FTB backups 1 

### Mod version

ftb-backups-2.1.1.6

### Forge / Fabric version

1.16.1 32.0.108

### What issue are you having?

So my game keeps crashing when I try to use a custom path. So is there a way for me to fix it?

### Crashlogs

https://pastebin.com/uYEg4qwg

### Steps to reproduce

I changed the folder path to my custom path and it crashed. If I use no custom path it works

**Comment by desht** [comment]
As already stated by @MichaelHillcox today:

> if this is for FTB Backups 2, please use this issue tracker https://github.com/CreeperHost/FTB-Backups-2/issues

**Comment by Fireworkstars46** [comment]
So that one is for on backup 2?
