### ISSUE TITLE
[Bug]: Server Crush

### ISSUE THREAD

**Issue by PydingAbsorber** [FTBTeam/FTB-Mods-Issues#1175]
### Mod

FTB Quests

### Mod version

v2001.3.0

### Forge / Fabric version

1.20.1 forge

### What issue are you having?

Server crush

### Crashlogs

[crash-2024-05-15_22.29.29-server.txt](https://github.com/FTBTeam/FTB-Mods-Issues/files/15333446/crash-2024-05-15_22.29.29-server.txt)

### Steps to reproduce

1. Just login on server

**Comment by WyFryMU** [comment]
Update your FTB Quests mod. It appears that Null Pointer Error was fixed.

**Comment by desht** [comment]
I think this is a separate issue, and is a result of no FTB Teams data found for this player ID.  @PydingAbsorber I need to see your _full_ server log, not just the crash data.

I also note that you're running Mohist; we don't recommend or support hybrid servers like this. FTB mods are written for pure Forge and Fabric environments.
