### ISSUE TITLE
[Bug]: XP and XP Levels reward window pops up outside of window

### ISSUE THREAD

**Issue by TheAngel7** [FTBTeam/FTB-Mods-Issues#1178]
### Mod

FTB Quests

### Mod version

2001.4.2

### Forge / Fabric version

Forge 47.2.1 (minecraft 1.20.1) Also happens on Forge 47.2.32

### What issue are you having?

When trying to add new reward in quest editing, the xp and xp levels window pop ups far beyond my window, I can only fix it by first making minecraft window tiny, and then after trying to add xp/xp levels reward maximise it so I can have the window in bottom right corner of window, otherwise it's not accessible.

There was no crash so I won't be uploading crash logs

### Steps to reproduce

1. create any quest

2. add xp/xp levels reward

3. window pops up outside of minecraft window. (not visible)

### Anything else to note?

my gui scale is set to 4 and I'm using 2560-1440 resolution.

The issue is present on my modpack (4.21 and 4.22)
https://www.curseforge.com/minecraft/modpacks/die-hard-forest

**Comment by desht** [comment]
Fixed in 2001.4.3 release
