### ISSUE TITLE
[Feature Request]: I would like to ask for help in making a data package that can add item interaction whitelist

### ISSUE THREAD

**Issue by QianMuu** [FTBTeam/FTB-Mods-Issues#1179]
### Mod

FTBchunks

### Description

I don't know the code well enough and I have tried many times how to make packets myself. But it has no effect.
Because there is no reference for this, it may be difficult for a novice like me to do.

### Describe the solution you'd like

Can you help me create a whitelisted packet with the ship added? I can add subsequent items myself.
(I want to put in KubeJS/data folder.)

### Describe alternatives you've considered

I searched the web (and Discord) for my problem, but couldn't find a solution

**Comment by desht** [comment]
If you already have KubeJS installed, you don't need a whole datapack - you can just use KubeJS.  See https://wiki.latvian.dev/books/kubejs/page/tags for full info.

e.g. to add a block for FTB Chunks whitelisting:

```javascript
ServerEvents.tags('block', event => {
  event.add("ftbchunks:interact_whitelist", "some:block")
})
```

replacing `some:block` with the actual block ID of the block you want to add.

**Comment by desht** [comment]
I should also mention that many tutorials for creating a full data pack are on the web, including this one on the official Minecraft wiki: https://minecraft.fandom.com/wiki/Tutorials/Creating_a_data_pack
