### ISSUE TITLE
[Bug]: The ship cannot be used after being placed, and the minecart cannot be placed but can be used.

### ISSUE THREAD

**Issue by QianMuu** [FTBTeam/FTB-Mods-Issues#1180]
### Mod

FTB chunks

### Mod version

ftb-chunks-forge-1902.4.4-build.326

### Forge / Fabric version

1.19.2-43.3.13

### What issue are you having?

I just discovered a problem. The boat can be placed, but it cannot be interactively ridden on it.
Minecarts cannot be placed, but you can sit on them interactively.
The ship may be an entity and the minecart may appear to be a block, but no matter how you transform it, this problem cannot be solved.
[interact-whitelist.zip](https://github.com/FTBTeam/FTB-Mods-Issues/files/15370226/interact-whitelist.zip)

### Steps to reproduce

Add interaction whitelist using packets

**Comment by UnRealDinnerbone** [comment]
This is an intended feature of the mod, and as you figured you can add entities to the list to change this per pack
