### ISSUE TITLE
[Bug]: FTBUltimine config window

### ISSUE THREAD

**Issue by drkanbs** [FTBTeam/FTB-Mods-Issues#1184]
### Mod

FTBUltimine

### Mod version

ftb-ultimine-forge-2001.1.4

### Forge / Fabric version

47.2.30

### What issue are you having?

![Screenshot (142)](https://github.com/FTBTeam/FTB-Mods-Issues/assets/22972588/fd49ca9c-92c5-4d4a-9372-ad6c92cd61f4)
This window won't let me click Accept to close, or if I press cancel it pops up are you sure, and then doesn't close. I had to just X out of Minecraft in order to exit.  

### Steps to reproduce

I decided to check the / commands for FTB. 
I used /ftbultimine clientconfig

**Comment by desht** [comment]
Fixed in FTB Ultimine 2001.1.5 release
