### ISSUE TITLE
[Bug]: /fly not working (incompatibility with a mod)

### ISSUE THREAD

**Issue by Agentx49** [FTBTeam/FTB-Mods-Issues#1189]
### Mod

FTB Essentials

### Mod version

ftb-essentials-forge-2001.2.2.jar

### Forge / Fabric version

1.20.1 47.2.30

### Modpack & version

Test build of my modpack

### What issue are you having?

/fly does nothing

### Steps to reproduce

1. install my modpack (import through curseforge) 
2. go into a world and try to use /fly

### Anything else to note?

Its very clearly an incompatibility with some mod in my pack so i've attached the modlist in addition to the modpack incase the mod that causes this issue is already known

[Project_Spacee-2.0_Test_Build_2.zip](https://github.com/FTBTeam/FTB-Mods-Issues/files/15410946/Project_Spacee-2.0_Test_Build_2.zip)
[modList.txt](https://github.com/FTBTeam/FTB-Mods-Issues/files/15410949/modList.txt)

**Comment by Agentx49** [comment]
Inventory pets was the cause
there isnt a config option in there that seems like it would fix it
I will also link this issue to the developer

**Comment by Agentx49** [comment]
Turns out they are aware and in the process of fixing
https://github.com/capnkirok/Inventory-Pets/issues/584

**Comment by desht** [comment]
Good to know, thanks.
