### ISSUE TITLE
[Bug]: Minimap does not dynamically resize with window

### ISSUE THREAD

**Issue by xElementzx** [FTBTeam/FTB-Mods-Issues#119]
### Mod

FTB Chunks

### Mod version

ftb-chunks-forge-1605.3.1-build.41

### Forge / Fabric version

1.16.5 36.2.2

### Modpack & version

FTB Presents Direwolf20 1.16

### What issue are you having?

The Minimap does not scale with the client window size. if i adjust the 'scale' option in the settings the minimap does infact resize, but resizing the window should also scale the minimap.

### Steps to reproduce

1. Launch Game
2. Look at minimap
3. Resize game
4. Look at minimap
5. Realize minimap did not change size, now you have a minimap bigger than your hotbar
6. `!Profit`

**Comment by MichaelHillcox** [comment]
This has been fixed as of newer versions
