### ISSUE TITLE
[Bug]: UI issue with a lot of tasks in a quest

### ISSUE THREAD

**Issue by TheAngel7** [FTBTeam/FTB-Mods-Issues#1191]
### Mod

FTB Quests

### Mod version

2001.4.4

### Forge / Fabric version

Forge 47.2.32

### What issue are you having?

Doesn't display tasks properly (you can't scroll up to see full icons
![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/170236510/d148e84a-e6f2-4981-b665-fd6a25d00d27)

### Steps to reproduce

1. create a quest
2. add a lot of tasks (17+)
3. can't scroll up to see all of them

### Anything else to note?

resolution 2560 x 1440
gui scale auto (probably 5?)

Also the missing_item wasn't actually fixed, I had it happen again and added new logs in now closed post, if I should make new one please tell me, thanks :)
The thing I'm talking about:
![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/170236510/a5d3e9b4-abe7-44df-8795-a1920d5987e0)

**Comment by desht** [comment]
FTB Quests isn't really designed to support that many tasks in a quest (although it works, the GUI isn't built for it). This isn't a feature we plan to address in the near future.  In this situation, I would suggest splitting this into two or more quests - you could have them all done at the same time by the player (and if there's a subsequent quest, you can make it dependent on all of the quest you've created).
