### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by superblast1** [FTBTeam/FTB-Mods-Issues#1192]
### Mod

FTB chunks/FTB library/

### Mod version

latest updtae acording to forge

### Forge / Fabric version

forge 1.20.1

### What issue are you having?

if you need more info please ask im not sure what im doing
![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/170805992/6771cb4b-c63e-4c2d-acab-79e7c6c0adfa)

### Crashlogs

![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/170805992/8ff2557d-1899-43c3-9046-609276ba5c25)

### Steps to reproduce

i start it and it crashes

**Comment by WyFryMU** [comment]
Update all your FTB mods. FTB Teams and Chunks should be 2001.3.0. FTB Library should be 2001.2.2 My guess is you didn't see the beta version for FTB Chunks: https://www.curseforge.com/minecraft/mc-mods/ftb-chunks-forge/files/5267364

**Comment by Lusey77** [comment]
This resolved the issue for me. For me the CurseForge app by default installs the latest release version of mods and as such didn't install the beta version but did install the latest lib version creating the mismatch.

**Comment by desht** [comment]
Yeah, 2001.3.0 should really have been a CF release, not beta. However, FTB Chunks 2001.3.1 will be out today, which will be a non-beta release.
