### ISSUE TITLE
[Bug]: FTB Quest(and other related FTB mods) with Obscure API can cause serious moiré pattern in the game

### ISSUE THREAD

**Issue by UnnamedWei** [FTBTeam/FTB-Mods-Issues#1195]
### Mod

ftb-quests-fabric-2001.4.4, ftb-library-fabric-2001.2.2, ftb-teams-fabric-2001.3.0

### Mod version

ftb-quests-fabric-2001.4.4, ftb-library-fabric-2001.2.2, ftb-teams-fabric-2001.3.0

### Forge / Fabric version

Fabric 0.15.7

### Modpack & version

Fabric 1.20.1

### What issue are you having?

![{55DC26DE-0B9A-425d-9855-AEF650C1C6C2}](https://github.com/FTBTeam/FTB-Mods-Issues/assets/153602372/992ea7e6-2efb-4062-97a9-b19f55f80a39)
This is a superflat world with sandstone, FTB mods used with Obscure API caused moiré pattern.

https://www.curseforge.com/minecraft/mc-mods/obscure-api-fabric

### Steps to reproduce

Start the game

**Comment by desht** [comment]
This report contains no useful information.  "FTB mods used with Obscure API caused moiré pattern" - what is the Obscure API, what FTB mods, where are the instructions to reproduce the issue, has this been reported with the author of the Obscure API?

**Comment by Kostabl** [comment]
When playing with Aquamirae mod and its library Obscure API in the game appears the above problem. It seems that mipmap level is set to 0.

To cause the error it is enough to enter any world with both mods.

**Comment by Lilac-Wendy** [comment]
Hi, i'm from the ObscureAPI server, (not dev, just user), saw his post in there.

It's the FTB Quest Mod. I'm using both mods too (Forge 1.20.1), so i'm concerned.
