### ISSUE TITLE
[Bug]: Game crashed on start with FTB Xmod Compat

### ISSUE THREAD

**Issue by UnnamedWei** [FTBTeam/FTB-Mods-Issues#1196]
### Mod

FTB Xmod Compat

### Mod version

ftb-xmod-compat-fabric-1.2.4

### Forge / Fabric version

Fabric 0.15.7

### Modpack & version

Fabric 1.20.1

### What issue are you having?

Game crashed on start

### Crashlogs

[crash-2024-05-27_03.11.03-client.txt](https://github.com/FTBTeam/FTB-Mods-Issues/files/15448356/crash-2024-05-27_03.11.03-client.txt)

### Steps to reproduce

Start the game

**Comment by desht** [comment]
FTB XMod Compat 1.2.4 is for Minecraft 1.19.2.  You're running 1.20.1, so please use the correct version of the mod: currently, 2.1.1
