### ISSUE TITLE
[Bug]: Bypass force load claims limit

### ISSUE THREAD

**Issue by funnycubeguy** [FTBTeam/FTB-Mods-Issues#1198]
### Mod

FTB Teams

### Mod version

ftb-teams-forge-2001.3.0.jar

### Forge / Fabric version

1.20.1

### Modpack & version

ATM9 0.2.59

### What issue are you having?

Can bypass the force load claims limit by using as many accounts as you want force loading chunks on all accounts then create a team. The team will have way more force loaded chunks than allowed. This allows for infinite force load chunks assuming you have a bunch of minecraft alt accounts.

### Steps to reproduce

Set force loads max to 2
Claim 2 force load chunks on 2 accounts
Create a team
Now you have 4/2 force loads

**Comment by UnRealDinnerbone** [comment]
This seems something that on the server to manage, not the mod itself. Anyone I can think to try and prevent this, there are others way to get around it.
