### ISSUE TITLE
[Feature Request]: Configurable sluice properties

### ISSUE THREAD

**Issue by MasterOfBob777** [FTBTeam/FTB-Mods-Issues#120]
### Mod

FTB Sluice

### Description

Currently features like IO or upgradability are limited to set defaults per sluice.

### Describe the solution you'd like

Allow changes to features like fluid / item IO or upgradability per sluice.

### Describe alternatives you've considered

These could be set defaults that never change (not accepting this feature). Or, this maybe could be expanded to allow custom sluices that are completely configurable.

**Comment by Raidobw2** [comment]
Looks like you got it fixed all yourself! I missed seeing the PR back then, glad our mod dev Michael could review it with you. Since that appears to be fixed by the PR, I'll close this issue.
Thank you for the contribution
