### ISSUE TITLE
[Bug]: Server crash when completing quests with dependency

### ISSUE THREAD

**Issue by Rodrigo816** [FTBTeam/FTB-Mods-Issues#1200]
### Mod

FTB Quests

### Mod version

 2001.3.5

### Forge / Fabric version

Forge-47.2.20

### Modpack & version

Create Chronicles: Bosses and Beyond - 1.6.2

### What issue are you having?

After updating my server from version 1.5.0 to 1.6.2, I encountered two separate issues that cause the server to crash repeatedly. The quest book updates introduced a requirement before the simulation chamber to make a copper spool. We are already well into chapter 9, so when I pick up a copper spool, it completes this quest and triggers dozens of quest complete popups for things that are already done, causing the server to crash.

The two problematic quests identified are:
The copper spool quest in chapter 4.
The fireclay quest in chapter 5.

I suspect the crash occurs because Chapter 9 depends on all previous chapters, and when quests from Chapter 4 are completed, it verifies all quests up to Chapter 9 again, leading to many popups and the subsequent crash.

![servercrash](https://github.com/FTBTeam/FTB-Mods-Issues/assets/12116265/70335a2f-3171-4dcb-bec8-3e41e2758bd2)

### Crashlogs

[crash-2024-05-27_16.01.40-server (1).txt](https://github.com/FTBTeam/FTB-Mods-Issues/files/15472910/crash-2024-05-27_16.01.40-server.1.txt)

### Steps to reproduce

1. Update the server from version 1.5.0 to 1.6.2.
2. Ensure the server has progress up to Chapter 9 in the quest book.
3. Pick up a copper spool item to complete the copper spool quest in Chapter 4.
4. Observe the server triggering multiple quest completion popups for already completed quests.
5. The server crashes due to the large number of triggered events.

**Comment by Rodrigo816** [comment]
> 1802.3.11 is quite an outdated version (newest for 1.18.2 is 1802.3.16). Please try that rather than raising issues against old versions of the mod.
Sorry the version installed is 2001.3.5 but I checked crash log and says a diferent thing

![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/12116265/93fd0166-d45f-4f72-ab37-456c111573e7)

**Comment by Rodrigo816** [comment]
Sorry for the confusion I sended you the wrong crash report xD. I edited the comment already.
[crash-2024-05-27_16.01.40-server (1).txt](https://github.com/FTBTeam/FTB-Mods-Issues/files/15472910/crash-2024-05-27_16.01.40-server.1.txt)

**Comment by desht** [comment]
This is already fixed, in 2001.4.x (currently 2001.4.5)

Again, please don't raise issues against old versions of the mod.
