### ISSUE TITLE
[Bug]: FTB Quest link creation to other chapters has a bug in its formatting by defailt

### ISSUE THREAD

**Issue by Saereth** [FTBTeam/FTB-Mods-Issues#1202]
### Mod

FTB Quests

### Mod version

ftb-quests-neoforge-2004.2.0

### Forge / Fabric version

20.4.234

### Modpack & version

FTB InDevelopment pack

### What issue are you having?

When making a link to another chapter with the ingame ui it formats it as such:

`[ "Head over to the ", { "text": "Wheels of Fortune Chapter", "underlined": "true", "clickEvent": { "action": "change_page", "value": "595F1E9BDF4FB832" } }, " to setup your first tree farm using Steve's Carts 2!" ]
`
The underlined value however should be an integer 1 or 0 instead of a string so it errors. 
<img width="556" alt="image" src="https://github.com/FTBTeam/FTB-Mods-Issues/assets/9200909/fa767e3f-aa8b-4e82-a424-abd94ab87532">

Changing it to a 1 instead of "true" fixes the issue
<img width="530" alt="image" src="https://github.com/FTBTeam/FTB-Mods-Issues/assets/9200909/b393237b-b5cb-4061-a275-cff22bb2e868">

### Steps to reproduce

Make a quest with a link to another quest

**Comment by desht** [comment]
Yeah I noticed that with the 1.20.6 port yesterday and fixed it there; can backport that to 1.20.4, I guess.

 Mojang's JSON parsing engine has obviously changed in 1.20.4+ and is stricter now, it appears.  Booleans should be an unquoted `true` or `1` now, not `"true"` which worked OK in 1.20.1.

**Comment by desht** [comment]
Fixed in 2004.2.2
