### ISSUE TITLE
[Feature Request]: add EMI bookmark from quest Tasks/Valid Items list

### ISSUE THREAD

**Issue by Spongman** [FTBTeam/FTB-Mods-Issues#1204]
### Mod

FTB Quests

### Description

please make it so pressing 'A' when hovering over an item in a quest's 'Tasks'  or 'Valid Items' lists adds that item to the EMI bookmark list.

**Comment by WyFryMU** [comment]
This would be a change to the EMI mod, not the FTB Quests mod afaik.

**Comment by desht** [comment]
This is best tracked in https://github.com/FTBTeam/FTB-XMod-Compat/pull/9
