### ISSUE TITLE
[Bug]: FTB Chunks Crashed after latest update

### ISSUE THREAD

**Issue by Periam** [FTBTeam/FTB-Mods-Issues#1214]
### Mod

FTB Chunks

### Mod version

ftb-chunks-forge-1902.4.5-build.357

### Forge / Fabric version

1.19.2 Forge 43.4.0

### Modpack & version

Custom

### What issue are you having?

After updating the mod the latest version the game crash, it does not load it does not create a crash logs.
If the mod is downgraded the modpack runs normally.

### Crashlogs

Logs https://paste.feed-the-beast.com/view/342f6c94

### Steps to reproduce

Updated the mod to the latest version or install it in a new custom modpack.

**Comment by desht** [comment]
Confirmed, something weird has happened with the mixin refmap reobfuscation in this build.  Investigating...

**Comment by desht** [comment]
Fixed in FTB Chunks 1902.4.6
