### ISSUE TITLE
[Bug]: Ender Tots still able to mob grief

### ISSUE THREAD

**Issue by gjennks** [FTBTeam/FTB-Mods-Issues#1218]
### Mod

FTB Chunks

### Mod version

ftb-chunks-forge-1902.4.4-build.326

### Forge / Fabric version

1.19.2 43.3.9

### Modpack & version

FTB Skies 1.5.1

### What issue are you having?

Been trying to make a mob farm, but it kept having blocks griefed, I then chunked claimed the area and the blocks were still getting griefed.
I eventually worked out that it is Ender Tots from Forcecraft that were causing the block grief.
Was hoping if there is somewhere I could add them to the mob grief list so I dont have to restart my save to enable cheats to set the gamerule.

### Steps to reproduce

Claim an area.
Place some pickup-able blocks down.
Spawn a bunch of Ender Tots.
Watch them pick up the blocks.

**Comment by UnRealDinnerbone** [comment]
This was fixed by adding the tag entity tag `ftbchunks:entity_mob_griefing_blacklist` adding the mod there will stop it from griefing mobs in claimed chunks. Please note, this only works on Forge / NeoFroge
