### ISSUE TITLE
[Feature Request]: Add ability to share waypoints

### ISSUE THREAD

**Issue by Rushmead** [FTBTeam/FTB-Mods-Issues#1223]
### Mod

FTB Chunks

### Description

Add a way to share a waypoint with other players, either by chat or some other way!

**Comment by desht** [comment]
Yeah chat is probably best.  Send the recipient a message with a clickable link which runs `/ftbchunks waypoint add <name> <x> <y> <z>`  (the command already exists, just need a bit of gui integration in the waypoint context menu)
