### ISSUE TITLE
/tpaccept from /tpa broken

### ISSUE THREAD

**Issue by Micaxs** [FTBTeam/FTB-Mods-Issues#1225]
### Modpack

FTB NeoTech

### Modpack version

1.0.1

### Pack has been modified

- [ ] Yes

### Describe the bug

When a player1 uses: /tpa <player2>
and player2 clicks accept or /tpaccept <player1>
An error comes up: "Invalid Request".

### Steps to reproduce

1: When a player1 uses: /tpa <player2>
2: Player2 clicks accept or /tpaccept <player1>
3: An error comes up: "Invalid Request".

### Expected behaviour

Able to teleport to a given player.

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/14205312/16a9a626-e578-4f74-9739-f1ced7aaf22a)

### Additional information

-

**Comment by Saereth** [comment]
I have confirmed this is an issue on our testing server as well @desht this happens with the gamestage for maps enabled or disable, seems to have no bearing. 

Here is the essentials config we're using:
https://gist.github.com/Saereth/e5b671da8fda40f9c7183f03e7aafa9c

**Comment by desht** [comment]
Think this is the same issue Mikey fixed for the 1.21 port.  If so, should be easy to sort out...

**Comment by MichaelHillcox** [comment]
I've back ported the fix to 1.20.4 so this should be fixed when ever we ship the version :D

**Comment by desht** [comment]
FTB Essentials 2004.1.3 should fix this (tested and working on multiplayer server)

Should be available on Curseforge shortly.
