### ISSUE TITLE
[Bug]: Quest chapter not showing as completed when all non-optional quests are

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-Mods-Issues#123]
### Mod

FTB Quests

### Mod version

ftb-quests-forge-1605.3.5-build.72

### Forge / Fabric version

1.16.5 36.2.4

### What issue are you having?

![image](https://user-images.githubusercontent.com/15698722/142748030-1ed62bb1-bec1-48f6-8da8-b6db1cb031bb.png)
The only quests here that are not done are optional

![image](https://user-images.githubusercontent.com/15698722/142748036-505d784c-de2f-4f09-b1b8-2862d8210d44.png)
Completing those two shows it as completed

### Steps to reproduce

^

**Comment by desht** [comment]
Fixed in latest quests releases
