### ISSUE TITLE
[Bug]: FTBQuestsEvents.customTask('task_id', event => {...} ) Does not trigger

### ISSUE THREAD

**Issue by Spyro1502** [FTBTeam/FTB-Mods-Issues#1230]
### Mod

FTB XMod Compat

### Mod version

ftb-xmod-compat-forge-2.1.1.jar

### Forge / Fabric version

Forge 1.20.1 47.3.0

### What issue are you having?

I am trying to make a custom task Using KubeJS & FTBQuest, but as I coded my quest with something as simple as this : 
```js
FTBQuestsEvents.customTask('7BC1E1C11D49BB22', event => {
    console.info('Custom task!')

    event.setMaxProgress(100)
    event.setCheckTimer(20)
    event.setCheck((task, player) => {
        task.progress++
    })
})
```
Nothing happens at all, even tho I did create the quest & task before using the task ID
 

### Steps to reproduce

- Install :
  - Kubejs
  - FTBQuest
  - FTB XMod Compat
- Create a world
- Create a quest with a custom objective
- Make your QuestEvent with the custom task in the SERVER script folder (server_scripts)
- /reload
- Now your quest should be triggering, according to the code, but absolutely nothing happens, the custom tag never initialize

### Anything else to note?

I tried both in the big modpack I'm making & in a test modpack incliding only these :

- architectury-9.2.14-forge.jar
- ftb-library-forge-2001.2.2.jar
- ftb-quests-forge-2001.4.6.jar
- ftb-teams-forge-2001.3.0.jar
- ftb-xmod-compat-forge-2.1.1.jar
- jei-1.20.1-forge-15.3.0.8.jar
- kubejs-forge-2001.6.5-build.7.jar
- rhino-forge-2001.2.2-build.18.jar

**Comment by desht** [comment]
Oh, one other thing: if you created the task before the KJS script, and did a `/reload`, it won't be picked up immediately. The custom task event is fired when the custom task is loaded.  So either restart your server, or run `/ftbquests reload` to force a quest book reload. Then the custom task event is fired.

**Comment by Spyro1502** [comment]
Oh okay ! I didn't know about that part, seems to be working that way, I will make more test on the whole pack to see if it works, thanks !

**Comment by desht** [comment]
Ok, closing this for now.  Feel free to update if you encounter any other issues.
