### ISSUE TITLE
[Bug]: Array doesn't work in 1.21

### ISSUE THREAD

**Issue by modpacka2** [FTBTeam/FTB-Mods-Issues#1231]
### Mod

FTB quests

### Mod version

ftb-quests-neoforge-2100.1.0

### Forge / Fabric version

Neoforge-21.0.20

### What issue are you having?

I try to add depencies and it didn't work. I test to reload my game and reset parameter but it still doesn't save this array. After some time I tried to save another array the tag one and it as the same issue (it doesn't save after leaving the editing menu of the quest)

### Steps to reproduce

1.Load the game

2.Enable editing mode

3.Try to change the tag or dependancies of a quest

### Anything else to note?

I don't know if it's a real issue of the version, but I tried everything. I removed all other mods and it still happen, but it's possible that I missed a update and that it require other step to save the quests settings

**Comment by desht** [comment]
No, there's an actual bug here, looking into it.

**Comment by desht** [comment]
Fixed in FTB Library 2100.1.1, now on Curseforge
