### ISSUE TITLE
[Bug]: Crash when doing advancement quests (1.21)

### ISSUE THREAD

**Issue by Gbergz** [FTBTeam/FTB-Mods-Issues#1233]
### Mod

FTB Quests

### Mod version

ftb-quests-neoforge-2100.1.0.jar

### Forge / Fabric version

NeoForge - 21.0.21

### Modpack & version

custom pack

### What issue are you having?

When creating an advancement quest, the game crashes to desktop.

### Crashlogs

Crash 1: https://gist.githubusercontent.com/Gbergz/b281e9ca1108d25188f06d23b980cd6a/raw/56e32da5e9a4f94f8fcbe23e413487cabbb6c582/gistfile1.txt

Crash 2: https://gist.githubusercontent.com/Gbergz/97aecb27accc5770740d3ca5f22f7b55/raw/1f4fe429580c87c849147b709a10e11695cb1fb8/gistfile1.txt

### Steps to reproduce

Install FTB Quests on NeoForge 1.21
Create a quest tied to advancement.
crash.

### Anything else to note?

Basically it.

**Comment by desht** [comment]
Confirmed, will be fixed in next release

**Comment by desht** [comment]
Fixed in FTB Quests 2100.1.1
