### ISSUE TITLE
[Bug]: Crash when in FTB Quests mouseClicked event handler

### ISSUE THREAD

**Issue by Loki-Unchained** [FTBTeam/FTB-Mods-Issues#1236]
### Mod

FTB Quests

### Mod version

ftb-quests-forge-1902.5.9-build.399

### Forge / Fabric version

Forge 1.19.2

### Modpack & version

Etherforge Chronicles- EFC-1.0.4.5

### What issue are you having?

Once I attempt to open the quest book, the game crashes, and the questbook doesn't open. 

### Crashlogs

The most recent crash logs https://pste.ch/wizuseximi.sql
[crash-2024-06-23_12.17.04-client.txt](https://github.com/user-attachments/files/15945338/crash-2024-06-23_12.17.04-client.txt)

### Steps to reproduce

1. open the inventory
2. attempt to open the questbook
3. crash...

### Anything else to note?

N/A

**Comment by desht** [comment]
It looks like your quest book has a circular dependency - a quest depending on itself.  Have you manually edited the quest book SNBT?

**Comment by Loki-Unchained** [comment]
Thank you for the reply, after deleting the section that had the circular dependency it appears to have fixed the issue, thank you very much.
