### ISSUE TITLE
[Bug]: Unable to use multiple component types in a string

### ISSUE THREAD

**Issue by MuteTiefling** [FTBTeam/FTB-Mods-Issues#1239]
### Mod

FTB Quests

### Mod version

ftb-quests-neoforge-2100.1.0

### Forge / Fabric version

NeoForge - 21.0.20

### What issue are you having?

The following multipart component string works in chat. However, FTB Quests won't recognize it/display it properly. 

`/tellraw @p [{"text":"Follow the advancements ("},{"keybind":"key.advancements"},{"text":") for now."}]`

![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/9543430/8d477261-84dd-4991-bd74-6f6a6cf962f1)

In the quests, I use the same syntax: 
![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/9543430/66ec6d72-33a2-45a7-abbf-bfd6fd7a9283)

But get this instead of the expected string:
![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/9543430/5a398242-e25b-4158-9dce-7009a4d28fb1)

### Crashlogs

No crash

### Steps to reproduce

See above

**Comment by desht** [comment]
Fixed in 2100.1.3
