### ISSUE TITLE
[Bug]: FTB Quests Auto Complete

### ISSUE THREAD

**Issue by Logan9312** [FTBTeam/FTB-Mods-Issues#1242]
### Mod

FTB Quests

### Mod version

ftb-quests-neoforge-2100.1.1.jar

### Forge / Fabric version

Neoforge - 21.0.38

### What issue are you having?

When creating kill quests, something goes very wrong. After creating them, they will auto complete even though I haven't killed a single entity specified.

Example Quest creation:
![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/87048158/49e1f47a-274b-4acb-80f0-daa9c9e3dde3)

After quest is saved, it will be marked completed after a short while or a game restart on my end.
![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/87048158/b8c47516-8a22-4e02-84ad-f7a3f0246d16)
![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/87048158/7c9ecb41-9110-498c-8fc6-dbf48298e2cf)

It's worth noting that after creating the quest, and hovering over it it says "Air" and can crash my game which is another bug, not sure if an issue exists for that yet.

### Steps to reproduce

1. Create Kill Quest for any entity (Issue tested with "Player" and "Trader Llama"
2. Restart Game
3. Observe quest marked as completed

**Comment by desht** [comment]
I can't reproduce this.  Created a kill quest for Trader Llamas, and exited/restarted.  It's fine:
![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/736831/8341194c-c25a-4420-a04d-e1476a6c5ea2)

And it doesn't auto-complete. Killing Trader Llamas does correctly advanced the task progress, as expected.

Can you you paste the quest config that's saved, after you create the quest, but before restarting? You can find it `config/ftbquests/quests/chapters/<chapter_name>.snbt`. Probably easiest just to create a temporary chapter with only this quest in it, and paste just that chapter file here.

**Comment by Logan9312** [comment]
I’m not sure what was going on but it was fixed in the latest versions of the mod. I can’t replicate this issue anymore after updating. My guess is it was related to some other bug that got fixed
