### ISSUE TITLE
[Bug]: Can't reload after I edit my lang file of ftbquest directly

### ISSUE THREAD

**Issue by nageih** [FTBTeam/FTB-Mods-Issues#1243]
### Mod

FTB Quests

### Mod version

ftb-quests-neoforge-2100.1.1.jar

### Forge / Fabric version

1.21 21.0.38beta

### Modpack & version

My own modpack

### What issue are you having?

I create a quest, and it generates a lang file in `config\ftbquests\quests\lang`
I try editing the lang file instead of editing the quest in game. And I find it happens nothing.
I try use the command `/reload` , and it says `Failed to execute reload`

### Crashlogs

https://pastebin.com/xkvgFZeW

### Steps to reproduce

I create a quest, and it generates a lang file in `config\ftbquests\quests\lang`
I try editing the lang file instead of editing the quest in game. And I find it happens nothing.
I try use the command `/reload` , and it says `Failed to execute reload`

**Comment by desht** [comment]
And what exactly did you edit the lang file to contain?

**Comment by nageih** [comment]
I just add some texts,I don't think it's some specific content.As long as I try adding text, it will happen

**Comment by desht** [comment]
I think I see the problem, should be fixed in the next FTB Quests release.

**Comment by desht** [comment]
Fixed in 2100.1.3
