### ISSUE TITLE
[Bug]: Can't find Quest are not working on singleplayer and server

### ISSUE THREAD

**Issue by xMrarthur** [FTBTeam/FTB-Mods-Issues#1245]
### Mod

FTB Quests

### Mod version

1605.3.7-build.165

### Forge / Fabric version

1.16.5 36.2.34

### Modpack & version

LT Adventure 0.0.7 (custom modpack avaible on forge)

### What issue are you having?

Hi, my config file for the quest are at the right place and this should work according to the console,

![Capture d'écran 2024-06-27 113215](https://github.com/FTBTeam/FTB-Mods-Issues/assets/174005607/1cf56198-22a7-4d4a-aa97-9722ecee4a00)

but in game I have this eror message and I can't find why.

![Capture d'écran 2024-06-27 113132](https://github.com/FTBTeam/FTB-Mods-Issues/assets/174005607/dff1d60a-c598-411c-9f7a-60f1f88aeca9)

Game is not crashing and I also don't see any errors in the console.

The same problem appears in singleplayer even thought the quest are in the config file.

Any help would be loved.
xMrarthur

### Steps to reproduce

1.I Created the quests in a singleplayer world
2.I took the quests file and put them in my config file (singleplayer and server)

**Comment by desht** [comment]
For some reason, your server quest data is not sync'ing to the client. This is an old and long running problem which occasionally gets reported, but we never been able to reproduce; we don't know the cause and there isn't a fix.

Are you in offline mode?

Can you paste your full client and server logs somewhere?

**Comment by xMrarthur** [comment]
Erff... I tried everything I just don't understand.

I'm not in offline mode, server is hosted by OMGSERV.

Where can i paste them? I never had such a big problem that needed me to ask for help

**Comment by desht** [comment]
Any paste site, like pastebin etc. will do.
