### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by 849025143** [FTBTeam/FTB-Mods-Issues#1246]
### Mod

FTBQuests

### Mod version

ftb-quests-fabric-2001.4.6

### Forge / Fabric version

Fabric - 1.20.1

### What issue are you having?

Command Rewards can't work.
command -> /money give @p 100
@P cannot be replaced with player name.
But like command -> "/minecraft:give @p stone" can work.

### Steps to reproduce

Just do it

**Comment by desht** [comment]
There's no FTB Money in 1.20, or in any version beyond 1.12.

There may be a replacement in future, but not now, sorry.
