### ISSUE TITLE
[Feature Request]: Tag matching in FTB Quests

### ISSUE THREAD

**Issue by MuteTiefling** [FTBTeam/FTB-Mods-Issues#1248]
### Mod

FTB Quests

### Description

In older versions it was possible to right click an item task and set it to match a tag instead. This seems to be missing in 1.21.

Looks like Smart Filters attempts to replace this, but it's falling short from a UX perspective. For example, here I've set a quest to accept anything from Building Gadgets: 

![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/9543430/a659e1b4-b65f-43d6-aac5-4f256d576b90)

But clicking into the task just shows this... which isn't very helpful to the player. 

![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/9543430/720d2de9-9130-4495-a979-9e559eb69ccf)

I've tried with tag filters there too, and while they detect they just don't give the player any sort of useful information. As above, they just show a filter item instead of the items in the tag. 

### Describe the solution you'd like

The return of the simple 'convert to tag' option on item tasks. Also better feedback when using Smart Filters

**Comment by desht** [comment]
The Convert to Tag option is still definitely a thing, but it does require that FTB XMod Compat is installed (although that's needed anyway for FTB Filter System integration...)

As for item display, the mod can only show matching items known via the creative search tab by default, so if the item being matched has any kind of custom data components (formerly NBT), then it probably won't appear here.

Good news is there's a way around this, with a little KubeJS - a snippet like this can register custom items for display:

```javascript
FTBQuestsEvents.customFilterItem(event => {
        event.addStack('minecraft:iron_axe {display:{Name:{text:\"Test Axe!\"}}, Damage: 50}')
        event.addStack('minecraft:diamond_axe {display:{Name:{text:\"Test Axe 2!\"}}, Damage: 300}')
})
```

Bad news is, KubeJS integration isn't quite there yet for 1.21 (KJS has been ported but the API is very different). I'm working on this now and there should be an FTB XMod Compat update in the next few days to get this working.

**Comment by MuteTiefling** [comment]
Ah, cool. Thanks for the clarification. I thought I had added FTB xMod but apparently not. All working normally.
