### ISSUE TITLE
[Bug]: 1.21 - crash when change dimension with KubeJS and FTB Chunks and FTB XMod Compat

### ISSUE THREAD

**Issue by FalAut** [FTBTeam/FTB-Mods-Issues#1249]
### Mod

FTB Chunks

### Mod version

ftb-chunks-neoforge-2100.1.0

### Forge / Fabric version

Neoforge 21.0.40-beta

### What issue are you having?

crash when change dimension with KubeJS and FTB Chunks and FTB XMod Compat
↓
java.lang.IncompatibleClassChangeError: Method 'dev.latvian.mods.kubejs.stages.Stages dev.latvian.mods.kubejs.stages.Stages.get(net.minecraft.world.entity.player.Player)' must be InterfaceMethodref constant

### Crashlogs

https://mclo.gs/PwtQH1V

### Steps to reproduce

1.change dimension
2.server crash

**Comment by desht** [comment]
KubeJS in 1.21 has a completely changed API, and we're in the process of updating to support this.  Next FTB XMod Compat release will have fixed support for KubeJS, but KubeJS is not currently usable with FTB XMod Compat, sorry.

**Comment by desht** [comment]
Fixed in FTB XMod Compat 3.2.1, which adds full support for 1.21 KubeJS.
