### ISSUE TITLE
[Bug]: Can't load my raw json text

### ISSUE THREAD

**Issue by nageih** [FTBTeam/FTB-Mods-Issues#1250]
### Mod

FTB Quests

### Mod version

ftb-quests-neoforge-2004.2.2

### Forge / Fabric version

1.20.4 20.4.237

### Modpack & version

My own modpack

### What issue are you having?

The raw json text I wrote in the quest is not working

### Steps to reproduce

I'm not sure if my problem is the same as #1239, so I created a new issue.
When I enter `[{"text": "Head over to the "},{"text": "Dimension Hopping","color": "aqua","underlined": 1,"clickEvent": {"action": "change_page","value": "7C8B7C3F2DBE9E03"}},{"text": " chapter to see what they are for!"}]` in the quest, my quest says "Invaild formatting! Can't nest multiple substitutes!", which strangely enough works in tellraw.
When I changed this to `["Head over to the ",{"text": "Dimension Hopping","color": "aqua","underlined": 1,"clickEvent": {"action": "change_page","value": "7C8B7C3F2DBE9E03"}}," chapter to see what they are for!"]`, it worked.

**Comment by desht** [comment]
Yes, this looks like the same issue as 1239. I have a fix there, can backport to 1.20.4.

**Comment by desht** [comment]
Fixed in FTB Quests 2004.2.3
