### ISSUE TITLE
[Bug]: Trouble with Advancement based quests

### ISSUE THREAD

**Issue by MuteTiefling** [FTBTeam/FTB-Mods-Issues#1251]
### Mod

FTB Quests

### Mod version

ftb-quests-neoforge-2100.1.2

### Forge / Fabric version

NeoForge - 21.0.42

### Modpack & version

Enigmatica 10 in-dev

### What issue are you having?

Advancement based tasks seem to be having some issues.

Here I've selected the appropriate advancement: 
![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/9543430/ff2917e6-f1c6-48dd-b910-866194b05244)

Upon adding it, the task is created like so:
![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/9543430/8fc1cbbf-6f88-4be7-a220-2dcfe628f515)

Clicking it immediately crashes the game.

### Crashlogs

https://gist.github.com/MuteTiefling/04bdd82d060720cee5a6bd31f444e0e8

### Steps to reproduce

1. Add an advancement based task to a quest
2. Click the task

**Comment by MuteTiefling** [comment]
It's a hidden advancement in Occultism.

**Comment by MuteTiefling** [comment]
Neat. I know occultism and kubejs are having some issues with conditions... Maybe that's the actual cause?

I'll keep testing on my side then.

**Comment by desht** [comment]
Yeah, I'll keep an eye out for it here too.

**Comment by MuteTiefling** [comment]
So, I went back, made sure everything was updated, and tried a vanilla advancement and I'm seeing the same thing. I'll start pulling mods out to see if I can figure out what's breaking this.

**Comment by MuteTiefling** [comment]
... ok, I'm at a loss here.

Stripped the pack back to just FTB quests and was able to make an advancement task. Then slowly added in chunks of mods, attempting to add more advancement tasks at every group and could do so at every group.

It never stopped working again. 

Possible that it's some kind of initialization issue? Works fine now that there is one, but something is breaking your ability to read them if there aren't any tasks/

**Comment by MuteTiefling** [comment]
Spoke too soon. With all mods in I can create a new quest by selecting the advancement task as the starting point. Adding it to an existing quest is where it breaks.

**Comment by desht** [comment]
Ah! Yeah, adding an advancement task to an existing quest is what triggers it. Can confirm, now investigating why...

**Comment by desht** [comment]
OK, should be fixed now. Will be in next release, but feel free to test out https://maven.ftb.dev/snapshots/dev/ftb/mods/ftb-quests-neoforge/2100.1.3-SNAPSHOT/ftb-quests-neoforge-2100.1.3-20240703.140245-1.jar if you want :)

**Comment by MuteTiefling** [comment]
Nice thanks!

**Comment by desht** [comment]
Fixed in 2100.1.3
