### ISSUE TITLE
[Bug]: Images aren't loading in FTB Quests

### ISSUE THREAD

**Issue by Kevin-Marsh** [FTBTeam/FTB-Mods-Issues#1257]
### Mod

FTB Quests

### Mod version

ftb-quests-neoforge-2100.1.2

### Forge / Fabric version

Neoforge 21.0.51

### What issue are you having?

Images added to FTB Quests are not showing up when loading back into the game.

### Steps to reproduce

Open FTB Quests, add an image, close out of the game and relaunch. The image is saved in the quests config file but not rendered in the menu.

![2024-07-04_05 59 09](https://github.com/FTBTeam/FTB-Mods-Issues/assets/9076964/2be840ea-b2e8-42ef-96e3-df1dd0183a94)
![2024-07-04_06 00 13](https://github.com/FTBTeam/FTB-Mods-Issues/assets/9076964/d621e1aa-7c0f-4d32-a40d-1ff23d6dd6ec)

**Comment by desht** [comment]
Confirmed.

**Comment by desht** [comment]
Fixed in 2100.1.3
