### ISSUE TITLE
[Bug]: The default for hide quests until dependecies are done doesnt have value in config

### ISSUE THREAD

**Issue by MagicMikey6** [FTBTeam/FTB-Mods-Issues#1260]
### Mod

FTB Quests

### Mod version

ftb-quests-forge:2001.4.7

### Forge / Fabric version

1.20.1 47.3.3

### What issue are you having?

The default for hide quests until dependecies are done doesnt have value in config

### Steps to reproduce

Install it and boot up

**Comment by desht** [comment]
What does this mean?  There is no "hide quest until dependencies are done" setting.  Which of these are you talking about?
![image](https://github.com/user-attachments/assets/a364f06a-63aa-47b7-aec6-35329eff8592)

**Comment by MagicMikey6** [comment]
The default Hide Quests Until Dependencies are Visible is not there |:

**Comment by desht** [comment]
Show a screenshot of your quest config panel please.
