### ISSUE TITLE
[Bug]: no minimap rendered when I using FTB chunks

### ISSUE THREAD

**Issue by oldsheep0205** [FTBTeam/FTB-Mods-Issues#1261]
### Mod

FTB chunks

### Mod version

ftb-chunks-fabric-2100.1.0

### Forge / Fabric version

1.21

### Modpack & version

ftb-chunks-fabric-2100.1.0

### What issue are you having?

I added ftb chunks and its 2 dependencies in my fabric server. I opened my invertory but there's no icon on the left top corner. I right clicked the land and nothing happened. However, when I try /ftbchunk command in game, I can see the recommendation which means this mod had loaded at that time. I can also claim and unclaim using commands. 

### Steps to reproduce

1. put ftb-chunks-fabric-2100.1.0 in mods folder of fabric 1.21 server. 
2. console forces u to install 2 dependencies, ftb library and ftb team
3. start server again
4. join game
5. right click land, nothing happened, open inventory, no icons.

**Comment by Gaz492** [comment]
To view the minimap you will also need to install FTB Chunks on your client.
