### ISSUE TITLE
[Bug]: The jei category of the loot crate is broken

### ISSUE THREAD

**Issue by FalAut** [FTBTeam/FTB-Mods-Issues#1262]
### Mod

FTB Quests

### Mod version

ftb-quests-forge-2001.4.7

### Forge / Fabric version

1.20.1 47.3.5

### What issue are you having?

jei-1.20.1-forge-15.3.0.8

The first review of The jei category of the loot crate was blank, and then the log showed an error

`[mezz.jei.library.ingredients.IngredientManager/]: Ingredients are being added at runtime: 1 net.minecraft.world.item.ItemStack`
`[mezz.jei.library.gui.recipes.RecipeLayout/]: Error caught from Recipe Category: ftbquests:loot_crate`
`java.lang.IllegalArgumentException: Unknown ingredient type: class net.minecraft.world.item.crafting.Ingredient`

After this, the jei category of the loot crate cannot be viewed again

### Steps to reproduce

1. check the jei category of the loot crate
2. blank
3. cannot be viewed again

**Comment by FalAut** [comment]
Uploading The jei category of the loot crate is broken.mp4…

**Comment by desht** [comment]
Fixed in 2001.4.8
