### ISSUE TITLE
[Bug]: Making new quests directly in a group do not get a generic name

### ISSUE THREAD

**Issue by MuteTiefling** [FTBTeam/FTB-Mods-Issues#1264]
### Mod

FTB Quests

### Mod version

ftb-quests-neoforge-2100.1.3

### Forge / Fabric version

NeoForge - 21.0.53

### Modpack & version

Enigmatica 10 in-dev

### What issue are you having?

If I create a new chapter at the root, it is created with the new naming convention (random id). However, if you create a chapter inside of a group, they get a name based on title.

![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/9543430/0369968d-8d08-43d8-8e73-62a8688ceae3)

The top ones were all made in the root and then moved to a group. The last two were made in a group directly.

### Steps to reproduce

1. Click the + next to a group
![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/9543430/3df751b2-f385-43dc-94ae-22ebd95d54cb)
2. Name the Chapter
3. Save to disk and check the file name

**Comment by desht** [comment]
Technically the new naming convention is wrong - it was mistake introduced in the earliest releases of the mod for 1.21.  I'll check this and fix for root chapters as needed.

Note that this is just a filename; as a workaround you can rename the file on disk (and change the "filename" field in the file), ideally while the server isn't running... (if it is running, use `/ftbquests reload` to reload it).

**Comment by MuteTiefling** [comment]
Good to know, thanks for looking into it. Either convention is fine, I was mainly just interested in keeping things consistent.

**Comment by desht** [comment]
Fixed in 2100.1.4
