### ISSUE TITLE
[Bug]: crash when trying to allow fake players in my claim

### ISSUE THREAD

**Issue by Daniel19921** [FTBTeam/FTB-Mods-Issues#1265]
### Mod

FTB chunks

### Mod version

ftb-chunks-forge-2001.3.1

### Forge / Fabric version

1.20.1 47.3.1

### Modpack & version

Haven Caveblock Reborn 1.1.2

### What issue are you having?

when i tried to allow fake players to place/break blocks in my claim, my server crashed and i haven't been able to join since, the reason i wanted to allow fake players is so i could use block placers from industrial foregoing

### Crashlogs

https://hastebin.com/share/okiluqorem.php

### Steps to reproduce

i went into single player and placed down a block placer in a claimed area, went and changed the fake player to true and the game crashed

**Comment by Daniel19921** [comment]
Edit: just found out from the pack dev that it's FTB Quests causing the issue

**Comment by desht** [comment]
That's not FTB Quests, it's FTB Quests Additions, a third party mod not maintained by FTB.  You will need to raise this issue with the author of that mod.
