### ISSUE TITLE
[Bug]: Crash client

### ISSUE THREAD

**Issue by BazZziliuS** [FTBTeam/FTB-Mods-Issues#1276]
### Mod

FTB Quests

### Mod version

ftb-quests-forge-2001.4.2

### Forge / Fabric version

1.20.1 forge 47.2.32

### What issue are you having?

Crash when ReplayMod is used
https://www.curseforge.com/minecraft/mc-mods/reforgedplay-mod

### Crashlogs

https://paste.fuix.net/1VfIG7x

### Steps to reproduce

1. Open an entry in ReplayMod

**Comment by desht** [comment]
Should be fixed in 2001.4.8
