### ISSUE TITLE
[Bug]: Team Creation Issue

### ISSUE THREAD

**Issue by frak42** [FTBTeam/FTB-Mods-Issues#1278]
### Mod

FTB Teams / FTB Chunks

### Mod version

ftb-teams-forge-2001.3.0 / ftb-chunks-forge-2001.3.1

### Forge / Fabric version

Forge 47.3.0

### What issue are you having?

I am not sure if this is a FTB Teams or FTB Chunks issue.

When creating a party, the party looks like it is properly created. However, whenever the server restarts the party is no longer there and the player is no longer in the party. Any chunks claimed while in the party are no longer claimed. Whenever the party is created, the server console shows "Unclaimed 0 chunks for <UUIDofPlayer> due to claim limits." 

This is what it shows on my test server when I try to create a party: 

[19:25:36] [Server thread/INFO] [FTB Chunks/]: attempting to transfer 45 chunks from _Frak_#eda7321e to test#0023dcad
[19:25:36] [Server thread/INFO] [FTB Chunks/]: Transferred 45 chunks from eda7321e-80fe-474a-8235-a3f0a5817de3 (_Frak_#eda7321e) to 0023dcad-ac94-4fae-9a8e-bc4a49386790 (test#0023dcad)
**[19:25:36] [Server thread/INFO] [FTB Chunks/]: Unclaimed 0 chunks for eda7321e-80fe-474a-8235-a3f0a5817de3 (_Frak_#eda7321e) due to claim limits**
[19:25:36] [Server thread/INFO] [FTB Chunks/]: Team test#0023dcad had 0 claimed chunks, now has 45

Like I mentioned before, the chunk map shows the chunks with the new parties name and I can claim new chunks. But when the server reboots, any new chunks are unclaimed and the chunks that were there before creating the party are no longer under the party name, but back to my own name.

I can check the server world files, in the ftbteams folder, I see the 0023dcad-ac94-4fae-9a8e-bc4a49386790.snbt file, so I know the team was created, but there is not a 0023dcad-ac94-4fae-9a8e-bc4a49386790.snbt file created in the ftbchunks folder. I can manually create this file and paste the info from my player chunks file eda7321e-80fe-474a-8235-a3f0a5817de3  into the manually created 0023dcad-ac94-4fae-9a8e-bc4a49386790.snbt in the chunks folder and reboot the server and the chunks will be there properly when the server comes back up. So it seems that something is not triggering the creation of the .snbt chunks file.

I've messed around with the different config options like the hard limits, max claimed chunks, and party_limit_mode but these did not seem to help.

I think this issue is specific to 1.20.1 because the same mods and settings on 1.18.2 work fine.

I am currently testing this on a bare bones forge server with only the mods necessary to run ftb teams and chunks to rule out other mod incompatibilities.

I have players on our new 1.20.1 server that are losing their party and chunks every time we reboot so I am definitely open to trying any suggestions if this isn't a bug and just an error on my part.

### Steps to reproduce

1. Create party
2. Claim chunks
3. reboot server
4. party is gone and chunks are unclaimed

**Comment by desht** [comment]
I can't reproduce this problem.  When I create a party and then stop the server, the party data file is written to `world/ftbchunks/<team-id>.snbt` as expected.

Note that the data file isn't written instantly, but saved when the world is saved (either periodically, when you execute `/save-all`, or when the server is stopped).

Could it be that some other mod is causing a crash or lock-up during the server shutdown process, which might prevent the chunk data from being written out?

Also try running `/save-all` after you've created your party team & claimed any chunks, then check that the data file has been written to `world/ftbchunks`

**Comment by desht** [comment]
Yeah, bad file permissions would definitely cause issues. I will take a look at the backend code and see if a clearer error message can be logged in cases like this.
