### ISSUE TITLE
[Bug]: Forceloading chunks

### ISSUE THREAD

**Issue by Thiran23** [FTBTeam/FTB-Mods-Issues#1279]
### Mod

FTB Chunks

### Mod version

ATM9 FTB Chunks 1.20.1

### Forge / Fabric version

Forge 47.2.20

### Modpack & version

ATM9

### What issue are you having?

I have tried a lot of different things to increase the amount of forceloaded chunks i can have. The current max is 25 but i want to increase this, i have watched videos on this but nothing seems to work, i dont know if this is because i am on a server and not a world, is this available on my server with modpack atm9 ? thankyou

### Steps to reproduce

Im not sure where else to ask this question apart from in the bug reports, sorry

**Comment by desht** [comment]
If you're the server admin, open the server config (from the full-screen map, click the purple gear icon in the bottom right, or press Ctrl-S), and change "Max Forceloaded Chunks per Player":

![image](https://github.com/user-attachments/assets/1280d991-3a6e-4e8a-bf6c-0b5d8be5c87d)

If you're not the server admin, then you'll need to ask a server admin to do this.

That changes it for everyone. If you want to change it for only certain players, install FTB Ranks and FTB XMod Compat, and set the `ftbchunks.max_force_loaded` value for the rank, e.g. `/ftbranks node add vip ftbchunks.max_force_loaded 100` allows players in the "vip" rank to force load 100 chunks (this is an admin-level command).
