### ISSUE TITLE
[Bug]: crash when check the jei category of loot crate

### ISSUE THREAD

**Issue by FalAut** [FTBTeam/FTB-Mods-Issues#1284]
### Mod

FTB Quests & FTB XMod Compat

### Mod version

ftb-quests-forge-2001.4.8 & ftb-xmod-compat-forge-2.1.1

### Forge / Fabric version

Forge 1.20.1 47.3.5

### What issue are you having?

https://github.com/user-attachments/assets/05ed8739-5a84-4a8b-87c4-0fb1068b8199

### Crashlogs

https://mclo.gs/Bjt2Gvf

### Steps to reproduce

1. check the jei category of loot crate
2. crash

**Comment by Daniel-1802** [comment]
Experiencing the same issue as well, bug was not fixed in 2001.4.8

**Comment by desht** [comment]
I can't reproduce this. Is this what you mean by "check the category" ?

![image](https://github.com/user-attachments/assets/f18302d2-2db6-438c-a9eb-5630bdfa16d6)
