### ISSUE TITLE
[Bug]: Server fails to launch when XMod and KubeJS are added

### ISSUE THREAD

**Issue by Martmists-GH** [FTBTeam/FTB-Mods-Issues#1291]
### Mod

FTB XMod Compat

### Mod version

2.1.1

### Forge / Fabric version

Forge 47.2.16

### What issue are you having?

The erver crashes on launch with `Loading errors encountered: [
        KubeJS (kubejs) encountered an error during the complete event phase
§7java.lang.RuntimeException: There were KubeJS startup script syntax errors! See logs/kubejs/startup.log for more info
]`

### Crashlogs

startup.log: https://pste.ch/mozoholime.log

### Steps to reproduce

1. Install FTB XMod Compat
2. Install KubeJS
3. Run server

**Comment by desht** [comment]
There's absolutely nothing here to indicate any problem with FTB mods.  You have errors in your scripts, check your `kubejs/startup.log` like the message says.

Closing this. If your startup.log actually suggests it's an FTB mod at fault, feel free to update and I'll take a look.

**Comment by Martmists-GH** [comment]
We have no startup scripts. The logs seem to indicate these scripts are added by `- dev.ftb.mods.ftbxmodcompat.ftbteams.kubejs.FTBTeamsKubeJSPlugin`

**Comment by desht** [comment]
Then please show the startup logs

**Comment by desht** [comment]
> We have no startup scripts
 
And that simply isn't true.  I can see a load of scripts being called in that partial log file you pasted.

**Comment by Martmists-GH** [comment]
Right, but we have none in our kubejs/startup_scripts folder. I can see that it's loading scripts but I have no clue where from, all I know is that it happens after XMod loads.

**Comment by desht** [comment]
I can also see a lot of error in that log which have nothing to do with FTB.  Again, full logs please.  Otherwise we're done here.

> I have no clue where from

I suggest you find out. They're most certainly not added by FTB.
