### ISSUE TITLE
[Bug]: Client crashes after changing oak_log to #log tag

### ISSUE THREAD

**Issue by Hiusi** [FTBTeam/FTB-Mods-Issues#1302]
### Mod

FTB Quest, FTB X Compat, FTB FIlter System

### Mod version

All is the newest

### Forge / Fabric version

Fabric 0.100.8 + 1.21

### Modpack & version

-

### What issue are you having?

Client crashes after adding #log to quest requirement

### Crashlogs

[crash-2024-08-07_14.14.27-client.txt](https://github.com/user-attachments/files/16519727/crash-2024-08-07_14.14.27-client.txt)

### Steps to reproduce

1. I open quest GUI
2. Add Oak log as requirement
3. change to #logs instead
4. crash

**Comment by desht** [comment]
This looks like a dubious mixin in Alloy Forgery to me.  The problem doesn't happen without this mod present.
