### ISSUE TITLE
[Feature Request]: Bulk Changing Shape

### ISSUE THREAD

**Issue by TheBedrockMaster** [FTBTeam/FTB-Mods-Issues#1303]
### Mod

FTB Quests

### Description

In the same way that you can change quests sizes in bulk, you should be able to change their shapes.

This would have saved me a lot of time changing all these quests from circles to squares.
![image](https://github.com/user-attachments/assets/ef822c17-6b51-4c18-b116-b0ad9732b928)

### Describe the solution you'd like

Add a way to change quests shapes in bulk.

### Describe alternatives you've considered

I'm playing 1.20.1, if this has been added since and I didn't know about it...sorry. If there's a way I don't know about, can you let me know? 🤣

**Comment by desht** [comment]
While it's a reasonable feature to request and will be considered, your particular use-case isn't a great one; you would have had a much better time changing the default shape in the chapter to square (and making the one quest at the top a circle).

**Comment by TheBedrockMaster** [comment]
True, but there are more quests than just those in the chapter.

**Comment by desht** [comment]
It's also possible to change the default shape globally (use the Settings button on the right, and "Edit File", select "Shape" from there).

It's a hierarchical system - file defaults, which are overridden by chapter defaults, which are overridden by quest settings.

But yeah more bulk editing options are always good to have so like I said, it's a good feature to add.

**Comment by TheBedrockMaster** [comment]
https://github.com/FTBTeam/FTB-Mods-Issues/issues/175 This issue already covers this.
