### ISSUE TITLE
[Bug]: "Hide Quest until Dependencies are visible" setting hides quests until dependencies are completed

### ISSUE THREAD

**Issue by Xefyr0** [FTBTeam/FTB-Mods-Issues#1306]
### Mod

FTB Quests

### Mod version

2001.4.8 (Latest)

### Forge / Fabric version

Minecraft 1.20.1, Forge 47.3.0

### What issue are you having?

"Hide Quest until Dependencies are visible" quest option actually hides the quest until dependencies are _completed_.

### Steps to reproduce

1. Create new instance with only FTB Quests & dependencies
2. Create new world.
3. In the new world, enable Editing Mode & create a new chapter with 2 quests, A and B
4. Make A a dependency of B.
5. Set B's "Hide Quest until dependencies are Visible" setting to True.
6. A is visible, B is hidden.
7. Force complete A.
8. B becomes visible.

### Anything else to note?

Not the best programmer, but I assume ![this](https://github.com/user-attachments/assets/ad849c7b-abce-471a-87b0-7d5f08f985dc) to be the most likely cause.

(FTB-Quests/common/src/main/java/dev/ftb/mods/ftbquests/quest/Quest.java, line 718)

When this is fixed, please allow both the described and actual behavior to be available options if you may - both are valuable for quest-making.

**Comment by desht** [comment]
There's actually another setting in "Quests -> Dependencies" : "Dependency Requirement".  That can set to all complete / one complete / all started / one started.

This still doesn't do _quite_ what you need ("started" means non-zero progress), but I wonder if adding "all visible" / "one visible" options to that setting might be the best approach here. Along with tidying up the wording of "Hide Quest Until Dependencies Visible"...

**Comment by Xefyr0** [comment]
The Dependency Requirement for a quest determines the level of completion dependent quests must be at before the current quest is unlocked, as indicated by the background becoming a lighter shade of gray.
It has little to do with quest visibility _except_ in combination with another setting, including the one I mentioned above. 
Your suggestion would result in a quest unlocking when one or all dependencies become visible which is not exactly what I'm looking for.

**Comment by desht** [comment]
Actually, the Dependency Requirement _is_ used as part of quest visibility checking (although that's not all it's used for).  You can verify that by looking at the call hierarchy for `Quest#areDependenciesComplete`:

![image](https://github.com/user-attachments/assets/397beebc-d681-467e-a95e-85ff5d74fd68)

Note that this gets called from `Quest#isVisible`

Having said that, I think it will make more sense to have independent "Hide until deps complete" and "Hide until deps visible" settings, simply because it's clearer, so I'm working on that route right now.

**Comment by Xefyr0** [comment]
Thank you for making the fix, and so promptly at that.
I hope to see the next release on Curseforge soon.
