### ISSUE TITLE
[Bug]: quests not visible outside edit mode

### ISSUE THREAD

**Issue by dawidwie** [FTBTeam/FTB-Mods-Issues#1314]
### Mod

FTB Quests

### Mod version

ftb-quests-fabric-2001.4.6

### Forge / Fabric version

fabric 0.15.11

### Modpack & version

Fantasy MC Fabric-2.9.4a-HF2

### What issue are you having?

Certain quests from a page have dissapeared, and are only visible when i turn on editing mode. This also blocks me from collecting the rewards and progressing the game
![image](https://github.com/user-attachments/assets/1075a55d-2e89-460b-9d97-172f54c389b8)
![image](https://github.com/user-attachments/assets/8d39a543-22d7-419e-86fd-cd2a4eeca3c0)

### Steps to reproduce

I dont remember clicking anything that made the quests dissapear

**Comment by desht** [comment]
The fact that the quests have an "eye" symbol on them when in edit mode means that you have indeed altered some setting which is making them invisible outside edit mode. Check the "Hide Quests Until Dependencies Visible" setting both on the quests and on the quest chapter.
