### ISSUE TITLE
[Bug]: FTB quests chash after clicking on the book with quests

### ISSUE THREAD

**Issue by bmd070** [FTBTeam/FTB-Mods-Issues#1317]
### Mod

FTB quests

### Mod version

FTBQuests-1202.9.0.15.jar

### Forge / Fabric version

1.12.2 14.23.5.2860

### Modpack & version

My own modpack

### What issue are you having?

After creating a quest to arrive in the biome, I go back to minecraft, click on the book tab and I am kicked out of the game, please fix the problems with biomes

### Crashlogs

Crash log: [crash-2024-08-17_15.31.45-client.txt](https://github.com/user-attachments/files/16644865/crash-2024-08-17_15.31.45-client.txt)
Log: [2024-08-17-4.log](https://github.com/user-attachments/files/16644869/2024-08-17-4.log)
Debug log: [debug-2.log](https://github.com/user-attachments/files/16644870/debug-2.log)

### Steps to reproduce

1 created a chapter
2 did quests with biomes
3 logged out of the game, logged back in
4 I click on the tab with quests and my game crashed

### Anything else to note?

After creating a quest with biomes, all the items in the store were also missing

**Comment by desht** [comment]
Sorry but 1.12.2 has not been supported for a long time.
