### ISSUE TITLE
[Bug]: Accidentally adding the same item stack twice [Loot Crate] to a Creative Mode Tab: FTB Quests

### ISSUE THREAD

**Issue by sirin1224** [FTBTeam/FTB-Mods-Issues#1318]
### Mod

FTB Quests

### Mod version

ftb-quests-fabric-2001.3.0

### Forge / Fabric version

1.20.1 Fabric 0.92.2

### What issue are you having?

Please Help me..
How can I solve this error?

When I try to open the inventory, game was forced to shut down and read the crash report.
For your information, I am not familiar with ftb quest mode.
Maybe it's a problem after I was trying this and that
I'm running Minecraft on server with my friends

### Crashlogs

[crash-2024-08-19_04.39.36-client.txt](https://github.com/user-attachments/files/16651745/crash-2024-08-19_04.39.36-client.txt)

### Steps to reproduce

When I try to open the inventory, game was forced to shut down and read the crash report.
For your information, I am not familiar with ftb quest mode.
Maybe it's a problem after I was trying this and that

**Comment by desht** [comment]
The error will happen if two loot crate items end up having the same reward table ID, which should never happen normally, so it could be a problem in the quest book data.

Are you running a published modpack downloaded from Curseforge or Modrinth? And if so, which one?

If you're building a custom quest book, or you've modified an existing quest book, I would need to see the your quest book data to know what's going on here - that can be found in `<instance>/config/ftbquests/quests`. Can you create a zip file of that folder and upload it somewhere I see it?
