### ISSUE TITLE
[Bug]: Crash creating a solo world (1.21)

### ISSUE THREAD

**Issue by Flamaghl** [FTBTeam/FTB-Mods-Issues#1322]
### Mod

FTB Quests

### Mod version

ftb-quests-fabric-2100.1.4

### Forge / Fabric version

Fabric - 0.16.2

### What issue are you having?

When trying to create a new world, the game completely crashes and sends me to desktop
When trying to join a 1.20.1 world upgraded to 1.21, game sends me back to title screen after loading to 100%

### Crashlogs

Crash log : 
https://hastebin.com/share/uvipivivof.yaml
Game log :
https://hastebin.com/share/kegereqeye.makefile

### Steps to reproduce

1 - try to create a new world in 1.21
2 - game crashes, pointing at ftb quests

### Anything else to note?

I have deactivated memory leak fix to perform the latest tests but somehow in the log it still speaks about it at some point

**Comment by Flamaghl** [comment]
I could finally get rid of the memory leak thing.
With my latest log and crash report, I think this issue is linked to REI :


[latest.log](https://github.com/user-attachments/files/16788718/latest.log)
[crash-2024-08-28_22.32.27-client.txt](https://github.com/user-attachments/files/16788720/crash-2024-08-28_22.32.27-client.txt)

**Comment by Flamaghl** [comment]
Sorry I misclicked

**Comment by desht** [comment]
FTB Library 2100.1.4 is out of date now, and there have been fixes in this area since.  Please re-test with the latest version of FTB mods (FTB Library is at 2101.1.1 now).

Note: MC 1.21.1 needed; we don't support MC 1.21 anymore (no one should be running a 1.21 server, at all).

**Comment by Flamaghl** [comment]
Hello, 
It indeed works in 1.21.1 with the latest version, no crash

But I can't seem to export my quests from 1.20, when I create a new world my quest book appears empty : Is there a way to export quests cleanly ? thx !

**Comment by Flamaghl** [comment]
Did the config path change perhaps ?
<img width="768" alt="config screenshot" src="https://github.com/user-attachments/assets/42ca3635-2934-48b5-9baa-4afe75f29234">
<img width="1280" alt="ingame screenshot" src="https://github.com/user-attachments/assets/1b085474-550c-47f8-8c43-0884e0d1201e">

**Comment by Flamaghl** [comment]
Nvm I got it to work :) Thx for answering
