### ISSUE TITLE
[Bug]: Can't Call getWaypointManager() from kubejs

### ISSUE THREAD

**Issue by theLadyStardust** [FTBTeam/FTB-Mods-Issues#1323]
### Mod

FTB Chunks

### Mod version

ftb-chunks-forge-2001.3.1

### Forge / Fabric version

1.20.1

### What issue are you having?

I've loaded the FTBChunksClientAPI class in kubejs but calling getWaypointManager throws a "has no public instance field or method named 'getWaypointManager'" error. The code I'm using to load and call the class is below. 

```
const $Manager = Java.loadClass("dev.ftb.mods.ftbchunks.api.client.FTBChunksClientAPI")

const createWaypoint = (wp, name, color) => {
    const wpmanager = $Manager.getWaypointManager()

    var waypoint = wpmanager.addWaypointAt(wp, name)
    waypoint.setColor(color)
}

### Crashlogs

_No response_

### Steps to reproduce

1. Load FTBChunksClientAPI
2. Call getWaypointManager()

### Anything else to note?

_No response_

**Comment by MichaelHillcox** [comment]
This isn't an issue with our mod.
