### ISSUE TITLE
[Bug]: endermen can pick up and place blocks with "Allow Mob Griefing Actions" disabled

### ISSUE THREAD

**Issue by MisteryDuck** [FTBTeam/FTB-Mods-Issues#1333]
### Mod

FTB Chunks

### Mod version

ftb-chunks-forge-1902.4.6-build.360

### Forge / Fabric version

1.19.2 43.3.5

### Modpack & version

All of Create - 3.7

### What issue are you having?

The option "Allow Mob Griefing Actions" in team settings doesn't work for endermen, they are able to pick blocks up and place them in claimed chunks

### Steps to reproduce

1. create a team
2. claim some chunks 
3. set "Allow Mob Griefing Actions" to false

### Anything else to note?

this modpack comes with "Open Parties and Claims" installed, we removed it and installed FTB Chunks

**Comment by desht** [comment]
Fixed in 1902.4.7
