### ISSUE TITLE
[Bug]: Latest Release Dependency ERROR Oversight

### ISSUE THREAD

**Issue by desagas** [FTBTeam/FTB-Mods-Issues#1335]
### Mod

FTB Chunks

### Mod version

neoforge-2101.1.1

### Forge / Fabric version

Neoforge 21.1.50

### Modpack & version

NA

### What issue are you having?

You have the relationship listed to use an version of the FTB Library NOT available on curse. Therefore, nothing will load with this mod installed. Pretty simple but game breaking oversight!

### Steps to reproduce

Install this mod on curse with the publicly available release of FTB Library (2101.1.1), when it is requiring 2101.1.2-SNAPSHOT, which is not available on curse.

**Comment by desht** [comment]
Yep sorry, FTB Library release got delayed. Working on it...

**Comment by desht** [comment]
FTB Library 2101.1.2 is released now, fixes this.
