### ISSUE TITLE
[Bug]: FTB teams claiming without party

### ISSUE THREAD

**Issue by djoey123** [FTBTeam/FTB-Mods-Issues#134]
### Mod

FTB Teams

### Mod version

ftb-teams-forge-1605.2.3-build.40

### Forge / Fabric version

forge-1.16.5-36.2.9

### Modpack & version

FTB Ultimate: Anniversary Edition 1.0.4

### What issue are you having?

When you claim without an party, and later create an party, and add an other player the user is allowed to build etc like normal.

After an server restart, user cant access anything, till you remove the party, and unclaim the chunks.

### Steps to reproduce

1. Claim chunks without party
2. Create party
3. Add player to party
4. Restart server
5. Added player cant acces anything anymore

**Comment by rmccarthy1504** [comment]
Getting the same issue.

1. Claim chunks
2. Create team
3. Invite player to team
4. Claim more chunks
5. Restart server

Chunks claimed in step 1 revert to player only claims.
Chunks claimed on step 4 remain as party only claims.

Other party member then cannot access chunks claimed in step 1.

Have had this happen to 2 parties on our server now.

**Comment by khjxiaogu** [comment]
Got exactly the same issue.

**Comment by billyp673** [comment]
I'm getting the same issue except chunks that were claimed after creating a party are also reverting to player only chunks owned by the person who claimed them

**Comment by MichaelHillcox** [comment]
I'll look into this, sounds like an annoying bug

**Comment by MichaelHillcox** [comment]
We've made modifications to this in newer minecraft versions but will not be backporting the feature changes. Thank you for the report but at this time, we won't be able to make any modifications related to this issue.
