### ISSUE TITLE
[Bug]: FTBChunks minimap uses 90% of client render thread (intermittently?)

### ISSUE THREAD

**Issue by muon-rw** [FTBTeam/FTB-Mods-Issues#1342]
### Mod

FTB Chunks

### Mod version

ftb-chunks-neoforge-2101.1.1

### Forge / Fabric version

1.21.1 21.1.54

### What issue are you having?

Playing with FTB Chunks installed with the default configs tanks performance to 7 FPS on my 7600x+4060 Ti system. 

Here is the spark client profile:
https://spark.lucko.me/DnyZ1Zl6si

In case it expires:
![image](https://github.com/user-attachments/assets/cf4fa161-195b-46d6-a90c-514c4905e466)

### Steps to reproduce

1. Install FTB Chunks
2. Possibly need to fly around a bit, this happens on and off (maybe caused by nearby entities - not sure if this could be some specific modded entity texture)

**Comment by muon-rw** [comment]
I just revisited this and noticed the Merchant Markers mixin, I *highly* suspect this to be the cause of the issue.

**Comment by desht** [comment]
Yep, this is definitely Merchant Markers messing with FTB Chunks. Feel free to complain to them (and let them know we don't love people mixing into our mods... this could break on any update, and we'll end up getting the player complaints).
