### ISSUE TITLE
Ultimine causes game to crash 

### ISSUE THREAD

**Issue by ozanorhan** [FTBTeam/FTB-Mods-Issues#1346]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.1.2

### Launcher

CurseForge

### Has the pack been modified

Yes

### Log Files

https://pste.ch/oqahomiled.pl

### Describe the bug

I added FTB Ultimine and FTB Ultimine Addition 

### Steps to reproduce

1. Equip Axe 
2. Right click with that axe
3. Game crashes

Attached logs are with Axe but most of the tools are the same. Also having the ultimine ability itself is irrelevant 

### Expected behaviour

It shouldn't crash

**Comment by desht** [comment]
This is due to a bad mixin in Ultimine Addition, a third party mod not created by us.

This is why we do not welcome other mods mixing into our mods; they invariably break something, and we end up taking the blame. Please complain to the author of Ultimine Addition.
