### ISSUE TITLE
[Bug]: mouseClicked event handler Crash

### ISSUE THREAD

**Issue by SirTwsted** [FTBTeam/FTB-Mods-Issues#1349]
### Mod

FTB Library

### Mod version

2101.1.3

### Forge / Fabric version

NEOForge v21.1.65

### What issue are you having?

Hi, 
I am using Minecraft v1.21.1 with NEOForge v21.1.65  and FTB Library v2101.1.3
I was using the FTB Quest and collecting my rewards, when BOOM got a crash when I clicked on something.  Here is the crash report.

### Crashlogs

https://paste.feed-the-beast.com/view/fa18cddf

and 

https://pastebin.com/hNd4AawF

### Steps to reproduce

Click on any rewards to get rewards, and BOOM crash.

### Anything else to note?

![ftb library crash](https://github.com/user-attachments/assets/5073871b-49af-4ce3-a331-32a8a32e791b)

**Comment by desht** [comment]
The crash appears to be occurring in BucketLib when it's trying to add its registered buckets to the creative tab, and encountering duplicates.  All FTB Quests is doing here is a requesting a creative tab rebuild from vanilla to ensure its item display cache is up to date, which isn't an operation that should cause crashes.

```
net.neoforged.fml.ModLoadingException: Loading errors encountered:
	- BucketLib (bucketlib) encountered an error while dispatching the net.neoforged.neoforge.event.BuildCreativeModeTabContentsEvent event
	  java.lang.IllegalArgumentException: Itemstack 1 woodenbucket:wooden_bucket already exists in the tab's list
```

So I'd suggest raising an issue with BucketLib to see why duplicates are occurring here.

**Comment by UnRealDinnerbone** [comment]
Mod issue fixed
