### ISSUE TITLE
[Bug]: Death Beam Remains annoyance

### ISSUE THREAD

**Issue by SirTwsted** [FTBTeam/FTB-Mods-Issues#1350]
### Mod

FTB Chunks

### Mod version

2101.1.1

### Forge / Fabric version

NEOForge v21.1.65

### What issue are you having?

I first checked with Journey mod developers and issued a complaint about this issue,
I was told it was NOT their issue or mod and that It is possibly FTB chunks.
I am using 

Minecraft v1.21.1
NEOForge v21.1.65
FTB Chunks v2101.1.1

The problem is when I delete my "Death Mark" a beam still remains after the bookmark is deleted.
When I pointed this out to Journey map, they immediately said, "That is not our beam"

So here I am submitting the issue with you guys.
Here are some screenshots,  they have the similar screenshots.
And as you can tell from ALL the screenshots, this is getting annoying, because its filling up my world.  😳😢

![2024-09-30_23 16 50](https://github.com/user-attachments/assets/550dd181-2cd6-4407-9621-f957c1c64bc1)

![2024-09-23_12 51 34](https://github.com/user-attachments/assets/3e29aa07-ced0-45c1-aa97-fde264c94f3d)

![2024-09-18_09 45 36](https://github.com/user-attachments/assets/4c99f2fb-cffa-4063-a339-554b95034f00)

![2024-09-18_13 15 48](https://github.com/user-attachments/assets/1ab18288-a7f3-4237-8f4c-b384504d294c)

![2024-09-18_08 47 21](https://github.com/user-attachments/assets/2a3cacec-6ca2-4a7b-99d6-ba46ad699b2e)

![2024-09-18_15 11 09](https://github.com/user-attachments/assets/e37b91b3-7af3-4993-beba-aa8f7a3c93ad)

![2024-09-20_14 36 06](https://github.com/user-attachments/assets/03a55b03-62d6-4839-81b1-aa4d0038ee2e)

### Crashlogs

There are no logs,  this is a graphics issue.

### Steps to reproduce

Have FTB entire lineup installed,  Have Journey Map installed.
Have a mob kill you,  then delete the death bookmark.
For some reason death mark still remains but not from Journey Map, I was told its from FTB Chunks.

**Comment by desht** [comment]
FTB Chunks has no integration with Journeymap whatsoever, so if deathpoints are leaving markers in world, it's hard to see how FTB Chunks could be at fault.

I just tested with both FTB Chunks and Journeymap in the instance, and as expected two waypoint beacons were added on player death. I removed the FTB Chunks waypoint (using the "remove all death waypoints" button on the map), and as expected the FTB Chunks waypoint and beacon both disappeared, leaving another beacon which is definitely not FTB Chunks (I can tell because it renders and animates quite differently).

Upon removing Journeymap from the instance, that second beacon unsurprisingly disappeared.

So no, I'm afraid you've been misinformed. The remaining beacon is very definitely from Journeymap, not FTB Chunks.

**Comment by mysticdrew** [comment]
> FTB Chunks has no integration with Journeymap whatsoever, so if deathpoints are leaving markers in world, it's hard to see how FTB Chunks could be at fault.

not sure where you got that from? No one said there was integration. 

The users said it was journeymap, I said it was not, and it is likely FTBChunks death beacon. (We get a lot of this when mod packs add both mods.) 

Also said they do not have to be a map mod adding them. 
![image](https://github.com/user-attachments/assets/52ea4651-76c3-4f95-942c-b3b244f6a6b7)


Either way, it's not yours, it's not ours. it's up to the user to figure it out. 
It is likely a gravestone mod adding them or some other mod. Beacons are pretty trivial to add, any mod can do it.

**Comment by SirTwsted** [comment]
**I don't have Gravestone mod installed.**

I am going to test thing again.   I will deactivate each mod, between Journey Map and FTB Chunks.
And see what results I get.  I will need to reboot minecraft 3 to 4 times, and activating and deactivating both mods.
FTB Chunks and Journey Map.

One of these 2 is doing this,  and I have to figure out exactly which one AGAIN.  😳😢

Maybe you guys can get together and hash this out so this problem doesn't happen again with other users,  since you mentioned that this is not the only time this has been brought up when people have both mods installed.

Anyway,  I am currently testing this out by turning ON and OFF each your mods and finding out what happens.
again, to make sure.

**Comment by SirTwsted** [comment]
Ok, test complete
I do not have any gravestone mods installed, because when I create a new game, 
I have "Keep Inventory Items on Death"  As seen here.   When I get off work, all I want to do is play and explore,
Not chase after my things on death.
![Screenshot_552](https://github.com/user-attachments/assets/bd9aec29-2aad-4829-a10c-c015913a0109)


As far as the test of both FTB Chunks and Journey Map, these are the results,
When activating and De-Activating each mod having to reboot minecraft 4 times throughout the process.

THIS is both mods activated ON and ON:
![THIS is both mods activated](https://github.com/user-attachments/assets/21c0e3a8-4163-4f91-aff8-28d238251c4d)


THIS is JourneyMap turned OFF and FTBChunks turned ON:
![THIS is JourneyMap turned OFF and FTBChunks turned ON](https://github.com/user-attachments/assets/50465c8a-7b5f-434c-9a9b-25585fde134e)


THIS is JourneyMAP turned ON and FTB Chunks turned OFF:
![THIS is JourneyMAP turned ON and FTB Chunks turned OFF](https://github.com/user-attachments/assets/d42cb9b5-30d6-49bf-a07c-72cbea920fa5)


THIS is both mod activated again ON and ON:
![THIS is both mod activated again](https://github.com/user-attachments/assets/6f50318c-bb6f-4192-aaf2-7f40bb4ba4b3)
