### ISSUE TITLE
[Bug]: quests have been reset to zero

### ISSUE THREAD

**Issue by imfakeheart** [FTBTeam/FTB-Mods-Issues#1354]
### Mod

FTB Quests

### Mod version

ftb-quests-fabric-2001.2.0.jar

### Forge / Fabric version

1.20.1

### Modpack & version

Prominance II (3.0.5h)

### What issue are you having?

I have my own hosting server, I played minecraft, went through some chain of quests. today, after 2 days of absence, I went back to my server and all my quests were reset. the file with quests on the server was simply overwritten (it weighed 11mb, it began to weigh 0). What could it be?

and the question is, is there any way to link quest data to a MySQL database?

### Crashlogs

[2024-10-02-4.log](https://github.com/user-attachments/files/17255785/2024-10-02-4.log)
[2024-10-02-5.log](https://github.com/user-attachments/files/17255786/2024-10-02-5.log)
[2024-10-02-6.log](https://github.com/user-attachments/files/17255787/2024-10-02-6.log)
[2024-10-02-7.log](https://github.com/user-attachments/files/17255788/2024-10-02-7.log)

### Steps to reproduce

Is this possible due to server overload?

**Comment by desht** [comment]
> the file with quests on the server was simply overwritten

Which file, exactly, are you talking about here?

> and the question is, is there any way to link quest data to a MySQL database?

No, there is no plan for any MySQL or other database support for this.
