### ISSUE TITLE
[Bug]: Quests not auto completing

### ISSUE THREAD

**Issue by violetkitty87** [FTBTeam/FTB-Mods-Issues#1355]
### Mod

FTB Quests

### Mod version

ftb-quests-forge-2001.4.8

### Forge / Fabric version

Forge- 47.3.10

### Modpack & version

Frisky Business Powercraft Edition 2 version 1.3

### What issue are you having?

Currently, the quests that are set to auto complete instead of submitting manually take a really long time to submit and sometimes won't till you enter edit mode. It's a problem for those who do not want to play in cheat mode and makes it impossible to continue the quests. Some do not do this, tho it's only a chunk of the quests.

### Steps to reproduce

1. Really any quest, complete it.
2. Sit and wait for quest to complete. If not, enter edit mode.

### Anything else to note?

I'd like to suggest also to make it easier to set the item to be a category of an item. i.e. logs. I do not know how to code, so the way it's currently set to do that is quite confusing.

**Comment by WyFryMU** [comment]
That modpack youre playing has the FTB Quests Optimizer addon mod which makes it so it only checks for quest progress every *x* amount of ticks. If you remove the FTB Quests Optimizer mod, you should be fine. Or you can look at it's config and make it check quest progression more often.

**Comment by violetkitty87** [comment]
Ok, appreciated, ill look into that when I go to attempt to update the pack in a few days.

**Comment by violetkitty87** [comment]
ok ty that fixed it
