### ISSUE TITLE
[Bug]: Throws out of the game when pressed yes

### ISSUE THREAD

**Issue by kokon4456** [FTBTeam/FTB-Mods-Issues#1360]
### Mod

FTB Infinity Evolved 1.7 Version 3.1.0

### Mod version

FTB Infinity Evolved 1.7 Version 3.1.0

### Forge / Fabric version

FTB Infinity Evolved 1.7 Version 3.1.0

### Modpack & version

FTB Infinity Evolved 1.7 Version 3.1.0

### What issue are you having?

![изображение_viber_2024-10-10_15-45-34-541](https://github.com/user-attachments/assets/cc85cf70-512d-4db0-ae78-79dfb09ec5d8)

### Crashlogs

https://hastebin.com/share/yivoxefero.ruby

### Steps to reproduce

Throws out of the game when pressed yes

**Comment by desht** [comment]
Sorry but 1.7 has not been supported for a very long time.

**Comment by kokon4456** [comment]
> Вибачте, але 1.7 не підтримується дуже довго.

Так видаліть з програми цю версію, якщо ви не хочете займатися підтримкою, або зробіть на новій версію цю саму збірку
