### ISSUE TITLE
[Bug]: Added tools are not able to activate ultimine

### ISSUE THREAD

**Issue by ShadowDragon1848** [FTBTeam/FTB-Mods-Issues#1368]
### Mod

FTB Ultimine

### Mod version

ftb-ultimine-fabric-2001.1.5

### Forge / Fabric version

Fabric 0.16.7

### What issue are you having?

It seems impossible to add items as tools in the included tools folder.

### Steps to reproduce

 I tried everything to include tools from Modern Industrialization, but no matter what I do, when I activate the option that you need a tool to ultimine it does not work. 

I looked into the files and tried to add the tools from MI. I opened the main folder and navigated to the data\ftbultimine\tags\items\ folder. Then I looked in the excluded tools to look how it's made there and copied the syntax. But as I said, it does not work.

**Comment by desht** [comment]
Show the tag files you created

**Comment by UnRealDinnerbone** [comment]
Looks like you are missing a `,` on line 7 and have an extra one on line 20

**Comment by ShadowDragon1848** [comment]
I fixed the two errors, but the result is the same.

**Comment by WyFryMU** [comment]
In order for a datapack to override the file, it needs the same file/folder structure. Your datapack is named "small_changes", but the 2nd "small_changes" should be "ftbultimine". So changed the folder name to ftbultimine.

**Comment by ShadowDragon1848** [comment]
You're right. It works now. Thank you very much!
