### ISSUE TITLE
[Bug]: Untamed Wilds entities not showing on FTB Chunks map

### ISSUE THREAD

**Issue by Maltshakes** [FTBTeam/FTB-Mods-Issues#1370]
### Mod

FTB Chunks

### Mod version

ftb-chunks-forge-2001.3.1

### Forge / Fabric version

Forge 47.3.0

### What issue are you having?

I'm noticing that neither my map or minimap are showing any entities from Untamed Wilds. I am still seeing icons/pips on the map for entities from other mods, just not Untamed Wilds. 

### Steps to reproduce

1. Install FTB Chunks
2. Install Untamed Wilds
3. Witness the lack of UW entities on the map

**Comment by UnRealDinnerbone** [comment]
This seems to be an issue with Untamed Wilds, they are marking all their mobs are `MISC` in the MobCategory and FTB Chunks does not render MISC mobs in 1.20. The most mobs should most likely either be `MONSTER` or `CREATURE`
