### ISSUE TITLE
[Bug: Chunks] Map shouldn't show non-activated waystones

### ISSUE THREAD

**Issue by MichaelHillcox** [FTBTeam/FTB-Mods-Issues#1374]
### Mod

FTB Chunks

### Mod version

---

### Forge / Fabric version

Both

### Modpack & version

---

### What issue are you having?

See title

### Steps to reproduce

See title

**Comment by desht** [comment]
By activated, I guess this means it's owned by a player. There's a `waystone.hasOwner()` method in the Waystones API we could probably use here.

**Comment by UnRealDinnerbone** [comment]
Oh, I did start this, never made the PR about https://github.com/FTBTeam/FTB-XMod-Compat/pull/27
I saw that `waystone.hasOwner()` was thing. But the issue with that was that it would then show if anyone found, not if you found it. Don't know what your thoughts about using no api method is https://github.com/FTBTeam/FTB-XMod-Compat/pull/27

**Comment by desht** [comment]
Hmm, maybe it should only show your own waystones?  Which would be a check of `waystone.getOwnerUid().equals(clientPlayer.getUUID())`.

Is there a reason to ever see other player's waystones? I guess we could expand that to player and player's team mates (we know FTB Teams is present so easy enough to use the FTB Teams api there).

**Comment by UnRealDinnerbone** [comment]
Released in FTB XMod Compat 21.1.1
