### ISSUE TITLE
[Bug: Ranks/Essentials]:  Cooldown on commands do not reset when a players rank is changes that mutates the cooldown

### ISSUE THREAD

**Issue by MichaelHillcox** [FTBTeam/FTB-Mods-Issues#1375]
### Mod

FTB Ranks / Essentials

### Mod version

Latest <3

### Forge / Fabric version

Both

### Modpack & version

---

### What issue are you having?

See title

### Steps to reproduce

- RTP
- RTP Again (see cooldown error)
- Create rank with different cooldown
- Add rank to player
- Try to RTP

**Comment by desht** [comment]
Fixed in 2101.1.1 release
