### ISSUE TITLE
[Feature Request]: make "Stays open" : "Doesn't stay open" translatable

### ISSUE THREAD

**Issue by marlester-dev** [FTBTeam/FTB-Mods-Issues#1376]
### Mod

FTB Quests

### Description

currently, "Stays open" : "Doesn't stay open" are hardcoded and we can't translate them
this code line: https://github.com/FTBTeam/FTB-Quests/blob/0e21d4342c5da36f353f277290f7985180466ad5/common/src/main/java/dev/ftb/mods/ftbquests/client/gui/quests/ChapterPanel.java#L273

### Describe the solution you'd like

add a translation key for them

**Comment by desht** [comment]
Fixed in 2101.1.1
