### ISSUE TITLE
[Feature Request]: Update JEI Extras to support the latest AdvancedAE update

### ISSUE THREAD

**Issue by Pumpkin7266** [FTBTeam/FTB-Mods-Issues#1378]
### Mod

JEI Extra

### Description

Reaction Chamber got changed, new recipe UI on EMI side is this
![image](https://github.com/user-attachments/assets/84043952-3f80-4fb4-8d7e-f51ff518ad79)
on JEI with jei extras it currently looks like this
![image](https://github.com/user-attachments/assets/c654fbc0-89f3-40ed-a3f8-1eb0ae0f5442)

for reference, this was the old UI with JEI extras before 27th october AdvancedAE update
![image](https://github.com/user-attachments/assets/d9368f4f-18b9-4f0b-9da7-99d21f888e6e)

**Comment by MichaelHillcox** [comment]
Oh no... Looks like someone updated a texture! I can look into this, thanks for letting us know :+1:

**Comment by Officialy** [comment]
Fixed and released :)
