### ISSUE TITLE
[Bug]: Minimap information is not saved

### ISSUE THREAD

**Issue by MrHimera** [FTBTeam/FTB-Mods-Issues#1379]
### Mod

FTB Chunks

### Mod version

ftb-chunks-forge-2001.3.2

### Forge / Fabric version

Forge 1.20.1 47.3.0

### What issue are you having?

After restarting the game, the minimap information (time type, visibility of elements, etc.) is reset to standard.

### Steps to reproduce

1. Change the minimap information (for example, the time type)
2. Restart the game
3. See how the information has reset to the standard.

**Comment by desht** [comment]
Confirmed, will be fixed in next FTB Library release (coming very soon).

**Comment by desht** [comment]
Fixed in 2001.2.5 release
