### ISSUE TITLE
[Bug]: Some non-full block appears black on FTB Chunks map

### ISSUE THREAD

**Issue by YocyCraft** [FTBTeam/FTB-Mods-Issues#1381]
### Mod

FTB Chunks

### Mod version

ftb-chunks-neoforge-2101.1.2

### Forge / Fabric version

Neoforge 1.21.1-21.1.72

### What issue are you having?

Some incomplete blocks appears completely black on the FTB Chunks map. I've found this issue for lever, chain, end rod, glass pane (and it's stained variant), redstone repeater and redstone comparator.

![2024-11-04_22 57 57](https://github.com/user-attachments/assets/aee8a3bb-379e-4bfb-b498-395ad63dc450)
![2024-11-04_22 58 02](https://github.com/user-attachments/assets/000924fb-afd5-423e-8dd3-6cf53b0385ec)

### Steps to reproduce

1. Fill a large area with levers in the open air.
2. Look at FTB Chunks map.

**Comment by desht** [comment]
Fixed in FTB Chunks 2101.1.3
