### ISSUE TITLE
[Bug]: Crash on creating/editing waypoints with negative coords

### ISSUE THREAD

**Issue by Gaz492** [FTBTeam/FTB-Mods-Issues#1382]
### Mod

FTB Chunks

### Mod version

ftb-chunks-neoforge-2101.1.2

### Forge / Fabric version

neoforge 21.1.72

### Modpack & version

FTB Evolution

### What issue are you having?

If you create or edit a waypoint with negative coords you can cause a crash to happen

### Crashlogs

https://pste.me/@ibQGNtgLiNc

https://github.com/user-attachments/files/17638298/crash-2024-11-05_21.36.08-client.txt

### Steps to reproduce

1. Open map
2. Create or edit a waypoint
3a. If editing a waypoint with a negative pos, press <kbd>Ctrl</kbd> + <kbd>A</kbd>, Now press <kbd>Backspace</kbd>
3b. If creating a waypoint paste a negative pos e.g -123
5. Crash

### Anything else to note?

You cant type a negative number in the x,y,z pos

Issue originally reported at https://github.com/FTBTeam/FTB-Modpack-Issues/issues/6093

**Comment by desht** [comment]
Fixed in FTB Library 2101.1.5
