### ISSUE TITLE
[Bug]: crash with carpet mod essential addons's reload fake players

### ISSUE THREAD

**Issue by krispyking24** [FTBTeam/FTB-Mods-Issues#1387]
### Mod

ftb ultimine

### Mod version

ftb-ultimine-fabric-2001.1.5

### NeoForge / Forge / Fabric version

fabric 0.16.9

### What issue are you having?

crash when loading into a world that has carpet mod, essential addons's reload fake players config enabled permanently

### Crashlogs

[crash log](https://hastebin.com/share/qekeyotuhu.yaml)
[latest.log](https://hastebin.com/share/holayaxeyi.makefile)

### Steps to reproduce

1. get the mods ftb-ultimine-fabric-2001.1.5, essentialaddons-1.20.1-1.2.2 and there dependences
2. load into a world run /carpet setDefault reloadFakePlayers true (might require /carpet reloadFakePlayers true ) then /player Steve spawn
3. leave the world and rejoin on rejoin the game crashes

### Anything else to note?

reading the log it looks like the crash is due to "this.knownServerRegistries" being null

**Comment by krispyking24** [comment]
not to rush u or anyone but is there an eta on 2101.1.6?

**Comment by desht** [comment]
Yeah, 10 days ago: https://www.curseforge.com/minecraft/mc-mods/ftb-library-fabric/files/5893688

**Comment by krispyking24** [comment]
ah sorry i looked at the github releases and didn't see a release

**Comment by krispyking24** [comment]
looks like its not released for 1.20.1 which is the version that I experienced the crash on

**Comment by desht** [comment]
Ah yeah, will get a 1.20.1 release out shortly. Sorry about that.

**Comment by desht** [comment]
2001.2.6 is out now with that fix.
https://www.curseforge.com/minecraft/mc-mods/ftb-library-fabric/files/5925396
