### ISSUE TITLE
[Bug]: Waypoint Markers Broken

### ISSUE THREAD

**Issue by gold-me** [FTBTeam/FTB-Mods-Issues#1389]
### Mod

FTB Chunks (NeoForge)

### Mod version

ftb-chunks-neoforge-2101.1.3.jar

### NeoForge / Forge / Fabric version

Minecraft 1.21.1 NeoForge 21.1.74

### Modpack & version

FTB Evolution 1.2.0

### What issue are you having?

The FTB Waypoint marker lines are broken and misaligned when rendered. See [this issue](https://github.com/FTBTeam/FTB-Modpack-Issues/issues/6047) for more details and a screenshot.

### Crashlogs

https://mclo.gs/0t80omi (Not a crash)

### Steps to reproduce

1. Make a waypoint
2. Reach a distance where the beacon line can be rendered
3. Observe

### Anything else to note?

Issue has been tested by me as the FTB Evolution pack updates, and still persists on the current latest version.

**Comment by desht** [comment]
This issue does not occur in a dev instance or in test instances (both SSP and SMP) outside FTB Evolution. So it's looking likely that some other mod is Evolution is causing this misalignment.

**Comment by desht** [comment]
This would appear to be an incompatibility with the Iris mod, but we're continuing to investigate.

**Comment by desht** [comment]
Confirmed as a bug in Iris, and affecting multiple mods: https://github.com/IrisShaders/Iris/issues/2535

This needs a fix in Iris, nothing we can do about it.
