### ISSUE TITLE
[Bug]: big arrow in ftb chunks

### ISSUE THREAD

**Issue by VaporeonScripts** [FTBTeam/FTB-Mods-Issues#1391]
### Mod

FTB Chunks

### Mod version

latest

### NeoForge / Forge / Fabric version

1.21.1 .79

### Modpack & version

NeoTech Reborn

### What issue are you having?

![image](https://github.com/user-attachments/assets/e387d664-afb5-4b4d-8698-cd5bab45299a)

### Crashlogs

nah

### Steps to reproduce

install latest mod

### Anything else to note?

:3

**Comment by VaporeonScripts** [comment]
so??

**Comment by desht** [comment]
Fixed in 2101.1.4 (can select player-head/arrow/both in client config now)
