### ISSUE TITLE
[Bug]: Mod file problem

### ISSUE THREAD

**Issue by GameFunn** [FTBTeam/FTB-Mods-Issues#1392]
### Mod

FTB Quests

### Mod version

ftb-quests-forge-2001.4.8

### NeoForge / Forge / Fabric version

forge-1.20.1-47.3.12-universal

### What issue are you having?

I have a problem with this mod, I have downloaded version **2001.4.8** and in the crash log it shows me that I have downloaded version **2001.3.0** but in the files it shows me in the filename that it is **2001.4.8** and I don't know how to fix it. I would be glad if someone could please help me.

### Crashlogs

[Crash log URL](https://hastebin.com/share/ejewufefax.php)
[Mod list](https://hastebin.com/share/etilupiguf.css)

### Steps to reproduce

1. I just run the minecraft nothing more

### Anything else to note?

I don't know anything more yet.

**Comment by desht** [comment]
I honestly have no idea why your instance is claiming that the installed FTB Quests is on version 2001.3.0. You have:

```
16.11.2024  15:09         1 181 709 ftb-quests-forge-2001.4.8.jar
```

which is definitely the correct file size for 2001.4.8, so I think you have the right file there.  (2001.3.0 is only 1167692 bytes in size).

I can only suggest reinstalling your instance, something is broken with it.

**Comment by desht** [comment]
It would be helpful if you provided your entire `latest.log`, not just the crash log.

**Comment by GameFunn** [comment]
Sorry for waiting here is the [ latest.log ](https://pastebin.com/4jCeqyuS), and thanks for trying to help me! :D

**Comment by desht** [comment]
This log file clearly shows that ftbquests 2001.4.8 is being loaded.  I suspect something's broken in your instance, and I can only suggest re-installing it (having backed up any worlds you've created first).

**Comment by GameFunn** [comment]
Okay I think I've got it sorted according to ChatGPT it was this: 

> Mixin Conflicts:
> Conflicts like ModifyConstant indicate that two mods (e.g. bigcontraptions and packetfixer) are trying to modify the same > method in the FriendlyByteBufMixin class, causing incompatibility.

So I removed the bigcontraptions mod and it works now! But otherwise thanks for the help 3:
