### ISSUE TITLE
[Feature Request]: FTBChunks 1.20.1 fix black map when switching servers behind Velocity Proxy

### ISSUE THREAD

**Issue by MineYF** [FTBTeam/FTB-Mods-Issues#1394]
### Mod

FTBChunks

### Description

https://github.com/FTBTeam/FTB-Mods-Issues/issues/1377
I saw a fix for this issue, but it was for version 1.21. I am currently using version 1.20.1 fabric, and I hope that version 1.20.1 can also fix this issue. Thank you

**Comment by desht** [comment]
Yes, we can do a backport of that fix.

**Comment by desht** [comment]
Fixed in 2001.3.3 release
