### ISSUE TITLE
[Feature]: Detect Farmers Delight Budding Tomato Plant as crops With FTB Ultimine. 

### ISSUE THREAD

**Issue by ellelapsus** [FTBTeam/FTB-Mods-Issues#1397]
### Mod

FTB Ultimine / Farmer's Delight

### Mod version

FTB Ultimine 2101.1.1, Farmer's Delight 1.2.5

### NeoForge / Forge / Fabric version

neoforge 21.1.74

### Modpack & version

FTB Evolution 1.3.0

### What issue are you having?

Using Ultimine on crops doesn't include budding tomato vines. It does still include onions and cabbage from the same mod.
"Budding Tomato Vine" isn't included but "Tomato Vine" is included. 

### Steps to reproduce

![image](https://github.com/user-attachments/assets/afce5465-0a35-4f3f-90c7-ac215a9814be)
![image](https://github.com/user-attachments/assets/0baee488-8980-44f8-a188-4226bfc39d5c)

**Comment by desht** [comment]
Not really a bug in Ultimine; Farmer's Delight budding tomato vine blocks are actually bushes, not crops, which is why Ultimine doesn't detect them.

This could be worked around, but it will require specific integration with Farmer's Delight to do.

**Comment by desht** [comment]
Thinking about this further, why do you actually need the budding vines to be included as crops? They're immature versions of the tomato crop, right?  So why would you want to harvest them before they're proper tomato crops?
