### ISSUE TITLE
[Feature Request]: AdvancedAE removed from FTB JEI Extras

### ISSUE THREAD

**Issue by pedroksl** [FTBTeam/FTB-Mods-Issues#1401]
### Mod

FTB JEI Extras

### Description

I'd like to request the removal of AdvancedAE from the mod. I'm the dev for AdvancedAE and I've added JEI support to it. I appreciate the support provided. However there were (and still are) some issues with the JEI support and there's a delay every time something gets changed or added. So I decided to implement it myself, to make sure it's always up to date and decrease the amount of issues I receive in my github page.

Again, greatly appreciate the support during the time I didn't provide it myself, but I will keep it up to date from now on.

**Comment by MichaelHillcox** [comment]
Sure thing! Great to hear that you've adopted JEI support yourself, <3 Could you let me know what version of your mod you have started supporting this for and if you've backported the support at all?

**Comment by UnRealDinnerbone** [comment]
Removed in FTB JEI Extras 21.1.4
