### ISSUE TITLE
[Bug]: Tinkers Construct 2.0 Smeltery

### ISSUE THREAD

**Issue by squishey123** [FTBTeam/FTB-Mods-Issues#1404]
### Mod

Tinkers Construct (Bedrock Edition)

### Mod version

2.0

### NeoForge / Forge / Fabric version

Bedrock Edition

### Modpack & version

Bedrock Edition 1.21.44

### What issue are you having?

I'm under the assumption that this is still categorized as an FTB Mod as the marketplace page says **Tinkers' Construct 2.0 By FTB** but with the new 2.0 release the smeltery can no longer be used. Existing smelterys made before the update have phantom blocks in place of the tank, controller and drain. When broken they give nothing and the items for those 3 are floating on the ground. After breaking and replacing the whole smeltery and adding fuel to the tank, the smeltery does not turn on, it does form the multi-block but not allow items to be put in. The controller and drain also seem to be duplicating with fortune oddly enough.

### Steps to reproduce

**Pre-Update:**

1. Make a functional smeltery

**Update the Add-on**

1. Break down the smeltery completely and pick up the floating controller, tank, and drain from the ground
2. Remove the phantom blocks
3. Attempt to re-assemble the smeltery

:sad

**Comment by WyFryMU** [comment]
This should be in https://github.com/FTBTeam/FTB-Bedrock-Issues/issues (which I think one of the FTB staff can move it there)

**Comment by squishey123** [comment]
https://github.com/FTBTeam/FTB-Bedrock-Issues/issues/143#issue-2713687467
