### ISSUE TITLE
[Bug]: FTB Quests - "/title" command as reward won't allow connection to server

### ISSUE THREAD

**Issue by aguzzfw** [FTBTeam/FTB-Mods-Issues#1406]
### Mod

FTB Quests

### Mod version

ftb-quests-forge-2001.4.9

### NeoForge / Forge / Fabric version

Forge 1.20.1 - 47.3.0

### What issue are you having?

Hello! I'm having trouble adding a "/title" command as a reward on a quest in FTB Quests. When I'm on the server, the command and the quest work perfectly, however, when resetting the server and trying to connect again from the client, the following message appears: 

![image](https://github.com/user-attachments/assets/46945a0c-d401-44d1-9f85-bef48fa2c14a)

The error won't dissappear (and won't allow me to connect to server), until I remove the quest file (.snbt) from the server, or the "/title" command from the file.

### Crashlogs

Here's the error message:
![image](https://github.com/user-attachments/assets/46945a0c-d401-44d1-9f85-bef48fa2c14a)

Here's the latest.log from server:

https://paste.feed-the-beast.com/view/af01b04f

The latest.log from client:

https://paste.feed-the-beast.com/view/90623c6a

And, here's the quest file used (.snbt):

https://paste.feed-the-beast.com/view/8f4652f7

### Steps to reproduce

1. On the client, add "/title" command as a reward for a quest on a modded server using the FTB Quests GUI. For example: _/title @p title \"Los Amantes\"_
2. Reset the server.
3. Try to connect from client.

**Comment by desht** [comment]
There's nothing in either log file to suggest any issue with FTB Quests, and just adding a /title command as a reward would not cause a network error like this.

This is just coincidence, I'm afraid, and nothing to do with FTB Quests.
