### ISSUE TITLE
[Bug]: Smart Filter OR filter issue

### ISSUE THREAD

**Issue by DarkBladeNemo** [FTBTeam/FTB-Mods-Issues#1419]
### Mod

FTB Filter System, FTB Quests

### Mod version

ftb-filter-system-neoforge-21.0.0.0, ftb-quests-neoforge-2101.1.1

### NeoForge / Forge / Fabric version

Neoforge - 21.1.85 (Tested on 21.1.83 as well)

### Modpack & version

Custom 1.21.1 pack

### What issue are you having?

Making a quest that uses an OR filter seems to not apply properly. I tried making some crop quests with Farmer's delight installed and it ends up doing weird things like Beetroot completing Cabbage quests or vice versa. 

I have FTB Xmod compat installed just in case.

### Steps to reproduce

Make a Smart Filter with OR for Farmer's delight Cabbage and Cabbage Seeds.
Create a quest with that filter.
Change the filter to Beetroot and Beetroot seeds.
Create a quest with that filter.
Grab item to trigger quests. (one item will trigger both quests, the other won't trigger any quests.)

### Anything else to note?

I have also experienced this issue with other mods like Croptopia. I created a test project with only the FTB mods and Farmer's delight to reproduce the issue. A video to show the issue, had to compress it a little more but it should be fine.

https://github.com/user-attachments/assets/6095e67e-86ad-466a-b8f1-73e859ef854f

It could be I am using it wrong.

**Comment by desht** [comment]
Confirmed.

**Comment by desht** [comment]
There's a bug in FTB Filter System right now which is causing some cache corruption (the cache is important to quickly look up compiled filters from the raw filter strings stored on the filter item).  I'm trying to track that down now, but a short-term workaround is to run `/ftbfiltersystem cache clear` after setting up the second quest. This should resolve the issue, and should only be necessary to run once, after the quests are set up.

**Comment by desht** [comment]
Fixed in FTB Filter System 21.0.1
