### ISSUE TITLE
[Feature Request]: Square Minimap on 1.16.5 for FTB Chunks

### ISSUE THREAD

**Issue by darealGameknight14** [FTBTeam/FTB-Mods-Issues#1421]
### Mod

FTB Chunks

### Description

I love this mod in almost every way, mainly because it is compatible with every other mod that you have. But for the life of me I cannot find a way to make the minimap square in earlier versions! The circular minimap has been a style I never really enjoyed, especially for a blocky game like minecraft. Compared to the other mods I have added, it just feels... off.

### Describe the solution you'd like

Add an option to make the minimap square instead of round. This shouldn't be too hard as it already features a "square" version in the large map.

### Describe alternatives you've considered

The only alternative is to use a different minimap mod, which saddens me because it means I will lose out on the chunk claiming capabilities of FTB chunks combined with FTB teams.

**Comment by WyFryMU** [comment]
> ### Describe alternatives you've considered
> The only alternative is to use a different minimap mod, which saddens me because it means I will lose out on the chunk claiming capabilities of FTB chunks combined with FTB teams.

You can use any additional minimap mod with FTB teams/chunks. I normally use Journeymap. You'll still bbe able to claim chunks. You'll just have to use the Chunks claim map (keybind or the ingame map when you open your inventory and map icon in the top left corner).

**Comment by MichaelHillcox** [comment]
Please see the above response. This is something we're unlikely to backport as 1.16 is quite old now...

**Comment by desht** [comment]
Mikey is correct, we won't be backporting a minor feature like this to an ancient version like 1.16.5, sorry.
