### ISSUE TITLE
[Feature Request]: Default recipes for FTB Dripper, Jars and Sluice mods

### ISSUE THREAD

**Issue by NightOps007** [FTBTeam/FTB-Mods-Issues#143]
### Mod

FTB Dripper, Jars, Sluice

### Description

I loaded the mods into my game and wanted to use them after having tried them in FTB Oceanblock modpack. Unfortunately, I'm not really talented with the scripting stuff.

### Describe the solution you'd like

It would be nice if their were some default recipes included with the mods, especially for the vanilla stuff. Then perhaps make it configurable to turn the defaults off when you have kubejs doing the recipes instead.

### Describe alternatives you've considered

Publish public files or a repository of balanced recipe kubejs files already made for the mods. For each mod there could be recipe files for: vanilla, a mod integration, b mod integration, x mod integration...
This way the modpack creator can just find and dl the files specific for the mods they have installed if they want to more easily use the FTB mods that use kubejs for recipes.
This could easily be something community developed, but most people would probably prefer something trusted. For recipe balance and other reasons.

**Comment by Raidobw2** [comment]
Ok Dripper has some docs
https://www.notion.so/feedthebeast/FTB-Dripper-cf307f6547824732b760a631e3a54941

But LatvianModder if you want you can add some on Jar:
https://www.notion.so/feedthebeast/FTB-Jar-Mod-4ed1a0d0ed2d457ca00837e39a71877c
And if MichaelHillcox wants, he can add some on Sluice:
https://www.notion.so/feedthebeast/FTB-Sluice-e301312f0e8843e597c03d3210cb8a96
Of course, as time allows you to do that.

Scripts from OB would work I'm pretty sure, they were good enough.

**Comment by Raidobw2** [comment]
FTB Sluice has some documentation now, I'll try and add FTB Jar at some point in the near future
(these docs may migrate some day, if they aren't accessible, check the FTB Discord's support channels https://go.ftb.team/discord, in the channel topics are going to be links to mod docs)
https://feedthebeast.notion.site/FTB-Sluice-f2fe9a95c4be429abd19a8a008826f93

**Comment by MichaelHillcox** [comment]
Thank you for your issue, as this mod has no real use case outside of a custom modpack experience, I don't feel that default recipes would apply to this mod.
