### ISSUE TITLE
[Bug]: /TPO is accessible to non-ops

### ISSUE THREAD

**Issue by LevyWilson** [FTBTeam/FTB-Mods-Issues#1433]
### Mod

FTB Essentials

### Mod version

ftb-essentials-neoforge-2101.1.1

### NeoForge / Forge / Fabric version

21.1.90 and 21.1.83

### Modpack & version

FTB Evolution 1.6.0

### What issue are you having?

Non-op players have full access to /tpo, which is a shortcut command for /tp_offline. This can be used to grief players by teleporting them into walls or into other peoples' bases. Attempted to find someone on Discord to tell this to, was directed here. Sorry to make this public. Attempted to disable it with FTBRanks, but it doesn't work. What I tried:
 		command.tpo: false
		command.tpo.id: false
		command.tpo.name: false

Confirmed it works on non-opped players in both FTB Evolution 1.6.0 and ATM10 2.10. The only way to stop it is to disable tp_offline completely in the essentials config.

### Steps to reproduce

Be non-opped, type /tpo and see the autocomplete options. Attempting to use them shows success.

### Anything else to note?

Y'all really should have a channel for issues like this to keep them on the down low.

**Comment by desht** [comment]
> Y'all really should have a channel for issues like this to keep them on the down low.

You're right, and we are working on some better protocols to let people report sensitive issues privately rather than creating public issues.

For this issue, a new release will be out today.

**Comment by desht** [comment]
Fixed in 2101.1.2
