### ISSUE TITLE
[Bug]: FTB Teams - Joining/leaving party wipes players inventory on private server. 

### ISSUE THREAD

**Issue by Duke-Nukem-3D** [FTBTeam/FTB-Mods-Issues#146]
### Mod

FTB Teams

### Mod version

ftb-teams-forge-1605.2.3-build.38

### Forge / Fabric version

1.16.5-36.2.20

### Modpack & version

FTB Oceanblock 1.9.0

### What issue are you having?

Everytime I join or leave a friends party it clears everything from my inventory but left things I had in curio slots. I can't find away to restore the items without going back to a previous backup.

### Steps to reproduce

1. Accept invite to friends party
2. Leave friends party

### Anything else to note?

Running FTB Oceanblock 1.9.0 server pack on my own server

**Comment by MichaelHillcox** [comment]
This is an intended feature :D If you do not like it, please see the FTB Team Islands config file
