### ISSUE TITLE
[Bug]: Performant Incompatible with FTB Mods

### ISSUE THREAD

**Issue by Ashley123477** [FTBTeam/FTB-Mods-Issues#156]
### Mod

FTB Chunks

### Mod version

ftb-chunks-forge-1605.3.2-build.83

### Forge / Fabric version

1.16.5 - 36.2.22

### Modpack & version

Ragnamod VI Beta 6.0.27

### What issue are you having?

I added a few performance mods to my server, server side and now the client crashes everytime they use the keybind M to open the FTB Chunks map

Performance mod in question seems to be Performant

### Crashlogs

https://paste.feed-the-beast.com/view/46bd8f5c

### Steps to reproduce

Add FTB Chunks or FTB Quests and Performant then open the map or quest book

**Comment by Raidobw2** [comment]
Thanks for report. We have a report of this at #70 as well!

**Comment by Raidobw2** [comment]
I'll keep #70 as the only opened issue for our mod dev, so I will be closing this issue as duplicate now
