### ISSUE TITLE
[Bug]: locked dimension quest "bugged"

### ISSUE THREAD

**Issue by MundM2007** [FTBTeam/FTB-Mods-Issues#159]
### Mod

FTB Quests

### Mod version

 ftb-quests-forge-1605.3.6-build.76.jar

### Forge / Fabric version

1.16.5 36.2.22

### Modpack & version

only installed FTB Quests

### What issue are you having?

you have a visit Dimension Quest wich is locked behind another quest 
![2022-01-06_15 02 06](https://user-images.githubusercontent.com/85188362/148394844-398d78d9-5a4e-466a-b825-84d570422499.png)
if you now visit the said dimension without having unlocked the visit dimension quest, the quest says it is 0% complete
![2022-01-06_15 02 25](https://user-images.githubusercontent.com/85188362/148394727-23a4b4f6-a583-412c-9d71-9861a683b791.png)
Now you cannot complete the quest anymore if you try to do so the quest says 100% completed but doesn't unlock future quests
![2022-01-06_15 07 22](https://user-images.githubusercontent.com/85188362/148395199-0a555c08-f06f-4172-9427-3048672e442a.png)
What should be happening?
The quest shouldn't start and you should be able to complete it after you have unlocked the dependency quest:
![2022-01-06_15 09 12](https://user-images.githubusercontent.com/85188362/148395852-56e0213a-8816-4696-a1a9-ad5bf1a6bc5d.png)

### Steps to reproduce

1. Install FTB Quests and start the game
2. Create Quest Like in this Screenshot (Dimension: nether)
![2022-01-06_15 11 00](https://user-images.githubusercontent.com/85188362/148396039-2c1976f0-87f1-4677-8299-b780c6ef7682.png)
3. Enter the nether

**Comment by desht** [comment]
Fixed in latest 1.16.5 release
