### ISSUE TITLE
[Bug]: Server Crash: Entity being ticked

### ISSUE THREAD

**Issue by ClaudiusMinimus** [FTBTeam/FTB-Mods-Issues#161]
### Mod

FTB Chunks

### Mod version

ftb-chunks-forge-1801.3.3-build.108

### Forge / Fabric version

1.18.1 39.0.10

### Modpack & version

[Create on a Potato PC 2.5.1](https://www.curseforge.com/minecraft/modpacks/create-on-a-potato/files/3597968)

### What issue are you having?

A player was close to a creeper and it tried to blow up and the server crashed

### Crashlogs

https://crashy.net/orA4sejYGiqCefxXLs2K
Raw crash report
https://crashy.net/orA4sejYGiqCefxXLs2K?raw

### Steps to reproduce

1. Creeper walks up
2. Boom
3. Crash

**Comment by ClaudiusMinimus** [comment]
TNT will also crash
https://crashy.net/XkyyrUpZyUCOHxHiDibR

**Comment by lhaeussler** [comment]
Having the same issues here
[crash-2022-01-08_18.59.38-server.txt](https://github.com/FTBTeam/FTB-Mods-Issues/files/7833738/crash-2022-01-08_18.59.38-server.txt)
[latest.log](https://github.com/FTBTeam/FTB-Mods-Issues/files/7833740/latest.log)

**Comment by MaxNeedsSnacks** [comment]
Fixed and released in build 110

**Comment by ClaudiusMinimus** [comment]
Can confirm ftb-chunks-forge-1801.3.3-build.110 fixed the issue
