### ISSUE TITLE
[Feature Request]: Do better work on backup mod

### ISSUE THREAD

**Issue by theArhar** [FTBTeam/FTB-Mods-Issues#162]
### Mod

FTB backups 2.1.2.2

Modpack: TNP limitless 3 1.11.7

### Description

I cant find words to explain how I am annoyed by excruciatingly terrible coding of ftb-backups mod
In modpack that I am playing it has setting to backup every 120 minutes
It means every 120 minutes straight
Today I had mekanism reactor explosion and I lost like 8 hours of playing, because this terrible mod does not backup every 2 hours of actual play, only if you play 2 hours straight

### Describe the solution you'd like

What I need from it is to backup every 2 hours of gameplay - if I play 40 minutes today, 60 minutes tommorrow and after next 20 minutes it starts to work

**Comment by MichaelHillcox** [comment]
This mod is scheduled for a rewrite, we can look into your issue though for existing versions. Sorry for any inconvenience and I understand your annoyance. I would recommend updating your original message or add a comment explaining your issue clearly so I can assign a developer to this. 

Recommended details to add: 
- Modpack 
- Modpack version
- FTB backups version
- What the mods doing wrong
- What you'd expect it to do

We recognise there are issues with this mod that need sorting, hopefully you can outline what needs sorting specifically in existing versions.

**Comment by MichaelHillcox** [comment]
Closed as we're deprecating our current version of FTB Backups in preference for a new mod... More updates soon
