### ISSUE TITLE
[Bug]: No map displayed in FTB Chunks

### ISSUE THREAD

**Issue by BonaireDreams** [FTBTeam/FTB-Mods-Issues#163]
### Mod

FTB Chunks

### Mod version

ftb-chunks-forge-1801.3.3-build.110.jar

### Forge / Fabric version

1.18.1 39.08

### Modpack & version

Custom

### What issue are you having?

FTB map is black aside from the player icon and mob icons.
![screenshot 94](https://user-images.githubusercontent.com/5133282/148659870-a419a360-a5ee-4a17-9116-97bde19045d9.jpg)

Tried removing Journey map and Journey Map Integrations to see if they were impacting FTB Chunks. Same result. 

### Steps to reproduce

Launch game
open FTB chunks
Black map

**Comment by wolrah** [comment]
Same behavior with ftb-chunks-forge-1801.3.3-build.110.jar as delivered by All The Mods 7 0.2.21  All mob icons and player icons appear and move around as expected, but the map itself is just black.

**Comment by Peach774** [comment]
Also having this issue

**Comment by lhaeussler** [comment]
+1

**Comment by Araneide** [comment]
I'm also having this issue
