### ISSUE TITLE
[Bug]: Crash on Saveload

### ISSUE THREAD

**Issue by lhaeussler** [FTBTeam/FTB-Mods-Issues#164]
### Mod

FTB Quests

### Mod version

ftb-quests-forge-1801.3.7-build.87.jar

### Forge / Fabric version

1.18.1 - 39.0.10

### What issue are you having?

Crash while lodaing world. "Encountered an unexpected exception
net.minecraft.ReportedException: Ticking player"

### Crashlogs

[crash-2022-01-09_11.26.39-server.txt](https://github.com/FTBTeam/FTB-Mods-Issues/files/7835537/crash-2022-01-09_11.26.39-server.txt)

### Steps to reproduce

1. Start Minecraft
2. Load Savegame
3. Crash

**Comment by desht** [comment]
Duplicated by #468 and will be fixed in the next release.
