### ISSUE TITLE
[Bug]: FTB Chunks Crashed during loading

### ISSUE THREAD

**Issue by littlepianist** [FTBTeam/FTB-Mods-Issues#166]
### Mod

FTB Chunks

### Mod version

ftb-chunks-forge-1605.3.2-build.95

### Forge / Fabric version

1.16.5-36.2.23

### What issue are you having?

![1641953614583](https://user-images.githubusercontent.com/75674050/149051703-7695e829-b426-40b4-a5f0-53fe4170fa66.jpg)

### Crashlogs

https://pastebin.com/dH3zarEd

### Steps to reproduce

1.download ftb chunks
2.launcher forge1.16.5 with other mods
3.crash

**Comment by Raidobw2** [comment]
Try adding FTB Ranks, you seem to be missing it and it's listed in the dependencies https://www.curseforge.com/minecraft/mc-mods/ftb-chunks-forge/relations/dependencies

**Comment by Raidobw2** [comment]
Should have been resolved by my last comment mentioning you need all dependencies, if not, feel free to reopen
