### ISSUE TITLE
[Bug]: NEI missing.

### ISSUE THREAD

**Issue by Kwick9** [FTBTeam/FTB-Mods-Issues#167]
### Mod

Mindcrack

### Mod version

1.4.7

### Forge / Fabric version

Forge 1.4.7

### Modpack & version

Mindcrack 8.3.2

### What issue are you having?

FTB Mindcrack refuses to run NEI. I am using the FTB app, Windows OS. Ctrl-O does nothing. NEI.jar exists in the coremods folder along with codechickencore.jar, but i get no functionality when playing. I don't see much discussion on this.

### Steps to reproduce

All mods are at the default version from a fresh install of mindcrack through the ftb app.

**Comment by Raidobw2** [comment]
Hi, add this in the "coremods" folder of your game: https://www.curseforge.com/minecraft/mc-mods/vanilla-nei-fix
For future support, please use the FTB Discord
![image](https://user-images.githubusercontent.com/17010632/150622703-44e271f1-54f0-419a-b2be-2d13af34a453.png)
![image](https://user-images.githubusercontent.com/17010632/150622713-07d24f26-4ba1-4d00-9fb9-242410651bec.png)
![image](https://user-images.githubusercontent.com/17010632/150622717-b91be077-262b-407e-881d-f3506f5f7801.png)
![image](https://user-images.githubusercontent.com/17010632/150622720-d573b819-8488-4a71-a121-6bbac58fa5ad.png)
