### ISSUE TITLE
[Bug]: Can't set any ranks or use commands

### ISSUE THREAD

**Issue by storiofmylife** [FTBTeam/FTB-Mods-Issues#168]
### Mod

FTB Ranks

### Mod version

ftb-ranks-forge-1801.1.6-build.22

### Forge / Fabric version

1.18.1 Forge 39.0.10

### What issue are you having?

I can't seem to get ranks to work at all.  When I try to list ranks via /ftbranks in game, I get error:  

![2022-01-12_14 20 44](https://user-images.githubusercontent.com/79773725/149232230-d9121dcd-4789-4051-b4e3-fe99a5ab06a8.png)
![2022-01-12_14 20 39](https://user-images.githubusercontent.com/79773725/149232276-1ef4e6b5-9116-4069-985b-fd567ec0ee4a.png)

I've also included my ranks.snbt to see if its my human error in formatting.

### Steps to reproduce

```
{
	member: {
		name: "Newcomer"
		power: 1
		condition: "always_active"
		ftbranks.name_format: "<&7{name}&r>"
	}

	bearded sub: {
		name: "Bearded"
		power: 50
		ftbranks.name_format: "<&6{name}&r>"
	}
	mod: {
		name: "Mod"
		power: 1000
		condition: "op"
		ftbranks.name_format: "<&5{name}&r>"
	}
	admin: {
		name: "Admin"
		power: 2000
		condition: "op"
		ftbranks.name_format: "<&4{name}&r>"
	}
	
	citizen: {
		name: "Citizen"
		power: 5
		ftbranks.name_format: "<&b&l[Citizen] {name}&r>",
		condition: {
		type: "playtime"
		time: 2
		time_unit: "weeks"
	}

	}
	trusted: {
		name: "Trusted"
		power: 10
		ftbranks.name_format: "<&9&l[Trusted] {name}&r>",
		condition:
		{
		type: "playtime"
		time: 8
		time_unit: "weeks"
	}
	}
	seasoned: {
		name: "Seasoned"
		power: 15
		ftbranks.name_format: "<&a&l[Seasoned] {name}&r>",
		condition:
		{
		type: "playtime"
		time: 16
		time_unit: "weeks"
	}
	}
	hero: {
		name: "Hero"
		power: 20
		ftbranks.name_format: "<&3&l[Hero] {name}&r>",
		condition:
		{
		type: "playtime"
		time: 36
		time_unit: "weeks"
	}
	}
	
}
```

**Comment by Raidobw2** [comment]
Hello, you have a space between "bearded" and "sub". Have it like that instead and it should be functional:
```
bearded_sub: {
	name: "Bearded"
	power: 50
	ftbranks.name_format: "<&6{name}&r>"
}
```
![image](https://user-images.githubusercontent.com/17010632/156764061-17f74f7a-75c9-46dc-9338-7fbc0813165e.png)

And the docs, which should give you more info as well for the future: https://feedthebeast.notion.site/FTB-Ranks-d56ec50cfa04412485ff0bf63d103b4d
Cheers, and feel free to come by the FTB Discord for ftb mod support!
