### ISSUE TITLE
[Feature Request]: Please add REI Support to FTB Quests

### ISSUE THREAD

**Issue by KaneHart** [FTBTeam/FTB-Mods-Issues#170]
### Mod

FTB Quests

### Description

Please add REI (RoughlyEnoughItems) Support for Fabric.
Please allow clicking quest items to show recipe and using the keys like R,U, and B as well for bookmarking said items directly from FTB Quests.

### Describe alternatives you've considered

I rather use FTB Quests then an alternative Quest Mod :)

**Comment by recon88** [comment]
That feature is already in and works fine for me. Check the latest (alpha/beta) version.

**Comment by MichaelHillcox** [comment]
This should just work, please comment to state otherwise
