### ISSUE TITLE
[Bug]: failed to load correctly

### ISSUE THREAD

**Issue by OcrSu** [FTBTeam/FTB-Mods-Issues#171]
### Mod

FTB Chunks

### Mod version

ftb-chunks-forge-1605.3.2-build.115

### Forge / Fabric version

1.16.5 36.2.23

### What issue are you having?

Client Crash When launch the game

### Crashlogs

https://paste.loliidc.cn/?164ca1359f108339#J6oEzfoqMU2PVxZ7XH6QvwKADFpn7wZXBQMNfe3gt9dJ

### Steps to reproduce

launch the game...............and it was crash

**Comment by Raidobw2** [comment]
I've put the error on https://paste.feed-the-beast.com/view/5442b037 since your paste expires in 10 months.
There's another mod in the stacktrace which is https://www.curseforge.com/minecraft/mc-mods/animated-splash-screen-logo/

**Comment by OcrSu** [comment]
> 我已经把错误放在 https://paste.feed-the-beast.com/view/5442b037，因为你的粘贴在10个月后过期。堆栈跟踪中还有另一个mod[，https://www.curseforge.com/minecraft/mc-mods/animated-splash-screen-logo/](https://www.curseforge.com/minecraft/mc-mods/animated-splash-screen-logo/)

I have deleted the mod[animated-splash-screen-logo], but the problem still exists

**Comment by MichaelHillcox** [comment]
Not sure why we're being blamed but it looks like some kinda mixin issue with merchantmarkers.mixins.json

**Comment by OcrSu** [comment]
> 

Thank you, I understand now, I'm very sorry to have opened so long in your issue

**Comment by Raidobw2** [comment]
See #209 in that case
