### ISSUE TITLE
[Feature Request]: Square Mini Map!

### ISSUE THREAD

**Issue by KaneHart** [FTBTeam/FTB-Mods-Issues#173]
### Mod

FTB Chunks

### Description

I would Love to see a more Minecraft Friendly Style Mini Map being a Square instead of a circle. For me I guess it feels like it fits the theme more and I enjoy the looks quite a bit.

### Describe the solution you'd like

I would like a ▢ Mini Map Option.

### Describe alternatives you've considered

I have looked at other Mini-Maps, but I rather keep the ecosystem going if there was a few options to satisfy my appetite :)

**Comment by desht** [comment]
This will be in the next FTB Chunks release (although square minimap will be rotation-locked, i.e. no rotating square map textures)
