### ISSUE TITLE
[Feature Request]: Quest & Chapter Copy

### ISSUE THREAD

**Issue by LegendaryTot** [FTBTeam/FTB-Mods-Issues#176]
### Mod

FTB Quests

### Description

I find myself setting up similar quests and chapters that share some common characteristics. For example, I'm adding the same images to section off quests in a chapter into groups.

Example: 
![image](https://user-images.githubusercontent.com/96359623/149832880-14f8a261-55bf-41e1-a155-92fac2475f48.png)

It's pretty painful doing this for every chapter, and having to go through and add each image element independently and setting up the same attributes.

### Describe the solution you'd like

If I could create a "template" chapter, and just make copies of it that would solve most of my pain. However, also being able to right-click and copy / paste quests + images would also be pretty neat. I set up a lot of quests for immersive engineering for the multi-blocks that all needed similar attributes (observe task, icon, etc.) If I could just copy each quest then I'd just have to modify what's different (instead of starting from scratch each time).

### Describe alternatives you've considered

I guess modifying the txt files are an option, but not quite as intuitive and easy to muck-up. It'd be better done via the GUI imo.

**Comment by Raidobw2** [comment]
Thanks for the suggestion

**Comment by Raidobw2** [comment]
## Description
Creating quests can be repetitive and infuriating when doing a mass amount, an example of this being having an "ingots" category. If a modpack had 100 ingots, you'd have to right click, type ingot, select the ingot you want, press accept, then repeat another 99 times. This takes time, and could be simplified easily with the following solution

## Solution
Having the ability to create multiple quests at a time would increase modpack production time tenfold. With a selection system like windows and many other places, using CTRL or SHIFT to:

CTRL: Holding this would allow you to select multiple specific desired quest items.

SHIFT: Clicking an item, then holding shift and clicking elsewhere should select multiple quest items.

If you don't understand this, open file explorer on windows and try this out for yourself.

Upon pressing the "Accept" button, it should create multiple quests within the original right clicked position. Grouping them in a grid would also help as you would be able to select and move any created quest to a desired area.

**Comment by desht** [comment]
Quest copying (and linking) will be in the next 1.18 & 1.19 releases.  The mechanism won't be as stated above though. 

Using the already existing "Copy Link ID" context menu item; subsequent right clicks on the background to create a quest will also offer new "Paste Quest", "Paste Quest (no dependencies)" and "Paste Quest Link" options if the clipboard contains the ID of a valid quest.  Pasting won't clear the clipboard contents, so can be repeated multiple times.

**Comment by itsdinkd** [comment]
Can you add this functionality to tasks?

**Comment by desht** [comment]
I'll look into the feasibility of doing this for tasks too.  Would be nice to have, I agree.

**Comment by desht** [comment]
Added in latest FTB Quests releases
