### ISSUE TITLE
[Bug]: FTB Quests crashing when I press the 'e' key.

### ISSUE THREAD

**Issue by GW-Dev** [FTBTeam/FTB-Mods-Issues#177]
### Mod

FTB Quests

### Mod version

ftb-quests-forge-1801.3.7-build.91.jar

### Forge / Fabric version

1.18.1 39.059

### Modpack & version

Custom Modpack

### What issue are you having?

FTB Quests crashes every time I press the 'e' key in the quest window

### Crashlogs

Log: https://pastebin.com/z8ecMYTg

### Steps to reproduce

Open FTB Quests window in either edit mode or not
Press the 'e' key

**Comment by Raidobw2** [comment]
Have you reported the issue to JEI as well? Looks like they have a reflection call and the field is null. I don't think this is due to architectury from the log

**Comment by Raidobw2** [comment]
I'm unable to replicate with FTB Quests on 1.18.2. This may have been caused by JEI or another mod that behaves weirdly when pressing 'E'. Currently in 1.18.2, pressing 'E' simply closes the questing book window.
