### ISSUE TITLE
[Bug]:  

### ISSUE THREAD

**Issue by K-The-Grey** [FTBTeam/FTB-Mods-Issues#179]
### Mod

FTB Power Pots

### Mod version

ftb-power-pots-forge-1605.1.2-build.16

### Forge / Fabric version

1605.1.2 I think, whatever is standard OceanBlock

### Modpack & version

FTB OceanBlock 1.11.0

### What issue are you having?

I am playing the standard downloaded OceanBlock, using the FTB launcher through Overwolf.  I have made no modifications to the generic install.  

There is no recipe for FTB-Power-Pots in the JEI. 

### Steps to reproduce

Launch OceanBlock, open the JEI type in power pot rightclick for recipe, no recipe available

**Comment by Raidobw2** [comment]
Hi, normally these are the recipes on a fresh install:
![image](https://user-images.githubusercontent.com/17010632/151683624-6fab2a41-4261-48cd-9eb6-2531a101cd37.png)
If you do not see those recipes, you might want to cleanly reinstall the modpack.
First, you will need to clear the download cache. You can open your instances folder located at `%localappdata%\.ftba\instances` and delete the `.localCache` folder.
Second, you can then backup your worlds if you have any:
![image](https://user-images.githubusercontent.com/17010632/151683888-e247c9ae-9dac-42ee-bf93-b07c0c3ab1cb.png)
![image](https://user-images.githubusercontent.com/17010632/151683896-cd087fdf-8324-48a6-aa56-e308b6d29189.png)
Inside the saves folder, you will find all your worlds. Copy them to a safe location.
![image](https://user-images.githubusercontent.com/17010632/151683908-998f887c-464b-4868-b73b-3f61426072af.png)
Third, you can then uninstall the modpack and the files will be downloaded again.

Once you load in the newly installed modpack, check if you see the recipes and if you do please close this issue.
For future modpack issues, please use https://github.com/FTBTeam/FTB-Modpack-Issues/issues.
Feel free to let me know if the issue persists.

**Comment by K-The-Grey** [comment]
Thanks for the reply. Turns out it doesn’t show the recipe by default you just have to click on the draconian infusion link at the top. It’s not normal but I should have been able to figure it out.  Sorry no bug

**Comment by Raidobw2** [comment]
Awesome, glad it was just that. Enjoy the modpack!
