### ISSUE TITLE
[Feature Request]: Minimap Mob Custom Icons

### ISSUE THREAD

**Issue by Deliphin** [FTBTeam/FTB-Mods-Issues#180]
### Mod

FTB Chunks

### Description

When using FTB Chunks' minimap and mods that add new mobs, many mobs do not have icons on the minimap, only generic white and red pips.
There appears to be no configuration option for this in the `world/serverconfig/ftbchunks.snbt` and what little documentation there is, is empty of anything relevant to this issue.

### Describe the solution you'd like

A simple configuration option to specify texture files per mobs, allowing us to make custom mob icons, as well as replace poor ones (such as the Ice & Fire dragon icons that are tiny and like to blend in with grass).

### Describe alternatives you've considered

Generate icons based on the face textures of the mob. This could easily be unreliable though, if a mob doesn't have a part labelled as its head or if the texture side or rotation is unexpected. It would also be problematic if its face is too simple to recognize on a minimap. Perhaps this could be done, with my main suggested solution as an available fix players can use in case if it does a poor job.

**Comment by sirR0bson** [comment]
Hello. I tried to search the help but I didn't find a satisfactory answer, namely - I wouldn't like to use the heads on the minimap, but some of the mobs added by custom mods would like them to be marked on the minimap as red dots and white ones - how to change it?
Will a tag be enough?
I will add that mobs that were passive were given predatory features through a separate script to attack the player.
How to change their display into red dots on the minimap
Regards

**Comment by MichaelHillcox** [comment]
You can actually do this via a datapack or an addon mod:

https://github.com/FTBTeam/FTB-Chunks/blob/main/common/src/main/java/dev/ftb/mods/ftbchunks/client/mapicon/EntityIcons.java#L49

We already support quite a few mods but there is only so far we can go with first party support.
https://github.com/FTBTeam/FTB-Chunks/tree/main/common/src/main/resources/assets/ftbchunks/textures/faces

**Comment by MichaelHillcox** [comment]
In the future, this system may move over to a tag based system
