### ISSUE TITLE
[Bug]: NPE at dev.ftb.mods.ftbschools.FTBSchoolsEventHandler.serverStopped

### ISSUE THREAD

**Issue by fforfeeee** [FTBTeam/FTB-Mods-Issues#183]
### Mod

FTB Schools

### Mod version

1.4.0

### Forge / Fabric version

FTB App at the latest version

### Modpack & version

FTB University

### What issue are you having?

The game hangs infinitely when I try to load this world

### Crashlogs

[latest.log FTB UNIVERSITY.txt](https://github.com/FTBTeam/FTB-Mods-Issues/files/7965863/latest.log.FTB.UNIVERSITY.txt)

### Steps to reproduce

I load up the world and get this issue.

**Comment by MichaelHillcox** [comment]
Delete this file `curios-server.toml` and restart your server / client

**Comment by MichaelHillcox** [comment]
No response
