### ISSUE TITLE
[Feature Request]: Add the function of using network texture（URL）

### ISSUE THREAD

**Issue by luoxiawuchen** [FTBTeam/FTB-Mods-Issues#188]
### Mod

FTB Quest

### Description

It is recommended to add the function of using network texture, not just local resource packages (like ftbquest1.12.2, you can use URL to add pictures)

-------------------------------------------------------------------------------------------------------
I'm sorry that my English is not very good
Thank you for your patience in reading
Thank the author and the development team for making and sharing this excellent quest mod

**Comment by MichaelHillcox** [comment]
I like the idea but at the exact same time, I'd much prefer you put images inside the datapack for the pack so we don't have to download images every time we want to show you quests. 

There is also a big old question about security and tracking which I won't go into but for now, this is gunna be a no from me. Sorry about that.

**Comment by luoxiawuchen** [comment]
> I like the idea but at the exact same time, I'd much prefer you put images inside the datapack for the pack so we don't have to download images every time we want to show you quests.
> 
> There is also a big old question about security and tracking which I won't go into but for now, this is gunna be a no from me. Sorry about that.

OK, thanks for your patient reply.
