### ISSUE TITLE
[Suggestion] Dependencies for Categories

### ISSUE THREAD

**Issue by MaxNeedsSnacks** [FTBTeam/FTB-Mods-Issues#19]
It'd be nice if you could hide entire "categories" / shops behind dependencies in addition to being able to hide individual items, e.g. if I had an entire shop dedicated to some mid- to late-game resources and I wanted to lock all of those behind one quest, it'd be much easier to add a dependency for the entire shop rather than for each individual item.

It might also be a good idea to hide "empty" shops such that they're invisible until you've unlocked at least one item inside the shop, I feel like that could be an option ^^

**Comment by Raidobw2** [comment]
> So you can disable/enable shop items for players with quest rewards
