### ISSUE TITLE
[Feature Request]: Multiple reward on loot crate

### ISSUE THREAD

**Issue by Sound-Pirate** [FTBTeam/FTB-Mods-Issues#192]
### Mod

FTB Quest

### Description

Add multiple reward with one loot crate

Exemple: 1 Apple 100%
                1 Stick 100%
                1 Bow 100%
              
The actual system is: Apple 33%, stick 33% and bow 33%

**Comment by Raidobw2** [comment]
I'll keep only #32 for our mod dev to track this issue, since they are the same
