### ISSUE TITLE
[Bug]: Game crashed when i open FTB shops on the server.

### ISSUE THREAD

**Issue by Lemonmito** [FTBTeam/FTB-Mods-Issues#195]
### Mod

FTB shops

### Mod version

ftb-money-1605.1.3-build.6

### Forge / Fabric version

1.16.5-Forge_36.2.28

### What issue are you having?

Game crashed.

### Crashlogs

https://mclo.gs/rTZLXhc

### Steps to reproduce

In the server, when I was on the FTB quests interface, the game crashed when I moved the mouse to the FTB shops. Even if I pressed the key to open the FTB shops, the game still crashed. The following is the crash report.

**Comment by Gunner76th** [comment]
I am not sure what launcher you are using, but I did notice you are using Java 11. Modded Minecraft 1.16.5 needs Java 8, so that could be a cause of your issue. I am unable to recreate the crash through AT Launcher using Java 8.

**Comment by gustavros** [comment]
> ### Mod
> FTB shops
> 
> ### Mod version
> ftb-money-1605.1.3-build.6
> 
> ### Forge / Fabric version
> 1.16.5-Forge_36.2.28
> 
> ### Modpack & version
> _No response_
> 
> ### What issue are you having?
> Game crashed.
> 
> ### Crashlogs
> https://mclo.gs/rTZLXhc
> 
> ### Steps to reproduce
> In the server, when I was on the FTB quests interface, the game crashed when I moved the mouse to the FTB shops. Even if I pressed the key to open the FTB shops, the game still crashed. The following is the crash report.
> 
> ### Anything else to note?
> _No response_

Do you have any news about your crash?

**Comment by gustavros** [comment]
I'm using Java 1.0.6 and is happen here too

**Comment by Gunner76th** [comment]
Your game is crashing because you're server is on offline mode,  and
possibly because you're using a cracked launcher.  This is intentional
behavior when a server is in offline mode.

**Comment by Gunner76th** [comment]
This has nothing to do with what version of Java you are using.

**Comment by gustavros** [comment]
My minecraft is not cracked. I'm using Curse Forge to play with my friends in a server with mode offline. It's possible to be this?

**Comment by Gunner76th** [comment]
Yes it's crashing because the server you're on is in offline mode.

**Comment by gustavros** [comment]
I'm looking in the internet about this problem and I found a guy saying that I need to install the "server pack" in my server folders. Can you talk more about that?

**Comment by Gunner76th** [comment]
That won't fix the crash issue that you're having.  You need to edit the
server.properties file and change online=false to be online=true.  Until
this is done your game will crash any time you try to open the shop in the
quest book.

**Comment by gustavros** [comment]
Yeah. That's it. Its working now with online mode. It's possible to work on offline mode?

**Comment by Gunner76th** [comment]
No, the shop requires the UUID of the player which is only obtained when
the server is on online mode.  Without the UUID the code crashes.
