### ISSUE TITLE
[Bug]: FTB chunk crash when placing anvil using AE2 formation plane

### ISSUE THREAD

**Issue by Eidigii** [FTBTeam/FTB-Mods-Issues#196]
### Mod

FTB Chunks

### Mod version

ftb-chunks-fabric-1801.3.3-build.119

### Forge / Fabric version

Fabric API 0.46.1+1.18

### Modpack & version

Benchmark II - 0.6.12

### What issue are you having?

Placing anvil in a chunk claimed area using AE2 formation plane crashes the server.

### Crashlogs

https://paste.feed-the-beast.com/view/ec1da68d

### Steps to reproduce

Claim chunk, try to place anvil using AE2 formation plane.

**Comment by desht** [comment]
Fixed in 1.16/1.18/1.19
