### ISSUE TITLE
[Bug]: Forced chunk loading not working

### ISSUE THREAD

**Issue by Rolo318** [FTBTeam/FTB-Mods-Issues#199]
### Mod

Ftb chunks

### Mod version

Ftb-chunks-forge-1801.3.4

### Forge / Fabric version

Forge 39.0.79

### Modpack & version

All the mods 7 version .42

### What issue are you having?

Seems the forced chunk loading isn't working. The ATM discord team ran extensive tests to see if there was a mod conflict and even with just the FTB mods the chunks would not remain loaded.  

### Steps to reproduce

Try and force anything to load like a tree or bee farm in the nether and it will unload even when claimed and force loaded

**Comment by djoveryde** [comment]
Can confirm chunks refuse to remain force loaded. Also using All the Mods 7. 
I've set the area surrounding my ME storage and power to remain chunk loaded, head to nether/end/moon etc. It remains accessible from a wireless crafting terminal for a moment and then after about a minute I loose connection to my ME until I return back home. Same issue with ender bags etc, so seems that the chunk loader is ignoring requested chunks to remain loaded.

**Comment by Raidobw2** [comment]
I'll be closing this as duplicate since #200 has more info and is more recent with a linked issue as well. If you want future feedback on that case, make sure to subscribe to the other issue 200 to get notifications when that will be looked at. Thanks for the report
