### ISSUE TITLE
[bug] FTB Drippers show fluid as "water" (blue quantity bar) as well as blue water drop, when filled with Lava.

### ISSUE THREAD

**Issue by 2ndRecon** [FTBTeam/FTB-Mods-Issues#2]
To help us help you, please provide as much information as you can, this helps us with debugging and reproducting the issue.

FTB OceanBlock 1.1.2

36.2.2 (i believe)

No crash, but recipe is supposed to convert Cobble ---> Magma Block but never seems to complete the process 
(maybe because it's dripping water instead of Lava ?)

Place a Wooden Dripper
Get a Lava source bucket
Right Click on the Dripper with the Lava bucket.
Place a cobble under the Lava Dripper.
Observe

![Dripper-Issues](https://user-images.githubusercontent.com/39180607/134718167-4681ce2f-e044-45b0-871e-515ce274e112.PNG)

Really enjoy this dripper !

**Comment by LatvianModder** [comment]
It's not exactly a bug, this is how I wrote it intentionally. The dripper doesn't send fluid to clients to save some precious bytes of data, so the client doesnt know what the stored fluid is, thus wouldn't know fluid color. So im just spawning water particles in all cases. I might fix this sometime later :p

**Comment by 2ndRecon** [comment]
Makes sense ! Great thinking :)  I appreciate you explaining this. Cheers.

**Comment by LatvianModder** [comment]
Fixed
