### ISSUE TITLE
[Bug]: Chunk forceloading is not working properly

### ISSUE THREAD

**Issue by official-Cromatin** [FTBTeam/FTB-Mods-Issues#200]
### Mod

FTB Chunks

### Mod version

ftb-chunks-forge-1801.3.4-build.127

### Forge / Fabric version

forge-1.18.1-39.0.85

### Modpack & version

No modpack but self choosen mods 
* Spark 
* Jei 
* FTB Teams 
* FTB Qests 
* *FTB Chunks* 
* Create 
* Create Addition

### What issue are you having?

When I claim a chunk and load that and then leave server or region so the chunks are unloaded.
All machines and redstone circuits are pausing, But Plants are Still Growing

### Crashlogs

No entry

### Steps to reproduce

Claim and load any chunk, build a redstone circuit there that executes a command that postes "Hi" in the chat and fly away.
If you are far enough away, no more messages will be posted in the chat

### Anything else to note?

No

**Comment by offical-Cromatin** [comment]
I think it is also important to add this even if I leave chunks in the menu Claime and then with displays how many chunks are loaded there is 0

Although the info says that the chunk is loaded

![grafik](https://user-images.githubusercontent.com/92319467/156256980-6842fe7a-c247-462d-a9f8-ea7d056346cf.png)
![grafik](https://user-images.githubusercontent.com/92319467/156257013-0679df37-0e78-4fc9-bb84-caf810bc29d4.png)

**Comment by offical-Cromatin** [comment]
One thing I should add though is that crops like sugar cane or wheat continue to grow, even though the chunk is not loaded and there is no player on the server.

Machines (for me it was a multiblock structure from Create, to which harvesters were attached, which macerated the plants) that macerate fully grown plants are pausing the Movement, just like the redstone circuits mentioned above

**Comment by Cntrldfusion** [comment]
It seems that the Minecraft "forceload" command works just fine though.  I'm not sure how FTBChunks does its force loading on chunks, but I tested the Minecraft "forceload" command on my server and it worked even though the FTBChunks did not.

To test it I had a furnace set up in a chunk that would allow multiple stacks of something to be smelted.  Sand for instance to be smelted into glass.  I used the "forceload" command to make the chunk loaded all the time.  Started the smelting process and logged out.  Waited about 15mins then logged back in.  All stacks had smelted while I was logged off.

I'm not sure how FTBChunks does its force loading of chunks.  But it seems almost like what its doing right now is filling out the data of claimed and loaded chunks, but not actually executing the forced loading of the chunks.  Just a guess on my part.

**Comment by JKIceman** [comment]
Any update on this issue? For 1.18.1 you could downgrade to 1801.3.3-build.113 but on 1.18.2 there is no working version. I would realy like to start using it as chunkloader mod again, but atm it is realy unusable as that.

**Comment by MichaelHillcox** [comment]
I did look into this and it seemed to work, I'll look into it again today

**Comment by Flatts3000** [comment]
Having the same issue on All the Mods 7. Additional info: the Chunk Loader from More Minecarts also doesn't work in my world, so maybe its something that effects modded Minecraft in general.

**Comment by LegitSoulja** [comment]
This really needs to get fixed.. Ugh

**Comment by MichaelHillcox** [comment]
Just released a fix for this issue :+1:

**Comment by InternetUnexplorer** [comment]
Thanks for the fix! Unfortunately it doesn't seem to work for me though :(

Here is what I am doing to test:
- Starting a new ATM7 server on localhost (using [SIMPLE-SERVER-FILES-0.3.16](https://www.curseforge.com/minecraft/mc-mods/ftb-chunks-forge/download/3773065))
- Replacing `ftb-chunks-forge-1802.3.5-build.130.jar` with `ftb-chunks-forge-1802.3.5-build.132.jar` in the server mods folder and restarting the server
- Joining, claiming a chunk away from spawn, and marking it as force-loaded
- Placing down an advanced computer (from CC:Tweaked) and running the `hello` program
- Leaving the server and rejoining

When I rejoin the computer has restarted and the output has been cleared, so the chunk seems to have been unloaded. I did this twice start to finish just to make sure.

**Comment by MichaelHillcox** [comment]
I was testing with furnaces... I setup a few hoppers for input, fuel and output, then claimed the chunks, force loaded them and disconnected. I noted down the output count before and came back about 5 minutes later. I came back to about a stack of iron or what ever so it appears to be working my end. Can you see if you get the same issue without CC?

**Comment by InternetUnexplorer** [comment]
I had a bit more time today and tried again with just FTB Chunks and its dependencies this time, and chunk loading definitely seems to be working. So it's probably some conflict with one of the other mods in ATM7 (which isn't surprising, it's a big pack). But until I have time to figure out what's going on with that I think it's safe to say that this issue is solved :) Thanks a bunch!

**Comment by MichaelHillcox** [comment]
If you can find out what the conflict is, I'd be happy to resolve it if I can
