### ISSUE TITLE
[Feature Request]: Show Claimed Chunks on Xaero's Map and Mini Map

### ISSUE THREAD

**Issue by offical-Cromatin** [FTBTeam/FTB-Mods-Issues#201]
### Mod

FTB Chunks

### Description

The Journeys Map has the ability to show which chunks were claimed by which player.
Unfortunately, this function cannot be found in the Xaero's Map Mod.

### Describe the solution you'd like

It should be possible to specify in the mod settings whether the chunks claimed by a player are displayed in the large fullscreen map as well as in the minimap.

Also when you are hovering over a claimed chunk the Information who claimed the Chunk gets displayed as a tooltip

**Comment by MichaelHillcox** [comment]
Due to the closed source nature of this mod, I don't think we can justify the time investimate to add a feature to a map mod that isn't our own... I'd be opne to considering PRs
