### ISSUE TITLE
[Feature Request]: Please add waystones integration

### ISSUE THREAD

**Issue by KMFrench1** [FTBTeam/FTB-Mods-Issues#204]
### Mod

FTB Chunks fabric

### Description

Can you please add waystone integration, So waystone show up on the map they show up on the map.
This was a feature on the forge version,
See picture
https://i.imgur.com/Tm6JZ3O.png

### Describe the solution you'd like

Would like waystones to show up on map

**Comment by Raidobw2** [comment]
Hello, can you link the waystone mod you're referring to as well (CurseForge page)? This will help with integrating it. Thanks!

**Comment by KMFrench1** [comment]
https://www.curseforge.com/minecraft/mc-mods/waystones-fabric

**Comment by Raidobw2** [comment]
Awesome, thank you!

**Comment by MichaelHillcox** [comment]
This is done :+1:

**Comment by 4rz0** [comment]
Is there plans to bring this to the Neoforge variant as well?

**Comment by MichaelHillcox** [comment]
I think it's on both
