### ISSUE TITLE
[Bug]: Serious Memory leak issue

### ISSUE THREAD

**Issue by NeptuneOkayasu** [FTBTeam/FTB-Mods-Issues#206]
### Mod

FTB Chunks

### Mod version

ftb-chunks-forge-1905.3.5.2-build.115

### Forge / Fabric version

36.2.20

### Modpack & version

Create Above and Beyond 1.3

### What issue are you having?

There is a serious memory leak issue with the mod, I don't know what is causing it but I know that when I remove it from the modpack the game stops lagging

### Steps to reproduce

Have a large amount of claims by other players on a server.

**Comment by NeptuneOkayasu** [comment]
Will update with a heap dump once I get around to it tonight

**Comment by Raidobw2** [comment]
Were you able to obtain more information on this leak?

**Comment by NeptuneOkayasu** [comment]
I haven't got around to doing the heap dump yet, 

But I know my friend who has 32GB ram can run it just fine, he allocates about 20 GB to minecraft

I only allocate 8GB due to having 12GB of ram

**Comment by Raidobw2** [comment]
You could then add your game logs when FTB Chunks is installed and we'll have some info to look at

**Comment by MichaelHillcox** [comment]
My assumption here is that you've mistaken a memory leak for people forcing your server to do a large amount of work every tick which inturn causes a lot of memory usage. If you're got a lot, like, more than a few hundred, chunks being chunkloaded then you'll very likely see a performance hit. That combined with the natrually high ram requirements of modded minecraft will cause you to very quickly hit that cap. Chunkloaded chunks should be used with moderation. We ran our test servers for Oceanblock on 8GB and we definitely ran the server redlined for the entire testing period. 

If there is a legitimate memory leak then please post a spark log for us. Remember that a memory leak is where a single task uses some ram but doesn't give it back. This in turn causes a gradual increase of ram until there is no ram left to use. Java does this cleanup task naturally so memory leaks are pretty rare (definitely possible!). I'm not disputing your claim, I don't know your technical background so I'm giving you as much info as I can to help you debug this issue.
