### ISSUE TITLE
[Bug]: CurseForge wrong version

### ISSUE THREAD

**Issue by viminio** [FTBTeam/FTB-Mods-Issues#207]
### Mod

FTB Ultimine

### Mod version

ftb-ultimine-forge-1801.3.2-build.50

### Forge / Fabric version

36.2.23 - 36.2.29

### What issue are you having?

The ftb-ultimine-forge-1801.3.2-build.50.jar file
Which is clearly from 1.18.1 was posted as 1.16.5

Link: https://www.curseforge.com/minecraft/mc-mods/ftb-ultimine-forge/files/3667327

![image](https://user-images.githubusercontent.com/62722905/156126105-0e6f2ecb-648c-4172-9b8e-1cdd14358cfc.png)

### Steps to reproduce

Download mod
Open in the same version described in curseforge
![image](https://user-images.githubusercontent.com/62722905/156126078-5b715888-67db-4163-a439-65d4357f5d2e.png)

**Comment by joaoespanhol** [comment]
i no have this problem

**Comment by viminio** [comment]
was solved

**Comment by joaoespanhol** [comment]
> was solved

good job
