### ISSUE TITLE
[Bug]: Crash

### ISSUE THREAD

**Issue by viminio** [FTBTeam/FTB-Mods-Issues#210]
### Mod

FTB Teams

### Mod version

ftb-teams-forge-1605.2.3-build.40.jar

### Forge / Fabric version

1.16.5 - 36.2.29

### What issue are you having?

Game Crash

### Crashlogs

https://www.toptal.com/developers/hastebin/fajizahino.rb

### Steps to reproduce

IDK

**Comment by Raidobw2** [comment]
Hi, did a reinstall of the mod and dependencies or the modpack fix it?

**Comment by hehziYT** [comment]
prubuje zainstalować po raz 3 mod paka ale nie moge zatrzymuje sie na "get Forge information" i nic dalej

**Comment by Raidobw2** [comment]
> prubuje zainstalować po raz 3 mod paka ale nie moge zatrzymuje sie na "get Forge information" i nic dalej

This does not belong here, if you have an issue with a modpack make a new ticket on https://github.com/FTBTeam/FTB-Modpack-Issues/issues. If you can use English as well this will help me to understand and make sure to add game logs or images showing the error.

**Comment by Raidobw2** [comment]
Missing information or feedback and currently the paste expired. I'm afraid myself or a mod dev cannot do anything to help in that case. If you need help, you can use the support channels of the FTB Discord https://go.ftb.team/discord
