### ISSUE TITLE
[Bug]: Checkmark tasks do not show the correct icon

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-Mods-Issues#214]
### Mod

FTB Quests

### Mod version

ftb-quests-forge-1605.3.6-build.98

### Forge / Fabric version

1.16.5 36.2.22

### What issue are you having?

![image](https://user-images.githubusercontent.com/15698722/157032791-b09b6823-1a27-4574-9102-3d8f5d72fa6b.png)
![image](https://user-images.githubusercontent.com/15698722/157032812-dd0c9734-cddc-4a79-a27b-112f90d306c0.png)

Strangely, the quest's icon is showing the task's icon correctly. The quest has no icon, but is showing an Excavator like the icon should.

### Steps to reproduce

Make a checkmark task, give it an icon, observe.

**Comment by desht** [comment]
I think that's intentional, since a checkmark is... just a checkmark. And it needs to guarantee that it can display a distinct image for unchecked and checked states.  I'm not sure of the value of being able to give it an arbitrary icon?

**Comment by aaronhowser1** [comment]
Maybe it should be removed as an option for the task then, if it's not fully functional

**Comment by desht** [comment]
Yeah that might be the best option.

**Comment by desht** [comment]
Fixed in 1.18/1.19
