### ISSUE TITLE
FTB Chunks (Forge) Error (newest version)

### ISSUE THREAD

**Issue by Joshernoob** [FTBTeam/FTB-Mods-Issues#215]
### Mod

FTB Chunks (Forge)

### Mod version

ftb-chunks-forge-1801.3.4-build.127

### Forge / Fabric version

1.18.1, Forge 39.1.2

### Modpack & version

Personal

### What issue are you having?

As seen in the crash log given newest version of FTB Chunk(Forge) seems to crash when trying to get the dimension its in, this happens when you try to press the hot key to go full screen only, otherwise the mini map seems to just not show up and nothing crashes

### Crashlogs

https://pastebin.com/pPAaCtj5

### Steps to reproduce

1: check for mini-map
2:open full map with hot key
3:game will freeze for about 2 minutes
4: game crashes with said error 

### Anything else to note?

If needed I can give a zip file of the personal pack the mod in if this is only happening to me

**Comment by Raidobw2** [comment]
Linked to #70

**Comment by Raidobw2** [comment]
I'll keep only the other issue #70 for our mod developer in order to avoid redundancy. You can subscribe to the other issue if you want to be notified about it.
