### ISSUE TITLE
[Bug]: FTB Sluice Autohammer stacks 58,320 items in output

### ISSUE THREAD

**Issue by hendrik1120** [FTBTeam/FTB-Mods-Issues#216]
### Mod

FTB Sluice

### Mod version

ftb-sluice-forge-1.0.11-build.47

### Forge / Fabric version

forge-1.16.5-36.2.20

### Modpack & version

FTB Oceablock 1.11.0

### What issue are you having?

The auto-hammers from ftb sluice are stacking items in their autput slot like crazy when the chest connected is already full. So far waila is reporting 8x 7290 items in one autohammer. All these items get dropped if the autohammer is destroyed, causing massive amounts of invisible items spilling all over the place.

### Steps to reproduce

1. Place any Auto-Hammer from FTB Sluice
2. Connect an item source to the input
3. Optional: Connect a chest to the ouput and let it fill up.
4. Now you can store 58k items.

### Anything else to note?

Not 100% sure if this is a bug, but the amount of items a single Auto-Hammer can store seems kinda ridiculous to me.

**Comment by Raidobw2** [comment]
Hi, thanks for the report, however this is already listed at #125
