### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Eidelmaim** [FTBTeam/FTB-Mods-Issues#217]
### Mod

FTB Ultimine

### Mod version

ftb-ultimine-forge-1801.3.2-build.52

### Forge / Fabric version

forge-1.18.2-40.0.12

### Modpack & version

private

### What issue are you having?

crashes server after ultimine mod along with its dependencies are installed.

### Crashlogs

https://pastebin.com/iRCtWpt1  - with vanilla plus tools

https://pastebin.com/VZYvgwt5  - without vanilla plus tools

### Steps to reproduce

create server with the 13 mods listed in the crash reports and run the server.

### Anything else to note?

the crash reports are including a version with vanilla plus tools and with out... the crash srtill hapopens even though vanilla plus tools are listed in the first report wth an error.

**Comment by Raidobw2** [comment]
Hi, it doesn't support 1.18.2 yet. Our mod author still hasn't had the time to update it, but will soon
https://github.com/FTBTeam/FTB-Ultimine/blob/506ed8a57c5a3036485bbe21911c196b3a711690/gradle.properties#L8
