### ISSUE TITLE
[Feature Request]: Enforce disable entities on map - Server

### ISSUE THREAD

**Issue by serialtasted** [FTBTeam/FTB-Mods-Issues#218]
### Mod

FTB Chunks

### Description

The mod has this options on the client side, but it would be good to have it on the server also so it's possible to enforce players to not be able to see enemy entities on the map.
This is useful for servers that want a bit more of a hardcore experience when exploring and not having players knowing where enemies are all the time.

### Describe the solution you'd like

Add the following options on server configs:
```
// Show waypoints on minimap
"minimapWaypoints": true
// Show player heads on minimap
"minimapPlayerHeads": true
// Show entities on minimap
"minimapEntities": true
// Show entity heads on minimap
"minimapEntityHeads": true
```

**Comment by Raidobw2** [comment]
Linked with https://github.com/FTBTeam/FTB-Mods-Issues/issues/64

**Comment by desht** [comment]
Here's the problem with requests like this: this is a client-side feature which the server can't do anything about. Vanilla clients already know where nearby mobs are, so if a player really wants to get round the rules, they'll just install another clientside map mod which shows the entities again, and there isn't anything FTB Chunks (or indeed any serverside mod) can do about it.

I should note that player heads are currently shown to all players; the next release of FTB Chunks will provide proper control over who can see who, based on a team setting (allow all, allies or only team mates). But as before, it's still possible for someone determined to cheat to install a client-side mod which reveals all nearby entities, so there's no 100% anti-cheat solution.

**Comment by serialtasted** [comment]
Well if your making a pack and enforce the mods on it you can keep control of it

**Comment by desht** [comment]
No, you really can't. You have zero control over what client-only mods a player adds to a modpack.

**Comment by MichaelHillcox** [comment]
Closing due to trivial bypass by players. We may revise the client options of our mods in the future but right now, having servers enforce settings isn't practical. It's just too easy for players to bypass and most of these features really don't give the player but much advantage. 

It's also worth noting people can just use a different map mod, most don't require a server component.
