### ISSUE TITLE
[Feature Request]: Remember Chapter pin setting

### ISSUE THREAD

**Issue by lpacphantom** [FTBTeam/FTB-Mods-Issues#220]
### Mod

FTB Quests

### Description

I always like to have the Chapter menu open when I'm playing and I'm able to pin it open currently, but when I restart the game, the setting is back to the default. I'd like for that setting to be persistent so that I don't always have to pin it when I launch. 

Navigation is so much easier with that menu open and it doesn't take up that much space. I honestly don't see why it can even close, but that's just my opinion.

### Describe the solution you'd like

Remember the options the user sets from session to session. Alternatively, add a config option for the default behavior.

### Describe alternatives you've considered

Technically the current behavior is the workaround, I have to click the pin option at start of play each time.

**Comment by desht** [comment]
That's always bothered me too.  Fortunately, not any longer; will be fixed in next release.

**Comment by desht** [comment]
Implemented for 1.18 & 1.19
