### ISSUE TITLE
[Bug]: Crash When place the mouse pointer over the shop button

### ISSUE THREAD

**Issue by OcrSu** [FTBTeam/FTB-Mods-Issues#222]
### Mod

FTB Money (Forge)

### Mod version

ftb-money-1605.1.3-build.6.jar

### Forge / Fabric version

1.16.5-36.2.31

### Modpack & version

https://www.curseforge.com/minecraft/modpacks/lcw/files 3.4.1

### What issue are you having?

Crash When place the mouse pointer over the shop button

### Crashlogs

https://paste.feed-the-beast.com/view/6436f567

### Steps to reproduce

Place the mouse pointer over the shop button

### Anything else to note?

Use Java11 To Start Game

**Comment by Domkem** [comment]
I have the same Problem when I play on my Server

**Comment by IvanDart1001** [comment]
I have the same Problem when I play on my Server, too.

**Comment by Gunner76th** [comment]
I am not sure what launcher you are using, but I did notice you are using Java 11. Modded Minecraft 1.16.5 needs Java 8, so that could be a cause of your issue. I am unable to recreate the crash through AT Launcher using Java 8.

**Comment by IvanDart1001** [comment]
I might have found the key to solve this problem :)
https://github.com/FTBTeam/FTB-Money/blob/2b0ede6d8afb094bbed99a3839711d9f02f1e998/src/main/java/dev/ftb/mods/ftbmoney/gui/TabButton.java#L45
there is a contextMenu be created at this line. And a key named 'selectServer.edit' doesn't appear in FTB Money's en_us.json.
https://github.com/FTBTeam/FTB-Money/blob/2b0ede6d8afb094bbed99a3839711d9f02f1e998/src/main/resources/assets/ftbmoney/lang/en_us.json

Then the FTB Library's ScreenWrapper.java need the wrappedGui.contextMenu to be Non Null: https://github.com/FTBTeam/FTB-Library/blob/bc1506837abbebbc05a028a10f1eaf09a4a64474/common/src/main/java/dev/ftb/mods/ftblibrary/ui/ScreenWrapper.java#L121

I ll try to add 'selectServer.edit' to my server's Modpack Translated Dictionary to see what if the crash would be solved.

**Comment by OniNezuko** [comment]
You may turn your server online-mode on , I just fix crash by doing that. :)
