### ISSUE TITLE
[Bug]: FTB Ranks 1.18.1 - ftbchunk claim/forceload options not applying

### ISSUE THREAD

**Issue by nanonestor** [FTBTeam/FTB-Mods-Issues#224]
### Mod

FTB Ranks

### Mod version

ftb-ranks-forge-1801.1.6-build.24

### Forge / Fabric version

1.18.1 39.1.2

### Modpack & version

Briar Patch 2

### What issue are you having?

Using FTB Ranks and FTB Chunks (ftb-chunks-forge-1801.3.4-build.127) together on a modpack.

The `ftbchunks.max_claimed` and `ftbchunks.max_force_loaded` options added to ranks on the webhosted (working-ish) server refuse to alter the allocation of either type of chunk claim / force loads.

### Steps to reproduce

Load Forge 39.1.2 both on a client and on a server and install
----------------
architectury-3.7.33
ftb-chunks-forge-1801.3.4-build.127
ftb-essentials-1801.1.6-build.37
ftb-library-forge-1801.3.5-build.109
ftb-ranks-forge-1801.1.6-build.24
ftb-teams-forge-1801.2.5-build.48

**Comment by Raidobw2** [comment]
Could you share your ranks file so our mod developers can test with the same settings?

**Comment by nanonestor** [comment]
Here's the ranks.json file i've been using as a test-
[https://paste.gg/p/anonymous/cdcf5b53f1a9483381f78624fd9be3b6](https://paste.gg/p/anonymous/cdcf5b53f1a9483381f78624fd9be3b6)

I've tinkered around and have encountered strange behavior from what i'd expect.  To take you through  the sequence of events - On booting a fresh world with these in the /defaultconfigs folder it will have assigned the chunk claim / force load amounts specified in ranks.json.  Editing those values will make no change to the in-game shown values, either on total server reboot, /reload, or /reload ftbranks.  On a lark I then deleted the player SNBT file inside the server world folder's /ftbchunks folder and rebooted.  Now changes to ranks.json will apply, but only on total server reboots.  I tested a fresh world again and same result - rebooting has no effect until i've purged the original /chunks/player.snbt file.

**Comment by Raidobw2** [comment]
Sorry for the late reply, appears to be working now in 1.18.2. Possibly our mod dev fixed this back then, I'm unsure, but he fixes a lot of stuff. This might have been a bug in 1.18.1 while the mod was being ported.

I see your modpack is now on 1.18.2, which means it should already have the fix. Thanks for your report
![image](https://user-images.githubusercontent.com/17010632/183239980-662b0b72-2e74-4b0a-9f00-65c9dc37b8ad.png)
![image](https://user-images.githubusercontent.com/17010632/183239983-10e1a969-85d7-44da-8bc8-ff199826f92b.png)
