### ISSUE TITLE
[Bug]: When checking chunks outside of claimed chunks 

### ISSUE THREAD

**Issue by Whottech** [FTBTeam/FTB-Mods-Issues#227]
### Mod

FTB Chunks

### Mod version

ftb-chunks-forge-1605.3.2-build.115

### Forge / Fabric version

1.16.5 36.2.21

### Modpack & version

Invicta 1 - 1.4.1.1

### What issue are you having?

When checking chunks outside of claim chunks the following message appears -

The game crashed whilst mouseclicked event handler
Error: java.lang.NullPointerException: mouseClicked event handler
Exit Code: -1

### Steps to reproduce

You click the map button on the inventory screen and the pack crashes instantly

**Comment by Raidobw2** [comment]
Hmm, that looks linked to #70 . Can you add your game log here so we can confirm?

**Comment by ChickenDestroyer** [comment]
I'm getting the same issue, as well as multiple people on my server. Sorry if too many crash reports, theese are from 3 different people, including myself.
[crash-2022-04-13_17.53.34-client.txt](https://github.com/FTBTeam/FTB-Mods-Issues/files/8499401/crash-2022-04-13_17.53.34-client.txt)
[crash-2022-04-12_22.48.11-client.txt](https://github.com/FTBTeam/FTB-Mods-Issues/files/8499402/crash-2022-04-12_22.48.11-client.txt)
[message (1).txt](https://github.com/FTBTeam/FTB-Mods-Issues/files/8499404/message.1.txt)
[message (4).txt](https://github.com/FTBTeam/FTB-Mods-Issues/files/8499405/message.4.txt)
[message (2).txt](https://github.com/FTBTeam/FTB-Mods-Issues/files/8499406/message.2.txt)

**Comment by MichaelHillcox** [comment]
Thanks for the reports, this issue is on my list and I'm working on sorting it

**Comment by ChickenDestroyer** [comment]
Any kind of update on this?

**Comment by MichaelHillcox** [comment]
Yeah, I'm working on it, I know it's annoying to not have it working right now but somethings changed in the way MC handles this and it's not respecting our system anymore. Hoping for an update in the next day or two

**Comment by Raidobw2** [comment]
I'll keep only #70 for our mod dev, to avoid redundancy. If you want to be updated, make sure to subscribe to the other issue to get notifications.
