### ISSUE TITLE
[Bug]: FTB Quests Crash

### ISSUE THREAD

**Issue by SharkieTV** [FTBTeam/FTB-Mods-Issues#230]
### Mod

FTB Quests (Forge)

### Mod version

ftb-quests-forge-1802.3.8-build.101.jar

### Forge / Fabric version

1.18.2 FORGE 40.0.32

### Modpack & version

Using my Own Modpack

### What issue are you having?

Crash with new FTB Quests or FTB Mods for 1.18.2

### Crashlogs

https://pastebin.com/L41nhzMQ

### Steps to reproduce

1. Add all the necessary Mods to my Own Modpack (Better Minecraft)
- architectury-4.1.36.jar
- ftb-library-forge-1802.3.6-build.115.jar
- ftb-quests-forge-1802.3.8-build.101.jar
- ftb-teams-forge-1802.2.6-build.51.jar
- item-filters-forge-1801.2.6-build.16.jar
2. Launch
3. Create a world and then Crash while Loading World

### Anything else to note?

I am a Modpack Dev and was trying to use this in my Better Minecraft [FORGE] 1.18.2 Modpack and getting this crash, can only assume its an issue with another Mod since its been released?

**Comment by MichaelHillcox** [comment]
`item-filters-forge-1801.2.6-build.16.jar`

You need to update item-filters https://www.curseforge.com/minecraft/mc-mods/item-filters-forge/files/3725923
