### ISSUE TITLE
[Feature Request]: Register FTB Sluice auto hammers as catalysts for hammer recipes

### ISSUE THREAD

**Issue by aeonic-dev** [FTBTeam/FTB-Mods-Issues#231]
### Mod

FTB Sluice

### Description

Auto hammers aren't registered as catalysts for the hammer recipes through JEI, which threw me for a loop for a bit in Oceanblock. Not a pressing issue but would make a useful QOL change.

### Describe the solution you'd like

I'm working on a PR to do this but I figure the correct procedure is to make an issue here first. It's a trivial non-breaking change; just thought I should post regardless. Will update here with a PR later assuming you guys are okay with it. Love the mod, thanks for consideration!

**Comment by aeonic-dev** [comment]
I've made a PR at https://github.com/FTBTeam/FTB-Sluice/pull/9. Thanks again for the hard work on FTB mods!

**Comment by Raidobw2** [comment]
Looks like both your PRs were merged, so I assume this has been fixed (by you!). Thank you for your contributions!

**Comment by aeonic-dev** [comment]
Yup, thought I had closed the issue but guess I forgot. Thanks!
