### ISSUE TITLE
[Feature Request]: FTB Ranks 1.16.5+ | Option to inherit/extend other ranks, for easier rank management. 

### ISSUE THREAD

**Issue by MagnusHJensen** [FTBTeam/FTB-Mods-Issues#236]
### Mod

FTB Ranks

### Description

The ability to have a key/value `extends: Member` or something along the lines, so that it would automatically pick up any command permissions in the rank specified. 

It could be overwritten by of course having the same command node with a new value.

### Describe the solution you'd like

Maybe a key like: `extends: [Rank name]` fully optional.

I would assume it wouldn't be too difficult, since all the elements already exists, they just need to be tied in, so other ranks can be linked/expanded onto the current rank instance.

### Describe alternatives you've considered

There isn't any real alternatives for permissions systems on modded forge.

**Comment by Raidobw2** [comment]
Hello, just to make sure, you do know that ranks with high power already have all permissions from ranks with lower power? For example take the following picture:
![image](https://user-images.githubusercontent.com/17010632/163518728-92e8d88c-fc35-4bbf-a7d1-c70be04ca66d.png)

People with the "Member" rank are newcomers on your server. Your experienced people are in the "BetterMember" rank. In addition from their own rank permissions, they will have all permissions below them in power, including those from the dummy rank "CoolPermissions" and from "Member".

If that picture does not represent what you wanted to suggest, then let us know here and our mod developers will have a look!

**Comment by MagnusHJensen** [comment]
Aha, does it automatically inherit from lower power ranks? Or do you need to stack them.

So in that case, the user would need to have the ranks: `BetterMember` and `Member` if so, then that is more or less what I want and the issue/feature request can be closed :D

Thank you!

**Comment by Raidobw2** [comment]
Yes, ranks with higher power inherit from all permissions in ranks with lower power. For example if you have the default VIP rank, you will have all permissions from ranks below you in power. Stacking or order does not matter, it's simply controlled by power. Your players can have more than one rank assigned to them as well, that is also possible.

I'll be closing this then!
