### ISSUE TITLE
[Bug]: "/ftbteams party join" not valid command

### ISSUE THREAD

**Issue by CyclistBrad** [FTBTeam/FTB-Mods-Issues#239]
### Mod

FTB TEAMS

### Mod version

Ftb-teams-forge-1802.2.6-build.51

### Forge / Fabric version

Forge 40.0.54

### Modpack & version

All The Mods 7

### What issue are you having?

On locally hosted server,  users cannot join teams via console nor any other method. Teams can be created,  invites can be sent but join function is not recognized as valid command. This renders mine colonies as well as other mods and functions that utilize ftbteams to be unusable. 

Am I overlooking a server side property to enable team joining?

### Steps to reproduce

Join server
Create team
Invite player
Player tries to join

**Comment by Raidobw2** [comment]
Hi, are you able to make the team "free to join" in its configuration and can players join it this way (click My Team in top left of inventory and twice the settings cogs)? This can work around the issue for now and give some cues to our mod developers so that they can pinpoint the issue and fix it. Thanks for letting me know if that worked

**Comment by CyclistBrad** [comment]
Even with my team set to free to join,  when I invite another user, the
message is sent for the user to join.  When they click the message to join
the party they get an error. I have attached a picture of the message.

**Comment by Raidobw2** [comment]
Hello, when the team is free to join they can join with `/ftbteams party join <name>` without the need for an invite. Let me know if that fails as well, thanks in advance

**Comment by CyclistBrad** [comment]
"join" throws an error, incorrect arguement. See attached.

**Comment by Raidobw2** [comment]
They have to leave their team in order to be able to join yours
