### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by gabgat** [FTBTeam/FTB-Mods-Issues#241]
### Mod

FTB Quests

### Description

A friend of mine has translated the mod to italian, i'll send you the file in .txt because github does not support .json in this field...
Can you update the mod? We need Italian for a modpack. Thank you!
[it_it.txt](https://github.com/FTBTeam/FTB-Mods-Issues/files/8577448/it_it.txt)

**Comment by MichaelHillcox** [comment]
Please make a pull request to FTBTeam/FTB-quests
