### ISSUE TITLE
[Bug]: Chat Rank Server Issues

### ISSUE THREAD

**Issue by djburg** [FTBTeam/FTB-Mods-Issues#244]
### Mod

FTB Ranks

### Mod version

ftb-ranks-forge-1802.1.7-build.27

### Forge / Fabric version

1.18.2

### Modpack & version

TNP 5 Limitless

### What issue are you having?

Server Chat is not formatted to game-chat all clients connecting have issues, they see their own ranks.

In-Game
![image](https://user-images.githubusercontent.com/94327035/165870656-63b6a053-3c7b-4d0c-8f75-6e5c61972c1d.png)

Server Log
![image](https://user-images.githubusercontent.com/94327035/165870685-08a2e258-562b-47f6-9099-949167ac0937.png)

### Steps to reproduce

1. Type in chat

**Comment by djburg** [comment]
It's a new issue was functional for the last few weeks too

**Comment by Raidobw2** [comment]
Where any mods added to the server before the issue started appearing? Are there any other mods that could modify chat, such as plugins like LuckPerms?

**Comment by DLCIncluded** [comment]
We ran into this same issue this week. It was working then all of a sudden it stopped. 
We are playing Direwolf20 1.18 v1.4.1, but I tested on a server with forge, ftb-ranks and its necessary libraries and could not get the ranks to properly show their colors/formatting with default configs:

 This is a server / pack with literally nothing in it but ftb ranks, architectury and ftb library forge:
 Client 1 and server console:
![image](https://user-images.githubusercontent.com/23517228/173168145-b7dc1a2a-62b3-4fa2-a897-add2debd52e0.png)
Client 2: 
![image](https://user-images.githubusercontent.com/23517228/173168150-bb33ff74-71bf-4022-9a2c-53bf4485f96c.png)

This was done on fresh installs of all the versions of the Direwolf20 1.18 pack from 1.0 to 1.4.1, as well as the version with only ftb ranks, and none will show the rank's name formatting properly.

This is a screenshot from 6-9-2022 (yesterday) where it was working properly, and no changes were made:
![2022-06-09_14 53 11](https://user-images.githubusercontent.com/23517228/173168283-4fea5357-4538-41f5-9d72-ac09c456f007.png)
And now today my client then a friends client:
![image](https://user-images.githubusercontent.com/23517228/173168327-9327c9e7-1266-4bef-a2d1-da3520e41b9b.png)
![image](https://user-images.githubusercontent.com/23517228/173168339-0354a172-d9ac-40b7-99c0-454eeb91eb6e.png)


and the server console has the titles correct: 
![image](https://user-images.githubusercontent.com/23517228/173168337-e1cf5ff6-8794-41a1-85d4-de4825011f6e.png)

**Comment by DLCIncluded** [comment]
apparently if you link an item in chat, using shift+T (unsure which mod adds that) ftb ranks can correctly format the name: 
![image](https://user-images.githubusercontent.com/23517228/173168474-a643e593-4ee8-4232-bd47-4deb460aaab2.png)

**Comment by Raidobw2** [comment]
Linked https://github.com/FTBTeam/FTB-Mods-Issues/issues/308, https://github.com/FTBTeam/FTB-Modpack-Issues/issues/938
Appears fixed with https://github.com/MinecraftForge/MinecraftForge/issues/8729,
so I will be closing this issue since it should be resolved
