### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by PABessero** [FTBTeam/FTB-Mods-Issues#248]
### Mod

FTB Chunks

### Mod version

ftb-chunks-forge-1801.3.4-build.134

### Forge / Fabric version

1.18.2 40.1.0

### Modpack & version

AllTheMods6

### What issue are you having?

After updating manually from ftb-chunks-forge-1801.3.4-build.130 to ftb-chunks-forge-1801.3.4-build.134, the game wont load anymore:
![image](https://user-images.githubusercontent.com/33829930/166138605-792d7dee-984e-4545-b6cd-36d62dbb4c5a.png)

### Crashlogs

https://pste.ch/xabuyeyemo.pl

### Steps to reproduce

1. Remove ftb-chunks-forge-1801.3.4-build.130
2. Add ftb-chunks-forge-1801.3.4-build.134

**Comment by MichaelHillcox** [comment]
This isn't our mod
