### ISSUE TITLE
[Bug] Chunk Protection bypasses

### ISSUE THREAD

**Issue by fireheart3911** [FTBTeam/FTB-Mods-Issues#250]
### Mod

FTB Chunks

### Mod version

ftb-chunks-forge-1605.3.2-build.115

### Forge / Fabric version

1.16.5 36.2.33

### Modpack & version

Survival Attack 7

### What issue are you having?

Players can use Sigils from [Blood Magic](https://github.com/WayofTime/BloodMagic) and the Slingshot from [Supplementaries](https://www.curseforge.com/minecraft/mc-mods/supplementaries) to place and destroy blocks on other claims. 

Initial issue: SurvivalAttack/Survival-Attack-7#7

#### Place blocks:
1. Get a slingshot
2. Throw a block at your desired location

#### Remove Blocks (anything not a full block):
1. Use a water/lava sigil on the surface below the block `(-> Block gets replaced with lava/water)`
2. Use a void sigil to remove the fluid

#### Remove Blocks (full blocks):
1. Place a chest using the method above next to the block you want to remove
2. Use the lava/water sigil on the pixel between the chest and the block
3. Remove the fluid using the void sigil
4. Remove the chest as stated above

**Comment by Raidobw2** [comment]
Linked with #71

**Comment by desht** [comment]
This is a bug in both Blood Magic and Supplementaries - both mods simply place blocks in the world, without verifying that they should.  The correct way to do this would be to fire a Forge block place event (or whatever the equivalent Architectury event is in the case of Supplementaries) before trying to place the block.
