### ISSUE TITLE
[Feature Request]: Vein 'mining' Stripping

### ISSUE THREAD

**Issue by milkev** [FTBTeam/FTB-Mods-Issues#251]
### Mod

FTB Ultimine

### Description

when stripping logs with an axe, or pathing grass with a shovel, you typically want to do large amounts of this process. It takes so long!

### Describe the solution you'd like

It would be interesting if you could 'vein mine' the action of stripping, like right clicking logs with an axe, or grass with a shovel.
idk if that fits within the design philosophy or anything, but i think it has good use since you typically want to strip or path a lot at once.

**Comment by desht** [comment]
Added in 1902.4.0 release
