### ISSUE TITLE
Allow people in a team to have seperate chunk claims

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [FTBTeam/FTB-Mods-Issues#254]
I have been thinking about this and I would like to be able to have separate claims per person even when on a team. I find it really annoying that once you are on a team - you only get so many blocks. Especially when the team leader wastes all the claims.

**Comment by desht** [comment]
The team chunk claim limit has effectively been worked around in newer releases, where you can define in server config how team limits are calculated (e.g. it's now possible to make the limit be the sum of all the members' limits).
