### ISSUE TITLE
disable pvp in claimed areas

### ISSUE THREAD

**Issue by Sitherious** [FTBTeam/FTB-Mods-Issues#256]
can we have an option to disable all pvp in claimed areas?

**Comment by SpigotDE** [comment]
Is it possible to disable pvp in claimed chunks with KubeJS on Fabric?

**Comment by joaoespanhol** [comment]
Exemple code for implement code

public void togglePvP(CommandSender sender, Chunk chunk) {
    // Check if the player has permission to toggle PvP in this chunk
    if (!sender.hasPermission("ftbchunk.pvp.toggle")) {
        sender.sendMessage("You do not have permission to change PvP in this chunk.");
        return;
    }

    // Toggle the PvP status in the chunk
    boolean pvpEnabled = chunk.isPvPEnabled();
    chunk.setPvPEnabled(!pvpEnabled);

    // Notify the player about the current PvP status in the chunk
    String message = pvpEnabled ? "PvP has been disabled in this chunk." : "PvP has been enabled in this chunk.";
    sender.sendMessage(message);
}

public boolean onCommand(CommandSender sender, Command cmd, String label, String[] args) {
    if (cmd.getName().equalsIgnoreCase("pvp")) {
        Player player = (Player) sender;
        Chunk chunk = player.getLocation().getChunk();

        togglePvP(sender, chunk);
        return true;
    }
    return false;
}

**Comment by joaoespanhol** [comment]
> 

yes



onEvent('ftbchunks:world_load', event => {
  // Desativa o PvP quando o mundo é carregado
  global.isPvpDisabled = true;
});

onEvent('ftbchunks:world_unload', event => {
  // Ativa o PvP quando o mundo é descarregado
  global.isPvpDisabled = false;
});

onEvent('entity:attack', event => {
  // Cancela o evento se o PvP estiver desativado
  if (global.isPvpDisabled && event.entity.getType() === 'player') {
    event.cancel();
  }
});




// Importar a classe Command do KubeJS
const { Command } = require('kubejs/command')

// Registrar o comando "/pvp"
events.listen('server.datapack.tags', event => {
  event.get('commands').add('pvp')
})

// Definir a ação do comando "/pvp"
Command.create('pvp')
  .alias('togglepvp')
  .description('Ativa ou desativa o PvP dentro das chunks protegidas pelo FTB Chunk.')
  .permission('ftbchunks.claim')
  .handler(({ player }) => {
    const chunk = player.getChunk()

    // Verificar se o jogador está em uma chunk protegida pelo FTB Chunk
    if (!ftbChunksAPI.canUse(player.getCommandSenderWorld(), chunk, 'pvp')) {
      player.sendMessage('Você não tem permissão para alterar o PvP nesta chunk.')
      return
    }

    // Alternar o status do PvP na chunk
    ftbChunksAPI.toggleFeature(player.getCommandSenderWorld(), chunk, 'pvp')

    // Notificar o jogador sobre o status atual do PvP na chunk
    const pvpEnabled = ftbChunksAPI.hasFeature(player.getCommandSenderWorld(), chunk, 'pvp')
    const message = pvpEnabled ? 'O PvP foi ativado nesta chunk.' : 'O PvP foi desativado nesta chunk.'
    player.sendMessage(message)
  })

**Comment by manmaed** [comment]
is this planed @desht ?

**Comment by BloodyPopelam** [comment]
Pvp mod - the pvp status status of your captured territories. My idea is to make a condition for enabling Pvp mod for captured territories with a delay or if the captured territory exists for more than a certain time. There are both of these characteristics of the chunk (Pvp combat and the time of the application for the territory) my problem is that I can't find either the file or the line of code responsible for Pvp Combat, the function itself is present in the game, but I can't customize it somehow due to the lack of a file/code with this very function.
