### ISSUE TITLE
[Bug]: Problem with JEI text select shortcuts, Ctrl+A to select all text doesn't work

### ISSUE THREAD

**Issue by hadrus** [FTBTeam/FTB-Mods-Issues#262]
### Mod

FTB Teams

### Mod version

ftb-teams-forge-1802.2.6-build.51

### Forge / Fabric version

1.18.2 40.1.0

### What issue are you having?

FTB Teams or FTB chunks overlay on inventory screen blocking keyboard shortcuts for selecting text in JEI. Example: Ctrl+A doesnt work to select all text in search bar.

### Steps to reproduce

1. Install FTB Teams
2. Install JEI
3. Open inventory
4. Type something in search bar
5. Try to select text with ctrl+a

**Comment by Xetaxheb** [comment]
Actually I'm having this issue with just FTBLibrary  (ftb-library-forge-1802.3.6-build.115.jar)  alone (and Architectury (architectury-4.4.54)) 

For clarity, breaks shift+left arrow or shift+right arrow as well. Cannot highlight in any way.

**Comment by Goufix** [comment]
Any update on this?

Having the same issue while playing ATM 7

**Comment by MichaelHillcox** [comment]
Can anyone take a screenshot or short video showing this issue?

**Comment by TheAndrata** [comment]
You can see it starting at about 10:09 on my latest YouTube video: [https://youtu.be/NIGMCuIqZeg](https://youtu.be/NIGMCuIqZeg) 

As stated by the others, no keyboard text shortcuts work period for highlighting.

**Comment by Xalcon** [comment]
Something I noticed while playing around in my custom pack, text selection seem to only break when any sort of inventory is shown (i.e. Player inventory, Creative Menu, chest, etc). As soon as you go into recipe view (Pressing R or U on an item), text selection in JEI starts working again.

**Comment by Raidobw2** [comment]
https://github.com/mezz/JustEnoughItems/issues/2938 also is another report on JEI about this issue. I'll mention this problem to our mod dev

**Comment by AerosAtar** [comment]
Just adding another voice to the "I'm getting this" crowd - 1.18.2, FTBLib 1802.3.6-build.140, JEI 1.18.2-9.7.1.255. I can also confirm what Xalcon said above - recipe view allows for text selection, but inventory view does not.

**Comment by GrubySan** [comment]
So i got this glitch/bug on my game too so just till the time for fix will come u can just set keybind clear search bar in jei to ctrl+a assuming u always want to clear the search bar when want to cl use ctrl+a

**Comment by desht** [comment]
Fixed in 1.18/1.19.

Recent versions of JEI also prevent this problem from occurring.
