### ISSUE TITLE
[Feature Request]: Client side config option "claimed_chunks_on_map" for server side

### ISSUE THREAD

**Issue by RadonCoding** [FTBTeam/FTB-Mods-Issues#264]
### Mod

FTB Teams

### Description

I think many people would like if it would be possible to keep your base hidden on a server.

### Describe the solution you'd like

"claimed_chunks_on_map" option for server config

**Comment by MichaelHillcox** [comment]
Hmm, I could likely add a hidden thing and allow server owners to decide if users can use it or not

**Comment by RadonCoding** [comment]
Btw would this be added to the 1.16.5 version aswell or just the latest?

**Comment by MichaelHillcox** [comment]
Not sure, I'd have to see how much needs changing

**Comment by RadonCoding** [comment]
Has there been any progress on this?

**Comment by desht** [comment]
Fixed in 1.18/1.19
