### ISSUE TITLE
[Bug]: Pressing M on client while connected to server crashes client (update)

### ISSUE THREAD

**Issue by kdx7214** [FTBTeam/FTB-Mods-Issues#265]
### Mod

Direwolf20

### Mod version

1.18

### Forge / Fabric version

not sure

### Modpack & version

1.0

### What issue are you having?

Client crashes while pressing M for the map.   More experimentation revealed that this happens when the server is started with start.sh (after fixing) rather than run.sh

### Steps to reproduce

1.  Load server with corrected run.sh (linux)
2. Load client (windows)
3. log into server
4. hit M

### Anything else to note?

This is an update to a previous report as I couldn't find the previous one.  Note that no dimension hopping or anything occurred, this was on initial login.

**Comment by MichaelHillcox** [comment]
Fixed in latest version, the dire pack should get an update soon, update FTB lib to the latest version if you want it sooner than the pack update
