### ISSUE TITLE
Changing tasks and/or rewards

### ISSUE THREAD

**Issue by LatvianModder** [FTBTeam/FTB-Mods-Issues#27]
After completing a repeatable quest, the requirements increase, e.g. instead of requiring 10 glowstone, it now requires 20 to complete

**Comment by MaxNeedsSnacks** [comment]
Sorry for the quick mislabel, forgot that our issues and mod repos had been separated for a second :sweat_smile:

**Comment by desht** [comment]
Rolled into #946

**Comment by desht** [comment]
Rolled into #946
