### ISSUE TITLE
[Bug]: Solar Panel + Pipez crashes game

### ISSUE THREAD

**Issue by zperk13** [FTBTeam/FTB-Mods-Issues#270]
### Mod

FTB Industrial Contraptions

### Mod version

ftb-industrial-contraptions-1802.1.4-build.139

### Forge / Fabric version

Forge 1.18.2 40.1.19

### Modpack & version

FTB Presents Direwolf20 1.18 1.0.0

### What issue are you having?

Placing down a pipez energy pipe next to a FTBIC solar panel causes the game to crash and makes the game crash upon further reopenings of the world.

I also tested out the following and none of them crashed
Pipez energy pipe next to FTBIC basic generator
Pipez energy pipe next to Thernal Series dynamo
Mekanism universal cable next to FTBIC solar panel

So it's specifically an issue with specifically pipez and solar panel. Crash log specifically mentioned FTBIC though.

Crash log is attached.

### Crashlogs

Crash log: https://pste.ch/uzahecihin.rb

### Steps to reproduce

1: Place down FTBIC solar panel
2: Place down Pipez energy pipe next to it

**Comment by MichaelHillcox** [comment]
This should be fixed as of .141 of the FTB IC, please update or wait for the pack to be updated
