### ISSUE TITLE
[Bug]: Chunk Force Loading does not take effect on Fabric

### ISSUE THREAD

**Issue by Merith-TK** [FTBTeam/FTB-Mods-Issues#272]
### Mod

FTB Chunks

### Mod version

ftb-chunks-fabric:1802.3.6-build.145

### Forge / Fabric version

1.18.2, 0.14.4

### What issue are you having?

I am making an computercraft server where the main focus is to not be on the server, and instead control turtles through an web page

I am usung FTB Chunks to make claims and allow players to control the turtles when no account is logged on, however when players are offline, the turtles become un-responsive in chunk loaded areas, 

### Steps to reproduce

claim chunk
force load chunk, 
make action inside chunk to measure how much time has passed in the chunk versus realtime, 
leave server, 
wait duration, 
join server,
measure difference 

### Anything else to note?

![image](https://user-images.githubusercontent.com/10422110/169670927-4344e75a-689e-4742-b515-d7c8c51cd9e0.png)
full mod list,

**Comment by desht** [comment]
@Merith-TK It's been a while, but this issue should be resolved in recent FTB Chunks builds for both 1.18 and 1.19.  I don't know if you are still interested, or if I should close this issue now?
