### ISSUE TITLE
[Feature Request]: Purge team and claimed chunks data after team members were all unactive for several weeks

### ISSUE THREAD

**Issue by Tollainmear** [FTBTeam/FTB-Mods-Issues#274]
### Mod

FTB Teams/FTBChunks

### Description

It might be a useful feature for server, expecially for that has large flow of players server
![image](https://user-images.githubusercontent.com/25898067/170171389-3c4f0638-f6b0-4114-b425-a1441e7bb410.png)
As you can see above, the world spawn point was nearly fully claimed, and newcome players have to march a long distance to find a resourceful place to settle down, that will leave them in risk.

### Describe the solution you'd like

Mark a team as unactive if every member had offline for 4 weeks.
Remind moderator when he's join: how many teams are no longer active, and guid them to purge these data manually(by using command).
Btw, if there is a rollback option will be great, so moderators can recover the resource for these chunks, and rollback to the chunks first generated or before claimed.

### Describe alternatives you've considered

No idea about alternative plan, snbt file stored with UUID, with poor readability....
So if not implement the purge method officially, moderator can hardly manage teams and claimed chunks...

**Comment by desht** [comment]
I would probably limit this (at least initially) to chunk claims. If no member of a team has been active for X time (configurable), then automatically unclaim all that team's chunks. This needs to apply to both party teams, and individual player teams.

Having old teams around isn't a big deal; the server resources needed for that are minimal.  But having large areas of the map unusable by player is more of a problem.

**Comment by desht** [comment]
Fixed in 1.18/1.19

See the new `max_idle_days_before_unclaim` setting in server config; this is a timeout period in days.  If no member of the team logs in for that long, the team's claims are automatically released.

This is 0 by default, meaning no auto-release of claims.
