### ISSUE TITLE
[Feature Request]: Update Ars Nouveau support

### ISSUE THREAD

**Issue by Alexthw46** [FTBTeam/FTB-Mods-Issues#275]
### Mod

FTB-Chunks

### Description

Sylphs and carbuncles have been renamed to Whirlisprig and Starbuncle in the 1.18 versions of the mod, so their head icon does not display on the radar like the 1.16 versions

### Describe the solution you'd like

Simply renaming the old assets should enable back their head icon.

As for drygmies and other mobs (and support for my an addon archwood color), i can try make and pr the assets when i have time, if you accept them.

**Comment by Raidobw2** [comment]
Hello, I believe you will have to sign a contributor licence agreement when making the PR, but yes, we do accept PRs

**Comment by desht** [comment]
Fixed in 1.18/1.19
