### ISSUE TITLE
[Crash]: FTB Industrial Contraptions causes crash

### ISSUE THREAD

**Issue by NextDozen** [FTBTeam/FTB-Mods-Issues#276]
### Mod

FTB Industrial Contraptions

### Mod version

ftb-industrial-contraptions-1802.1.4-build.141

### Forge / Fabric version

1.18 40.1.20 

### Modpack & version

FTB Presents Direwolf20 1.18 - 1.2.0

### What issue are you having?

When launching the modpack after deepscan Ftbic causes crash.

![image](https://user-images.githubusercontent.com/45523256/170310821-348ebc55-7f10-4bd5-b053-6963810fe627.png)

### Crashlogs

https://pastebin.com/1msRqaRB

### Steps to reproduce

When launching the modpack issue persists.

### Anything else to note?

No optifine no additional mods.

Fresh install and reinstalled FTB app reinstalled modpack.

**Comment by NextDozen** [comment]
Works like a charm thank you.

**Comment by MichaelHillcox** [comment]
Awesome, I'll release an update today and let the pack developers know

**Comment by Raidobw2** [comment]
Looks like this was fixed and released in https://www.curseforge.com/minecraft/mc-mods/ftb-industrial-contraptions-forge/files/3807215

`fix: local issues on registry - Michael Hillcox`

I'll close this issue since it looks resolved!
