### ISSUE TITLE
[Bug]: Custom tags defined in KubeJS are not picked up by FTB Ultimine. (?).

### ISSUE THREAD

**Issue by Gbergz** [FTBTeam/FTB-Mods-Issues#277]
### Mod

FTb Ultimine

### Mod version

ftb-ultimine-forge-1802.3.3-build.55

### Forge / Fabric version

1.18.2 | 40.1.19

### Modpack & version

TNP Limitless 5, but solo too.

### What issue are you having?

Trying to add Merge tags so the ores from the mod Compact Ores can be ultimined together with the compact variants & deepslate & normal ore.
I've added a custom tag through KubeJS to allow this, but in-game it's not working, can't mine any of those together even if they are in the same tag. 

Custom tag example: "tnp:compact_coal"
With these blocks in the tag entry through kubejs: 
'minecraft:deepslate_coal_ore'
'minecraft:coal_ore'
'compactores:compactore__minecraft__deepslate_coal_ore'
'compactores:compactore__minecraft__coal_ore'

But in-game later, these are not able to be ultimined together. 
The tags are added to the ftbultimine-server.snbt under "merge_tags:".

### Crashlogs

No crash.

### Steps to reproduce

1. Install FTB Ultimine & KubeJS
2. Add custom tags through kubejs to blocks that should be mined together that arent normally.
3. Add tag to the "merge_tags" entry in the ftbultimine server config.
4. test ultimining blocks ingame.
5. blocks do not get mined "merged" together while mining.
profit.

### Anything else to note?

Am I just missing something maybe? Or is it not working.. 🤔 

They are simply not recognized by Ultimine would be my guess, not sure though.

**Comment by Raidobw2** [comment]
Hello, try this in the file:
```
# Server-specific configuration for FTB Ultimine
# This file is meant for server administrators to control user behaviour.
# Changes in this file currently require a server restart to take effect

{
	# Hunger multiplied for each block mined with ultimine
	# Default: 20.0
	# Range: 0.0 ~ 10000.0
	exhaustion_per_block: 20.0d
	
	# Max amount of blocks that can be ultimined at once
	# Default: 64
	# Range: 0 ~ 32768
	max_blocks: 64
	
	# These tags will be considered the same block when checking for blocks to Ultimine
	# Default: ["minecraft:base_stone_overworld", "c:*_ores", "forge:ores/*"]
	merge_tags: ["forge:ores/*", "tnp:compact_coal"]
}
```
Keep in mind that item tags are applied to items, and block tags are applied to blocks. If tnp:compact_coal is an item tag used in recipes and not a block tag, Ultimine will not work with it. If this solved the problem please close the issue, otherwise feel free to give us more information about the problem.

**Comment by Gbergz** [comment]
> If tnp:compact_coal is an item tag used in recipes and not a block tag:

I feel a little bit stupid now, yes they were indeed in the items tag and not blocks. Thanks for pointing that out.
Switched to blocks tag and now it works as expected!
