### ISSUE TITLE
[Feature Request]: Subcategories

### ISSUE THREAD

**Issue by TheButterbrotMan** [FTBTeam/FTB-Mods-Issues#278]
### Mod

FTB Quests

### Description

I would like to make subcategories like in FTB Quests on Forge. We dont have that on Fabric.

### Describe the solution you'd like

I would like to make subcategories like in FTB Quests on Forge.,

**Comment by desht** [comment]
Forge and Fabric builds of the mod are using basically the same codebase, so have complete feature parity.  Can you please confirm you're using the latest version of FTB Quests for Fabric (https://www.curseforge.com/minecraft/mc-mods/ftb-quests-fabric/files/3940954 - 1802.3.8-build.106) ?

**Comment by MichaelHillcox** [comment]
No reply, closing
