### ISSUE TITLE
[Bug]: FTB Teams don't share Claimable Chunks between players

### ISSUE THREAD

**Issue by wildficus** [FTBTeam/FTB-Mods-Issues#280]
### Mod

FTB Teams 

### Mod version

ftb-teams-fabric-1802.2.6-build.51.jar;  ftb-chunks-fabric-1802.3.6-build.145.jar

### Forge / Fabric version

fabric-api-0.53.4+1.18.2.jar

### Modpack & version

DeathDusk - 2.0.6

### What issue are you having?

Players that join a team do not acquire the total sum of each player's individual chunks as claimable team chunks.

Example: Three players on the DeathDusk official server have 9 claimable chunks individually. When they join a team, the team claimable chunks stay at 9, instead of 27.

### Steps to reproduce

1. Have the config made in such a way that a player gets 9 chunks 
2. Have a multiplayer server 
3. Have 3 people join 
4. Make a team that all 3 people join 
5. Experience the glorious 9 chunks instead of 27 of claimable space

**Comment by Raidobw2** [comment]
I'll keep only https://github.com/FTBTeam/FTB-Mods-Issues/issues/66 for tracking this issue for our mod dev, since it's basically the same request
