### ISSUE TITLE
[Bug]: My game won't even start.

### ISSUE THREAD

**Issue by Zulussu** [FTBTeam/FTB-Mods-Issues#281]
### Mod

FTB Industrial Contraptions (Forge)

### Mod version

 ftb-industrial-contraptions-1802.1.4-build.141

### Forge / Fabric version

forge-1.18.2-40.1.20

### Modpack & version

FTB Presents Direwolf 1.18 - 1.2.0

### What issue are you having?

My game won't even start.

![image](https://user-images.githubusercontent.com/97294732/170671852-1597c952-cde2-48df-8386-99f5185fd850.png)

### Crashlogs

https://pastebin.com/yTV5pV0f

### Steps to reproduce

I just downloaded the modpack and tried to open it and got the error shown in the screenshot.
Then I downloaded it again and got the same error again.
And I downloaded 5 more times and got the same error 5 more times.
I am using Windows 10 64 bit operating system, RTX 3050 Laptop graphics card. For some reason modpack doesn't seem to want to run on my pc.

### Anything else to note?

While browsing Crashlog, something caught my attention. It says "tın_ore" instead of "tin_ore". I don't know, but maybe that's the reason for the error. Just a guess.
![image](https://user-images.githubusercontent.com/97294732/170672980-69c800e4-c2a4-4cef-a552-1f0e70e95163.png)

**Comment by Raidobw2** [comment]
Hello, this was fixed recently at #276. Update the mod to the version pointed out in the linked issue and it will be fixed
