### ISSUE TITLE
[Feature Request]: Client and server options to disable world map (FTB Chunks)

### ISSUE THREAD

**Issue by Spleenczar** [FTBTeam/FTB-Mods-Issues#282]
### Mod

FTB Chunks

### Description

The map function of the mod can't be disabled, which creates problems for modpacks that want the mod's chunk claiming and loading but not player access to a world map or minimap, whether for a "hardcore" pack or for PvP reasons.

### Describe the solution you'd like

Ability to fully disable world and minimap function for players (forced by server) while still allowing chunk claiming/loading and the limited map view that comes with that.

**Comment by Brittank88** [comment]
There is a secondary reason for having this - the reserved heap space of (what I assume to be) the mapping this mod does is not insignificant, which is a shame as I don't even need that functionality for the pack I'm developing:
![image](https://user-images.githubusercontent.com/24266948/180134577-4925b7ff-908b-4be1-8b19-c2ea8979e777.png)

**Comment by Raidobw2** [comment]
I'll keep only https://github.com/FTBTeam/FTB-Mods-Issues/issues/185 opened for this feature to avoid redundancy
