### ISSUE TITLE
[Bug]: Waystone integration not working with FTB Chunks on Forge 1.18.2

### ISSUE THREAD

**Issue by KindarConrath** [FTBTeam/FTB-Mods-Issues#283]
### Mod

FTB Chunks

### Mod version

ftb-chunks-forge-1802.2.6-build.145

### Forge / Fabric version

1.18.2 40.1.0

### Modpack & version

Direwolf20 1.18

### What issue are you having?

Noticed on DW20 pack, but tested in a separate world with just FTB Chunks, JEI & Waystones

Waystones integration does not seem to work anymore, I can't get Waystones to appear on my map or minimap.

### Steps to reproduce

1. Place Waypoint
2. Right Click waypoint & name
3. check map

Expected: Waypoint appears on map

I forgot to name it... could someone update it with a name please, I can't change its name.

**Comment by Raidobw2** [comment]
The mod in question https://www.curseforge.com/minecraft/mc-mods/waystones

**Comment by desht** [comment]
Waystones compat will be back in the next FTB Chunks release.

**Comment by desht** [comment]
Fixed in 1.18/1.19

Waystones integration is back, for both Forge and Fabric releases

**Comment by KindarConrath** [comment]
this excites me more than it probably should!

**Comment by pwaksman973** [comment]
Don't want ressurect an old topic for a simple question, but how do I disable the integration, like I don't want that waystone marker on my minimap or map, but I can't find how to disable it
