### ISSUE TITLE
[Feature Request]: Luckperms

### ISSUE THREAD

**Issue by blacksythe** [FTBTeam/FTB-Mods-Issues#285]
### Mod

FTBChunks, FTBEssentials

### Description

I would like to see greater compatibility with Luckperms within the forge 1.18.2 environment.

### Describe the solution you'd like

I would like to be able to manage claim, chunkload and home allowances through luckperms if possible.

It now uses forge permission api, which should allow this kind of behaviour to happen

### Describe alternatives you've considered

If this is already possible then I apologise for the request.

**Comment by Merith-TK** [comment]
Would like this for Fabric 1.18.2 as well, as fabric ports of FTB mods do not expose permission nodes,

**Comment by Yann151924** [comment]
I made two pr for this :

- https://github.com/FTBTeam/FTB-Chunks/pull/214
- https://github.com/FTBTeam/FTB-Essentials/pull/35

My server need this integration too. It work like a charm on forge. It use luckperms meta to custom number of chunks claims or home.

**Comment by MichaelHillcox** [comment]
I'll review your pr in the coming days :+1:

**Comment by Yann151924** [comment]
I draft the 2 pr because there is an issue with luckperms when a player is killed and don't respawn but leaving the server.
And i need to put a quick refacto for removing a minor issue fixed in local.

**Comment by Yann151924** [comment]
I undraft the two pr, i made a "work around" with a try-catch. That's not sexy but until luckperms look into this that fix the crash problem.
For better understanding i reference the problem with an issue and this is like a edge case problem. I nearly haven"t the problem on my server with a custom build

**Comment by burg5204** [comment]
Any update on this Request?

**Comment by Yann151924** [comment]
For me it's ok, just waiting a review. I have a custom build for almost two or three month on two servers and i don't have any bug :).

**Comment by desht** [comment]
Sorry for the delay, but I've reviewed this and don't see any problems.  Will get it merged in the very near future.

I'll also get this into the 1.19.2 version of FTB Essentials (which is now our primary development focus).

**Comment by desht** [comment]
Luckperms support is now in FTB Essentials.
