### ISSUE TITLE
[Bug]: Dublication all block on server

### ISSUE THREAD

**Issue by Tupilak** [FTBTeam/FTB-Mods-Issues#288]
### Mod

FTB Teams (Fabric)

### Mod version

 ftb-teams-fabric-1802.2.6-build.51.jar

### Forge / Fabric version

Fabric API 0.53.4+1.18.2

### Modpack & version

Benchmark II - 1.18

### What issue are you having?

When I place a block in clamed chunk the block is placed and I also have it in my back. The owner can havest the block and now also have it.

### Steps to reproduce

1. Clame a chunk
2. Set the premission that other can interact with door and chest
3. Get other player to place a block
4. Get the player that place to refress his stack, by moving it and see that the item is still in his inventory
5. You can havest the block, so you both have it.

### Anything else to note?

Only work on multiplayer server.

**Comment by Raidobw2** [comment]
Thanks for the report, I'll keep #315 only for our mod developers to track the issue
