### ISSUE TITLE
[Bug]: disable_protection: true doesn't work

### ISSUE THREAD

**Issue by TupacTheLazy** [FTBTeam/FTB-Mods-Issues#292]
### Mod

ftb chunks

### Mod version

ftb-chunks-forge-1802.3.6-build.145

### Forge / Fabric version

1.18.2 - 40.1.31

### Modpack & version

Only ftb chunks + dependencies

### What issue are you having?

Setting the option disable_protection: true in ftbchunks.snbt from the serverconfig folder doesn't work, the mod still prevents mob griefing and such.

### Steps to reproduce

edit the config
enter the game
claim the chunk
explode a creeper
no block destroyed

**Comment by Raidobw2** [comment]
I'll keep only #329 for our mod developers to avoid redundancy, since the issues are the same. Thanks for reporting
