### ISSUE TITLE
[Feature Request]: Config to disable ore generation

### ISSUE THREAD

**Issue by XXxinsanityxX** [FTBTeam/FTB-Mods-Issues#293]
### Mod

FTB Industrial Contraptions

### Description

Seemingly there's no way to disable the ore generation added by FTBIC

### Describe the solution you'd like

A config option to disable each of the ores added by FTBIC from generating

**Comment by Raidobw2** [comment]
I've kept #297 only to track this request for our mod developers. Thanks for reporting!
