### ISSUE TITLE
[Feature Request]: Remove deathpoints when near

### ISSUE THREAD

**Issue by row454** [FTBTeam/FTB-Mods-Issues#294]
### Mod

FTB Chunks

### Description

FTB Chunks should add a setting to remove deathpoint when near to them. This is more convenient than removing them manually. Journeymap has this feature, so it would be nice to have in FTB Chunks

**Comment by desht** [comment]
Fixed in 1.18/1.19

See the new "Auto-remove deathpoint distance" setting in the map settings screen.  Set this to any value >0 to enable auto-removal of deathpoints when near.
