### ISSUE TITLE
[Bug]: Quest creation preview not highlighting

### ISSUE THREAD

**Issue by vizthex123** [FTBTeam/FTB-Mods-Issues#295]
### Mod

FTB Quests

### Mod version

ftb-quests-forge-1802.3.8-build.101

### Forge / Fabric version

Forge 40.1.31

### Modpack & version

Custom, Minecraft 1.18.2

### What issue are you having?

When I go to create a quest, it doesn't highlight the area like it does in older version - making quest planning a bit annoying.

### Steps to reproduce

1. Load a 1.18 modpack
2. Try to make a quest
3. You should notice that there isn't a preview highlight like the 1.12 version had

### Anything else to note?

There's a typo at the end of this bug report forum - it says "but due to time and technical limitations, it my not be possible to solve your issue.", but it should be *may*, not "my"

**Comment by desht** [comment]
Duplicated by #356 which is fixed in dev and will be in next FTB Quests release (soon).  Closing this.
