### ISSUE TITLE
[Feature Request]: Re-add the multi-item feature from 1.12

### ISSUE THREAD

**Issue by vizthex123** [FTBTeam/FTB-Mods-Issues#296]
### Mod

FTB  Quests

### Description

In the 1.12 versions of the mod, you can set multiple accepted items for a single item task, but that is absent in the 1.13+ versions of the mod. It'd be nice to have it back.

### Describe alternatives you've considered

I could use tags, but it's annoying to add a new tag that only ever gets used once.

**Comment by Raidobw2** [comment]
Could be implemeted in compliment with https://github.com/FTBTeam/FTB-Mods-Issues/issues/37

**Comment by MichaelHillcox** [comment]
You can do this via ItemFilters using an OR filter

**Comment by vizthex123** [comment]
Entirely forgot about that mod ngl. Guess I'll try it out.
