### ISSUE TITLE
[Bug]: ftb quest to get the item can't detect nbt correctly

### ISSUE THREAD

**Issue by LILPRINCES** [FTBTeam/FTB-Mods-Issues#300]
### Mod

FTBquest

### Mod version

ftb-quests-forge-1605.3.6-build.98

### Forge / Fabric version

1.16.5 Forge 36.2.34

### What issue are you having?

The ftb quest to get the item can't detect nbt correctly, I make a quest that needs to get the specified nbt item to complete, but I can also complete the quest when I get the item without nbt.

### Steps to reproduce

Make a quest to get nbt items.

**Comment by Raidobw2** [comment]
Hello, sorry for the delay, what does your quest look like? (the code/configuration & nbt stuff)

**Comment by Raidobw2** [comment]
I'll keep just https://github.com/FTBTeam/FTB-Mods-Issues/issues/182 for tracking, for our mod dev
