### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by vizzair** [FTBTeam/FTB-Mods-Issues#301]
### Mod

ftb industrial contraptions

### Mod version

ftb industrial contraptions 1802.1.5-build.149

### Forge / Fabric version

forge 40.1.47

### Modpack & version

ftb presents direwolf20 1.18

### What issue are you having?

none of the  solar panels seem to generate energy when located in the mining dimension.
These all work fine in the overworld.

### Steps to reproduce

simply teleport to mining dimension and place solar panels on ground.

**Comment by MichaelHillcox** [comment]
This is down to how the mining dimentions define how light works. This isn't an issue on our side.
