### ISSUE TITLE
[Bug]: FTB Chunks crash when pressing M setFullscreen

### ISSUE THREAD

**Issue by Infernalized** [FTBTeam/FTB-Mods-Issues#304]
### Mod

FTB Chunks

### Mod version

ftb-chunks-forge-1802.3.6-build.147

### Forge / Fabric version

1.18.2 Forge-40.1.51

### What issue are you having?

Game crash on pressing M to open map.

### Crashlogs

Crash Log https://pste.ch/lodakubozi.rb

### Steps to reproduce

Log into server and press 'M' to open map

### Anything else to note?

 I have already checked previous closed issues and have made sure I have latest version on client and server. I do also have latest FTB Library 'ftb-library-forge-1802.3.6-build.123'

**Comment by Raidobw2** [comment]
Linked with https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1040 from the modpack tracker which contains more information on this issue as well

**Comment by Raidobw2** [comment]
We found out in https://github.com/FTBTeam/FTB-Modpack-Issues/issues/996 this happens if the server is running vanilla Minecraft, make sure you're using the Forge jar to start the server and not minecraft_server.jar
