### ISSUE TITLE
[Bug]: FTBRanks - Users can only see their own rank chat color and rank name format

### ISSUE THREAD

**Issue by sprocketaudio** [FTBTeam/FTB-Mods-Issues#308]
### Mod

FTBRanks

### Mod version

ftb-ranks-forge-1802.1.8-build.34

### Forge / Fabric version

40.1.31

### Modpack & version

ATM7 0.4.9

### What issue are you having?

Users can only see their own rank color and rank name format in chat (all other users appear normal or white).

In the following 2 pics, you can see in the first pic the user Vladisomire appearing as white and without the Admin tag he should have (which the 2nd pic shows he has from his chat) - This is happening with all ranks levels.

![image](https://user-images.githubusercontent.com/13222732/173249693-7cd6cc77-0fe6-49c1-afd3-ea59bcdb2f04.png)
![image](https://user-images.githubusercontent.com/13222732/173249697-8a20e3c7-177d-432a-bca4-75ff9b213adc.png)

{
	member: {
		name: "Member"
		power: 1
		ftbchunks.max_claimed: 100
		ftbchunks.max_force_loaded: 5
		command.back: false
		command.warp: false
		command.setwarp: false
		command.nickname: false
	}
	vip: {
		name: "VIP"
		power: 30
		ftbranks.name_format: "<&2VIP - {name}&r>"
		ftbchunks.max_claimed: 150
		ftbchunks.max_force_loaded: 7
		command.nickname: false
		command.back: true
		command.warp: false
		command.setwarp: false
	}
	vip_plus: {
		name: "VIP+"
		power: 40
		ftbranks.name_format: "<&6VIP+ - {name}&r>"
		command.nickname: false
		command.back: true
		command.warp: true
		command.warp.name: true
		command.setwarp: true
		command.setwarp.name: true
		ftbchunks.max_claimed: 200
		ftbchunks.max_force_loaded: 10
	}
	vip_special: {
		name: "VIP+Special"
		power: 50
		command.fly: true
	}
	legend: {
		name: "Legend"
		power: 60
		ftbranks.name_format: "<&dLegend - {name}&r>"
		command.nickname: true
		command.back: true
		command.warp: true
		command.warp.name: true
		command.setwarp: true
		command.setwarp.name: true
		ftbchunks.max_claimed: 250
		ftbchunks.max_force_loaded: 13
	}
	titan: {
		name: "Titan"
		power: 70
		ftbranks.name_format: "<&4Titan - {name}&r>"
		command.nickname: true
		command.back: true
		command.warp: true
		command.warp.name: true
		command.setwarp: true
		command.setwarp.name: true
		ftbchunks.max_claimed: 300
		ftbchunks.max_force_loaded: 16
		command.cofh.enderchest: true
	}
	mascot: {
		name: "Mascot"
		power: 70
		ftbranks.name_format: "<&aMascot - {name}&r>"
		command.nickname: true
		command.back: true
		command.warp: true
		command.warp.name: true
		command.setwarp: true
		command.setwarp.name: true
		ftbchunks.max_claimed: 300
		ftbchunks.max_force_loaded: 16
		command.cofh.enderchest: true
	}
	mythic: {
		name: "Mythic"
		power: 80
		ftbranks.name_format: "<&5Mythic - {name}&r>"
		command.nickname: true
		command.back: true
		command.warp: true
		command.warp.name: true
		command.setwarp: true
		command.setwarp.name: true
		ftbchunks.max_claimed: 400
		ftbchunks.max_force_loaded: 20
		command.cofh.enderchest: true
		command.gamemode.spectator: true
		command.gamemode.survival: true
	}
	admin: {
		name: "Admin"
		power: 1000
		condition: "op"
		ftbranks.name_format: "<&eAdmin - {name}&r>"
		command.back: true
		command.warp: true
		command.setwarp: true
		ftbchunks.max_claimed: 500
		ftbchunks.max_force_loaded: 20
	}
}

### Steps to reproduce

Creat 2 ranks with a chat color and name format.

Aply to 2 users and ask them to talk in chat. Each user will only sede theior own collor and name format.

**Comment by phit** [comment]
some more info in https://github.com/FTBTeam/FTB-Modpack-Issues/issues/938 aswell, something is definitely broken if it helps any this started on the 9th of June for us without any modpack changes!

**Comment by Yertled** [comment]
Same issue with my network.

**Comment by phit** [comment]
it's a Forge issue https://github.com/MinecraftForge/MinecraftForge/issues/8729

**Comment by Raidobw2** [comment]
Is this still an issue even with the newest Forge version? Thanks for any help / feedback in advance!

**Comment by phit** [comment]
no, this was fixed by Forge

**Comment by Raidobw2** [comment]
Alrighty, I'll go ahead and close this then. Thanks for the follow up and the previous report to Forge!
