### ISSUE TITLE
[Bug]: FTB Chunks Spectator access

### ISSUE THREAD

**Issue by Saereth** [FTBTeam/FTB-Mods-Issues#311]
### Mod

ftb chunks

### Mod version

ftb-chunks-forge-1900.3.7-build.148

### Forge / Fabric version

41.0.22

### Modpack & version

FTB One pre release

### What issue are you having?

When in spectator, if you're not in a claimed chunk and right click a chest, you get read-only access to that chest, being able to view all the contents inside without being able to manipulate them.
However, if you are in a claimed chunk, you are not able to view inside of the chests.

### Crashlogs

N/A

### Steps to reproduce

Try viewing a chest in spectator mode, in a claimed chunk that's not owned by you.

**Comment by MichaelHillcox** [comment]
Fixed and being shipped atm
