### ISSUE TITLE
[Bug]: Waypoints not showing on World Map or Minimap

### ISSUE THREAD

**Issue by e-SonOfAnder** [FTBTeam/FTB-Mods-Issues#313]
### Mod

FTB Chunks

### Mod version

1802.3.6-build.145

### Forge / Fabric version

40.1.47

### Modpack & version

FTB Presents Direwolf20 1.18

### What issue are you having?

Waypoints do not show up on the world map or the minimap. They only show up in world, This means there is no way to modify or remove waypoints, as it can only be done via mouse interaction on the world map. (No menu to show / modify waypoints, and no hotkey to do so either.)

### Steps to reproduce

1. Open the world map (default key 'm')
2. Right click somewhere in the map, and select 'Add Waypoint' (Alternately, click the plus button on the left of the screen to add a waypoint to the location the player is at.)
3. Give the waypoint a name and hit Add
4. See the waypoint in the world
5. See the waypoint does not show up in the minimap
6. Open the world map again
7. See the waypoint does not show in the world map

Screenshots showing the issue: (these are from the nether, but this happens in both overworld and nether - cannot confirm The End, but suspect the problem exists there as well)
![2022-06-13_21 35 57](https://user-images.githubusercontent.com/4420108/173494249-b39a2cb4-a983-4ac2-b408-20b8d0140bb6.png)
![2022-06-13_21 35 50](https://user-images.githubusercontent.com/4420108/173494252-25efb327-aa42-4ba2-b15b-dc38a483961f.png)

**Comment by MichaelHillcox** [comment]
Are you running optifine? This is a strange issue

**Comment by e-SonOfAnder** [comment]
No, no optifine or anything. I ended up having to completely delete the instance from my PC and redownload the pack, and that fixed the issue. Thankfully making a backup of the save folder kept all of the important information.
