### ISSUE TITLE
[Bug]: FTB Rank network.chat Error

### ISSUE THREAD

**Issue by molefool** [FTBTeam/FTB-Mods-Issues#316]
### Mod

FTB Rank 

### Mod version

FTB Rank 1802.1.8-build.34

### Forge / Fabric version

minecraft:1.18.2  Forge:40.1.31

### What issue are you having?

My chat bar cannot be used. Any normally entered text will not be displayed and an error will be reported in the background.

### Crashlogs

https://coracles-my.sharepoint.com/personal/admin_coracles_onmicrosoft_com/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fadmin%5Fcoracles%5Fonmicrosoft%5Fcom%2FDocuments%2FREADME%2Etxt&parent=%2Fpersonal%2Fadmin%5Fcoracles%5Fonmicrosoft%5Fcom%2FDocuments&ga=1

### Steps to reproduce

I don't know how to reproduce it, but I will provide all my information
V：forge arclight 1.05
mod list：TofuCraftReload-1.18.2-1.0.1.0.jar	15.7 MB	2022/6/13 20:15:14
3dskinlayers-forge-1.4.6-mc1.18.2.jar	430 kB	2022/6/12 11:55:12
flowingagony-1.18.2-1.2.5.jar	450 kB	2022/6/12 11:22:53
BiomesOPlenty-1.18.2-16.0.0.134.jar	20.3 MB	2022/6/13 20:38:08
waystones-forge-1.18.2-10.1.0.jar	349 kB	2022/6/14 15:29:12
 Mantle-1.18.2-1.9.27.jar	895 kB	2022/6/14 11:00:23
flywheel-forge-1.18-0.6.2.jar	1.2 MB	2022/6/12 10:25:12
 ToolBelt-1.18.2-1.18.8.jar	245 kB	2022/6/13 20:26:09
mmlib-1.0.2-1.18.2.jar	255 kB	2022/6/13 20:33:05
MyServerIsCompatible-1.18-1.0.jar	3.3 kB	2022/6/14 09:33:12
Paraglider-1.18.2-1.6.0.0.jar	394 kB	2022/6/13 21:28:59
create-stuff-additions1.18.2_v1.1.6.jar	614 kB	2022/6/13 20:24:03
create-mc1.18.2_v0.4.1.jar	11.5 MB	2022/6/12 10:25:20
create-confectionery1.18.2_v1.0.8.jar	2.2 MB	2022/6/13 22:09:50
 stalwart-dungeons-1.18.2-1.2.2.jar	1.2 MB	2022/6/12 10:55:03
 TConstruct-1.18.2-3.5.1.31.jar	12.5 MB	2022/6/14 11:00:16
 sophisticatedbackpacks-1.18.2-3.17.4.592.jar	692 kB	2022/6/12 10:36:33
sophisticatedcore-1.18.2-0.3.1.39.jar	857 kB	2022/6/12 10:36:54
 krypton-0.1.10-SNAPSHOT.jar	140 kB	2022/6/12 11:14:44
 Quark-3.2-357.jar	13.1 MB	2022/6/13 21:43:04
]AutoRegLib-1.7-53.jar	41.7 kB	2022/6/13 21:43:10
moreminecarts-1.4.6.jar	673 kB	2022/6/12 11:48:53
twilightforest-1.18.2-4.1.1102-universal.jar	31.4 MB	2022/6/14 15:33:39
FarmersDelight-1.18.2-1.1.1.jar	2.5 MB	2022/6/12 10:31:07
configured-1.5.3-1.18.2.jar	136 kB	2022/6/13 21:58:06
TerraBlender-forge-1.18.2-1.1.0.102.jar	96.7 kB	2022/6/13 20:38:21
 rubidium-0.5.2a.jar	1.3 MB	2022/6/13 22:25:43
rubidium_extras-1.18.2_v1.3.1.jar	59.6 kB	2022/6/14 09:49:54
toms_storage-1.18.2-1.3.2.jar	346 kB	2022/6/14 09:45:34
ferritecore-4.2.1-forge.jar	114 kB	2022/6/12 11:58:42
JustEnoughCharacters-1.18.1-4.3.3.jar	263 kB	2022/6/12 11:56:20
CopperAndCrystal-MC1.18.2-1.0.3.jar	822 kB	2022/6/13 21:39:06
ModernUI-1.18.2-3.4.6.107-universal.jar	14.3 MB	2022/6/12 11:20:43
Jade-1.18.2-forge-5.2.1.jar	291 kB	2022/6/12 10:27:48
JadeAddons-1.18.2-2.0.0.jar	15.4 kB	2022/6/12 10:27:58
supplementaries-1.18.2-1.4.3.jar	12.8 MB	2022/6/12 11:10:26
selene-1.18.2-1.17.6.jar	443 kB	2022/6/12 11:10:07
 steampowered-1.18.2-2.0.3-alpha.jar	254 kB	2022/6/12 11:08:56
 NaturesCompass-1.18.2-1.9.5-forge.jar	199 kB	2022/6/12 11:48:11
JEIEnchantmentInfo-1.17.1-2.0.0.jar	30.7 kB	2022/6/13 21:40:51
jei-1.18.2-9.7.0.196.jar	970 kB	2022/6/13 21:40:43
YungsBridges-1.18.2-Forge-2.1.0.jar	1.0 MB	2022/6/13 20:16:54
【测试】architectury-4.4.71.jar	534 kB	2022/6/15 08:06:08
【测试】ftb-chunks-forge-1802.3.6-build.147.jar	724 kB	2022/6/15 08:39:24
【测试】ftb-essentials-1802.1.7-build.42.jar	76.9 kB	2022/6/15 08:05:49
【测试】ftb-library-forge-1802.3.6-build.123.jar	562 kB	2022/6/15 08:05:58
【测试】ftb-teams-forge-1802.2.6-build.51.jar	164 kB	2022/6/15 08:38:56
YungsBetterMineshafts-1.18.2-Forge-2.1.3.jar	264 kB	2022/6/13 20:26:30
YungsBetterStrongholds-1.18.2-Forge-2.1.1.jar	579 kB	2022/6/13 20:26:44
YungsBetterWitchHuts-1.18.2-Forge-1.0.jar	146 kB	2022/6/14 19:02:36
YungsExtras-1.18.2-Forge-2.1.0.jar	848 kB	2022/6/13 20:27:13

**Comment by molefool** [comment]
FTBRank has been deleted

**Comment by Raidobw2** [comment]
Hi, sorry for the delay! May I ask if you would be able to drop the crash log here as a text file? (drag and drop the file to this window) This would help, thanks!

**Comment by MichaelHillcox** [comment]
No reply, closing
