### ISSUE TITLE
[Bug]: Zaps cables cannot connect and power machines that require FE or RF

### ISSUE THREAD

**Issue by Leclowndu93150** [FTBTeam/FTB-Mods-Issues#320]
### Mod

FTB IC

### Mod version

ftb-industrial-contraptions-1802.1.6-build.182

### Forge / Fabric version

1.18.2 40.1.31

### What issue are you having?

![2022-06-20_10 12 43](https://user-images.githubusercontent.com/73310949/174558306-6a11638f-c8ec-4d4f-b4a8-610ca443486b.png)

### Steps to reproduce

Try to connect a FTBIC cable to an Thermal energy cell or flux point

**Comment by Leclowndu93150** [comment]
The induction cell one works

**Comment by MichaelHillcox** [comment]
I'll see what can be done about this :+1:

**Comment by github-fave** [comment]
+1 for the feature request, as I like this mod but I think exactly this holds it back from becoming a truly great one.

**Comment by TheSniper19902** [comment]
It seems Zaps now convert to FE/RF, but not the other way around.
Is there a way to convert this? By example power the macerator with FE/RF?

**Comment by exetico** [comment]
> The induction cell one works

This is the answer right now.

Here's our journey for powering the AE2 stuff... Damn :upside_down_face: 
LV Battery Box > Basic Energy Cube (or simular) > Energy Acceptor (for AE2) > ME Controller

**Comment by Raidobw2** [comment]
Linked with https://github.com/FTBTeam/FTB-Mods-Issues/issues/370

**Comment by Raidobw2** [comment]
I'll assume Zaps => FE have been implemented, so the issue would remain with powering an energy acceptor properly now.

I'll close this since the main issue seems solved (conversion), for the AE2 problem we'll track this at https://github.com/FTBTeam/FTB-Mods-Issues/issues/476

If I'm wrong, them let me know please and thanks
