### ISSUE TITLE
[Bug]: Changing Values in the Config files dont work

### ISSUE THREAD

**Issue by Leclowndu93150** [FTBTeam/FTB-Mods-Issues#321]
### Mod

FTB IC

### Mod version

ftb-industrial-contraptions-1802.1.6-build.182

### Forge / Fabric version

1.18.2 40.1.31

### What issue are you having?

![2022-06-20_11 58 00](https://user-images.githubusercontent.com/73310949/174577336-1a94e199-80f8-4d1f-845f-fefa04a2c8f0.png)
![unknown](https://user-images.githubusercontent.com/73310949/174577396-31cccc7e-5d6c-4588-9e7a-82d012daeb39.png)

### Steps to reproduce

change config

**Comment by MichaelHillcox** [comment]
I'll look into this, thanks for the report

**Comment by MichaelHillcox** [comment]
Fixed as of the latest 1.18 + 1.19 versions. Please note that we've moved over to `.snbt` files meaning if you've made any config changes, you'll need to convert these to the new file.
