### ISSUE TITLE
[Bug]: Gamestage Reward for FTB Quests doesn't work

### ISSUE THREAD

**Issue by SuddenlySentient** [FTBTeam/FTB-Mods-Issues#324]
### Mod

FTB Quests

### Mod version

ftb-quests-forge-1802.3.8-build.101.jar

### Forge / Fabric version

1.18.2 Forge 40.1.51

### What issue are you having?

The Gamestage reward for FTB Quests does not give the player who got it the Gamestage they were supposed to be rewarded, it might say it in chat but doing /gamestage info reveals that no Gamestage has been given

### Steps to reproduce

1. Have a Quest with the Gamestage reward
2. complete the quest (cand claim it if it needs to be claimed first)

**Comment by SuddenlySentient** [comment]
![Screenshot 2022-06-23 235804](https://user-images.githubusercontent.com/53958806/175459633-dcdba240-16c6-4084-bca7-03c3149eb190.jpg)

**Comment by Raidobw2** [comment]
Sorry for the delay! What's your command reward looking like?

**Comment by MichaelHillcox** [comment]
No reply, closing
