### ISSUE TITLE
[Bug]: Wither duplicates blocks

### ISSUE THREAD

**Issue by DrebisDavid** [FTBTeam/FTB-Mods-Issues#328]
### Mod

Progressive bosses

### Mod version

3.5.14

### Forge / Fabric version

1.18.2

### Modpack & version

FTB Presents Direwolf20 1.18

### What issue are you having?

The attack when the wither becomes purple and destroys blocks can duplicate items. I have tested it with a botania bellethorn + manapool which duped, a thermal expansion redstone furnace and also a mekanism wind generator which also duped.

### Steps to reproduce

1. Spawn wither
2. Wait for purple charge up
3. Place blocks to dupe before explosion in the vicinity
4. Profit

### Anything else to note?

I filmed a clip but it was too big to share but i will keep it if more info is needed.

**Comment by MichaelHillcox** [comment]
Not our mod, please request this from the actual mod author, this tracker is for FTB Mods. If you believe this to be a modpack issue (aka, you made no changes to an FTB Modpack, then please report it here https://github.com/FTBTeam/FTB-Modpack-Issues/issues)
