### ISSUE TITLE
[Bug]: Crash on world load after update

### ISSUE THREAD

**Issue by Albertostadas** [FTBTeam/FTB-Mods-Issues#331]
### Mod

Tesla core lib registries, tesla core lib, AE2 Unofficial extended life

### Mod version

tesla-core-lib-1.12.2-1.0.17 

### Forge / Fabric version

14.23.5.2847

### Modpack & version

FTB: Interactions

### What issue are you having?

After updating the modpack from 2.0.9 to 2.12.1 a crash happens everytime I try to load a save,
![5e30f6119725d85721563d63bc5587e6](https://user-images.githubusercontent.com/12597884/176057754-34a0497c-a60e-46e1-8998-1add934b7010.png)
 

### Crashlogs

https://pste.ch/ivaraveran.rb
https://pste.ch/awosojemuz.rb
https://pste.ch/awexorecuk.rb

### Steps to reproduce

1. Start a world in a version prior to version 2.12.0
2. Update the modpack to version 2.12.1
3. Try to load said world

### Anything else to note?

After updating I also got some missing registries from little tiles, but I think i also got those when updating to prior versions
![1fe1dfd5cedb5bf9648ae3cd89f9af80](https://user-images.githubusercontent.com/12597884/176058540-487e0291-a2f2-48fa-ab7b-2b4fc77140fa.png)

**Comment by MichaelHillcox** [comment]
Not our mod, please request this from the actual mod author, this tracker is for FTB Mods. If you believe this to be a modpack issue (aka, you made no changes to an FTB Modpack, then please report it here https://github.com/FTBTeam/FTB-Modpack-Issues/issues)
