### ISSUE TITLE
[Bug]: Highlight Renders Improperly and Inconsistently

### ISSUE THREAD

**Issue by MinerB4** [FTBTeam/FTB-Mods-Issues#335]
### Mod

FTB Ultimine

### Mod version

ftb-ultimine-fabric-1900.3.4-build.58.jar

### Forge / Fabric version

1.19.0: Fabric Loader 0.14.8

### Modpack & version

Custom

### What issue are you having?

**Visual Bug**
Ultimine Highlight does not render in the correct position, but will do so if Hide GUI (F1) is enabled...
It has minimal effect to gameplay however is still weird to see.

CurseForge Custom Modpack Export:
https://drive.google.com/file/d/1YygpF6uHwzvHJl6oNHRDywqlc7Rwc-GK/view?usp=sharing

![2022-06-30_09 14 49](https://user-images.githubusercontent.com/70791904/176687393-cb2194c5-3457-4818-ac7b-93045b226e25.png)
![2022-06-30_09 14 54](https://user-images.githubusercontent.com/70791904/176687398-7e250cc7-05f3-4e02-b1b8-1925a63ed902.png)
![2022-06-30_09 15 01](https://user-images.githubusercontent.com/70791904/176687401-7555d8e2-9771-465d-86e9-651e0825a8a7.png)
![2022-06-30_09 15 04](https://user-images.githubusercontent.com/70791904/176687404-fdbe7e5a-1cba-4458-b7b2-419a35e368d7.png)

### Steps to reproduce

1. Load Modpack
2. Start Minecraft
3. Suffer in Silence as the loading bar reaches 100% but does not finish...
4. Start a brand new Minecraft world with high hopes of magic and adventure
5. Stare at a block while pressing **Grave**...
6. "... wait, why's the highlight in the floor?"

**Comment by MichaelHillcox** [comment]
Does it happen without shaders?

**Comment by Raidobw2** [comment]
I'll keep only #341 for our mod developer to avoid redundancy. Thanks for reporting
