### ISSUE TITLE
Allow us to make a new reward table from the rewards menu

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-Mods-Issues#34]
![image](https://user-images.githubusercontent.com/15698722/59298035-3ae67e80-8c4f-11e9-8f9b-49abba4207d8.png)
We should be able to make a new reward table here

**Comment by Raidobw2** [comment]
It's possible to do that now:
![image](https://user-images.githubusercontent.com/17010632/137678705-13f754d5-aa17-476a-9354-d7d874e70d92.png)

**Comment by aaronhowser1** [comment]
Isn't Edit Reward Table like... for editing the reward table? Or was it changed to changing the reward table it's a part of?

**Comment by MichaelHillcox** [comment]
I think this is fixed in later versions, let me know if it isn't
