### ISSUE TITLE
Random crash when opening FTB Chunks map

### ISSUE THREAD

**Issue by RadonCoding** [FTBTeam/FTB-Mods-Issues#340]
### Mod

FTB Chunks

### Mod version

ftb-chunks-forge:1605.3.2-build.115

### Forge / Fabric version

Forge - 1.16.5 36.2.34

### What issue are you having?

Joined my minecraft world couldn't see the minimap then pressed M and got a crash

### Crashlogs

https://paste.feed-the-beast.com/view/0343b289

### Steps to reproduce

This is the first time this crash happened and didn't happen afterwards.
1. Join a world
2. Don't see minimap
3. Press M
4. Client side crash

**Comment by RadonCoding** [comment]
I want to note this crash is actually now happening everytime i join my world and try to open the map. I thought it was a random crash since i didn't do any changes.

**Comment by RadonCoding** [comment]
Crash stopped happening after restarting server.

**Comment by Raidobw2** [comment]
Linked to #70

**Comment by Raidobw2** [comment]
I'll keep only #70 as a way to track this issue for our mod developer. Thanks for the report
