### ISSUE TITLE
[Feature Request]: Redstone interactions for some FTB:IC machines

### ISSUE THREAD

**Issue by vikanezrimaya** [FTBTeam/FTB-Mods-Issues#348]
### Mod

FTB Industrial Contraptions

### Description

In the mod that FTB:IC was inspired from, Nuclear Reactors (and some other machines) had the ability to be controlled using Redstone. From my experiments in Creative Mode, it doesn't seem like this Nuclear Reactor can be controlled using Redstone, which limits its usefulness as a relatively long-lived high-power generator.

Possible use-cases for redstone control include:
 - Powering a small automated processing plant using a single reactor with a few cells and using Comparators to detect a Battery Box/other energy storage fill level
 - Disabling a high-risk reactor for a cooldown using a timer
 - Having a cut-off lever for energy generation in case of mishaps

### Describe the solution you'd like

Redstone enables a paused Nuclear Reactor. If the Nuclear Reactor was launched from the UI (possibly could be controlled using a new button), a redstone signal disables the reactor instead.

(If not implemented yet) Energy-distributing blocks (Battery boxes, MFEs and such) output their energy fill level through a comparator.

### Describe alternatives you've considered

- Manually monitoring a reactor
  - Tedious and boring
  - Infeasible when reactor is running in an SMP environment/unattended
  - Prone to human mistakes, examples: (thankfully fictional... for now!)
    - forgot to turn off the reactor and went mining, reactor was chunkloaded and highly unstable, returned to a crater in the ground instead of the base
    - Too much power generated after a processing plant got clogged with items/finished its work, wasted uranium

**Comment by MichaelHillcox** [comment]
Added as of  FTBTeam/FTB-Industrial-Contraptions#26 (it'll be released soon and ported to 1.19, later on)
