### ISSUE TITLE
[Bug]: The Reactor tries to output its entire buffer at once, even if that's >IV

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-Mods-Issues#349]
### Mod

FTB Industrial Contraptions

### Mod version

1.18 dev environment

### Forge / Fabric version

40.1.51

### What issue are you having?

![image](https://user-images.githubusercontent.com/15698722/178099069-a6bf0df6-ced0-4a72-9905-1aceb9ad63ce.png)

![image](https://user-images.githubusercontent.com/15698722/178099078-19e0929e-98c7-402f-b8ab-ce19cbf0541f.png)
This Reactor was going for a while with no cables connected to it, building up a buffer of >8,192 Zaps. When I try to send this power to an EV transformer, it burns since it can only handle up to IV.

### Steps to reproduce

1. Make Reactor
2. Let Reactor build up big buffer
3. Try to send it to something
4. Fail

**Comment by MichaelHillcox** [comment]
Can you show me how you've setup the reactor?

**Comment by Qysher** [comment]
Had the same issue today.

Mod Version: 1802.1.6-build.182 (Curseforge)
Enviroment: Modded Forge Server

I also tried placing the reactor last with no success. It worked for a few seconds and then the fuse blew.

![image](https://user-images.githubusercontent.com/33176595/178178542-f2c07721-3da2-47e7-b402-5c1d4e38617f.png)
![image](https://user-images.githubusercontent.com/33176595/178178573-142319d3-2137-4a1c-b270-246af5f578cc.png)

https://i.imgur.com/pLrDA88.mp4

**Comment by MichaelHillcox** [comment]
Should be fixed as of https://github.com/FTBTeam/FTB-Industrial-Contraptions/commit/28e34fbf2803bf61b981cc16caa1bba7df06ea1c (releasing atm)
