### ISSUE TITLE
[Bug]: Nuke Arrows only work on hitting a block, not an entity

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-Mods-Issues#350]
### Mod

FTB Industrial Contraptions

### Mod version

1.18 dev environment

### Forge / Fabric version

40.1.51

### What issue are you having?

Title

### Steps to reproduce

Shoot a mob with a Nuke Arrow

**Comment by MichaelHillcox** [comment]
Fixed as of https://github.com/FTBTeam/FTB-Industrial-Contraptions/commit/ae7099a56a9a983fc16a59e4c79e22c1e789585e (releasing soon, already on maven)
