### ISSUE TITLE
[Bug]: Autp Pin not doing anything

### ISSUE THREAD

**Issue by Deragonis** [FTBTeam/FTB-Mods-Issues#354]
### Mod

FTB Quests

### Mod version

ftb-quests-forge-1802.3.8-build.101

### Forge / Fabric version

1.18.2 40.1.52

### Modpack & version

Skyopolis 5 - 1.0

### What issue are you having?

clicking on the [Auto-pin: Disabled] button does not pin anything, I quite enjoy having the quest log on the side of the screen, and manually pinning every quest as I'm going through then has been getting tedious.

### Steps to reproduce

1. I click on the Auto-pin button
2. nothing happens

**Comment by desht** [comment]
Implemented for 1.18 & 1.19
