### ISSUE TITLE
[Bug]: E is not confirm in some menus in FTB Quests

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-Mods-Issues#355]
### Mod

FTB Quests

### Mod version

ftb-quests-forge-1802.3.8-build.101

### Forge / Fabric version

Forge 1.18.2 40.1.60

### What issue are you having?

I'll add to the list as I discover them:

![image](https://user-images.githubusercontent.com/15698722/178915556-839072e8-997a-4c1d-8c96-bee9730953f7.png)
![image](https://user-images.githubusercontent.com/15698722/178915696-e7a28d86-50f5-4e10-86e1-1254aa2f423e.png)
The set item menu, in icons and item tasks

### Steps to reproduce

Go to that menu, change from what it is, hit E to confirm, see it not be saved

**Comment by desht** [comment]
Needs a fix in FTB Library (`SelectItemStackScreen`).
