### ISSUE TITLE
[Bug]: FTB Quests doesn't remember List Mode when closed

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-Mods-Issues#359]
### Mod

FTB Quests

### Mod version

ftb-quests-forge-1802.3.8-build.101

### Forge / Fabric version

Forge 1.18.2 40.1.60

### What issue are you having?

![image](https://user-images.githubusercontent.com/15698722/178934868-6c8cdab1-8088-4b5a-8877-ad8e93d11889.png)

When I close this menu and then reopen it, it should stay on the List Mode it was on. Instead, I have to click it twice, from REI to All Items to Inventory, every single time.

### Steps to reproduce

N/A

**Comment by desht** [comment]
Fix needs to be in FTB Library (`SelectItemStackScreen`).

**Comment by desht** [comment]
Implemented for 1.18 & 1.19
