### ISSUE TITLE
[Bug]: Reward Table GUI squished

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-Mods-Issues#360]
### Mod

FTB Quests

### Mod version

ftb-quests-forge-1802.3.8-build.101

### Forge / Fabric version

Forge 1.18.2 40.1.60

### What issue are you having?

![image](https://user-images.githubusercontent.com/15698722/178935142-80933905-180f-465d-a84f-2f397274bbdd.png)

I have no idea what caused this, but it only happened after adding Potatoes. Removing them fixed it, and adding it back didn't reproduce the issue.

### Steps to reproduce

N/A

**Comment by aaronhowser1** [comment]
TBH everything to do with Reward Table GUIs looks WAY different than the rest of the mods GUIs

**Comment by desht** [comment]
Implemented for 1.18 & 1.19
