### ISSUE TITLE
[Bug]: FTB Essentials NoClassDefFoundError with recent Forge version

### ISSUE THREAD

**Issue by fpinkela** [FTBTeam/FTB-Mods-Issues#363]
### Mod

FTB Essentials

### Mod version

1900.1.8-build.44

### Forge / Fabric version

forge-1.19-41.0.98

### What issue are you having?

Error when starting up minecraft. This happened after updating from Forge 1.9-63 to the latest Forge Version 98.

### Crashlogs

https://pastebin.com/SaLQXZkZ

### Steps to reproduce

1 Just starting the minecraft client I get this:
FTB Essentials has failed to load correctly
java.lang.NoClassDefFoundError:
net/minecraftforge/event/world/WorldEventSave

**Comment by MichaelHillcox** [comment]
Your forge version is too new, I've fixed this in dev but not released the changes yet

**Comment by fpinkela** [comment]
That's what I figured.
Thanks for the response, just making sure I was correct on that. 
Whenever it's done, it's done. Thanks!

**Comment by Raidobw2** [comment]
I assume this fixed with `ftb-essentials-1900.1.9-build.46.jar`, so I will be closing this issue. Thanks for the report
