### ISSUE TITLE
[Feature Request]: Font support in quests

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-Mods-Issues#365]
### Mod

FTB Quests

### Description

`/tellraw @p {"text": "test", "font": "minecraft:alt"}` gives you a message in enchanting table language. You can also [add custom fonts](https://www.reddit.com/r/Minecraft/comments/8yjroi/how_to_add_a_ttf_font_to_your_resource_pack/), which could be useful.

![image](https://user-images.githubusercontent.com/15698722/179351517-2f2c9a00-b5f7-4c40-908c-a4de149b0298.png)

![image](https://user-images.githubusercontent.com/15698722/179351630-efa0640c-a0d2-4bb1-9187-df31b7bdaed6.png)

**Comment by desht** [comment]
This is now added as part of #495 (raw json support)
