### ISSUE TITLE
[Crash]: FTB essentials server crash (Please I really need this mod to work)

### ISSUE THREAD

**Issue by SsHro** [FTBTeam/FTB-Mods-Issues#367]
### Mod

FTB essentials

### Mod version

ftb-essentials-1900.1.8-build.44

### Forge / Fabric version

forge-1.18.2-40.1.54

### What issue are you having?

The servers opens normally but if I try to connect to the server it crash.

### Crashlogs

https://www.toptal.com/developers/hastebin/etetokiguy.yaml

### Steps to reproduce

Open the server, connect to the server.
Crash.

**Comment by Raidobw2** [comment]
Hello, it appears you are using FTB Essentials for Minecraft 1.19 and running a 1.18.2 Minecraft server. That will not work, you have to use a version for 1.18.2 in that case, please use this build https://www.curseforge.com/minecraft/mc-mods/ftb-essentials-forge/files/3773058.

Once that is sorted out let us know if that was the issue, thanks
