### ISSUE TITLE
[Feature Request]: Automatically unclaim chunks after the player has been offline for a period of time

### ISSUE THREAD

**Issue by official-Cromatin** [FTBTeam/FTB-Mods-Issues#372]
### Mod

FTB Chunks

### Description

When you run larger projects it happens that people stop playing, after a certain amount of time you have to manually unclaim the chunks to make room for other players.

The actual thing I'm getting at is the automatic deforceloading of chunks after the player has been offline for a while.
The whole thing can also be connected to FTB Ranks and then, as with claiming and loading, you can set a time after the chunks are unloaded.

If you are in a team, you could (also via the configs and FTB ranks) set whether this should come into effect, e.g. the creator of the team or the last player was no longer on the server for the specific time

### Describe the solution you'd like

Setting options in the config, via a command and for certain ranks

**Comment by Raidobw2** [comment]
We'll keep only https://github.com/FTBTeam/FTB-Mods-Issues/issues/274 to track this issue, in order to avoid redundancy. Thanks for reporting
