### ISSUE TITLE
[Bug]: Crash with latest version when start game or server (FTB Industrial Contraption)

### ISSUE THREAD

**Issue by Lucreeper74** [FTBTeam/FTB-Mods-Issues#373]
### Mod

FTB Industrial Contraptions (Forge)

### Mod version

ftb-industrial-contraptions-1802.1.6-build.197.jar

### Forge / Fabric version

Forge 1.18.2 40.1.68

### Modpack & version

Toasted Of Tech v0.0.12 (Mine, but tested in alone)

### What issue are you having?

I have crash when started alone in server and solo, same with my modpack (Toasted Of Tech v0.0.12)

Description: Mod loading error has occurred

Check the crash report when launch with Toasted Of Tech modpack (same report without modpack) below

### Crashlogs

https://www.toptal.com/developers/hastebin/ocezihufin.rb

### Steps to reproduce

Just start solo and on server without any another mods.

**Comment by Raidobw2** [comment]
Hi, do you still need help with this? I've loaded your pack from CurseForge and it looks like it's loading fine, I've created a world to make sure as well. Possibly this was fixed in the previous days. Let me know and thanks

**Comment by Lucreeper74** [comment]
No thx, this bug has been fixed with the latest mod update. And then, it's normal that by downloading my modpack you didn't have this error, because I had tested to launch it before publishing it so when I published it I took an earlier version.
