### ISSUE TITLE
[Bug]: Tetra Tools cannot Ultimine when `require_tool` is set to `true` in the config

### ISSUE THREAD

**Issue by NielsPilgaard** [FTBTeam/FTB-Mods-Issues#377]
### Mod

FTB Ultimine

### Mod version

ftb-ultimine-forge-1802.3.3-build.55

### Forge / Fabric version

1.18.2-40.1.68

### Modpack & version

Enigmatica 8 2.1.0

### What issue are you having?

Tetra Tools cannot be used to Ultimine, despite having the required tags to be identified by Ultimine. Please see this issue for all of the context :D

https://github.com/EnigmaticaModpacks/Enigmatica8/issues/182

### Steps to reproduce

1. Make a Tetra shovel in E8
2. Try to ultimine with it
3. Fail

### Anything else to note?

Max told me to come here!!!

**Comment by Raidobw2** [comment]
Thanks for reaching out, I'll transfer relevant information onto #336 to collect info in one spot. You can subscribe to that other issue to get notifications when this is being worked on

**Comment by MichaelHillcox** [comment]
Fixed and shipped for 1.18 + 1.19
