### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by natman121699** [FTBTeam/FTB-Mods-Issues#382]
### Mod

ftb  chunks

### Mod version

FTB chunks forge 1802.3.6

### Forge / Fabric version

1.18.2(40.1.68)

### Modpack & version

personal pack

### What issue are you having?

when ever i click the chunks button it starts a loading screen then crashes to desktop.

### Crashlogs

The game crashed whilst mouseclicked event handler
Error: java.lang.NullPointerException: Cannot invoke "com.mojang.blaze3d.platform.Window.m_85445_()" because "this.screen" is null
error code -1

https://pste.ch/rukiciqoho.rb

### Steps to reproduce

1open inventory
2cliick the ftb chunks icon in the top left

**Comment by Raidobw2** [comment]
Already reported at https://github.com/FTBTeam/FTB-Mods-Issues/issues/379, but thanks for reporting in any case
