### ISSUE TITLE
[Bug]: FTBLibrary generate loot tables throws an error

### ISSUE THREAD

**Issue by Raidobw2** [FTBTeam/FTB-Mods-Issues#384]
### Mod

FTB Library

### Mod version

ftb-library-forge-1900.3.8-build.135.jar

### Forge / Fabric version

1.19 41.1.0

### Modpack & version

N/A

### What issue are you having?

Generating a loot table with FTB Library throws an error due to date format

### Crashlogs

`[28Jul2022 01:09:36.523] [Server thread/ERROR] [FTB Library/]: java.nio.file.InvalidPathException: Illegal char <:> at index 24: loot-chest-2022-07-28T01:09:36.5198095.json`

### Steps to reproduce

1. Fill a chest with random blocks
2. Look at it
3. Run `/ftblibrary generate_loot_tables`
4. Check log for the error

### Anything else to note?

It's not possible to put a ":" in a filename, at least on Windows

**Comment by MichaelHillcox** [comment]
Tested on a Mac, rip, I'll sort that

**Comment by Raidobw2** [comment]
Thanks Mikey :^)

**Comment by MichaelHillcox** [comment]
Fixed and should be releasing now https://github.com/FTBTeam/FTB-Library/actions/runs/2955540940
