### ISSUE TITLE
[Feature Request]: adding compatibility support

### ISSUE THREAD

**Issue by SGZ-Creations** [FTBTeam/FTB-Mods-Issues#385]
### Mod

FTB Contraptions

### Description

Hey want to ask of there are plans for adding Compatibility with other mods?

One example is this:
![image](https://user-images.githubusercontent.com/59801736/181482615-dfe870bc-3234-4ac1-a700-7f1e1358de81.png)

 Think there's more i just haven't seen it yet myself.
 
 Thanks for returning a nice mod.

**Comment by Raidobw2** [comment]
This is reported at https://github.com/FTBTeam/FTB-Mods-Issues/issues/320, I'll close this issue to avoid redundancy
