### ISSUE TITLE
[Bug]: Clicking the map button in the inventory kicks player from the server

### ISSUE THREAD

**Issue by KuroNecron** [FTBTeam/FTB-Mods-Issues#386]
### Mod

FTB Chunks

### Mod version

ftb-chunks-forge-1802.3.6-build.147

### Forge / Fabric version

Forge - 40.1.55

### Modpack & version

Another Quality Modpack 3 + personally added FTB Chunks for MP QoL

### What issue are you having?

Whenever i (and another player i had test it) click on the Chunk-claim-management-map-button, we got kicked to title and couldnt join again until we restarted the game.

This only seems to happen if the server has been online for a while, a reboot temporarily fixes the issue.
Crashlog from my client:
[crash-2022-07-29_14.36.03-client.txt](https://github.com/FTBTeam/FTB-Mods-Issues/files/9220478/crash-2022-07-29_14.36.03-client.txt)

### Steps to reproduce

not 100% consistent:
1. Server is running for a while
2. Player clicks on Map to manage claimed/loaded chunks
3. Player gets booted

### Anything else to note?

This might appear as duplicate with https://github.com/FTBTeam/FTB-Mods-Issues/issues/382 but my error is different.

**Comment by MichaelHillcox** [comment]
Are you able to send me your world on the server? My email is mikey@feed-the-beast.com I'm attempting to replicate this issue to provide a fix but thus far have been unable to do so, having your world may help me sort the issue

**Comment by MichaelHillcox** [comment]
Please see #616 as our main tracking issue for this crash
