### ISSUE TITLE
[Bug]: FTBIC Iron Furnace smelts less items per coal than a normal furnace

### ISSUE THREAD

**Issue by zach2039** [FTBTeam/FTB-Mods-Issues#388]
### Mod

FTB Industrial Contraptions

### Mod version

1900.1.7-build.195

### Forge / Fabric version

1.19 41.0.105

### What issue are you having?

After using the Iron Furnace in-game, it smelts less items per coal than a vanilla furnace. The code below is the issue:

```
@Override
protected int getBurnDuration(ItemStack stack) {
  return super.getBurnDuration(stack) * 8 / FTBICConfig.MACHINES.IRON_FURNACE_ITEMS_PER_COAL.get();
}
```

I think it should be the following for the intended iron furnace items per coal config effect:

```
@Override
protected int getBurnDuration(ItemStack stack) {
  return Math.round(super.getBurnDuration(stack) * (float) FTBICConfig.MACHINES.IRON_FURNACE_ITEMS_PER_COAL.get() / 8);
}
```

### Steps to reproduce

1. Try to smelt 12 items in an Iron Furnace with 1 Coal
2. Observe that smelting of entire 12 items does not complete

**Comment by MichaelHillcox** [comment]
Fixed in dev as of https://github.com/FTBTeam/FTB-Industrial-Contraptions/pull/33 releasing soon
