### ISSUE TITLE
[Bug]: With the latest version of FTBIC, Minecraft fails to load.

### ISSUE THREAD

**Issue by ShibeTemple** [FTBTeam/FTB-Mods-Issues#389]
### Mod

FTBIC

### Mod version

 ftb-industrial-contraptions-1802.1.6-build.206.jar

### Forge / Fabric version

1.18.2 40.1.68

### What issue are you having?

With the latest version of FTBIC, Minecraft fails to load.

### Crashlogs

https://pste.ch/nowoyijevo.rb

### Steps to reproduce

Launch game.
Crash.

**Comment by ShibeTemple** [comment]
Older version ftb-industrial-contraptions-1802.1.6-build.192.jar works in the same environment.

**Comment by ShibeTemple** [comment]
Maybe related to the config method switch?

**Comment by MichaelHillcox** [comment]
It would appear that you don't have FTB Library installed, this is likely the issue, I'll fix the dependencies list today

**Comment by MichaelHillcox** [comment]
Just released a new version of FTB IC that now shows FTB Library is a required dep of the mod
