### ISSUE TITLE
[Feature Request]: The View Dependents menu should signify quests that are in another chapter

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-Mods-Issues#390]
### Mod

FTB Quests

### Description

![image](https://user-images.githubusercontent.com/15698722/181873371-4cab5ca0-2fe6-4058-88f1-6e594c2cbb6e.png)

It would be useful if quests that in a different chapter were highlighted in some way, by recoloring them or making putting them past a separator line or something

### Describe the solution you'd like

Like this maybe
![image](https://user-images.githubusercontent.com/15698722/181874528-194cbfcf-7251-4b92-8bf3-a86ab256e20c.png)

**Comment by desht** [comment]
How about if the chapter name was simply appended to the menu entry title?  Like this:

![2022-10-06_16 46 57](https://user-images.githubusercontent.com/736831/194359131-30675ee0-1a26-4ead-b195-739512620f12.png)

**Comment by aaronhowser1** [comment]
That would work great, but preferably only if the dep is in another chapter. Also, maybe `[]` instead of `()`

**Comment by desht** [comment]
Yes definitely only when in a different chapter. Happy to use `[]` if you prefer.

**Comment by desht** [comment]
Implemented in 1.18/1.19
