### ISSUE TITLE
[Feature Request]: Tunnel Shape for Ultime

### ISSUE THREAD

**Issue by recon88** [FTBTeam/FTB-Mods-Issues#391]
### Mod

FTB Ultimine

### Description

I really would like to see Tunnel shapes. 2x2 + 3x3. Or just a way to provide own shapes like `Ore Excavation` has.
Yes, there's a simple 1x1 but if I want to strip mine, I have to repeat the 1x1 tunnel several times until my tunnel reaches 2x2 or 3x3.
If that makes it in, I would love to have a backport to 1.18.2 (Fabric).

**Comment by desht** [comment]
Next Ultimine release will have a 3x3 tunnel shape (subject to the standard block break limit, e.g. if your break limit is 64 blocks, a 3x3 tunnel will go up to 7 blocks deep per ultimining operation).  Planned for 1.18 and 1.19.
