### ISSUE TITLE
[Bug]: Item filters/FTBQ not detecting NBT

### ISSUE THREAD

**Issue by redgoblin88** [FTBTeam/FTB-Mods-Issues#392]
### Mod

Item filters/ FTB questing

### Mod version

item filters: 1802.2.7-build.33 | FTB Quests 1802.3.8-build.101

### Forge / Fabric version

40.1.68

### What issue are you having?

upon creating a quest which needs a specific NBT to complete, the mod ignores the NBT and accepts anything

this can be with anything enchanted, such as a mending, fortune, unbreaking

or you can also recreate this issue with the "custom machinery" mod as this mod makes ALL the blocks exactly the same "dummy" but are specified to be unique as NBT

### Steps to reproduce

as an enchanted book:
create a quest with an enchanted book as a requirement, for example a protection 4 book

empty your inventory so it is not to trigger the quest

give yourself an enchanted book ***OTHER*** than what you set as the quest, such as a curse of vanishing

the mod only cares that it is an "enchanted book", just not what kind, so it will think the quest is completed

====================
as a custom machine:
create two custom machines with different names, in-game this should create two new "machine" blocks (requires game restart to add new ones or modify them), lets call these, for arguments sake "creative generator" and "trash can"

make a quest to detect one of these machines and then clear your inventory of ***EVERYTHING*** that is a custom machine being careful not to trigger the quest

give yourself any custom machine ***EXCEPT*** the one the quest SHOULD be specifically for (for example, if you set it to "trash can", give yourself the "creative generator")

note how the quest is marked as completed despite, in theory, being nothing alike

### Anything else to note?

i noted in the game files that the NBTs ARE saved correctly every time, but is "ignored", as seen below
{
            x: 9.5d
            y: 4.5d
            id: "71243767CA1FE1DF"
            tasks: [{
                id: "1CA91EABFBD36C69"
                type: "item"
                item: {
                    id: "minecraft:enchanted_book"
                    Count: 1b
                    tag: {
                        StoredEnchantments: [{
                            lvl: 4s
                            id: "minecraft:protection"
                        }]
                    }
                }
            }]
        }
===============
i have asked for aaronhowser for his help as he has more experience than i do, he asked me to do "/kubejs hand" in which this resulted 
![image](https://user-images.githubusercontent.com/13396472/181934314-e53f3466-04e8-4d28-9eee-e7ace8815fc1.png)
his response is that it seems item filters is broken, of which i have no idea what item filters even is, other than just some "stuff" added which can do "things"

**Comment by Raidobw2** [comment]
This is also reported at https://github.com/FTBTeam/FTB-Mods-Issues/issues/182, I'll close this issue to avoid duplicates. Thank you for reporting
