### ISSUE TITLE
[Bug]: FileNotFoundException modname:sidebar_button_groups.json

### ISSUE THREAD

**Issue by recon88** [FTBTeam/FTB-Mods-Issues#394]
### Mod

FTB Library

### Mod version

ftb-library-fabric-1802.3.6-build.138

### Forge / Fabric version

fabric 0.58.0+1.18.2 / fabricloader 0.14.8

### Modpack & version

Custom

### What issue are you having?

When starting my custom pack, I'm getting my log spammed with
 `java.io.FileNotFoundException modname:sidebar_button_groups.json`
It does that for literally once for every single mod installed.

### Crashlogs

Error: https://pastebin.com/raw/jDAk1AHS

Full log, had to compress because it was over Github's limits and online paste sites were just crashing when inserting.
[latest.zip](https://github.com/FTBTeam/FTB-Mods-Issues/files/9228220/latest.zip)
.

### Steps to reproduce

I'm honestly not sure how you would reprocude that. It just happens when I load up my custom pack.

**Comment by MichaelHillcox** [comment]
Fixed and should be released as of the latest version
