### ISSUE TITLE
[Bug]: Dupe glitch with Spectrum's Black Hole Chest (and possibly others)

### ISSUE THREAD

**Issue by recon88** [FTBTeam/FTB-Mods-Issues#399]
### Mod

FTB Ultimine

### Mod version

ftbultimine 1802.3.3-build.55

### Forge / Fabric version

fabric 0.58.0+1.18.2

### Modpack & version

N/A

### What issue are you having?

When mining near a Black Hole Chest, the item output get doubled.

Quoting Spectrum's dev:
The Black Hole Chest directly hooks into the spawning of the items, triggering instantly.
FTB Ultimine saves a copy of the drop without removing it from the item entity.

`tempBlockDropsList.add(((ItemEntity) entity).getItem());`

https://github.com/FTBTeam/FTB-Ultimine/blob/fbf9ca12441bd28ac8b321fd520eec8780d35bc1/common/src/main/java/dev/ftb/mods/ftbultimine/FTBUltimine.java#L355

![spectrum_blackholechest](https://user-images.githubusercontent.com/1056686/182367575-c31556b0-60d2-49a8-bea0-ada6db0095b9.gif)

### Steps to reproduce

- Place Spectrum's Black Hole Chest
- Mine blocks with FTB Ultimine activated
- Output doubled

**Comment by recon88** [comment]
I've provided a fix, although I'm not 100% sure if it is the right approach.

I'm also wondering if the same issue would apply to the experience drops a couple lines below, same method.

**Comment by desht** [comment]
Coming back to this late I know, but yes the experience orbs could conceivably suffer from the same issue, if another mod were to intercept their spawning.  XP orb entities can't have their value modified like item entities can (the value is a final field), but the entity can be killed; mods should check if the entity is alive before trying to use it.

I'll get a fix into Ultimine for 1.18 & 1.19 for that.

**Comment by desht** [comment]
This should be fixed now in latest 1.18/1.19 releases.
