### ISSUE TITLE
You can steal team chunks ownership

### ISSUE THREAD

**Issue by kiriharu** [FTBTeam/FTB-Mods-Issues#4]
There's a way to steal chunks when adding other people in your group.
Steps to reproduce:
1. Player 1 claims chunks, creates team and adds Player 2
2. Player 2 claims area anywhere and accepts team invite
3. Player 1 (team owner) kicks Player 2 or Player 2 leave from team
4. Player 2 left without claimed chunks, because they now belong to Player 1 team

**Comment by fabrossmann** [comment]
This problem can also lead to players "duping" chunks.
If player 2 then claims again, gets invited, the new claimed chunks will be added on top of the current chunks + stolen chunks and the newly claimed chunks.

This is a pretty major bug, especially for bigger servers using the mod.

**Comment by desht** [comment]
Fixed in dev in 1.18 now (party teams will keep track of each player's original claims, and return them to the player when the player leaves the party).

**Comment by desht** [comment]
Fixed in 1.16/1.18/1.19
