### ISSUE TITLE
[Bug]: 1.18.2, install with the ftb-library the jei can't use ctrl+A to select all in the search input

### ISSUE THREAD

**Issue by rylwl** [FTBTeam/FTB-Mods-Issues#403]
### Mod

 FTB Library (Forge)

### Mod version

 FTB Library (Forge):1802.3.6-build.140

### Forge / Fabric version

1.18.2  Forge: 40.1.68

### What issue are you having?

Minecraft is installed with the JustEnoughItems, architectury, FTB library
as we all known, jei can search the item in the backpack window and it can use some shortcut keys in the input search line,such as Ctrl+A to select all words, or Shift +left or right to select some letters.
However if you involve with the FTB library, the shortcut keys can't be used.

The thing should be happening:
if click ctrl+A, the all word in the search input line will be selected
if hold the shift+left,the number of letters you click left will be selected

Actual Behavior(The thing is happening)
I can't use the normal shortcut keys to select all the words or some letters(include ctrl+A etc.)

### Steps to reproduce

1.start minecraft with JustEnoughItems and FTB library
2.go into a world
3.when you are creative or survival, click E to open the backpack
4.input the item which you want to search in the search input line
5.click ctrl+A to select or press and hold the shift+left to select some words

### Anything else to note?

minecraft version:1.18.2
forge version:40.1.68
jei version: 9.7.0.209 or 9.7.1.232
ftb-library version:1802.3.6-build.140
Architectury API version:4.7.78

**Comment by Raidobw2** [comment]
This is reported at https://github.com/FTBTeam/FTB-Mods-Issues/issues/262, I'll keep only that issue for our mod dev to avoid redundancy. I'll adjust the title for searching purposes
