### ISSUE TITLE
[Bug]: Apotheosis explosive/mining arrows bypassing chunk protection 

### ISSUE THREAD

**Issue by funAlways** [FTBTeam/FTB-Mods-Issues#404]
### Mod

FTB Chunks

### Mod version

ftb-chunks-forge-1802.3.6-build.147.jar

### Forge / Fabric version

1.16.5 40.1.68

### Modpack & version

https://www.technicpack.net/modpack/twilight-forest-id.1929795 v1.5

### What issue are you having?

Apotheosis mod adds explosive arrows (explodes on impact like TNT) and mining arrows (breaks through blocks), and this can bypass protection and break things in other player's claimed chunks.

### Steps to reproduce

1. Have another player claim an area
2. Get a bow, explosive arrows, and mining (diamond or iron) arrows
3. Shoot the arrows at the claimed area

**Comment by desht** [comment]
This is a bug in Apotheosis, which creates its custom arrow entities with a `null` owner.  So FTB Chunks has no way of knowing who the owner is.  Please report this to the Apotheosis author.
