### ISSUE TITLE
[Feature Request]: Incorporate Minecrafts own Teams system for more Options to the players

### ISSUE THREAD

**Issue by Honeth** [FTBTeam/FTB-Mods-Issues#405]
### Mod

FTB Teams

### Description

Playing the game try to kill a monster friend almost died to it is low on health, I swing my sweeping edge triggers and kills my friend.

Farming a mob farm friend walks too close sweeping edge kills him.

### Describe the solution you'd like

By incorporating the /teams command from minecraft into FTBTeams you'll give players the option to decide on things like name color , FriendlyFire etc.

FriendlyFire being the biggest option being requested with this as i've had too many modpacks played / made for my friends where they wish pvp was off at one point and on at another in the same hour or 2 dif teams have dif requests for it.

And most of the pvp they do is FriendlyFire.

Would be a Amazing addition if added.

Much love, Honeth

### Describe alternatives you've considered

We've tried turning the server pvp off entirely but that only works for 10 min before people complain that it's off.

**Comment by desht** [comment]
This is covered by #631 so will track progress there (it is something we want to add since it could be very useful, but there are complexities to it...)
