### ISSUE TITLE
[Feature Request]: Add ftblibrary to the dependencies on Curseforge

### ISSUE THREAD

**Issue by AlexanderPezarro** [FTBTeam/FTB-Mods-Issues#410]
### Mod

FTB Industrical Contraptions

### Description

When looking at the dependencies for FTB IC on Curseforge it only shows Architecture and Myrtrees, even though it also required FTB Library to run. 

While FTB IC is set as a dependent of FTB Library on its Curseforge page this isn't as useful as I would have know to search for FTB Library ahead of time to check if it is a require dependancy.

### Describe the solution you'd like

Add FTB Library to the list of dependancies of FTB Industrial Contraptions.

**Comment by MichaelHillcox** [comment]
Sorted :+1:
