### ISSUE TITLE
[Bug]: FTB Ultimine outline renders incorrectly with shaders

### ISSUE THREAD

**Issue by zkitkatwise** [FTBTeam/FTB-Mods-Issues#411]
### Mod

FTB Ultimine

### Mod version

ftb-ultimine-forge-1605.3.1-build.45

### Forge / Fabric version

Forge-36.2-35 (1.16.5)

### What issue are you having?

The outline of the blocks you are going to mine of FTB Ultimine renders moved and not on the blocks.
I am using Oculus and Rubidium with Complementary Shaders. (The issue happens with other shaders.)
Turning of shaders fixes it.
![2022-08-12_18 24 28](https://user-images.githubusercontent.com/82173746/184401524-fe06dbff-8dce-4bd1-8b86-d04187771838.png)

### Steps to reproduce

1. Lauch 1.16.5 Forge with FTB Ultimine, Rubidium and Oculus (and necessary dependencies)
2. Activate shaders
3. Wait a bit (For me the bug happens about 2 min in)
4. Press veinmine button

Here´s the screenshot with just FTB Ultimine, Rubidium and Oculus: (I used /forge mods to show active mods)
![2022-08-12_18 37 31](https://user-images.githubusercontent.com/82173746/184404138-48201e1d-469e-4748-a217-3eb337d4da02.png)

### Anything else to note?

I am using GUI Scale 3x

**Comment by Raidobw2** [comment]
See https://github.com/FTBTeam/FTB-Mods-Issues/issues/341, it's the same issue. I'll add information to this other ticket and close this one to avoid redundancy
