### ISSUE TITLE
[Bug]: ftbchunks.snbt does not get copied from the defaultconfig folder when creating a new world

### ISSUE THREAD

**Issue by EnderMelody** [FTBTeam/FTB-Mods-Issues#412]
### Mod

FTB Chunks

### Mod version

ftb-chunks-forge-1802.3.6-build.147

### Forge / Fabric version

1.18.2 40.1.73

### What issue are you having?

creating a new world does not automatically copy the config for ftb chunks from the defaultconfig folder into the new worlds serverconfig folder

### Steps to reproduce

1. change values in the config and move it to defaultconfig
2. create new world and it will not use the values in defaultconfig

**Comment by Raidobw2** [comment]
Please see https://github.com/FTBTeam/FTB-Mods-Issues/issues/69 for copying server configs. Forge requires the file to end in `-server` to copy it from `defaultconfigs` into the `serverconfig` folder.
If that did it, close this issue to avoid duplicates for our mod devs!

**Comment by EnderMelody** [comment]
so i should add -server to the .snbt? i will give it a try.

**Comment by EnderMelody** [comment]
adding -server to the file did not have it move from the defaultconfig folder. it might be something you need to change on your end.

**Comment by Raidobw2** [comment]
I see, upon further investigation it looks like FTB Essentials is coded to use the defaultconfigs while FTB Chunks isn't.

FTB Essentials is using...
https://github.com/FTBTeam/FTB-Essentials/blob/96b8ae7706ef4e033f8db54114515bd84e5d3298/src/main/java/dev/ftb/mods/ftbessentials/FTBEEventHandler.java#L48-L60
Which is using the advanced load function from FTB Library:
https://github.com/FTBTeam/FTB-Library/blob/2331b30ab493b221092cf049111ccc6816c0f544/common/src/main/java/dev/ftb/mods/ftblibrary/snbt/config/SNBTConfig.java#L134
![image](https://user-images.githubusercontent.com/17010632/184571349-8b371476-3b62-4719-9bd4-6bf029947ea9.png)


While FTB Chunks uses this function...
https://github.com/FTBTeam/FTB-Chunks/blob/33edb04bcd2040ec728d4d1d785cda71870a47a6/common/src/main/java/dev/ftb/mods/ftbchunks/FTBChunks.java#L150
Which is the simple load function of FTB Library instead, which does not support defaultconfig copy:
https://github.com/FTBTeam/FTB-Library/blob/2331b30ab493b221092cf049111ccc6816c0f544/common/src/main/java/dev/ftb/mods/ftblibrary/snbt/config/SNBTConfig.java#L110
![image](https://user-images.githubusercontent.com/17010632/184571468-192c1ff5-d75f-4bd1-b9a4-ce42b72759f2.png)

Our mod dev will have to take a look when he can, for now this doesn't look possible to use a defaultconfig, thanks for reporting

**Comment by Raidobw2** [comment]
Hey, a little late sorry! Looks like FTB Chunks had a build in September with this notice:
![image](https://user-images.githubusercontent.com/17010632/198976350-ed3dd1aa-0f92-45be-82da-98411bf54da2.png)

I assume this should solve the issue of not having any configs copied over, now they should work (put them in defaultconfigs folder). I'll close this issue then!
