### ISSUE TITLE
[Feature Request]: Chat Announcement

### ISSUE THREAD

**Issue by Windgott1910** [FTBTeam/FTB-Mods-Issues#414]
### Mod

FTB Quests

### Description

a true/false toggleable option to announce it when a player has completed a quest
if possible, also for 1.12 because some other mods only work up to 1.12.2

**Comment by MichaelHillcox** [comment]
This likely has very limited scope, but can also be relatively trivial to achieve via KubeJS and using our events we fire for when quests are completed. I'll leave this one up to the community in preference of adding it to the mod directly.
