### ISSUE TITLE
[Bug]: FTB Chunks show loaded chunks not accurate

### ISSUE THREAD

**Issue by Raidobw2** [FTBTeam/FTB-Mods-Issues#415]
### Mod

FTB Chunks

### Mod version

ftb-chunks-forge-1802.3.6-build.147.jar

### Forge / Fabric version

1.18.2 40.1.73

### Modpack & version

FTB Plexiglass Mountain 1.1.1 & in-dev 1.2.0

### What issue are you having?

Relaying from https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1104

Render distance of 16, show loaded chunk with `/ftbchunks admin view_loaded_chunks`:
![image](https://user-images.githubusercontent.com/17010632/185048196-cbe02c77-3502-4657-b6fa-3982aaf2045b.png)
![image](https://user-images.githubusercontent.com/17010632/185048210-6f78ebce-bc43-41d8-bb65-c8620238945f.png)

~16 times 16 is 256, so 4k+ looks impossible~
Edit 1: I suck at math
Edit 2: 33 x 33 = 1089, 4k+ still doesn't feel right, even if spawn is loaded (which are 16x16)

Maybe feature can be removed if irrelevant, or made more accurate if possible

### Crashlogs

N/A

### Steps to reproduce

1. Log in world
2. Set render to 16 chunks
3. `/ftbchunks admin view_loaded_chunks`
4. View chat output and how many chunks are loaded
5. Press M to check map if you want

### Anything else to note?

N/A

**Comment by desht** [comment]
The number of chunks shown is what the server currently has loaded, which could be significantly more than what the client shows.  The number is size of the set union of:

* All chunks the server currently knows about
* All chunks which are force-loaded by vanilla
* All chunks which are listed as force-loaded by FTB Chunks

(in practice these should always overlap, but the point is that the server can have many more chunks loaded than any particular client knows about).

I've double-checked the code and don't see any obvious logic errors here, so I think this is safe to close.

**Comment by Raidobw2** [comment]
Sounds good, thanks for explaining!
