### ISSUE TITLE
[Bug]: You can use armor stands in other's claimed chunks

### ISSUE THREAD

**Issue by LavaCatPlayz** [FTBTeam/FTB-Mods-Issues#418]
### Mod

FTB Chunks

### Mod version

ftb-chunks-forge:1802.3.6-build.147

### Forge / Fabric version

1.18.2 40.1.68

### Modpack & version

ATM7 - 0.4.26

### What issue are you having?

People can take/give items from armor stands regardless of the fact that the chunk is claimed. I have experienced this bug on multiple servers however I was only made aware of this GitHub page on the most recent mod pack I started playing. 

### Steps to reproduce

1. Visit a chunk claimed by another player
2. Interact with an armor stand with armor equipped or an item held

### Anything else to note?

This bug requires 2 people due to it involving actions done in another's claim.

**Comment by desht** [comment]
FTB Chunks is currently lacking support for entity interaction prevention in claimed chunks, and that's something I will get added for the next release.

However, there's actually a bug in Forge right now, which means that interactions on Armor Stands (and possibly other modded entities which are sensitive to the exact click position) are impossible to catch.  So we can currently catch interactions with e.g. item frames and paintings, but not Armor Stands.  I will look at some possible ways around this, but proper Armor Stand protection might need to wait until 1.19.2...

**Comment by desht** [comment]
Fixed in 1.18/1.19

(Armor stands _are_ now protected in 1.18, despite my previous comment)
