### ISSUE TITLE
[feature] Location: Structure

### ISSUE THREAD

**Issue by VorpaltheFox** [FTBTeam/FTB-Mods-Issues#42]
because of random world generation, not all structures will spawn at a pin-pointed location, most times there won't be a structure at the specified location at all or even a different biome's structure.

due to the dependency on world generation, number of biomes, seed, etc for a structure's location, it'd be much easier if it was possible to a specific structure to be found to complete a quest.

as an example, a quest guiding you to find a desert temple, however the player is on a different seed than the modpack creator, so the coordinates direct the player to a deep ocean. if instead the quest could be set to "find structure minecraft:desert_pyramid" or "examplemod:loot_dungeon" it'd be far easier to use the location quest option

**Comment by Raidobw2** [comment]
With the new addition of FTB Structures to the FTB Mods list this becomes quite an interesting suggestion.

**Comment by MaxNeedsSnacks** [comment]
Implemented in a recent build of FTB Quests, see https://github.com/FTBTeam/FTB-Quests/commit/ce83446dd77a9c7c26e7b464a24d19e2a1a5b3aa

**Comment by recon88** [comment]
@MaxNeedsSnacks question regarding the Structure feature:
I tried it with different mods (mo's structures, stoneholm, and more). Most of them don't trigger the structure detection, just a couple mods work. I assume it's an issue with the mods itself, but what exactly do they have to implement to get it working with the detection? 
Or would it be possible for you to implement a workaround? For example, Mo's Structures don't work at all for me.

**Comment by MaxNeedsSnacks** [comment]
Right now, our Structure Task (erroneously) relies on the structure being present in BuiltinRegistries, maybe these mods don't use that and instead use datapack JSONs, which are loaded into the registry access directly

**Comment by recon88** [comment]
Thanks for explaining. You are right, most of the mods rely on the datapack method nowadays.
Would it even possible for you to detect such structures? I don't think that the of mod devs will ever change back to BuiltinRegistries.

**Comment by MaxNeedsSnacks** [comment]
I already pushed an update to both 1.16 and 1.18 ^^

**Comment by jpruitt2297** [comment]
My apologizes on somewhat necro-posting, but is there some guidance or tutorial on getting the Structure Task to function in the case of datapack JSONs? Cause I can't get the task to trigger.
