### ISSUE TITLE
[Feature Request]: More QoL/moderating commands for Essentials

### ISSUE THREAD

**Issue by Illios42** [FTBTeam/FTB-Mods-Issues#424]
### Mod

FTB Essentials

### Description

Since FTB Essentials is currently one of the few, if not only, good command mod for forge servers, I think some more QoL and moderating commands as seen in other mods/plugins would be nice.

Things like /anvil, /enderchest, /stonecutter, /workbench, /smithingtable that open the gui of each block are nice donator perks to offer and very useful. 

/vanish is something integral to moderating, I also dearly miss. Last but not least, /view enderchest or any similar format really would also be a great addition to /invsee.

### Describe the solution you'd like

Adding the listed commands to make the mod even more useful to forge servers.

- /anvil, /enderchest, /stonecutter, /workbench, /smithingtable

- /vanish and /vanishfor

- Expanding on /invsee by adding /enderchestsee | /echestsee | /view enderchest

### Describe alternatives you've considered

Without changing the mod loader, which is sometimes not possible due to mod availability, there are no real alternatives for FTB Essentials that'd add the missing commands, besides /vanish. But even there I would argue that only having to use one mod to achieve all your needs would be much better, since there's no guarantee another vanish mod would work with FTB Ranks/Essentials and it prevents clutter.

**Comment by Raidobw2** [comment]
Just to add on your suggestion, I've had other people in the FTB Discord mention that a built-in vanish would be useful. These are all great suggestions though, thanks for taking the time to write them here!

**Comment by Illios42** [comment]
Of course! Can't wait to see some of the ideas implemented ^^

**Comment by desht** [comment]
Just to note, there's already a `/enderchest` which lets you see yours or anyone else's Ender Chest (admin permission needed to see others)

There will be new `/crafting`, `/smithing`, `/stonecutter` and `/anvil` commands in the next 1.20 release of the mod.

The `/vanish` commands is not so simple, needing a very large number of mixins to work correctly.  Given there are already working vanish mods for both Forge and Fabric, I'm less inclined to add this to Essentials.
