### ISSUE TITLE
[Bug]: Item Filters' check_nbt tag not working

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-Mods-Issues#425]
### Mod

FTB Quests + Item Filters

### Mod version

ftb-quests-forge-1802.3.8-build.101 + item-filters-forge-1802.2.7-build.33

### Forge / Fabric version

40.1.68

### Modpack & version

N/A

### What issue are you having?

Quest requires any small gate, which has the check_nbt tag
![image](https://user-images.githubusercontent.com/15698722/186701618-5c54ff3f-acf3-427c-a121-936a7ac7964a.png)

There's several quests, for each of the tiers
![image](https://user-images.githubusercontent.com/15698722/186701655-eba4b8b0-e23f-47f3-a573-36a9db26532b.png)

Spawn in the second-to-last tier
![image](https://user-images.githubusercontent.com/15698722/186701814-b55d8125-ae8a-4f73-a0fe-7a47aded0b9e.png)

All 4 quests are completed
![image](https://user-images.githubusercontent.com/15698722/186701837-e3b9e693-2e98-4edc-ad91-cdcdc8018360.png)

### Steps to reproduce

N/A

**Comment by MichaelHillcox** [comment]
Issue on Item Filters mod, PR has been made https://github.com/latvian-dev/Item-Filters/pull/28
