### ISSUE TITLE
Some ultimine issues I found in Academy

### ISSUE THREAD

**Issue by ThatOneJose95** [FTBTeam/FTB-Mods-Issues#431]
When used on...

Bonsais: Doesn't return the ultimined ones with or without an axe
Redstone ore: As mentioned in another issue, it doesn't mine other ones because the one you mine changes id to lit_redstone_ore
All drawers from storage drawers: Ultimined ones return as oak ones in case of wooden drawers, always empty except the original one you mined. May bug framed drawers too (didn't make any yet)
Wither skulls straight up dissapeared
Hardened fluxducts dissapeared and i'm scared of trying with other ducts

On addition to this, ultimine doesn't add XP to tinker tools that level but take durability.

I'll keep editing when I find anything, I know some other stuff bugs but I don't remember them

**Comment by MichaelHillcox** [comment]
This looks like it's 1.12, thank you for the report but we will not be continuing support for 1.12. If this continues to happen in newer versions, please open a new issue
