### ISSUE TITLE
Suggestion: experience cost

### ISSUE THREAD

**Issue by Terpo** [FTBTeam/FTB-Mods-Issues#435]
I really loved the option of an older excavate mod, which allowed to use player experience as an additional cost to hunger. With this option players on my server needed to think about when using the excavate option and experience became much more useful.

It would be really cool if such an option find its way to ftb ultimine. (1.16+)

**Comment by desht** [comment]
Added in 2001.1.4 release. See the new `experience_per_block` configuration entry in server config.
