### ISSUE TITLE
Conflict with Inventory Pets

### ISSUE THREAD

**Issue by HueyKablooey** [FTBTeam/FTB-Mods-Issues#439]
Currently the Loot Pet has to be disabled with Ultimine installed because apparently they both use the "block break" function. The modder for Inventory Pets asked me to reach out to you to see if it would be possible for you to "open up an API to FTBUltimine so I could access the result set and we solve all problems for everyone." He wants the two mods to be able to work together. Is there any way you could look into this and reach out to Purplicious_Cow_?

**Comment by desht** [comment]
Closing this. If it's still an issue, please reopen and I'll take a look.
