### ISSUE TITLE
[Suggestion] Ability to toggle merging on the client-side

### ISSUE THREAD

**Issue by tanyan-tanyan** [FTBTeam/FTB-Mods-Issues#440]
```#Doesn't stop at different types of stones
merge_stone = false
```
Is it possible to make this config option client-side rather than server-side for players that are playing on a server?
To my understanding, changing the client-side toml's merge_stone value to true doesn't make a difference if the server-side's merge_stone value is set to false, and vice versa.

It would be extremely useful if it was possible to switch between false and true value in-game or just not be restricted to the server's configuration, as our server's players have found the need for both of them, and right now they're limited to the server configuration.

In our modpack's case, we have a lot of new stone types which gets generated alongside vanilla stone. Some of our players wanted to have the ability to leave all stone intact except for the one stone type they want to mine, however when the value is set to true, they end up mining everything which is not convenient. 
On another hand, it is difficult to mine in small square mode if the value is set to false, if they're attempting to excavate large areas for builds.

Here's an example screenshot of the mess which happens in the latter scenario:
![javaw_WjOvTiVGEi](https://user-images.githubusercontent.com/68793071/110412960-f76baf00-8084-11eb-820e-3d7da5c2df55.png)

**Comment by desht** [comment]
Next release of Ultimine will have separate "merge" modes for shapeless and shaped digging which should resolve this problem; see #444.
