### ISSUE TITLE
[1.18.2] (Possibly 1.19) Require tools is not respecting allowed tool tags

### ISSUE THREAD

**Issue by Saereth** [FTBTeam/FTB-Mods-Issues#442]
https://cdn.discordapp.com/attachments/983613921355255808/992780645443043378/unknown.png

Adding the tag to tinkers pickaxes, the tool in hand shows the tag is on it and valid, but ultimine does not see it as a valid ultimine tool.

**Comment by desht** [comment]
Closing old issue, should be resolved now.
