### ISSUE TITLE
[Feature request] separate shapeless vs shaped merge tag behavior

### ISSUE THREAD

**Issue by AngleWyrm10** [FTBTeam/FTB-Mods-Issues#444]
During [this reddit conversation](https://www.reddit.com/r/feedthebeast/comments/wtnc45/comment/il9g2n7/?utm_source=reddit&utm_medium=web2x&context=3) I advertised Ultimine as a possible solution, but a problem was pointed out: The shaped modes are often obstructed by blocks where the player would rather they were all mined instead.

One poster recommended, and I tested using merge_tag: "*" which brought to light the reason for this feature request

- While using shapeless mode, merge_tags are useful for tasks such as felling trees, mowing the lawn, or mining veins
- While using shaped modes, merge tags are undesirable, and a merge_tag of "*" is preferable

**Feature Request**
Either two separate merge_tag entries, one for shaped and one for shapeless
Or a keybind to quickly disable the use of merge_tags 
Or an automatic disable merge tags while in shaped modes, with a config option to alter this behavior

**Comment by desht** [comment]
I'm inclined to go with separate merge tags for shaped and shapeless here, with the existing `merge_tag` continuing to be used for shapeless digging, and a new `merge_tag_shaped` with a default value of "*" used for the shaped modes.

**Comment by desht** [comment]
Fixed in 1902.4.0 release
