### ISSUE TITLE
[Bug]: Durability Bars on top of Nav Bar

### ISSUE THREAD

**Issue by Jkosio23** [FTBTeam/FTB-Mods-Issues#448]
### Mod

FTB Quests

### Mod version

ftb-quests-forge:1802.3.8-build.101

### Forge / Fabric version

1.18.2-40.1.74

### What issue are you having?

![image](https://user-images.githubusercontent.com/17010632/188537120-dc5f7c77-8418-40b9-afca-e1db2e90da54.png)
![image](https://user-images.githubusercontent.com/17010632/188537108-698519fc-d7ac-487f-86f4-976d5b423e64.png)
![image](https://user-images.githubusercontent.com/17010632/188537135-91f0ba9e-69b9-4cdc-b1c9-ed3b30dd9831.png)
![image](https://user-images.githubusercontent.com/17010632/188537130-64ad2df7-b4e6-4d27-b9e6-e2df6a0631b0.png)

### Steps to reproduce

I used ATM 7 To The Sky to find this bug, but any quests that have an icon with a durability bar should trigger it, just have the nav bar open with the quest icon on the left part of the screen

**Comment by Raidobw2** [comment]
Same thing happens in other modpacks:
![image](https://user-images.githubusercontent.com/17010632/193792775-3ce2fe80-3ef7-4693-82ba-6a77f1f74b5e.png)

**Comment by desht** [comment]
Implemented for 1.18 & 1.19
