### ISSUE TITLE
[Feature Request]: Update FTB Ultimine (Fabric) for Minecraft 1.19.2

### ISSUE THREAD

**Issue by Zarepheth** [FTBTeam/FTB-Mods-Issues#450]
### Mod

FTB Ultimine (Fabric)

### Description

I'd just like the existing FTB Ultimine for Fabric mod updated for Minecraft 1.19.2.

### Describe alternatives you've considered

I originally attempted to manually change the dependency in the `*.jar` file, but ended up with crashes at startup, so I dropped the FTB mods from my Curse Forge profile. Since then, I've been waiting for it to be updated.

**Comment by Zarepheth** [comment]
Although the alternative I tried a week ago failed then, I tried again this evening (using the most recent FTB Library for Fabric) and it worked. The freshly downloaded FTB Library did not require any manual change. And my older copy of the FTB Ultimine was either hand editing some time ago, or worked as is.

One thing of note, on Curse Forge, both mods claimed to be incompatible with the "Better MC [FABRIC] 1.19.2 v3" modpack. I had to manually download (and/or) copy them to the profile's "mods" folder.

**Comment by Raidobw2** [comment]
Hi, sorry for the delay.

FTB Library is updated for Minecraft 1.19.2 https://www.curseforge.com/minecraft/mc-mods/ftb-library-fabric/files/3963541.

FTB Ultimine looks like it hasn't specifically updated for 1.19.2, though the 1.19 version might work fine. https://www.curseforge.com/minecraft/mc-mods/ftb-ultimine-fabric/files/3830987

I've seen one user report a similar issue about this but for FTB Chunks, on the FTB Discord. If I understand properly, the main problem is the mislabel on CurseForge. I will poke Mikey (our lead mod dev) about that and ask him to correct it.

I'm unsure if FTB Ultimine is planned for an update for 1.19.2, but considering FTB One is going to jump from 1.19 -> 1.19.2, FTB Ultimine might get one then.
If the 1.19 version works though, feel free to use it, even if it's on 1.19.2.

**Comment by Zarepheth** [comment]
Thanks for the update. 
FTB Ultimine has been working fine on Minecraft 1.19.2. It just required some manual effort to workaround Curse Forge not recognizing that it should work.
