### ISSUE TITLE
[Feature Request]: Configurable keybind for Ultimine 1.19

### ISSUE THREAD

**Issue by DAmNRelentless** [FTBTeam/FTB-Mods-Issues#451]
### Mod

FTB Ultimine

### Description

There should be a configurable keybind for FTB Ultimine 1.19. There is currently no way to configure it.

**Comment by Raidobw2** [comment]
Thanks for the report! Looks like it's supposed to be set at https://github.com/FTBTeam/FTB-Ultimine/blob/f702682333c36f40c8667e93fe0a7b28d61fe46e/common/src/main/java/dev/ftb/mods/ftbultimine/client/FTBUltimineClient.java#L74 but maybe something broke.

I tried setting it manually in the options.txt file as well (using the format from a 1.18 options file), but that did not work either. Our mod dev will have to take a look when he can, until then I think there is no workaround for this issue, sorry.

Versions:
Arch `architectury-5.12.44-forge.jar`
FTB Lib `ftb-library-forge-1900.3.8-build.142.jar`
Ultimine `ftb-ultimine-forge-1900.3.4-build.58.jar`

**Comment by desht** [comment]
Sorry for the delay.  Ultimine keybinds work fine in the current 1.19.2 release.  1.19 isn't supported anymore, so closing this.
