### ISSUE TITLE
[Bug]: FTB Industrial Contraptions (ftbic) has failed to load correctly MC 1.18.2

### ISSUE THREAD

**Issue by shinduke** [FTBTeam/FTB-Mods-Issues#458]
### Mod

FTB Industrial Contraptions

### Mod version

ftb-industrial-contraptions-1802.1.6-build.197

### Forge / Fabric version

forge 40.1.68

### What issue are you having?

MC not starting because of error

### Crashlogs

https://hastebin.com/sikulusevi.properties

https://hastebin.com/rojomupori.sql

### Steps to reproduce

Error occours at start

**Comment by Raidobw2** [comment]
Add FTB Library for Forge 1.18.2 and let me know if it resolves the crash https://www.curseforge.com/minecraft/mc-mods/ftb-library-forge

To dev: If FTB Lib is used, it's not included in dependencies, that likely needs to change https://www.curseforge.com/minecraft/mc-mods/ftb-industrial-contraptions-forge/relations/dependencies

```
Caused by 1: java.lang.NoClassDefFoundError: dev/ftb/mods/ftblibrary/snbt/config/SNBTConfig
		at dev.ftb.mods.ftbic.FTBICConfig.<clinit>(FTBICConfig.java:29) ~[ftb-industrial-contraptions-1802.1.6-build.197.jar%2399!/:1802.1.6-build.197] {re:classloading}
		at dev.ftb.mods.ftbic.FTBIC.<init>(FTBIC.java:79) ~[ftb-industrial-contraptions-1802.1.6-build.197.jar%2399!/:1802.1.6-build.197] {re:classloading}
```

**Comment by shinduke** [comment]
@ Raidobw2
Thank you for you help. Adding "ftb-library-forge-1802.3.6-build.138" fixed this issue.
MC started as expected.
