### ISSUE TITLE
[Feature Request]: FTB-Chunks Config

### ISSUE THREAD

**Issue by OcrSu** [FTBTeam/FTB-Mods-Issues#46]
### Mod

FTB-Chunks

### Description

[New Feature Suggestion]

Move the mindmap settings config to the config in the root directory
so that the minimap can be turned off by default when making the ModPacks

**Comment by Raidobw2** [comment]
Just to be sure @OcrSu, you're making this suggestion while being aware that the config can be already be shipped through `local/ftbchunks/client-config.snbt`?

**Comment by OcrSu** [comment]
What I do know is: there is a separate ftbchunks under each world folder.
My suggestion is to create a generic FTBchunks config in the .minecraft folder, or under .minecraft/config, so that it will be much easier to move the config to the other client or make Modpacks
