### ISSUE TITLE
[Feature Request]: Add a config option to disable ftbic ore generation

### ISSUE THREAD

**Issue by taraxsmallboy** [FTBTeam/FTB-Mods-Issues#460]
### Mod

FTB Industrial Contraptions

### Description

I wanted to create a modpack with custom ore gen but i couldnt find a config option to disable ftbic ore generation

### Describe the solution you'd like

Add a simple config option for ores that allows us to configure how much is generated and to disable it entirely.

**Comment by Raidobw2** [comment]
Thanks for suggesting it, however another user suggested that as well at https://github.com/FTBTeam/FTB-Mods-Issues/issues/297, so I'll be keeping only the other one for our developer.

Feel free to write a small message in the other issue to manifest your interest in that suggestion or put a thumbs up
