### ISSUE TITLE
[Bug]: REI Entrypoint Used by FTB Quests is Deprecated

### ISSUE THREAD

**Issue by GW-Dev** [FTBTeam/FTB-Mods-Issues#464]
### Mod

FTB Quests

### Mod version

ftb-quests-fabric-1902.2.9-build.41

### Forge / Fabric version

1.19.2 0.14.9

### What issue are you having?

REI gives a warning during initialization, not an issue right now, but something to patch for future compatibility. Screenshot below.

### Crashlogs

Initialization log: [https://pastebin.com/nMEw6k4G](url)

### Steps to reproduce

1. Install FTB Quests with REI
2. Launch

### Anything else to note?

![Screenshot 2022-09-17 125836](https://user-images.githubusercontent.com/93411305/190870335-34f4ff41-379b-4a46-b4e9-91d90f9a45d5.png)

**Comment by MichaelHillcox** [comment]
https://github.com/FTBTeam/FTB-Quests/commit/f6df3f95588542d5d03630259fb1cf1623d434b8 fixed here
