### ISSUE TITLE
[Bug]: Please make it so ppl cant just use comas in team names it makes any commands involving them unusable

### ISSUE THREAD

**Issue by AlexGuignard** [FTBTeam/FTB-Mods-Issues#465]
### Mod

FTB Teas

### Mod version

ftb-teams-forge-1605.2.3-build.40.jar

### Forge / Fabric version

1.16.5 36.2.35

### Modpack & version

NTC2 Latest

### What issue are you having?

Commands nto working when team name contains ' 

### Steps to reproduce

Just name a team with a  ' in it

**Comment by desht** [comment]
Non-issue.  Team names with non-alpha characters (such as the `'` character) can be referred to in commands simply by removing those character.  Command completion even offers the right team name.

![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/736831/307af4b0-b9d7-4f61-a358-b1a1ce0b1389)
