### ISSUE TITLE
[Bug]: Visit Dimension tasks trigger regardless of if the quest is unlocked or not

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-Mods-Issues#466]
### Mod

FTB Quests

### Mod version

ftb-quests-forge-1802.3.8-build.101

### Forge / Fabric version

Forge 40.1.68

### What issue are you having?

![image](https://user-images.githubusercontent.com/15698722/190984904-689e6bb1-283a-4a9c-89f8-b65901fa193b.png)
![image](https://user-images.githubusercontent.com/15698722/190984923-215a2f66-77e9-4dad-b909-2fa13a591444.png)

This triggers even with the quest locked, and the quest doesn't properly become completed when unlocked.

### Steps to reproduce

N/A

**Comment by desht** [comment]
Implemented for 1.18 & 1.19
