### ISSUE TITLE
[Bug]: On 1.18 energy quests don't work?

### ISSUE THREAD

**Issue by tuturox91** [FTBTeam/FTB-Mods-Issues#467]
### Mod

FTB quests

### Mod version

ftb-quests-forge-1802.3.8-build.101

### Forge / Fabric version

40.1.73

### Modpack & version

-

### What issue are you having?

On 1.18 energy quests don't work? If work, how to complete their?

### Steps to reproduce

Can't complete energy quest.

**Comment by tuturox91** [comment]
Please give oportunity to complete FE energy quest

**Comment by desht** [comment]
Unfortunately, handling of energy & fluids via input screens was a feature that never got ported from 1.12.2.  However, this is functionality we would like to bring back to FTB Quests in a future release.

**Comment by Raidobw2** [comment]
I'll close this issue in favor of keeping https://github.com/FTBTeam/FTB-Mods-Issues/issues/467 for tracking. I'll be closing other related ones to screen tasks as well. You can subscribe to the other issue to get notifications when this will be worked on
