### ISSUE TITLE
[Bug]: Invalid Player Data with Quests using Stats

### ISSUE THREAD

**Issue by yaxley** [FTBTeam/FTB-Mods-Issues#468]
### Mod

FTB Quests

### Mod version

ftb-quests-forge-1802.3.8-build.101

### Forge / Fabric version

forge-1.18.2-40.1.76-installer

### What issue are you having?

When completing a quests that uses minecraft stats as a requirement, the game crashes. On multiplayer the player is kicked off the server. After this the player can't connect anymore because of invalid player data.

### Crashlogs

https://hastebin.com/ewuvabebit.properties

### Steps to reproduce

1. Start a new world without quests
2. Create a quest using a stat, for instance "distance sprinted"
3. Complete the quest

**Comment by desht** [comment]
Can you please repost your crash log?  The hastebin link appears to be invalid or no longer working.

**Comment by yaxley** [comment]
https://hastebin.com/oxowupiqiz.properties

I did some more testing, and discovered I made a mistake. The crash actually comes from a vault in my own quest tree. I made a mistake while upgrading to 1.18 and used a stat that was no longer in the game. I don't know why I didn't notice this in my earlier testing. My excuses. 

You can close this issue, or rename it if it is still an issue you are interested in.

**Comment by desht** [comment]
Thanks for the update.  I'll keep this open for now, since Quests should be more tolerant of situations like this (i.e. not crash the whole server...)

**Comment by katubug** [comment]
I believe I am having this same issue, however I have some quests with stats which *do not* crash the game. For example, I have one which requires the user to walk 500 miles, and then 500 more - this does not crash. I'm wondering if it's because in my testing world, I haven't reached either goal.

However, setting a quest target to "Waystones Activated: 1" *does* cause the following crash: https://pastebin.com/7Pa2ASsc

**Comment by desht** [comment]
Yes, that looks like the same issue. A stat resource location which the game doesn't recognise will lead to this NPE.  It's fixed in dev already, and will be fixed in the next release.

**Comment by desht** [comment]
Implemented for 1.18 & 1.19
