### ISSUE TITLE
[Bug]: Quests ignore NBT values in 1.16.5

### ISSUE THREAD

**Issue by Jesslerchip** [FTBTeam/FTB-Mods-Issues#469]
### Mod

FTB Quests

### Mod version

ftb-quests-forge-1605.3.6-build.98

### Forge / Fabric version

1.16.5 Forge - 36.2.34

### What issue are you having?

As the title says, in 1.16.5 the NBT values are ignored when set on a quest. Any item of a given type will register the task as complete regardless of whether or not it matches the NBT values. This breaks several of my quests.

### Steps to reproduce

1. Create an item task with specific NBT values
2. Get any item of that type without those NBT values

**Comment by desht** [comment]
Fixed in latest 1.16.5 release
