### ISSUE TITLE
Enable Discussions or Issues at FTB Industrial Contraptions Github repository

### ISSUE THREAD

**Issue by karl-police** [FTBTeam/FTB-Mods-Issues#472]
Enable discussions or issues on FTB Industrial Contraptions Github repository

https://github.com/FTBTeam/FTB-Industrial-Contraptions

So that it is easier to create pull requests and communicate with other developers other than having to dig into the source code?

**Comment by MichaelHillcox** [comment]
We disable issues on all the separate mod repos as all the projects follow the same structure. Having one place to manage all of those issues simplifies our life greatly! So, as of right now, we'll be sticking with it. If you intend on making a pull request and want to reference an issue from here. You can do so using the following format `org/repo#number`, for example: ftbteam/ftb-mods-issues#472

**Comment by karl-police** [comment]
> We disable issues on all the separate mod repos as all the projects follow the same structure. Having one place to manage all of those issues simplifies our life greatly! So, as of right now, we'll be sticking with it. If you intend on making a pull request and want to reference an issue from here. You can do so using the following format `org/repo#number`, for example: #472

I am not sure if I understood quite right.

So, I can use this repository to report issues for all the mods? Not sure what you ment with ``org/repo#number``
