### ISSUE TITLE
[Bug]: FTB Chunks (Forge) crash on server if try to open map (1.19.2)

### ISSUE THREAD

**Issue by Joshernoob** [FTBTeam/FTB-Mods-Issues#477]
### Mod

FTB Chunks

### Mod version

ftb-chunks-forge-1902.3.9-build.168

### Forge / Fabric version

1.19.2-43.1.25 Forge

### Modpack & version

Custom

### What issue are you having?

Added FTB Chunks to a 1.19.2 server as soon as it released and it started acting up not showing the map, we thought nothing of this and as the big map was working for a small bit. today however both me and someone else that plays the server crashed while both trying to hit the map icon and hit the "m" key to open the large map with on click event even for the key.

### Crashlogs

https://paste.feed-the-beast.com/view/99efcfed

### Steps to reproduce

1) Have the mod installed in server
2) Map will not show up, (if does you may be lucky)
3) try to click icon to open large map or key to open large map
4) crash with on click event

### Anything else to note?

This could very well be another mod in the pack making this happen and conficting if you think it is and need the mod list please let me know

**Comment by MichaelHillcox** [comment]
Are you on a server by any chance?

**Comment by Raidobw2** [comment]
Might be related to https://github.com/FTBTeam/FTB-Modpack-Issues/issues/996; in addition to Michael's question, is the server properly started with Forge?
Typing `forge tps` in the console should give you information, if not, then it's currently not using Forge (the modloader).

**Comment by Joshernoob** [comment]
> Are you on a server by any chance?

yes am sure am on server, sorry for long wait, seems that 

> Are you on a server by any chance?

Yes it on server

> Might be related to [FTBTeam/FTB-Modpack-Issues#996](https://github.com/FTBTeam/FTB-Modpack-Issues/issues/996); in addition to Michael's question, is the server properly started with Forge? Typing `forge tps` in the console should give you information, if not, then it's currently not using Forge (the modloader).

and yes it seems exactly like this

**Comment by Raidobw2** [comment]
I see, how is the server started?

**Comment by MichaelHillcox** [comment]
Please see #616 as our main tracking issue for this problem.
