### ISSUE TITLE
[Bug]: Location tasks not working properly

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-Mods-Issues#479]
### Mod

FTB Quests

### Mod version

ftb-quests-forge-1802.3.8-build.101

### Forge / Fabric version

Forge 1.18.2 40.1.60

### What issue are you having?

![image](https://user-images.githubusercontent.com/15698722/192729524-496ea794-7cdf-4c98-adc4-5386cc9ba249.png)

It's set to require going to 0, 64, 0, with a tolerance of 500 blocks vertically, as well as 30 blocks in both horizontal directions. 

![image](https://user-images.githubusercontent.com/15698722/192729703-673e918e-7ae5-4cad-a5a4-4e066e95460f.png)
It does not complete here

![image](https://user-images.githubusercontent.com/15698722/192729767-9b4cdf3e-b5a0-4b70-8718-55603aa4eab7.png)
I have to get here for it to register

### Steps to reproduce

N/A

**Comment by desht** [comment]
The way the location task works is that it checks the player's location is within (x -> x+h, y -> y+h, z -> z+h).  So the tolerance box _starts_ at the given x,y,z coords - it's not centered on them.

Adjusting your coords accordingly will fix your problem, but the current behaviour is unintuitive and not well documented.  Possibly a new boolean value "center box on x/y/z" in the task settings would help here?  Would need to be false so as not to break any existing location tasks.

**Comment by aaronhowser1** [comment]
Maybe it should be DX, DY, DZ?

**Comment by desht** [comment]
I'm not sure that makes it any clearer how the co-ordinates should be interpreted, though.  What about just adding tooltips to the X/Y/Z fields stating that it's the start coordinate for the area?

**Comment by aaronhowser1** [comment]
That would work yeah

**Comment by desht** [comment]
Implemented in 1.18/1.19
