### ISSUE TITLE
[Feature Request]: Quest item multi-selection

### ISSUE THREAD

**Issue by Officialy** [FTBTeam/FTB-Mods-Issues#480]
### Mod

FTB Quests

### Description

Creating quests can be repetitive and infuriating when doing a mass amount, an example of this being having an "ingots" category. If a modpack had 100 ingots, you'd have to right click, type ingot, select the ingot you want, press accept, then repeat another 99 times. This takes time, and could be simplified easily with the following solution:

### Describe the solution you'd like

Having the ability to create multiple quests at a time would increase modpack production time tenfold. With a selection system like windows and many other places, using CTRL or SHIFT to:

CTRL: Holding this would allow you to select multiple specific desired quest items.

SHIFT: Clicking an item, then holding shift and clicking elsewhere should select multiple quest items.

If you don't understand this, open file explorer on windows and try this out for yourself. 

Upon pressing the "Accept" button, it should create multiple quests within the original right clicked position. Grouping them in a grid would also help as you would be able to select and move any created quest to a desired area.

**Comment by itsdinkd** [comment]
Or allowing to Copy and Paste quests :)

**Comment by Raidobw2** [comment]
Actually there is a suggestion about this at https://github.com/FTBTeam/FTB-Mods-Issues/issues/176. I'll close this one to avoid duplicates, but I'll update the other issue with the information you put here
