### ISSUE TITLE
[Bug]: More teleportation integration in FTB Essentials when using the `/back` command

### ISSUE THREAD

**Issue by smmmadden** [FTBTeam/FTB-Mods-Issues#481]
### Mod

FTB Essentials

### Mod version

ftb-essentials-1902.1.10-build.47

### Forge / Fabric version

1.19.2 43.1.30

### What issue are you having?

I've recently installed FTB Essentials, Library and Ranks and while I was in a village, I teleported to a couple places and tried to use /back but it says my teleportation history is empty, but clearly it isn't.  I even set my home and it shows not found.  Am I missing something in the config other than enabling them?  The other commands I've tried (Warp, Spawn, etc).

![image](https://user-images.githubusercontent.com/10309346/193384365-e852ddb0-c895-41d5-a233-82e2b9ba63cc.png)

### Steps to reproduce

see screenshot
![image](https://user-images.githubusercontent.com/10309346/193384421-bfa520bd-422b-4394-906c-7cc97577e46f.png)

### Anything else to note?

Let me know if you need the logfile but it has no warnings or errors when executing the commands.

**Comment by Raidobw2** [comment]
Hi, I'm not sure if `/tp` counts for `/back`. Can you try any of the teleport commands in https://feedthebeast.notion.site/FTB-Essentials-f1650e409e91416d941d3167f9ec89f4 and then try `/back` afterwards.

If that doesn't work, it's indeed a bug.

If that works, I can turn this into a suggestion if you want, where `/tp` would work with `/back`. Let me know and thanks

**Comment by smmmadden** [comment]
/back works with: /spawn, /rtp and /warp XXX - but if you do a /teleport_last then it removes all teleport history and then you get stuck where you are.
I did not try with /tpa * commands as they have dependencies on players and not used as frequently as /tp - so if there is any teleporting going on, I would have expected it be supported to teleport back to where I came from.  Please consider adding to all teleporting commands and it looks like teleport_last needs fixing. :-)  Thanks!

**Comment by Raidobw2** [comment]
Thanks for the feedback!

**Comment by desht** [comment]
`/tp` and `/teleport` are the vanilla commands; those do not currently get placed on the "back" stack for Essentials purposes.  However, that would not be hard to add, and would be a useful feature.

In my testing, `/teleport_last` does not clear the "back" stack, but it also doesn't place your previous location onto the stack; looking at the code, it doesn't touch the stack at all. It would probably make sense for this to work like other teleport commands, I agree.
