### ISSUE TITLE
[Feature Request]: FTB Quests Reload

### ISSUE THREAD

**Issue by MissPotato** [FTBTeam/FTB-Mods-Issues#483]
### Mod

FTB Quests

### Description

I find the in-game text editor to be a bit cumbersome. As the SNBT file type is pretty much just .json, I prefer editing it with a text editor. However, currently the only way to get the book to sync with the file is to exit the world and reload it. The vanilla /reload command doesn't refresh it.

### Describe the solution you'd like

A straight forward solution is "/ftbquests reload" which would load the quests from file. 

### Describe alternatives you've considered

Making the vanilla /reload command reload the book would work as well.

**Comment by DeleteMetaInf** [comment]
This is a frustrating issue, so I hope this can be implemented. I would love an `/ftbquests reload` as opposed to allowing the files to be reloaded with the vanilla `/reload` command, as reloading in a large modpack can take a long time and can even crash the game. A `/ftbquests reload` command would be wonderful. I hope that can be added to 1.18.2.

**Comment by desht** [comment]
Yes, `/ftbquests reload` will be in the next release of the mod.  Although I should stress that this is intended as developer convenience tool while creating quests, and not advisable for use on a live server where players are playing quests.

**Comment by DeleteMetaInf** [comment]
Sweet! As a modpack developer, this’ll make everything much easier.

**Comment by DeleteMetaInf** [comment]
Sweet! As a modpack developer, this’ll make everything much easier. I hope it doesn’t take too long to come out :)

**Comment by desht** [comment]
Implemented for 1.18 & 1.19
