### ISSUE TITLE
[Bug]: Iron Ore not macerating into 2 dust items

### ISSUE THREAD

**Issue by Ross2609** [FTBTeam/FTB-Mods-Issues#487]
### Mod

FTB Industrial Craft

### Mod version

ftb-industrial-contraptions:1900.1.7-build.212

### Forge / Fabric version

1.19 41.1

### What issue are you having?

When macerating iron ores, they do not macerate to 2 dust. Guessing since they are no longer iron ore blocks?

### Steps to reproduce

Macerate the new iron ore items.

**Comment by Raidobw2** [comment]
Hi, thanks for reporting. It works for me on Forge 41.1 with FTB : IC version `ftb-industrial-contraptions-1900.1.7-build.212.jar` (the same version you reported this issue with).
Is this in a modpack with changed recipes or some form of unification scripts?
![macerator](https://user-images.githubusercontent.com/17010632/193794138-af2cef38-2059-45c7-831b-e92dabd5f5ea.gif)
