### ISSUE TITLE
[Bug]: Non-Alpha Character Crash in FTB Quests

### ISSUE THREAD

**Issue by firemaster1294** [FTBTeam/FTB-Mods-Issues#491]
### Mod

FTB Quests

### Mod version

ftb-quests-forge-1802.3.8-build.101

### Forge / Fabric version

1.18.2 40.1.73

### What issue are you having?

FTB Quests crashes when I try to provide it with a structure using a non-alphabetic character in the name. The expected result would be for the mod to throw an error or provide a little pop-up, not for it to crash the game.

### Crashlogs

https://pste.ch/liqetijede.pl

### Steps to reproduce

1. Load up a game with FTB Quests installed
2. Create a new quest using a location
3. Provide a location name using a hashtag as the first character in the name (I used `#betterstrongholds:stronghold`)
4. Wait for the game to crash!

### Anything else to note?

The mod doesn't provide any warnings that location names should be exact structure names and inform you that it cannot accept dictionary entries. Perhaps this could be changed in a future update? At the very least, it shouldn't crash the game on error.

**Comment by aaronhowser1** [comment]
`#betterstrongholds:stronghold` isn't a structure, it's a structure tag. Tag support would be nice though

**Comment by desht** [comment]
Next Quests release will have structure tag support (and also gracefully handle bad resource locations).

**Comment by desht** [comment]
Implemented for 1.18 & 1.19
