### ISSUE TITLE
[Feature Request]: Quests that are locked and hidden should have their own color, to make it easier to see for dev

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-Mods-Issues#497]
### Mod

FTB Quests

### Description

In dev, there's no way to see which quests are invisible when locked, which makes it harder to dev. Maybe a slightly different color for those?

**Comment by manmaed** [comment]
or an icon?

**Comment by desht** [comment]
Implemented for 1.18 & 1.19
