### ISSUE TITLE
[Feature Request]: Better dependency visibility

### ISSUE THREAD

**Issue by Officialy** [FTBTeam/FTB-Mods-Issues#498]
### Mod

FTB Quests

### Description

When quests are within a straight line, you cannot tell which quest is linked to which dependency without clicking into the quest, and hovering over the linked dependencies' thingy in the top left.

### Describe the solution you'd like

The solution to this problem would be two things. 

1: Being able to hover over dependency lines should make them glow, visualising where they link to. The glow colour should be configurable depending on the pack?

2: If hovering over an incomplete quest that has hidden linked quests, the hidden quests should appear slightly faded, pulsating. This would symbolize that that quest unlocks those pulsating quests. Maybe have them greyed out, black and white?

**Comment by desht** [comment]
Implemented for 1.18 & 1.19
