### ISSUE TITLE
[Feature Request]: Quest Screens

### ISSUE THREAD

**Issue by manmaed** [FTBTeam/FTB-Mods-Issues#499]
### Mod

FTB Quests

### Description

If not already planned to reimplement quest screens

![](https://help.ftb.team/api/v1/attachments/37)

**Comment by Raidobw2** [comment]
This is being requested for 1.16.5 and 1.18, and future versions. Users on related issues have been made aware that depending on current projects and time available, this might only be added in future versions of the mod and not backported.
Keywords for search:
energy, fluid, item, quest, screen, task, wall, world

**Comment by desht** [comment]
This is made a bit more complicated by the fact that we now support Fabric as well as Forge, unlike in 1.12.2.  Ideally a solution will be cross-platform, so I'll need to figure out the Architectury transfer API.

**Comment by desht** [comment]
Implemented for 1.18 & 1.19

**Comment by Raidobw2** [comment]
Super awesome, thanks! :D
