### ISSUE TITLE
[Feature Request]: Remove the "Click for recipes" button, and just show the normal tooltip

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-Mods-Issues#500]
### Mod

FTB Quests

### Description

Only for tasks with a single item

The only thing shown about an item in a single-item task is the name. Anything in the tooltip is not shown the the player, instead if says to click for recipes, which doesn't really need a tooltip imo. If I want to show the tooltip I have to make the task like, the actual item and a dummy item to make it into a multi-item task, to open the other menu when clicked

**Comment by desht** [comment]
I'm not really sure I follow the logic here.  Can you provide an actual example of how this currently works and how you think it should work?

**Comment by aaronhowser1** [comment]
![image](https://user-images.githubusercontent.com/15698722/196147806-93bf18d0-3657-49fe-a20d-4d36a8a280ba.png)
![image](https://user-images.githubusercontent.com/15698722/196147832-4899ad96-ad30-48f7-acbb-f64dc6bdb71b.png)

To actually see the item's tooltip, it has to be in this menu
![image](https://user-images.githubusercontent.com/15698722/196147932-9e02a96d-47c6-498d-ab3f-3e5d42613690.png)

**Comment by aaronhowser1** [comment]
Basically I just want the second screenshot's tooltip to be the item's tooltip, not just the item's name and `Click to view recipe(s)`

**Comment by desht** [comment]
Getting the item tooltip data into the button tooltip is definitely doable and I have that mostly working now - should be a new build today with that in it.  Not sure I'd drop the "Click to view recipe" text at the bottom though - it's still useful information IMHO.

**Comment by desht** [comment]
Implemented in 1.18/1.19
