### ISSUE TITLE
[Feature Request]: A signifier that a quest only needs X amount of deps completed

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-Mods-Issues#504]
### Mod

FTB Quests

### Description

![image](https://user-images.githubusercontent.com/15698722/196031578-ce800226-e6a1-4aef-bc61-78e56abfb841.png)

This quest only needs one of the deps to be completed. Maybe it should have a line at the top like, "<u>1 Required:</u>" underlined

**Comment by desht** [comment]
Implemented for 1.18 & 1.19
