### ISSUE TITLE
[Feature Request]: A way to copy/paste quest images

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-Mods-Issues#507]
### Mod

FTB Quests

### Description

![image](https://user-images.githubusercontent.com/15698722/196933412-479cb6a1-f8e5-4ba4-ac4e-b36c8ee3acce.png)
This is 8 separate image objects (4 instances of the corner image, 4 instances of the line image) (or it will be when the left line is put in, w/e)

With the long lag when selecting images, plus the fact that they're identical, being able to copy/paste would make the process a lot faster.

**Comment by desht** [comment]
Added in latest quests releases
