### ISSUE TITLE
[Feature Request]: Theme support for locked, and unlocked but unstarted quests

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-Mods-Issues#510]
### Mod

Ftb quests

### Description

.

**Comment by desht** [comment]
New "quest_not_started_color" and "quest_locked_color" settings will be in the `ftb_quests_theme.txt` file in the next release. Defaults are the same as currently (white for not started, grey for locked due to dependencies).

**Comment by desht** [comment]
Implemented for 1.18 & 1.19
