### ISSUE TITLE
[Bug]: FTB Ranks and LuckPerms not working

### ISSUE THREAD

**Issue by Trampa3** [FTBTeam/FTB-Mods-Issues#511]
### Mod

FTB Ranks

### Mod version

ftb-ranks-forge-1802.1.8-build.34

### Forge / Fabric version

1.18.2 40.1.80

### What issue are you having?

Luckperm Forge needed for Multiworld Forge 

### Crashlogs

https://paste.shockbyte.com/hasigapogetazohiyuzo 
Console 

### Steps to reproduce

intall and not work

**Comment by Raidobw2** [comment]
I believe this was solved on the FTB Discord, when I mentioned FTB Ranks and LuckPerms don't behave properly with each other without doing any config.

FTB Ranks needs to have its config done right, then with LuckPerms you must manage FTB Ranks permissions.

Let's say you wanted to change the amount of chunks a player can have through permissions. You'd have:
```
VIP: {
        name: "VIP"
        power: 10
        ftbchunks.max_claimed: 50
        ftbchunks.max_force_loaded: 9
    }
```

For example if you have RankUp (Spigot) installed, you'd add the command `ftbranks add %p <name-of-group>` to the RankUp file `rankups.yml`.

Then you'd promote the user with LuckPerms with something alike `lp user &p promote player-track`.

The player that got promoted to VIP then just has to relog to see the changes.

-------------

This was answered on the FTB Discord already, so I will close the issue. I will however change the title for search purposes, for others to see.

**Comment by Raidobw2** [comment]
For documentation, please see https://go.ftb.team/mods-wiki (redirects to Notion, our current docs, at the time of writing this).

The configuration for Forge is inside the world folder, in a folder called `serverconfig`.
