### ISSUE TITLE
[Feature Request]: More keyboard shortcuts for quest editing

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-Mods-Issues#513]
### Mod

FTB Quests

### Description

Writing quests requires a lot of moving your hand between the mouse and the keyboard, which is slow. A couple keyboard shortcuts would be nice to reduce the amount of clicking required.

---

When in this menu in quests and tasks, `T` should open the title edit menu.
![image](https://user-images.githubusercontent.com/15698722/197872455-9098417d-75bb-4ad1-92f9-5456bb670a3c.png)

---

![image](https://user-images.githubusercontent.com/15698722/197872628-3f48095f-e06d-4de7-aa08-555f65364711.png)
While in a quest, maybe `T` could open the title edit menu, `S` could open the subtitle edit menu, and `D` could open this?
![image](https://user-images.githubusercontent.com/15698722/197872684-02f44180-742f-4af4-9e35-dfa9427b3fae.png)

**Comment by aaronhowser1** [comment]
The task title edit keybind isn't working (if it's supposed to be implemented yet)

**Comment by desht** [comment]
How were you intending for that to work?  Pressing 'T' while hovering over the task button?

**Comment by aaronhowser1** [comment]
![image](https://user-images.githubusercontent.com/15698722/198820178-4b636cf3-42ff-4d8a-b7b9-9efe0789b257.png)
While in this menu, or after right-clicking the task

**Comment by desht** [comment]
Implemented in 1.18/1.19
