### ISSUE TITLE
[Bug]: Invalid player data using maybe caused by FTB essentials or FTB library

### ISSUE THREAD

**Issue by luizndh** [FTBTeam/FTB-Mods-Issues#516]
### Mod

FTB Essentials or FTB Library

### Mod version

ftb-essentials-1902.1.10-build.47 or ftb-library-forge-1902.3.9-build.144

### Forge / Fabric version

1.19.2 43.1.43

### Modpack & version

All the mods 8 - 1.19.2

### What issue are you having?

So I was playing on my own minecraft server earlier, and suddenly my pc restarted. After turning it on and opening my server again, I couldn't enter it and because I was getting an "Invalid player data" error. I searched it up and tried to delete my player .DAT file to reset my data, but the error persisted. I searched the logs and posted on minecraft forge forums, and some guy told me that could be FTB essentials or library based on the logs. I'll post them here.

![Answer](https://user-images.githubusercontent.com/79621478/198852568-3cf5d2b4-8032-43ff-9854-597b76db3bef.png) - The answer I got from the guy in the forums

OBS: I had other friends playing on the server too when my pc turned off, and they had no problem reconnecting after.

### Crashlogs

[https://pastebin.com/1cKyVkuk](url) - debug log

[https://pastebin.com/SyhkyVeA](url) - console log

### Steps to reproduce

1. Was running my minecraft server normally
2. PC got turned off
3. Tried getting back on
4. Invalid player data error

**Comment by luizndh** [comment]
UPDATE: I deleted my .DAT file from the ftbessentials and it worked.

**Comment by desht** [comment]
Yep, a crashed server can easily leave your .dat files in an invalid state.  This isn't a bug in Ranks or Essentials - they just reported problems reloading your .dat file afterward.
