### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by akex06** [FTBTeam/FTB-Mods-Issues#517]
### Mod

FTB Essentials

### Mod version

1802.1.7-build.42

### Forge / Fabric version

1.18.2 40.1.80

### Modpack & version

All The Mods 7

### What issue are you having?

The messages aren't sending and it posts this error
https://pastebin.com/CaBfR79G

### Steps to reproduce

I just talk in chat

**Comment by desht** [comment]
FTB Ranks 1802.1.7 is quite out of date now.  If you still have this problem, please update to the latest (1802.1.11) and test again.

Closing this - feel free to reopen if this is still a problem on the latest release.
