### ISSUE TITLE
[Bug]: FTB Quests right-click menu overflows game window

### ISSUE THREAD

**Issue by fengshuo2004** [FTBTeam/FTB-Mods-Issues#518]
### Mod

FTB Quests

### Mod version

ftb-quests-forge-1802.3.8-build.101

### Forge / Fabric version

1.18.2 40.1.84

### What issue are you having?

When the game is set to default GUI scale, the right click menu in FTB Quests will overflow the screen with no way to access the top half of it. Notice the items added by the _Quests Additions_ mod, which made this menu even longer.

The only way to see or click the top most buttons of this menu is to go into video settings and decrease the GUI scale.

My game is running at 1920x1080 full screen, but this bug occurs on windowed minecraft as well.

Below is a screenshot showing the problem:

![FTB Quests right click menu](https://user-images.githubusercontent.com/25703836/199353224-1aee1516-f4b2-4baa-999d-ee819716e0dd.png)

### Steps to reproduce

1. Install FTB Quests and Quests Additions for Forge 1.18.2
2. Launch game and open any save
3. Make sure you can edit quests by `/ftbquests editing_mode`
4. Navigate to the FTB Quests interface and right click on empty space

**Comment by desht** [comment]
In the short term, the only workaround is to use a smaller GUI scale, but there are several options for a proper fix, which will need some consideration:

1. Reduce the font scaling for the context menu if it's too big to on screen
2. Have a multi-column list if one column is too tall
3. Have a scrollable list (either via scrollbar or buttons at top/bottom of context menu)

**Comment by desht** [comment]
Fixed in recent release.  Context menu now uses more than one column if necessary to stay within screen height.
