### ISSUE TITLE
Disable PvP in claimed areas

### ISSUE THREAD

**Issue by LatvianModder** [FTBTeam/FTB-Mods-Issues#52]
FTBTeam/FTB-Mods-Issues#256

**Comment by desht** [comment]
FTB Chunks has never been a PvP protection mod, so there is no feature to enable.

**Comment by StevenG5** [comment]
I don't understand, it says this issue has been completed over a year ago to "Disable PvP in Claimed Areas". Am I wildly misreading this or something? I feel like the logical person would come to this thread and assume this feature has been implemented.

**Comment by desht** [comment]
Nope, that's just github reporting the issue closure.  Nothing was ever completed, or indeed even started with this feature request.

**Comment by erikvasilyan** [comment]
Actually now you can disable/enable pvp in claimed chunks just editing config file of mod
