### ISSUE TITLE
[Suggestion]: Adding the option to enable explosion damage to claimed chunks in 1.16.5 and higher

### ISSUE THREAD

**Issue by Ch4ra** [FTBTeam/FTB-Mods-Issues#520]
### Modpack

Ftb Chunks

### Is your suggestion related to a problem? Please describe.

Its really annoying when you try to build a farm with tnt and then cant claim it on an public server because the tnt doesnt break claimed blocks, since im the admin and would like to change that, could you please add the option to enable/disable the explosion protection.

**Comment by MichaelHillcox** [comment]
If I recall correctly, I have made this change for 1.18+

**Comment by Raidobw2** [comment]
I didn't know \o/ then this would be for a suggestion for the backport of this feature

**Comment by desht** [comment]
This will be in the next release for 1.16.5.
