### ISSUE TITLE
[Feature Request]: FTB Essentials (Forge) 1.19 is not marked for 1.19.2

### ISSUE THREAD

**Issue by drenough** [FTBTeam/FTB-Mods-Issues#525]
### Mod

FTB Essentials (Forge) 1.19.2

### Description

Hello, under your last file for 1.19 [ftb-essentials-1902.1.10-build.47.jar](https://www.curseforge.com/minecraft/mc-mods/ftb-essentials-forge/files/3963646) in changelog is stated "feat: ported to 1.19.2 - Michael Hillcox" and yet it's marked for 1.19 version and not 1.19.2 so I can not download that for my modpack on 1.19.2

### Describe the solution you'd like

Please mark your last 1.19 version of FTB Essentials (Forge) for 1.19.2 aswell please! Anyway, thanks for amazing work you guys doing!

**Comment by MichaelHillcox** [comment]
Fixed :+1: thanks for spotting that
