### ISSUE TITLE
[Bug]: 1.19.2 FTB Quests [optional] tasks still count as mandatory

### ISSUE THREAD

**Issue by FinxdMC** [FTBTeam/FTB-Mods-Issues#527]
### Mod

FTB Quests

### Mod version

ftb-quests-forge-1902.4.2-build.116

### Forge / Fabric version

forge 1.19.2 43.1.47

### What issue are you having?

quests/tasks has to be completed no matter if set as optional or not

![2022-11-07_15 45 26](https://user-images.githubusercontent.com/97098979/200325702-bc68165c-5d07-4430-a07f-2aa174b6d542.png) 

in the image above, i have set the stone quest as [optional] but i still won't get the dirt quest completed

i have tried this with a fresh minecraft instance and it still happens

### Steps to reproduce

1. create a new instance
2. install latest 1.19.2 Forge, with FTB Quests (and it's dependencies)
3. create 2 quests, for example, dirt and stone quest.
4. edit the dirt quest and under Dependencies, add the stone quest
5. set the stone quest as [optional]
6. try giving yourself some dirt. does it complete the dirt quest? if not, that's what i am experiencing. normally it should complete the dirt quest, because the stone quest is set as optional

**Comment by desht** [comment]
That's not what optional means - optional quests don't count toward chapter progress, and that's all.  If you don't want to require quest A to be completed to start quest B, simply don't make it a dependency of quest B.
