### ISSUE TITLE
[Bug]: Unable to see entity after rejoin world/server

### ISSUE THREAD

**Issue by ArenuZero** [FTBTeam/FTB-Mods-Issues#531]
### Mod

-

### Mod version

-

### Forge / Fabric version

1.18.2 40.1.84

### Modpack & version

FTB Stoneblock 1.0.2

### What issue are you having?

Unable to see all entity after attempting rejoin session

### Steps to reproduce

1. Leave session once
2. Unable to see entity (not even borders from F3+B or F3+G)

### Anything else to note?

Problem solves itself after restart Minecraft

**Comment by MichaelHillcox** [comment]
This isn't the right tracker for this and it's my understanding in newer versions of SB3, this has been resolved.
