### ISSUE TITLE
[Bug]: Incompatibility between newer KubeJS & FTBQuests

### ISSUE THREAD

**Issue by ImAK9** [FTBTeam/FTB-Mods-Issues#532]
### Mod

FTB Quests

### Mod version

ftb-quests-fabric-1902.4.2-build.116.jar

### Forge / Fabric version

Fabric (1.19.2-0.14.10)

### What issue are you having?

Using newer KubeJS ([KubeJS Fabric 1902.6.0-build.114](https://www.curseforge.com/minecraft/mc-mods/kubejs/files/4073867)) breaks FTB Quests. Gotta update your integration with it?

### Crashlogs

https://aofpaste.com/nodusaqono.yaml

### Steps to reproduce

**1.** Download [KubeJS Fabric 1902.6.0-build.114](https://www.curseforge.com/minecraft/mc-mods/kubejs/files/4073867)
**2.** Download [ftb-quests-fabric-1902.4.2-build.116.jar](https://www.curseforge.com/minecraft/mc-mods/ftb-quests-fabric/files/3994214)
**3.** Launch the game.

**Comment by desht** [comment]
FTB Quests 1902.4.3 was released yesterday and should work fine with the latest KubeJS release.

**Comment by ImAK9** [comment]
> FTB Quests 1902.4.3 was released yesterday and should work fine with the latest KubeJS release.
> 
> (Note: you'll also need the latest FTB Library, also just released)

Hey, latest [FTB Library](https://www.curseforge.com/minecraft/mc-mods/ftb-library-fabric/files/4076617) that was just uploaded is only tagged as "1.19" and not "1.19.2" therefore not showing up in the Curseforge App

**Comment by desht** [comment]
Thanks for pointing that out, it's fixed now.
