### ISSUE TITLE
[Feature Request]: Changing FTB utils and lib 1.7.10 license to something permissive

### ISSUE THREAD

**Issue by trollogyadherent** [FTBTeam/FTB-Mods-Issues#533]
### Mod

FTB Utils/Lib

### Description

Would it be possible to re-license the 1.7.10 branch to something like lgpl or mit? I would like to add compat to a mod of mine, and generally tinker with it without needing to make PR's every time.

**Comment by MichaelHillcox** [comment]
We won't be doing that. You can depend on our code without breaking our license so if you wanted to make a compatibility mod, you can.

**Comment by trollogyadherent** [comment]
In the meantime I found this and just forked the repo: 
https://github.com/GTNewHorizons/FTB-Utilities/
![image](https://user-images.githubusercontent.com/19153947/203315716-e7a80805-0de6-43f1-8c01-e474c8eef8d5.png)
