### ISSUE TITLE
[Bug]: FTB Quests 1902.4.3-build.140 requires ftblibrary 1903.3.10-build.155

### ISSUE THREAD

**Issue by pandory-network** [FTBTeam/FTB-Mods-Issues#535]
### Mod

FTB Quests

### Mod version

ftb-quests-forge-1902.4.3-build.140

### Forge / Fabric version

Forge 1.19.2 43.1.47

### What issue are you having?

FTB Quests 1902.4.3-build.140 requires ftblibrary 1903.3.10-build.155 which is not available on curseforge

![2022-11-10 00_12_27-Minecraft_ 1 19 2](https://user-images.githubusercontent.com/5018275/200962415-82d18883-a967-46ff-8f2c-da164b647a53.png)

### Steps to reproduce

Start Minecraft with FTB Quests 1902.4.3-build.140 with latest FTB Library which is available on curseforge ([ftb-library-forge-1902.3.9-build.144.jar])

![2022-11-10 00_12_27-Minecraft_ 1 19 2](https://user-images.githubusercontent.com/5018275/200962989-e083b2c6-6724-45e3-b912-9d9a5493e4ba.png)

**Comment by desht** [comment]
A valid version of FTB Library is now available at https://www.curseforge.com/minecraft/mc-mods/ftb-library-forge/files/4076618, apologies for the delay in getting this dependency published.
