### ISSUE TITLE
[Bug]:  1.7.10 ftbu crash  (Exception getting block type in world)

### ISSUE THREAD

**Issue by kotmatross28729** [FTBTeam/FTB-Mods-Issues#537]
### Mod

FTB Utilities

### Mod version

FTBUtilities-1.7.10-1.0.18.3

### Forge / Fabric version

1.7.10/10.13.4.1614

### What issue are you having?

when I create a new world there is a chance that the game will crash with this error

### Crashlogs

https://paste.feed-the-beast.com/view/dc72f4ac

### Steps to reproduce

1.enter the game with FTBUtilities and FTBLib
2.`safe_spawn` must be enabled in configs
3.create 5-10 worlds (usually 2-3 is enough)
4. the game crashes when creating one of these worlds

**Comment by Gaz492** [comment]
Due to the age of the minecraft version and mod, we currently don't have any plans on releasing an update to fix this issue.
