### ISSUE TITLE
[Bug]: The total claims for a team doesn't stack from each player's max

### ISSUE THREAD

**Issue by Nathan22211** [FTBTeam/FTB-Mods-Issues#540]
### Mod

FTB Teams

### Mod version

forge:1802.2.7-build:71

### Forge / Fabric version

1.18.2 forge 40.1.84

### Modpack & version

FTB Stoneblock 3 1.2.0

### What issue are you having?

I'm in a team with 2 others in a server. one of whom can claim twice as much due to rank. In total we should be able to claim 200 chunks and 16 force-loaded ones. However, I'm not able to utilize my VIP teammate's chunks, and my chunk count is showing over max because of him claiming chunks for my team. We're limited to 100 claims and 10 force loads, and we can only change chunk claims when he's online.

### Steps to reproduce

1: have one person able to claim more than another
2: have person 2 claim more than person 1 max chunk count
Something similar should happen with forceloadsone

### Anything else to note?

We're a few versions behind due to Stoneblock 3 being in beta, but I doubt the FTB teams and chunk-claiming versions have changed much

**Comment by desht** [comment]
Which player here is the party leader?

**Comment by Nathan22211** [comment]
I'm the one who created the party. I don't have any special rank on the server though so I'm limited to the minimum pretty much.

**Comment by desht** [comment]
OK, thanks.  The limit-updating logic does look quite strange right now, and I need to figure out a better way of doing this (possibly making the party limit either the largest of all team members, or the sum of all team members' limits, or clamped to the party leader's limits).  Possibly a new server configurable for this?  Open to suggestions on this :)

**Comment by desht** [comment]
There is a new server side setting: `Party Limit Calculation Mode` which determines how an aggregate team limit is calculated:

* LARGEST: use the limits of the member with the largest limits
* SUM: add up all the members' limits
* OWNER: use the party owner's limits only
* AVERAGE: use the average of all members' limits.

Default is LARGEST, but can be changed in config now.

In addition there `Hard Team Claim Limit` and `Hard Team Force Limit` settings which can be used to impose a hard maximum on the calculated values (e.g. very large teams might need a limit to avoid allowing thousands of chunks to be force-loaded).
