### ISSUE TITLE
FTBQuests Crashing game when attempting to open Questbook in Engineer's Life 2

### ISSUE THREAD

**Issue by 2ndRecon** [FTBTeam/FTB-Mods-Issues#542]
### Mod

FTB Quests

### Mod version

ftb-quests-forge-1605.3.6-build.98

### Forge / Fabric version

forge-1.16.5-36.2.33.

### Modpack & version

Engineer's Life 2 1.17 [MC 1.16.5]

### What issue are you having?

Game crashed upon attempting to open FTB Quests book. 

<script src="https://gist.github.com/2ndRecon/58eca8e0fba62fd65fa0276504c596e4.js"></script>

<script src="https://gist.github.com/2ndRecon/123e5ae88da9c777da2ba3e69ca951d2.js"></script>

### Crashlogs

<script src="https://gist.github.com/2ndRecon/123e5ae88da9c777da2ba3e69ca951d2.js"></script>

### Steps to reproduce

Run EL2 v. 1.17 
Connect to EL2 dedicated server
attempt to open the quest book

**Comment by desht** [comment]
The linked crash log is not a crash log at all.  Please attach an actual crash log to the report.

**Comment by 2ndRecon** [comment]
No crash log is produced. The client silently closes / crashes to desktop. It's easily duplicated with the above steps.

**Comment by 2ndRecon** [comment]
desht,

When I search for this crash / EL2 crashing on questbook open there actually are several other reports, NOT dozens, but several others. I have also searched the discord and found people with the same issue.

NOTE: I am not suggesting this is an FTB issue, but this mod is in the Engineer's Life:2 pack 1.17 so I am chasing down the issue with the persistent crash. 

I'm very surprised you were unable to duplicate the issue with my steps, because I loaded all this from fresh install on a different PC and got the same result.

Here is a Gist of a crashlog demonstrating the quiet crash. I had to go back into the loader and dig this out, because it doesn't report any crashdump to my screen. 

https://gist.github.com/2ndRecon/22f4bb21fc0161aaaf2f44d267463361


Another user reported that they had to load 'questadditions' server-side to resolve this issue. I have reached out to the pack author to determine if this is in fact the issue. 


Thanks as always for looking into it, just trying to be thorough.

-2R-

**Comment by 2ndRecon** [comment]
Thank you, sorry these were going into my spam folder. So weird. 

I have since just moved on from this pack. I believe the pack author has been significantly impacted by the War in Ukraine and it may be abandoned due to real life. 

I may pick this back up in which case I really do appreciate you being thorough and providing this root cause analysis so at least we have an audit trail for the issue. (these things tend to pop up in clusters, of course.) So perhaps this log will provide someone else with a fix. 

Cheers +!
