### ISSUE TITLE
[Bug]: FTBquests - Adding Stage via reward isnt picked up by other mods

### ISSUE THREAD

**Issue by whosursensei** [FTBTeam/FTB-Mods-Issues#544]
### Mod

FTBquests

### Mod version

ftb-quests-forge-1802.3.10-build.138

### Forge / Fabric version

1.18.2 40.1.85

### What issue are you having?

If you add a Stage via reward, CraftTweaker nor KubeJS picks it up. But if i add the "/gamestage add @p Stage1" as a command reward, works just fine. 

Technically it gives you the stage, but you need to f3+t for it to apply to everything. With the command reward no reload is needed

### Steps to reproduce

1. Block a mod via Itemstage/recipestage (Crafttweaker), You can make a event send a message via the GameStageAdded for debug
2a. Add a checkmark quest with Stage as reward (FTBquests)
3a. Completing quest will add stage (/gamestage check) but will not trigger any scripts

2b. Add a checkmark quest with command as reward, using "/gamestage add @p Stage1" (FTBquests)
3b. Completing quest will add stage (/gamestage check) and trigger all scripts

**Comment by desht** [comment]
Can I check which version of KubeJS you have installed?

FTB Quests uses KubeJS to add stages when it's present, even if Gamestages is also present, since recent versions of KubeJS update Gamestages when it's loaded.  It's possible you have an older version of KJS installed?

**Comment by desht** [comment]
Closing due to lack of response.
