### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by M003R** [FTBTeam/FTB-Mods-Issues#546]
### Mod

FTB Quests

### Mod version

1902.3.10-build.156

### Forge / Fabric version

forge 1.19.2

### Modpack & version

Astropolis on forge

### What issue are you having?

The Mod says that it failed to load properly 
code says this: java.lang.reflect.InvocationTargetException: null

### Steps to reproduce

1. I start the modpack
2. mod pack boots up
3. gets and mod loading failure

**Comment by MichaelHillcox** [comment]
Actual log please
