### ISSUE TITLE
[Feature Request]: Chunks Loaded lines

### ISSUE THREAD

**Issue by manmaed** [FTBTeam/FTB-Mods-Issues#550]
### Mod

FTB Chunks

### Description

Can we get the chunks that are loaded lines bolder and the ability to change the color

**Comment by desht** [comment]
This is fixed in the latest 1.19.2 release, and will be in the next 1.18.2 release, coming very soon.

Hatching is much thicker, and while not changeable, is set to always contrast with the background (team color), so is now highly visible.

**Comment by desht** [comment]
Fixed in 1.18/1.19
