### ISSUE TITLE
[Bug]: crash after opening ftb quests

### ISSUE THREAD

**Issue by czychuuu** [FTBTeam/FTB-Mods-Issues#551]
### Mod

ftb quests

### Mod version

forge-1605.3.6-build.76

### Forge / Fabric version

1.16.5 36.2.34

### What issue are you having?

Everytime i try to open quests menu my mc crashes

### Crashlogs

https://pastebin.com/NRMZtpiX

### Steps to reproduce

1. open quests with " ` " key

**Comment by KreverRol** [comment]
where is upload the mod with the issue fixed?

**Comment by desht** [comment]
It hasn't been released yet (which is is why the status is "fixed **in dev**")

A new 1.16.5 release will be coming soon.

**Comment by desht** [comment]
Fixed in latest 1.16.5 release
