### ISSUE TITLE
[Bug]: Crashing on world join

### ISSUE THREAD

**Issue by ShadowkillerGB** [FTBTeam/FTB-Mods-Issues#552]
### Mod

FTB Chunks

### Mod version

ftb-chunks-forge-1605.3.2-build.115.jar

### Forge / Fabric version

1.16.5 36.2.34

### Modpack & version

Private modpack by me

### What issue are you having?

If I want to join a singelplayer world, Minecraft crashes.
I don't know if it is the same on servers but I think it is.

### Crashlogs

[crash-2022-11-23_16.15.39-client.txt](https://github.com/FTBTeam/FTB-Mods-Issues/files/10076955/crash-2022-11-23_16.15.39-client.txt)

### Steps to reproduce

1. Installing the mods as they are listed in the crash log
2. Joining a singleplayer world

### Anything else to note?

If needed I can upload the mods folder to make it easier to reproduce

**Comment by desht** [comment]
That Sodium mod in your instance is an unofficial Forge port, and looks to be extremely out of date, in that it's trying to call into a much older version of FTB Chunks than you have installed.   We can not support usage of FTB Chunks with that mod, sorry.

If you need a video optimization mod, I'd suggest using Rubidium for 1.16.5 instead, which should be much more up to date: https://www.curseforge.com/minecraft/mc-mods/rubidium
