### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by LindaJuffermans** [FTBTeam/FTB-Mods-Issues#554]
### Mod

FTB Chunks

### Description

We would like more flexibility in the blacklisting of dimensions where chunks can be claimed. We have a custom mod that generates and deletes dimensions on demand but because the name uses a UUID it cannot be blacklisted.

### Describe the solution you'd like

Option1: Allow a blacklist wildcard, e.g. "modid:*"
Option2: Allow a whitelist, e.g. and empty blacklist and a whitelist with "minecraft:overworld" would block claiming anywhere else.

### Describe alternatives you've considered

The only alternative is a different claims mod.

**Comment by desht** [comment]
Added in 1902.3.21
