### ISSUE TITLE
[Feature Request]: FTB Essentials Fabric

### ISSUE THREAD

**Issue by Wolfkid200444** [FTBTeam/FTB-Mods-Issues#555]
### Mod

FTB Essentials

### Description

Since majority Suite Mods have a counter part like FTB Ranks or FTB Backup have support for Fabric i was wondering if it would be possible if FTB Essentials would get the same treatment as the rest.

**Comment by desht** [comment]
Apologies for the slow response here: yes, a Fabric version is planned for hopefully the near future.

**Comment by MichaelHillcox** [comment]
Fabric essentials has been released https://www.curseforge.com/minecraft/mc-mods/ftb-essentials-forge/files/4610351
