### ISSUE TITLE
[Bug]: Game Crashing 

### ISSUE THREAD

**Issue by BananaGuru17** [FTBTeam/FTB-Mods-Issues#556]
### Mod

All/Any

### Mod version

Any/All

### Forge / Fabric version

Any/All

### Modpack & version

Any/All

### What issue are you having?

none of the mods will open a world, and crashes before it even opens the game sometimes. My brother and i both have this problem. Normal Minecraft runs but nothing on FTB will run for us. 

### Steps to reproduce

1. i pick a modpack to play
2. let it load
3. either loads and then crashes
4. or it crashes before finishing download.
5.

**Comment by manmaed** [comment]
latest log please

**Comment by BananaGuru17** [comment]
what do you mean, ive tried infinity evolved, ftb lite, both the academy's. none of them will even open.

**Comment by BananaGuru17** [comment]
ive tried uninstalling and reinstalling ftb 7 times.

**Comment by manmaed** [comment]
is this only on the FTB App or other launchers?

**Comment by BananaGuru17** [comment]
It’s just ftb, I can run normal minecraft fine. I can also run Revelation but that’s just a beta. Sent from my iPhoneOn Nov 25, 2022, at 6:43 PM, manmaed ***@***.***> wrote:﻿
is this only on the FTB App or other launchers?

**Comment by BananaGuru17** [comment]
Now Relevation wont run. I have no problem with running normal Minecraft. Its just FTB.

**Comment by manmaed** [comment]
Please use the link below to download and run the FTB Debug tool. This tool will provide you a code that you can give to the support team which they can use to support your issue more specifically. The code will look like FTB-DBGAOIDOSDII. If you are unsure on how to use this tool, please [follow this guide](https://go.ftb.team/ftbdbg-support).

Windows
[ftb-debug.exe](https://dist.creeper.host/tools/ftb-debug/ftb-debug.exe)
MacOS
[ftb-debug-macos](https://dist.creeper.host/tools/ftb-debug/ftb-debug-macos)
Linux
[ftb-debug-linux](https://dist.creeper.host/tools/ftb-debug/ftb-debug-linux)
Windows (Arm)
[ftb-debug-arm64.exe](https://dist.creeper.host/tools/ftb-debug/ftb-debug-arm64.exe)
MacOS (Arm)
[ftb-debug-macos-arm64](https://dist.creeper.host/tools/ftb-debug/ftb-debug-macos-arm64)
Linux (Arm)
[ftb-debug-linux-arm](https://dist.creeper.host/tools/ftb-debug/ftb-debug-linux-arm)
