### ISSUE TITLE
crash: 

### ISSUE THREAD

**Issue by wraith1981** [FTBTeam/FTB-Mods-Issues#557]
### Mod

stoneblock 2

### Mod version

FTBPresentsStoneblock2-1.16.1-1.12.2.zip-overrides

### Forge / Fabric version

ftb app 1.4.1

### Modpack & version

FTBPresentsStoneblock2-1.16.1-1.12.2.

### What issue are you having?

keeps crashing on world loading.

### Crashlogs

[hs_err_pid14304.log](https://github.com/FTBTeam/FTB-Mods-Issues/files/10095351/hs_err_pid14304.log)

### Steps to reproduce

every time i try to load the game

### Anything else to note?

not tech savy

**Comment by manmaed** [comment]
can you uploaded the latest log please

**Comment by wraith1981** [comment]
That should be the latest one.

**Comment by wraith1981** [comment]
Thinking it may be a hardware issue. Was able the play a smaller pack with
some stuttering. Rocking a old i3 and 16gb of ram. Got a i7 comming soon.
But wanted to make sure it wasn't a program issue

**Comment by wraith1981** [comment]
[hs_err_pid14072.log](https://github.com/FTBTeam/FTB-Mods-Issues/files/10096870/hs_err_pid14072.log)

**Comment by wraith1981** [comment]
new crash log

**Comment by manmaed** [comment]
Please use the link below to download and run the FTB Debug tool. This tool will provide you a code that you can give to the support team which they can use to support your issue more specifically. The code will look like FTB-DBGAOIDOSDII. If you are unsure on how to use this tool, please [follow this guide](https://go.ftb.team/ftbdbg-support).

Windows:
[ftb-debug.exe](https://dist.creeper.host/tools/ftb-debug/ftb-debug.exe)
Windows (Arm):
[ftb-debug-arm64.exe](https://dist.creeper.host/tools/ftb-debug/ftb-debug-arm64.exe)

MacOS
[ftb-debug-macos](https://dist.creeper.host/tools/ftb-debug/ftb-debug-macos)
MacOS (Arm)
[ftb-debug-macos-arm64](https://dist.creeper.host/tools/ftb-debug/ftb-debug-macos-arm64)

Linux
[ftb-debug-linux](https://dist.creeper.host/tools/ftb-debug/ftb-debug-linux)
Linux (Arm)
[ftb-debug-linux-arm](https://dist.creeper.host/tools/ftb-debug/ftb-debug-linux-arm)

**Comment by wraith1981** [comment]
FTB-DBGIFOXULUPUN

**Comment by manmaed** [comment]
Looks like a GPU driver issue. Might be fixed by using java 8u51

**Comment by wraith1981** [comment]
How do I do that?

**Comment by wraith1981** [comment]
Would this work for stoneblock 3 as well. I am having the same issue there
