### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by EinsWlanKabel** [FTBTeam/FTB-Mods-Issues#561]
### Mod

FTB Chunks

### Mod version

ftb-chunks-forge-1902.3.9-build.168

### Forge / Fabric version

1.19.2 43.1.7

### What issue are you having?

Chests from the [Expanded Storage](https://www.curseforge.com/minecraft/mc-mods/expanded-storage) mod can still be opened in other players claims.

### Steps to reproduce

1. Claim chunks
2. Place Expanded Storage Chests
3. Other players can now open them too

### Anything else to note?

Expanded Storage mod version: expandedstorage-8.0.5+1.19.2-forge
[Expanded Storage Issue](https://gitlab.com/Ellemes/expanded-storage/-/issues/6)

**Comment by Ellemes** [comment]
If `dev.ftb.mods.ftbchunks.data.FTBChunksAPI` is safe to use by other mods then I can have this properly fixed on my end.

**Comment by MichaelHillcox** [comment]
You're welcome to use the API, but know that things can change without warning whilst we're still properly defining our API's

**Comment by BucketOfCompasses** [comment]
This has been fixed on our end by changing how our blocks are implemented rather than trying to implement code support for all claim mods.
