### ISSUE TITLE
[Bug]: FT Teams 1.19 is not flagged as 1.19.2

### ISSUE THREAD

**Issue by ZEROX7** [FTBTeam/FTB-Mods-Issues#563]
### Mod

FTB teams

### Mod version

ftb-teams-forge-1902.2.10-build.76.jar

### Forge / Fabric version

forge

### What issue are you having?

pls flag the mod as 1.19.2 as the file name suggests

### Steps to reproduce

look at mod page trough curseforge app

**Comment by desht** [comment]
Fixed now.

(Also fixed game version for FTB Ranks)
