### ISSUE TITLE
[Bug]: Crash when in FTB Quests mouseClicked event handler

### ISSUE THREAD

**Issue by Gamerbolts** [FTBTeam/FTB-Mods-Issues#564]
### Mod

FTB Quests

### Mod version

ftb-quests-fabric-1902.4.3-build.140

### Forge / Fabric version

1.19.2 0.14.10

### Modpack & version

Personal Modpack

### What issue are you having?

I was just in my modpack and clicked around the FTB Quests window and got a crash, says mouseClicked event handler.

### Crashlogs

[latest.log](https://github.com/FTBTeam/FTB-Mods-Issues/files/10118137/latest.log)
[crash-2022-11-29_17.13.45-client.txt](https://github.com/FTBTeam/FTB-Mods-Issues/files/10118138/crash-2022-11-29_17.13.45-client.txt)

### Steps to reproduce

I am not sure how to reproduce without having my modpack installed which is not available on curseforge as of yet.

**Comment by Gamerbolts** [comment]
I see this was fixed in Dev, any news on when that release will come out on CurseForge? I can't continue my questlines til it's fixed :(

**Comment by desht** [comment]
Fixed in current quests releases for 1.18/1.19
