### ISSUE TITLE
[Bug]: server crash after player disconnected

### ISSUE THREAD

**Issue by ZEROX7** [FTBTeam/FTB-Mods-Issues#571]
### Mod

FTB Chunks

### Mod version

ftb-chunks-forge-1902.3.11-build.194.jar

### Forge / Fabric version

1.19.2 43.1.58

### Modpack & version

Singularity Create

### What issue are you having?

after a player disconnected the server crashed

### Crashlogs

[crash-2022-12-06_22.44.02-server.txt](https://github.com/FTBTeam/FTB-Mods-Issues/files/10170462/crash-2022-12-06_22.44.02-server.txt)

### Steps to reproduce

IDK

**Comment by desht** [comment]
Fixed in 1902.3.13 (hopefully - I couldn't reproduce the problem myself).

**Comment by Glease** [comment]
Hi. Can we backport the fix to MC 1.18? I'm also having this issue with ftb-chunks-forge-1802.3.9-build.202.jar. The symptom and crashreport is almost identical. The method in question is the same for FTB chunks on 1.18 and 1.19 as well, so I believe a cherrypick is needed.

**Comment by desht** [comment]
Yes, I'll try to get that done today.
