### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by asheden** [FTBTeam/FTB-Mods-Issues#572]
### Mod

FTB Ranks

### Description

where's any of the relevant info???? is this mod server side only? what does it look like when applied? what does each command do? you put literally 1 screenshot up and called it a day

**Comment by desht** [comment]
FTB Ranks wiki documentation is here: https://feedthebeast.notion.site/FTB-Ranks-d56ec50cfa04412485ff0bf63d103b4d

It's still not very complete, but mod documentation is something we're aware of, and working on.

**Comment by MichaelHillcox** [comment]
Closing as it's not an issue
