### ISSUE TITLE
[Bug]: My game crashes every time I launch it.

### ISSUE THREAD

**Issue by sharpkyle16** [FTBTeam/FTB-Mods-Issues#574]
### Mod

FTB Stoneblock 3

### Mod version

FTB Stoneblock 3 1.4.2

### Forge / Fabric version

idk what this is

### Modpack & version

FTB Stoneblock 3

### What issue are you having?

It is crashing as soon as I launch. 

### Steps to reproduce

As soon as it Iaunches, it loads and then crashes.

**Comment by manmaed** [comment]
This is the wrong tracker to be reporting this to! but the issue is with Better then llamas so you can remove that mod or change your clock so its not the 9th 
pacj crashes go to https://github.com/FTBTeam/FTB-Modpack-Issues/
Main Issue: https://github.com/FTBTeam/FTB-Modpack-Issues/issues/2269
