### ISSUE TITLE
[Bug]: Direwolf 1.18.2 1.10.2 Wont Start

### ISSUE THREAD

**Issue by DocCodeSharp** [FTBTeam/FTB-Mods-Issues#576]
### Mod

Curious Elytra, Cyclic, Functional Storage

### Mod version

curiouselytra-forge-1.18.1-5.0.1.0, Cyclic-1.18.2-1.7.3, functionalstorage-1.18.2-1.0.1

### Forge / Fabric version

forge-1.18.2-40.1.84-server.jar

### Modpack & version

Direwolf 1.18.2 1.10.2

### What issue are you having?

When trying to start the server with the Linux download file for Direwolf 1.18.2 1.10.2 it does not work. The install put all the files in the location wanted, but the moment that start.sh is ran it fails to start Minecraft due to 3 mods that will not load.

### Crashlogs

https://pastebin.com/36urWf9y

### Steps to reproduce

Running start.sh on Linux server ubuntu 20.04

**Comment by manmaed** [comment]
This is the wrong tracker to be reporting this to! 
Pack crashes go to https://github.com/FTBTeam/FTB-Modpack-Issues/
