### ISSUE TITLE
[Bug]: Server crashes whenever someone leaves

### ISSUE THREAD

**Issue by JonWisniewski** [FTBTeam/FTB-Mods-Issues#577]
### Mod

FTB Chunks

### Mod version

ftb-chunks-fabric-1902.3.11-build.194.jar

### Forge / Fabric version

fabric-loader 0.14.10

### Modpack & version

CF_AOF6_1.0.2

### What issue are you having?

When a player leaves the server sometimes, especially while holding an item, the server will crash after they leave.

### Crashlogs

https://paste.feed-the-beast.com/view/b19542f2

### Steps to reproduce

It is hard to reproduce since it is random, but it has happened when either you log out of the server when holding an item (Cobblestone), or force quit (alt + f4).

**Comment by Zarathaen** [comment]
Ran into the same problem.
Minecraft: 1.18.2
FTB Chunks: 1802.3.9-build.202
Forge: 40.1.86

Modpack: Industry, Exploration, & Arcana (CurseForge)

It seems to randomly occur when people leave the server. It isn't every time, or even frequently. Occasionally we'll just get a crash for seemingly no reason.

**Comment by desht** [comment]
Already fixed, update to the latest FTB Chunks (1902.3.13)

**Comment by desht** [comment]
Now fixed in for 1.18.2 as well, update to 1802.3.10.
