### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by MrBlaze789** [FTBTeam/FTB-Mods-Issues#578]
### Mod

FTB Chunk

### Description

Hello,
I'm currently on the Stoneblock 3 modpack. I'm playing local and wish I had more home. How to increase the maximum number please.
Sorry for my English, my text is translated by google translate

**Comment by desht** [comment]
Maximum claim and force load size is set in the `saves/<world>/serverconfig/ftbchunks-world.snbt` config file.
* With your insttance not running, edit that file
* Look for `max_claimed_chunks` and/or `max_force_loaded_chunks` and edit as you need
* Restart your instance

Note that next FTB Chunks release will allow editing of server config settings while in-game, but for now you will need the config file from outside the game, as above.
