### ISSUE TITLE
[feature] Option for limited-time chunkloading

### ISSUE THREAD

**Issue by NielsPilgaard** [FTBTeam/FTB-Mods-Issues#58]
The need for chunkloading is often only until some work is completed, for example a Quarry finishing an area, a farm getting a certain amount of crops, etc. 

Being able to only chunkload for lets say 24 hours could potentially help server performance immensely, as fewer chunks would be chunkloaded continually.

I have a suggest for how the time could be set - When in the chunk claiming/loading map, the player could use the scroll wheel to set time to chunkload in hours.

**Comment by bookerthegeek** [comment]
An option to have the offline chunks unload automatically on server start would be another option for server owners that I think would be a nice feature.

**Comment by zediious** [comment]
I think having a configuration option similar to the following would be fantastic, setting a hard time limit on loaded chunks after a player has logged off.
`# Time in hours before a player's chunkloaders become inactive.
MaxHoursOffline=12`

**Comment by Raidobw2** [comment]
This could be implemented while bugfixing #101

**Comment by desht** [comment]
Fixed in 1.18/1.19

Can use mouse wheel on force loaded chunks to set a force-loading time limit (hours->days->weeks)

**Comment by NielsPilgaard** [comment]
Thank you ❤
