### ISSUE TITLE
[Feature Request]: Toggle FTBChunks map with KubeJS Stages

### ISSUE THREAD

**Issue by lamoyrl90** [FTBTeam/FTB-Mods-Issues#580]
### Mod

FTB Chunks

### Description

Currently, as far as I'm aware, FTBChunks has no method to toggle the availability of its maps to players. This limits the option of using this mod in certain styles of pack (think SevTech).

### Describe the solution you'd like

A global forced "off" switch available through scripting. As the mod already has some integration with KubeJS, it's probably a good route to take if this suggestion were to be implemented.

### Describe alternatives you've considered

The only two routes I can see as options currently are: 

1) Have item-based map mods such as MapAtlas or Antique Atlas.

2) Give stone-age denizens of the cuboid variety perfect memory of their locations and the ability to see in a 360 degree circle around them, including nearby threats. I wouldn't mind this quite as much if it didn't completely obsolete vanilla maps.

**Comment by desht** [comment]
I've gone with option A for now at least: player will see everything once they get the stage.

**Comment by lamoyrl90** [comment]
I feel like it would be nice to have both options available, to be decided by the server

**Comment by desht** [comment]
Yep, agreed.
