### ISSUE TITLE
[Bug]: Auto pickup affix from Apotheosis is incompatible with FTB Ultimine

### ISSUE THREAD

**Issue by James103** [FTBTeam/FTB-Mods-Issues#581]
### Mod

FTB Ultimine

### Mod version

1902.3.5-build.65

### Forge / Fabric version

Forge 43.1.55

### Modpack & version

All the Mods 8 version 1.0.4 (also happens in minimal environment)

### What issue are you having?

The auto-pickup affix from the Apotheosis mod ("Block drops will teleport to you") does not work when FTB Ultimine is active.
This leads to not all items being picked up if mining with FTB Ultimine active and a large reach distance as granted by Apotheosis (presumably to clear out an area and/or gather hundreds to thousands of blocks per minute).

### Steps to reproduce

Per https://github.com/Shadows-of-Fire/Apotheosis/issues/718:

(versions listed here are what's in my current ATM8 instance as of the time of writing and are not necessarily latest)

1. Create a new instance with Minecraft 1.19.2 and Forge 43.1.55.
2. Install Placebo 7.0.1 and Apotheosis 6.0.1.
3. Install FTB Ultimine `1902.3.5-build.65`, FTB Library `1902.3.10-build.156`, and Architectury API `6.3.56`.
4. Create a new world with cheats enabled.
5. Give yourself a Netherite Pickaxe.
6. Give yourself some GodForged Pearls and a Reforging Table.
7. Repeatedly reforge the tool until one of its effects say "Block drops will teleport to you" (hereafter referred to as the auto-pickup affix).
8. Go into survival mode: `/gamemode survival`
9. Mine a block normally and notice the drop is automatically sent to your inventory.
10. Use FTB Ultimine to mine a bunch a blocks.
11. Notice none of the drops were automatically sent to your inventory.

### Anything else to note?

See also https://github.com/Shadows-of-Fire/Apotheosis/issues/718

@Shadows-of-Fire's response:

> Detecting block drops is _very_ difficult (even the existing functionality already uses a mixin). The current system in place hooks into `Block#dropResources` and moves and dropped entities from that method to the player, but if ultimine doesn't utilize that method, it won't get picked up. I'm not sure what ultimine does, but I think hooking into it would be extremely fragile, so I'll have to opt to allow it to remain as-is.

**Comment by desht** [comment]
Having looked at how both Apotheosis and Ultimine do this, I concur with Shadows-of-Fire that any kind of integration here would be extremely fragile. Given that Ultimine already moves dropped items to the initially broken block (which is generally within easy reach of the player), I'm also going to opt to leave this as-is, sorry.
