### ISSUE TITLE
[Bug]: Numpad Enter does not function as Enter in most GUIs

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-Mods-Issues#582]
### Mod

FTB Library(?)

### Mod version

ftb-library-fabric-1902.3.10-build.162

### Forge / Fabric version

Fabric 1.19.2 0.14.11

### What issue are you having?

![image](https://user-images.githubusercontent.com/15698722/206945878-9ceb0242-36d6-468e-b011-2c50776e256c.png)

Hitting Enter here works, but not Numpad Enter

### Steps to reproduce

.

**Comment by desht** [comment]
Fixed in latest FTB Library release
