### ISSUE TITLE
[Bug]: FTB Chunks chunkloading broken across dimensions

### ISSUE THREAD

**Issue by iTitus** [FTBTeam/FTB-Mods-Issues#595]
### Mod

FTB Chunks

### Mod version

ftb-chunks-forge-1802.3.8-build.199 and newer

### Forge / Fabric version

1.18.2 40.1.84

### Modpack & version

AllTheMods7 - To The Sky - 1.1.8

### What issue are you having?

FTB Chunks does not keep chunks loaded in other dimensions since build 199.
I don't know if this is a mod pack issue, but that ticket is over at https://github.com/AllTheMods/All-the-mods-7-Sky/issues/372

It could be that all chunk loading is broken, not only cross dimensional. But I only noticed it across dimensions.

### Steps to reproduce

1. Claim and force load some chunks in the Nether, far away from any spawn chunks or other shenanigans and build some machinery there, so that you can check if the chunks were loaded
2. Go to the Overworld and wait for the other chunks to unload and then wait some more
3. Go back to the Nether and notice that the chunks were not loaded during your away time

=> Easiest to see with some kind of ender chest setup

**Comment by desht** [comment]
I don't think build 199 is relevant to this, but there are problems here, yes.  I suspect the issues are related to using Forge's chunk loading functionality instead of vanilla's, and I'm working on an experimental build which just uses vanilla chunk loading (equivalent to using the `/forceload` command).  So far the results are promising, but more testing is needed.

Forge's chunkloading isn't truly necessary here, since FTB Chunks does all the forced-chunk tracking that we need (and in any case isn't available in the Fabric build of the mod).

**Comment by iTitus** [comment]
Build 199 was significant in my case because build 172 worked just fine (that's what I downgraded to).
So do you think there is an issue on Forge's side or are you using it wrong - maybe due to the double modloader compat?

**Comment by desht** [comment]
Are you in a position to try a dev build?  https://maven.saps.dev/releases/dev/ftb/mods/ftb-chunks/1802.3.11-build.214/ftb-chunks-1802.3.11-build.214.jar should fix the problem (been testing with furnaces in the nether for the last couple of hours, and it seems to be working very well, including server restarts).

Obviously I don't recommend running a dev build on a production server, but if you have a test environment, that would be great.

**Comment by iTitus** [comment]
I do not have a dev environment set up right now, I could only check this in that modpack installation (ATM7: TTS, Forge).

**Comment by iTitus** [comment]
Does your dev build work with Forge 1.18 ?

**Comment by desht** [comment]
Yes, it does - it's a drop-in replacement for the current release.  If you have a single-player world it should be fine to drop in and test.  As always, making a world backup is recommended.

**Comment by iTitus** [comment]
The mod you send does not load, you sure it is a valid Forge mod?

**Comment by desht** [comment]
Sorry, try this URL: https://maven.saps.dev/releases/dev/ftb/mods/ftb-chunks-forge/1802.3.11-build.214/ftb-chunks-forge-1802.3.11-build.214.jar

**Comment by iTitus** [comment]
This build seems to work in my single player test world.
Chunk loading across dimensions and also in a single dimension works.

**Comment by desht** [comment]
Excellent news.  I'll hopefully have a new release out this week.

**Comment by iTitus** [comment]
The version was released as build 217 on curse forge, so I think this issue can be closed, right?
