### ISSUE TITLE
[Bug]: FTB Chunks Blank Map Screen

### ISSUE THREAD

**Issue by Sarelth** [FTBTeam/FTB-Mods-Issues#596]
### Mod

FTB Chunks

### Mod version

ftb-chunks-forge-1802.3.11-build.213.jar

### Forge / Fabric version

1.18.2

### Modpack & version

Vault Hunters 3rd

### What issue are you having?

The server added the FTB Chunks mod so we could claim chunks. Some people, myself included, get a blank screen for Large map and claim chunk screen, while others have no issues at all.

### Steps to reproduce

Installed the pack, then added the following FTB mods, 
Ranks, Chunks, Teams, Essentials, and Library.

**Comment by desht** [comment]
There's not much info to go on here.  Are all of you on exactly the same versions of the client-side mods?

What do you mean exactly by blank?  Can I see a screenshot?

And are there any client-side errors logged when you open the map screen?

**Comment by Sarelth** [comment]
Sorry that it took so long to respond. We figured out it was a version issue for sure. 
I'll close this now.
