### ISSUE TITLE
[Feature Request]: Allow admins to change team owners

### ISSUE THREAD

**Issue by Martmists-GH** [FTBTeam/FTB-Mods-Issues#600]
### Mod

FTB Teams 1.18

### Description

Currently there is no way to change the owner of a team unless the team owner themselves transfer the team.

### Describe the solution you'd like

Add an admin command like `/ftbparty set-owner <team> <player>` which sets the team's new owner

**Comment by desht** [comment]
Yeah, that could be added.  In the meantime it is possible for a server admin to do this now, by stopping the server, editing `<world>/ftbteams/party/<team-id>.snbt` and changing the `owner` field to the UUID of the new owner.  Obviously take care and make backups if editing files directly.

**Comment by UnRealDinnerbone** [comment]
This feature has been added https://github.com/FTBTeam/FTB-Teams/commit/4d7ae768864abe3c5fd725fd8ac94c0dfd6a2268
