### ISSUE TITLE
[Bug]: FTBTeam crashing when clicking My Teams

### ISSUE THREAD

**Issue by chisaki38** [FTBTeam/FTB-Mods-Issues#601]
### Mod

FTB Team

### Mod version

ftb-teams-forge-1902.2.10-build.76

### Forge / Fabric version

1.19.2 43.1.57

### Modpack & version

Better MC [FORGE] 1.19.2 v11

### What issue are you having?

Our game crashes when we click My Teams - https://mclo.gs/L8zgudK. I have tried to update to ftb-teams-forge-1802.2.8-build.78 - both server & client side but the server won't launch at all as FTB Quest is not reading this version properly. Crash log for the updated FTB Teams here: https://mclo.gs/QAoEFPm

### Crashlogs

https://mclo.gs/L8zgudK
https://mclo.gs/QAoEFPm

### Steps to reproduce

1. Just click My Teams on Better MC Forge 1.19.2 v11 and it insta crashes.

**Comment by desht** [comment]
The crash is easy to work around with a null check, but the field it's checking should not be null by the time this code is executed.   The only way this could happen is if your client never received the teams data from the server (and if this is the case, teams won't work very well for you).  Can you check your server log for any stack traces etc. when you log in?

(The reason that ftb-teams-forge-1802.2.8-build.78 isn't working for you is that it's for 1.18.2, and you're on 1.19.2)

**Comment by papillo12** [comment]
> The crash is easy to work around with a null check, but the field it's checking should not be null by the time this code is executed. The only way this could happen is if your client never received the teams data from the server (and if this is the case, teams won't work very well for you).
> 
> Can you check your server log for any stack traces etc. when you log in?
> 
> Also, can you confirm you are actually playing online, and your client-side player UUID matches the server-side UUID? A mismatch there could also lead to this crash.
> 
> (The reason that ftb-teams-forge-1802.2.8-build.78 isn't working for you is that it's for 1.18.2, and you're on 1.19.2)

hi, i updated all the mods to the latest version and now i can access the ftb teams menu, but when someone wants to add someone else it crashes.
[crash-2022-12-21_18.47.49-client.txt](https://github.com/FTBTeam/FTB-Mods-Issues/files/10282914/crash-2022-12-21_18.47.49-client.txt)

**Comment by desht** [comment]
That crash doesn't appear to be related to Teams.  There's nothing in the stacktrace suggesting teams is involved there.

Also, I'll ask again: are you running an offline server?

**Comment by papillo12** [comment]
I migrated from a forge 1.19.2 server to fabric 1.19.2 and in the forge server I also had ftb chunks and teams and I didn't have this problem with crashes
