### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by sauramel** [FTBTeam/FTB-Mods-Issues#602]
### Mod

FTB Essentials

### Mod version

ftb-essentials-1802.1.7-build.42.jar

### Forge / Fabric version

1.18.2 40.1.61

### Modpack & version

Vault Hunters 3rd Edition

### What issue are you having?

Seems like the /delwarp command is not working, it doesn't seem to exist.

### Steps to reproduce

1. Create a warp
2. Attempt to delete that warp using the /delwarp command

### Anything else to note?

No

**Comment by desht** [comment]
The `/delwarp` command most certainly exists.

Can you confirm that 
1. The command is enabled in the mod config (look in `<world-dir>/serverconfig/ftbessentials.snbt` for the `warp: { }` section.  There should be an `enabled: true` entry in there; if that's missing or set to false, then someone has disabled it in config.
2. You have op status.
