### ISSUE TITLE
[Bug]: the "delete award" button is gone

### ISSUE THREAD

**Issue by BlackAures1** [FTBTeam/FTB-Mods-Issues#603]
### Mod

ftb-teams-forge-1802.2.9-build.88

### Mod version

ftb-teams-forge-1802.2.9-build.88

### Forge / Fabric version

forge

### Modpack & version

Play as dragon

### What issue are you having?

In the new FTB Quest update (ftb-teams-forge-1802.2.9-build.88 + ftb-quests-forge-1802.3.11-build.151+ ftb-library-forge-1802.3.9-build.167), it has become impossible to remove a specific reward. Previously, you could just click the delete button in the drop-down menu. 

![2332](https://user-images.githubusercontent.com/43911230/209228457-6723d1ff-ce21-4978-ae07-92362926ae3e.png)
![image1](https://user-images.githubusercontent.com/43911230/209228465-c86b76d5-430c-4304-9b8c-eb97e0f650a9.png)

But the delete button in the quest item works.
![image213123213](https://user-images.githubusercontent.com/43911230/209228539-29253dde-c4ef-4452-829f-b72cd544db0d.png)

### Steps to reproduce

I don't think it's necessary here.

### Anything else to note?

Why was it necessary to hide additional settings in a separate button? It wastes unnecessary time with mass edits.

**Comment by ItoKyoshiro** [comment]
Can confirm for FTB Quests build-151 (ftb-quests-forge-1802.3.11-build.151).

The Delete option for the Rewards inside a Quest is gone. Hopefully this can get high priority?

**Comment by emanuele246gi** [comment]
Me too

**Comment by desht** [comment]
Will be fixed in next release, tracking this is in #615
