### ISSUE TITLE
[Crash]: Crash on click "My teams"

### ISSUE THREAD

**Issue by WeleSS2** [FTBTeam/FTB-Mods-Issues#604]
### Mod

FTB Quests

### Mod version

ftb-quests-forge-1802.3.10-build.138.jar

### Forge / Fabric version
Forge
1.18.2 40.1.87

### Modpack & version

Custom

### What issue are you having?

Crash when clicking "My Team" button

### Crashlogs

https://pste.ch/yegigukiku.rb

### Steps to reproduce

1. Clicking on My Team just crash a game, nothing more complicated

### Anything else to note?

I think it can be caused by another mod, if do you don't have any idea what can cause this from crash from logs, I'll paste here modpack.

**Comment by desht** [comment]
This is a crash in FTB Teams, but you included the FTB Quests version.  We need the FTB Teams versions.

Also, are you running your server in offline mode?
