### ISSUE TITLE
[Bug]: FTB Ranks prefix disappears when adding a nickname with FTB Essentials

### ISSUE THREAD

**Issue by FloofyCandy** [FTBTeam/FTB-Mods-Issues#606]
### Mod

FTB Ranks

### Mod version

ftb-ranks-forge-1902.1.14-build.70

### Forge / Fabric version

Forge: 1.19.2-43.1.60

### What issue are you having?

After giving myself a nickname with FTB Essentials, my rank prefix disappears and my nickname is just shown in chat. I believe this is a bug with FTB Ranks because nicknames from FTB Essentials should be compatible with FTB Ranks.

Before adding nickname:
![image](https://user-images.githubusercontent.com/69277905/209495105-6bd8408f-b20e-4321-b27d-9751fd9d048b.png)

After adding nickname:
![image](https://user-images.githubusercontent.com/69277905/209495288-1f2171f8-7482-4945-be87-6206b3774f23.png)

### Steps to reproduce

1) Add FTB Ranks and FTB Essentials to your mods folder
2) Create a rank and add a prefix
3) Give yourself the rank
4) Type in chat to confirm the prefix is working
5) Give yourself a nickname with /nickname
6) Type in chat and see the prefix is gone and its just the nickname

**Comment by NovaLynxie** [comment]
Hey there, am also noticing this issue in current versions but did notice the commit referenced in this issue.
Is this fix currently available in one of the latest beta builds for forge or still yet to be released?
Am also running on Forge for 1.19.2

**Comment by desht** [comment]
If you're on the latest version of FTB Ranks, FTB Essentials and FTB Library, all should work fine:

![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/736831/29e8b471-49a2-40dd-9e62-fabc54a9d6c1)

Shows the green [Admin] prefix added by FTB Ranks, and the nickname change by FTB Essentials.

**Comment by NovaLynxie** [comment]
Tested this, after updating all to the latest versions available this is now confirmed as working 👍🏼 
Used the following in testing (at time of this messag):
ftb-essentials-forge-1902.3.3-build.100
ftb-library-forge-1902.4.1-build.236
ftb-ranks-forge-1902.1.15-build.77
