### ISSUE TITLE
[Bug]: FTB Quests Visibility crash

### ISSUE THREAD

**Issue by Proxwian** [FTBTeam/FTB-Mods-Issues#607]
### Mod

FTB Quests

### Mod version

ftb-quests-forge-1802.3.11-build.151.jar

### Forge / Fabric version

40.1.92

### Modpack & version

OxFORTPACK x256 6.1

### What issue are you having?

When changed dependency visibility in quest chapter for one of quests, game crashes
[crash-2022-12-26_14.25.56-client.txt](https://github.com/FTBTeam/FTB-Mods-Issues/files/10302234/crash-2022-12-26_14.25.56-client.txt)
[crash-2022-12-26_14.31.31-client.txt](https://github.com/FTBTeam/FTB-Mods-Issues/files/10302233/crash-2022-12-26_14.31.31-client.txt)

### Steps to reproduce

1. Change dependency visbility for quest
(Not always repeatable, just sometimes when changing that setting)

**Comment by Proxwian** [comment]
hide: true <- this line brokes client screen rendering

**Comment by desht** [comment]
You appear to have somehow introduced a circular dependency into your quest book, where a quest ends up depending on itself.  This is normally impossible to do (the GUI will prevent circular deps), but could happen if you've edited the quest file from outside the game, with a text editor.  Is this the case?

**Comment by Proxwian** [comment]
No, I’ve edited quests via game GUI, and only edit file when get crash to fix quest chapter

**Comment by desht** [comment]
I will need to see your quest files then.  The crash log you posted could only be caused by a dependency loop.

**Comment by Proxwian** [comment]
Would try with latest version and reopen later, if issue still exist
