### ISSUE TITLE
[Bug]: "Stacked" Quests don't work anymore

### ISSUE THREAD

**Issue by ItoKyoshiro** [FTBTeam/FTB-Mods-Issues#608]
### Mod

FTB Quest

### Mod version

ftb-quests-forge-1802.3.11-build.151

### Forge / Fabric version

Forge 1.18.2 - 40.1.85

### Modpack & version

Vault Hunters 3rd Edition - Update 4.1

### What issue are you having?

If you have multiple Quests on top of each other (hidden behind a selector so only one shows at a time) you can only select the last one moved while editing (the "top one"), regardless if the player can see it or not.

In this case I got the icon of the quest but it's "unclickable" (nothing happens since the game is trying to reach the most top one which is hidden). I selected the one called "Create"
![1](https://user-images.githubusercontent.com/72139058/209564355-e7bb00e3-e41e-404f-a0fa-b8384a74d77d.png)

On edit mode I can see the top one is this one called "Botania"
![2](https://user-images.githubusercontent.com/72139058/209564356-621f99ca-159c-4aaa-8abe-662422711371.png)

If I move the Botania to the side I can see that "Create" (the chosen one) is behind and therefore "unclikable"
![3](https://user-images.githubusercontent.com/72139058/209564358-62b1325d-6c19-40e0-bf25-645c27c79a06.png)

This still happens if you add more "layered" ones (so only can interact with the top one).

Not sure on which version this change came (since I didn't notice till now) but I was able to interact with the "visible one" on older versions with no issues before but my guess is either the build-130 (ftb-quests-forge-1802.3.9-build.130) or build-101 (ftb-quests-forge-1802.3.8-build.101). Could be wrong but I think this issue was presented on build-138 already.

Just for clarification, before I was able to interact with the top one of the "visibles" Quests (this makes sense) but now I'm only able to interact with the top one, regardless of visibility to the player (which create the issue) so if I selected any other one than the top one I get the "unclickable" Quests.

### Steps to reproduce

1.- Stack multiple Quest on top of each other (with hidden selectors, so only one shows at a time)
2.- Leave Edit Mode
3.- Choose your selector (other than the top one)
4.- Quest is "unclickable" (and since the top one is still hidden, you can't interact with it)

### Anything else to note?

This modpack doesn't have FTB Quest included (but still added it, just in case)

**Comment by desht** [comment]
Fixed in latest quests release
