### ISSUE TITLE
[Feature Request]: FTB Chunks and Corpse 

### ISSUE THREAD

**Issue by nageih** [FTBTeam/FTB-Mods-Issues#609]
### Mod

FTB Chunks

### Description

When Corpse and FTBChunks are installed on the server at the same time, the remains cannot be opened to pick up items in chunks that have already been claimed by other players.

**Comment by desht** [comment]
You can whitelist entity types for right-clicking via the `ftbchunks:entity_interact_whitelist` entity type tag.  If you add `corpse:corpse` to that tag, all players should be able to right-click corpses, regardless of chunk claim status.

You can do this for your server now via datapack, but I will get this added as a mod default in the next release of FTB Chunks.

**Comment by desht** [comment]
Fixed in latest FTB Chunks release
