### ISSUE TITLE
Reimplement Ally Map Sharing

### ISSUE THREAD

**Issue by Phr3d13** [FTBTeam/FTB-Mods-Issues#61]
Minecraft version 1.16.4, forge version 35.1.36, mod versions ftb-chunks-1604.2.2.57 and ftb-gui-library-1604.1.1.26

**Comment by kafuuchino-desu** [comment]
any update for this issue? will it be fixed?

**Comment by Red3Tango** [comment]
Could this feature at least be removed from the CurseForge page at this time, or made more clear that this is not (and has not been for years) a current feature.

> Add people as allies with Allies button to allow them to interact with your chunks. (This has changed recently, update will soon follow)
> 
> If they also add you as ally, you can share map data with them.

This reads more like the feature of an ally interacting with your chunks has changed, and not to deal with sharing map data. "update will soon follow" also can be interpreted as "soon", and not a feature that has had no update in years.

I play a modpack that really encourages exploration, and was so giddy when I saw this feature listed, however, it has been disabled for almost 4 years now.

**Comment by UnRealDinnerbone** [comment]
Closing this in favor of #1061
