### ISSUE TITLE
[Feature Request]: The chain link on Linked Quests should be visible outside of editing mode

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-Mods-Issues#613]
### Mod

FTB Quests

### Description

![image](https://user-images.githubusercontent.com/15698722/210028288-d338366b-d309-46f2-a6f0-985f3b96c5dc.png)
Specifically the one above, not the one below
![image](https://user-images.githubusercontent.com/15698722/210028303-3b45374b-1fd8-49a5-955c-209ee9b34eb0.png)

![image](https://user-images.githubusercontent.com/15698722/210028320-a63a679b-c741-4ad5-8f93-6aec1bf80b67.png)
The original should also have one right here, with a dropdown with clickable links to all the copies

**Comment by desht** [comment]
Fixed in latest quests release
