### ISSUE TITLE
[Bug]: FTB Quests task screen will extract tag filter when quest is item task with tag

### ISSUE THREAD

**Issue by SettingDust** [FTBTeam/FTB-Mods-Issues#614]
### Mod

FTB Quests

### Mod version

ftb-quests-fabric-1802.3.11-build.151

### Forge / Fabric version

Quilt 1.18.2 0.18.1-beta.25

### What issue are you having?

The Task Screen block will extract a lot of tag filter instead of accept items when the item task is tag filter

### Steps to reproduce

https://user-images.githubusercontent.com/19922286/210032620-f81f9251-bb34-4d18-8b79-65e2a037de53.mp4

1. Create a item task with a tag filter
2. Put a task screen and hopper on top and bottom
3. Put any item into hopper and take off again and again
4. There will be many tag filter in bottom hopper. And it's can be used for complete quest

**Comment by desht** [comment]
Fixed in latest quests release
