### ISSUE TITLE
[Feature Request]: bring back the delete option

### ISSUE THREAD

**Issue by Looodon** [FTBTeam/FTB-Mods-Issues#615]
### Mod

FTB Quests Forge 902.4.4 build 150

### Description

In the latest FTB Quest update, the delete option when you right-click a reward item is gone in editing mode. If you add a reward now you can't remove it unless you downgrade to the previous FTB Quest version which is 1902.4.3-build.140. The reward I tried to remove was from a kill entity quest

### Describe the solution you'd like

Adding the Delete option back when your right click rewards in editing mode

### Describe alternatives you've considered

I downgraded to previous version

**Comment by desht** [comment]
Fixed in latest quests release
