### ISSUE TITLE
[Bug]: FTB Chunks Fabric: NullPointerException: Cannot invoke "net.minecraft.class_1041.method_4486()"

### ISSUE THREAD

**Issue by suerion** [FTBTeam/FTB-Mods-Issues#616]
### Mod

FTB Chunks

### Mod version

ftb-chunks-fabric-1902.3.14-build.218

### Forge / Fabric version

1.19.2 Fabric 0.14.12

### What issue are you having?

After clicking "M" the client crash with an NPE

### Crashlogs

https://pastebin.com/97iDCRYy

### Steps to reproduce

1. Start the Client and push M

**Comment by desht** [comment]
Can I check please if you are running your server in offline mode?

**Comment by suerion** [comment]
> 

hey, how would you do that? is there something you need?

**Comment by desht** [comment]
OK, you are in online mode, which rules out that possibility.  Does this happen every time you start the instance, or was it an isolated crash?

**Comment by suerion** [comment]
It crashes always when i start with the actuall version. It crash only when i try to open the map.

**Comment by suerion** [comment]
[Ecki's Communityserver.zip](https://github.com/FTBTeam/FTB-Mods-Issues/files/10366451/Ecki.s.Communityserver.zip)

Here the Modlist from Curse Forge :)

After starting, joining Server and clicking M to open the Map. Then it Crash.

**Comment by KAMKEEL** [comment]
I also experience this crash. But, if I move back to the version for 1.19.2 on Sept 10th. I do not get this crash. I know the crash is on the latest version. I'll try and continuously update by version, until I can see where the change may have occurred!

**Comment by desht** [comment]
The fundamental problem is that server data isn't being sync'd to your client when you log in, for some reason.  This process is normally initiated by FTB Teams when it detects you logging on, but in this case, it's not happening.

Are you in a position to test a dev build of FTB Teams on your server?

The build in question is
* https://maven-admin.ftb.dev/repository/maven-public/dev/ftb/mods/ftb-teams-forge/1902.2.12-build.91/ftb-teams-forge-1902.2.12-build.91.jar (Forge)
* https://maven-admin.ftb.dev/repository/maven-public/dev/ftb/mods/ftb-teams-fabric/1902.2.12-build.91/ftb-teams-fabric-1902.2.12-build.91.jar

With this build installed, you should extra messages from FTB Teams in your server `debug.log` when you log in.  I would be very interested to know what gets logged in this situation.

**Comment by suerion** [comment]
I will come back to you after testing :)

**Comment by suerion** [comment]
@desht on our side, it does not write an debug.log anymore. i had activated all logs, but Teams does not log something.

But with the Dev Build the server work and FTB Chunks are also work fine with de Dev FTB Teams.

**Comment by desht** [comment]
That's very interesting.  So it was consistently failing on the old version, and consistently working with the dev build?

Odd that it's not writing a debug log, though.  I would expect that to happen even with default server startup options.

**Comment by suerion** [comment]
Hey, we got an new error, but only on client side

[crash-2023-01-26_14.14.10-client.txt](https://github.com/FTBTeam/FTB-Mods-Issues/files/10511552/crash-2023-01-26_14.14.10-client.txt)

**Comment by desht** [comment]
That's completely unrelated to Chunks, and caused  by a badly-behaved Fabric mod.

**Comment by suerion** [comment]
> That's completely unrelated to Chunks, and caused by a badly-behaved Fabric mod.

Hey, @desht sorry for worriing you, did you see in the stacktrace, what the bad plugin is? 

Is it one of this? 	
Packs: Default, Fabric Mods, Supplementaries Generated Pack, V Slab Compat Generated Pack, continuity/default, redstone-tweaks-2-2-1.zip, continuity/glass_pane_culling_fix

**Comment by desht** [comment]
Not sure... I'd heard it was a mod called `bleachhack` but I don't see that in your pack.  I'll get back to you if/when I find out.

**Comment by suerion** [comment]
Okey, thanks a lot.

**Comment by desht** [comment]
Just to note that there is now a release of Curseforge with those changes: https://www.curseforge.com/minecraft/mc-mods/ftb-teams-fabric/files/4367025

**Comment by AlienXAXS** [comment]
Hi, Apologies for bumping a 2 week old thread.
I have a player who is playing on AOF6 with this exact issue (MC 1.19.2)

I see that you have released a patch on CurseForge with the link above, but it's only for 1.18.2 - is there a 1.19.2 release expected with the NRE patch included or have I misunderstood?

[crash-2023-02-09_11.48.31-client.txt](https://github.com/FTBTeam/FTB-Mods-Issues/files/10696365/crash-2023-02-09_11.48.31-client.txt)

Many thanks

**Comment by desht** [comment]
Thanks for the reminder.  There should be a new release for 1.19.2 today or tomorrow.

**Comment by desht** [comment]
Fixed in latest FTB Library release.  Note this just fixes the client crash; there is a more fundamental problem with data not getting sync'd to the client for which there isn't a fix at this time.

**Comment by Danny335962** [comment]
Encountering this exact issue with a server created today, is there a fix I can implement on my end?

**Comment by desht** [comment]
Please upload both your server and client's `debug.log` files to a paste site somewhere, and link them here.

**Comment by Danny335962** [comment]
https://pastebin.com/6JRaxqwa - Server's Log doesn't seem to show anything specific, just states I disconnected. 
https://pastebin.com/fyr7Gqsa - Client side crash report 

"java.lang.NullPointerException: Cannot invoke "dev.ftb.mods.ftbchunks.client.map.MapDimension.getLoadedRegions()" because "this.dimension" is null" seems to be the 1st line of the issue occuring.

**Comment by Danny335962** [comment]
Trying to locate that file, it doesn't seem to be in any of the obvious locations. Do you have a file name it should be getting saved in by default? Or a document with instructions to collect it?

**Comment by ryadov** [comment]
Hello, I am having the same issue but I followed this thread closely and I couldn't find a solution. I am running FTB University 1.19 latest build, and latest server build as well. Pressing M crashes the game with the same error: 
Cannot invoke "dev.ftb.mods.ftbchunks.client.map.MapDimension.getLoadedRegions()" because "this.dimension" is null

Crash report:
[crash-2024-04-13_01.13.06-client.txt](https://github.com/FTBTeam/FTB-Mods-Issues/files/14964414/crash-2024-04-13_01.13.06-client.txt)

**Comment by OtosanX** [comment]
I'm playing on a personal pack, it all of the sudden started crashing this time when restarting and no updates were done or mod changes other than since it started i added crash assistant and doesnt seem to fix it. added latest and modlist. tried turning off any shader mods and no change.

[latest.log](https://github.com/user-attachments/files/21092696/latest.log)
[modlist.txt](https://github.com/user-attachments/files/21092695/modlist.txt)

**Comment by desht** [comment]
From the log:
```
[15:28:34] [Render thread/WARN]: Attempted to access MapManager before it's set up! Client never received team initialization data from server; check server log for errors around the time your player logged in.
```
I need to see the `debug.log` from the server at the time you logged and got the crash.
