### ISSUE TITLE
[Feature Request]: locked quests should say [Locked] in the tooltip

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-Mods-Issues#618]
### Mod

Ftb quests

### Description

![Screenshot_20230102_030517_Discord](https://user-images.githubusercontent.com/15698722/210211549-524f8f96-98dd-4303-930e-4253b456f579.jpg)

You'd think it being grey and not completing would be enough, but eh

If it has a third line saying it was locked it would be clearer I think. The deps arrow flashing could also be made more visually noticeable I think, flashing red instead of white

**Comment by desht** [comment]
Fixed in latest quests release
