### ISSUE TITLE
[Feature Request]: Suggestion About FTB Quests（Fabric）

### ISSUE THREAD

**Issue by YUANXINGlingyun** [FTBTeam/FTB-Mods-Issues#619]
### Mod

FTB Quests（Fabric）

### Description

I have a minecraft 1.19 server. I want to use FTB Quests（Fabric）to make an beginner's guide for new players in my server.
When I search and then try to download mod,I can't find a mod for 1.19,only 1.19.2

### Describe the solution you'd like

Make a mod for Minecraft 1.19

**Comment by desht** [comment]
Sorry, but we don't support 1.19.  1.18.2 and 1.19.2 are fully supported; please update to 1.19.2.
