### ISSUE TITLE
[Bug]: Marking quests as optional does not stick after reload. 

### ISSUE THREAD

**Issue by DelviousCrafts** [FTBTeam/FTB-Mods-Issues#620]
### Mod

FTB Quests

### Mod version

ftb-quests-forge-1802.3.12-build.157

### Forge / Fabric version

Forge 1.18.2 - 40.2.0

### Modpack & version

N/A

### What issue are you having?

When setting a quest as optional, it will save and continue to be optional throughout that playthrough, however, once the game is unloaded and reloaded completely, the optional setting reverts to the default of false. This is true of both single-player and multi-player environments.

### Steps to reproduce

1. Create an optional quest.
2. Close Minecraft completely.
3. Reload the game.
4. See that optional quests have reverted to not optional.

### Anything else to note?

Reproduced in a minimal environment with only Architectury API, FTB Library, FTB Quests, FTB Teams, and Item Filters installed.

**Comment by desht** [comment]
Confirmed, there is a bug here, but it's actually a client sync issue rather than a server-side persistence issue.  I.e. the value is correctly saved and reloaded on the server, but not properly sync'd to the client after reload.  Will get this fixed for the next Quests release.

**Comment by desht** [comment]
Fixed in latest FTB Quests release
