### ISSUE TITLE
[Bug]: FTB Ultimine cannot ultimine anymore after ultimining Sculk blocks

### ISSUE THREAD

**Issue by yifanwww** [FTBTeam/FTB-Mods-Issues#624]
### Mod

FTB Ultimine

### Mod version

ftb-ultimine-fabric-1902.3.5-build.65

### Forge / Fabric version

0.14.12

### What issue are you having?

Once I mined Sculk blocks in Sharpless mode (mining 128 blocks), FTB Ultimine seemd to get crashed(?). After that I could not ultimine anymore or get any items when mining normally.

### Crashlogs

Don't know where to find the logs of FTP Ultimine mod.

### Steps to reproduce

1. Turn on FTB Ultimine
2. Create a new world
3. Go to ancient city
4. ultimine Sculk blocks in Sharpless mode (or maybe other modes?)
5. then you (at least me) cannot ultimine anymore, or cannot get any items when mining blocks normally

**Comment by desht** [comment]
Cannot reproduce this, either on Forge or Fabric.  Ultimining Sculk blocks works as expected, and I can still ultimine and mine normally after I've done this. 

Looks like some other mod is likely messing something up here.  Problem is not with Ultimine.
