### ISSUE TITLE
[Bug]: Chunk Loading Ticket is only connected to owner of FTB Teams team

### ISSUE THREAD

**Issue by NielsPilgaard** [FTBTeam/FTB-Mods-Issues#625]
### Mod

FTB Teams & FTB Chunks

### Mod version

ftb-teams-forge-1902.2.11-build.87 & ftb-chunks-forge-1902.3.14-build.218

### Forge / Fabric version

1.19.2-43.2.3

### Modpack & version

Enigmatica 9 1.3.0

### What issue are you having?

When a player is part of a team, all of his chunkload tickets are connected to the team, but they're registered as owned by the owner of the team. This means, that if the owner goes offline, the chunks unload after some time, if that config is enabled, or if the Limited Chunks mod is used.

https://github.com/EnigmaticaModpacks/Enigmatica9/issues/205

### Steps to reproduce

2 accounts are needed to reproduce:

1. Create an FTB Teams team with 2 players
2. The player who doesn't own the team should then chunkload a chunk.
3. Both players move away from the chunk, at least 440 blocks iirc.
4. The owner of the team logs out
5. The chunk should now be unloaded

**Comment by desht** [comment]
Actually, all chunkload tickets (as in, chunks passed to the Forge chunkloading system - ForgeChunkManager#forceChunk()`) are created with a UUID of the party team ID, which is neither the player nor the owner of the team, but a completely separate random UUID chosen when the party was created.

Which config are you referring to by "if that config is enabled" ?

And what exactly is this Limited Chunks mod doing?  Sounds like it's wrongly unloading chunks that should remain loaded.  When FTB Chunks marks a chunk for loading (via `ForgeChunkManager#forceChunk()`) it keeps the chunk loaded if any of the following are true:
* `force_load_mode` is set to "never" and there's at least one team member online
* `force_load_mode` is set to "always"
* `force_load_mode` is set to "default" and the team has at least one member with the "ftbchunks.chunk_load_offline" FTB Ranks permission OR `chunk_load_offline` in the server config is set to true

If all of those conditions are satisfied, the chunk should remain loaded; if they're getting unloaded, I would suggest looking more closely at just what Limited Chunks is doing...

**Comment by NielsPilgaard** [comment]
Ahh that makes a lot of sense, Limited Chunks must be checking whether a player matching the Team Id is online, and since there is no such player it will be seen as being offline. 

I think I'll just remove Limited Chunks then 😄 Thank you!
