### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Pex666** [FTBTeam/FTB-Mods-Issues#626]
### Mod

FTB Chunks

### Mod version

ftb-chunks-forge-1902.3.14-build.218

### Forge / Fabric version

1.19.2 43.2.0

### What issue are you having?

mechanical drill from mod "Create" can break blocks inside the claimed chunk
all ftbchunk properties are set to private (fake players - false)
how can i prevent this block from interacting with the claimed chunk?

### Steps to reproduce

1. place the drill near the chunk

**Comment by desht** [comment]
Looking at the Create source code (`BlockBreakingKineticTileEntity` in particular), I don't see any evidence of the mod firing block break events (although it's possible I've missed something - the Create developers can confirm that).  Therefore, FTB Chunks has no way of preventing blocks being broken by Create.

This is something you would need to take up with Create, as to why they don't fire block break events.
