### ISSUE TITLE
[Bug]: Cant jump backwards

### ISSUE THREAD

**Issue by MasterSloth1** [FTBTeam/FTB-Mods-Issues#628]
### Mod

Ftb Ultimine

### Mod version

ftb-ultimine-forge-1802.3.3-build.70

### Forge / Fabric version

40.2.0

### What issue are you having?

If you hold the ultimine key and try jumping backwards, it doesnt allow you to, but all other directions work fine

### Steps to reproduce

1. load up a creative world
2. hold the default ultimine key `
3. hold jump and backwards keys
4. notice you cant jump

### Anything else to note?

I only have these mods installed
`architectury-4.10.88-forge`
`ftb-library-forge-1802.3.9-build.167`
`ftb-ultimine-forge-1802.3.3-build.70`

**Comment by desht** [comment]
Can't reproduce this problem; I can jump backwards just fine while holding the Ultimine key.  Can you check if you have any clashing keybindings?  It may be some other mod interfering here.

**Comment by MasterSloth1** [comment]
there was no other mods the only mods i had was
`architectury-4.10.88-forge`
`ftb-library-forge-1802.3.9-build.167`
`ftb-ultimine-forge-1802.3.3-build.70`
All of my keybinds were default, i did change the video settings but i dont think that will have any effect on the bug

--------------------------------------------------------------------------------------------------------------------------------------------

As of today I can still reproduce this bug - only ultimine and its dependencies the ones that GDLauncher will download automatically are installed
`Forge-40.2.1`
`Architectury-4.11.89-forge`
`ftb-library-forge-1802.3.3-build.177`
`ftb-ultimine-forge-1802.33-build.70`
![image](https://user-images.githubusercontent.com/34207969/227699054-f7a22bde-93d1-4304-a0d6-c69650386919.png)

All of my settings/keybinds are default here is my keybinds config - 
[options.txt](https://github.com/FTBTeam/FTB-Mods-Issues/files/11068104/options.txt)


Let me know if there is any other files you need or i can just straight up export my instance, its freshly created so its a tiny download

**Comment by MasterSloth1** [comment]
ok so i just went to `https://keyboard-test.space` to test my keyboard and i can hold down all buttons at once except when i do ` + s. as soon as i do them 2 buttons nothing will work afterwards, so its defiantly a issue on my end sorry for the confusion this is no longer a issue
