### ISSUE TITLE
Suggestion: More ServerConfig options

### ISSUE THREAD

**Issue by Suraru** [FTBTeam/FTB-Mods-Issues#64]
I don't want my players to be able to turn on death waypoints, or see other players/mobs on the minimap. I'm sure others would also like to disable waypoints or minimaps completely. 

Atm, I can turn them off by default in the modpack settings, but it's not too hard for a player to find out that they can simply turn them back on.

**Comment by Raidobw2** [comment]
LatvianModder, this looks exactly like Xaero's Minimap Fair Play edition.
I could see this being implemented server side or as a standalone like Xaero did.
Thank you for the good suggestion.

**Comment by Raidobw2** [comment]
From dupe ticket:
> Disabling player radar function on map in the server configuration file.

> I'm on 1.16, but this. Dear god this. I'd love it if you could still see players you were allied with, but fully turning it off works just as well honestly.

> I'd recommend renaming this to a 1.16 suggestion because it still hasn't been implemented. This is one of the main issues my friends and I have been having in Enigmatica 6. It makes it real difficult to prepare any surprises.

**Comment by desht** [comment]
Death waypoints are a purely clientside feature, and there's nothing the server can do to disable this functionality.  I suppose it would be possible to also distribute a "FTB Chunks Fairplay" edition which just removes the waypoint code entirely, but here's the thing: if cheaty players want waypoints or the ability to see nearby mobs (the client still knows about nearby entities - vanilla sees to that), they'll find a way to get that with a cheat mod.  So I'm really not sure this is at all worth the effort.  Cheaters gonna cheat.
