### ISSUE TITLE
[Feature Request]: Option to set the delay before offline forced chunks = false, server-wide.

### ISSUE THREAD

**Issue by Mihoshika** [FTBTeam/FTB-Mods-Issues#642]
### Mod

FTB Chunks

### Description

Option to set the a delay before offline force chunk loading is disabled.

### Describe the solution you'd like

This would allow for servers to have regular players keep their chunks loaded for the short times they're offline (for sleep/work/school etc.), while allowing the chunks of those who've stopped playing, or who play infrequently, to not be loaded, thus reducing load on servers.

### Describe alternatives you've considered

There's currently the option to disable offline chunk loading, but a middle ground between the two would be nice.

**Comment by Mihoshika** [comment]
Similar to https://github.com/FTBTeam/FTB-Mods-Issues/issues/58 , but server-sided option for all, rather than client-sided. I think.

**Comment by desht** [comment]
Good idea.  This would likely work similarly to the existing server config setting `max_idle_days_before_unclaim` - but unforcing chunks for an idle team rather than unclaiming them completely.

**Comment by desht** [comment]
Fixed in latest FTB Chunks release
