### ISSUE TITLE
[Bug]: FTB Ranks is not loading on my server

### ISSUE THREAD

**Issue by GalaxyStylix** [FTBTeam/FTB-Mods-Issues#645]
### Mod

FTB Ranks

### Mod version

ftb-ranks-forge-1802.1.11-build.71

### Forge / Fabric version

1.18.2 40.2.0

### Modpack & version

AstroworldSMP custom modpack

### What issue are you having?

I added my own ranks to the server by changing the ranks.snbt file but it seems like the mod/server is not recognizing the changes. When I run /ftbranks list_all_ranks an error shows up (attached image). Custom ranks used to work on my server around a month ago but now it's not working and it won't update the ranks I added (season 1, before server reset). When I reseted the server on Saturday (for season 2) the server now won't recognize the ranks.snbt file and it just recognizes the default ranks. My server's modpack for the list of mods on the server: https://www.curseforge.com/minecraft/modpacks/shrooms-mushroomcraft-astroworld-edition (Current season 2 modpack that I haven't uploaded yet since it's in the beta access stage has 106 mods. Main mods include: Create, Tinkers Construct, Immersive Engineering, MrCrayfish's mods, Biomes O' Plenty, Blue Skies, The Undergarden and Tetra)
![2023-01-22_23 28 16](https://user-images.githubusercontent.com/103090982/213971845-15862506-933c-428b-920b-1f329eb336fd.png)

### Steps to reproduce

Run /ftbranks list_all_ranks

**Comment by desht** [comment]
I'll need to see your ranks.snbt file.  Looks like that's not loading for some reason...

**Comment by GalaxyStylix** [comment]
> I'll need to see your ranks.snbt file. Looks like that's not loading for some reason...

I asked another server owner friend of mine so I made mine based on his ranks.snbt file. Added into pastebin for easy reading.
https://pastebin.com/R9AQeY9v

**Comment by desht** [comment]
Yep, you have a syntax error in your ranks.snbt.  Line 80: "lore writer" can't have a space in it like that.  Use an underscore, so you have `lore_writer: { ...`.

That will fix your problem, but I'm keeping this open for now, because the error reporting isn't working properly (the stacktrace when loading the ranks file isn't giving the right information).  Needs fixing in FTB Library.

**Comment by GalaxyStylix** [comment]
It works now, thanks for the help!

**Comment by desht** [comment]
Fixed in latest FTB Library release
