### ISSUE TITLE
[Feature Request]: FTBquest localization

### ISSUE THREAD

**Issue by nageih** [FTBTeam/FTB-Mods-Issues#647]
### Mod

FTB Quest

### Description

For modpacker，quest localization is hard，because it doesn't has lang file

### Describe the solution you'd like

After using FTBquest can automatically generate lang files, which will be very convenient for translators

### Describe alternatives you've considered

Convert the text in the file stored in config into a string, and then generate the string into a language file.
Just like this mod:https://www.curseforge.com/minecraft/mc-mods/ftb-quests-localization-keys
But this mod still has limitations, so I hope ftb quest natively supports localization

**Comment by nageih** [comment]
The stoneblock 3 modpack does just that

**Comment by nageih** [comment]
I think you can release a test version with the base localization and then improve the functionality step by step with feedback from the authors of the modpacks and issues

**Comment by nageih** [comment]
After a year, this issue seems to have been resolved, but unfortunately it doesn't work on lower versions. Finally I have a question about the text in the Item Stack Component, such as `minecraft:custom_name` and `lore`, and whether it's possible to support localization?

**Comment by nageih** [comment]
@desht

**Comment by desht** [comment]
> Finally I have a question about the text in the Item Stack Component, such as minecraft:custom_name and lore, and whether it's possible to support localization?

Not quite clear what you mean here, can you provide an example?

**Comment by nageih** [comment]
For example,I have a item which have custom name "test" , it will be stored in snbt file like this
![PixPin_2024-06-28_21-12-15.png](https://s2.loli.net/2024/06/28/4qCgJYOFLjHPd9B.png)
The custom name cann't be translated,but as long as I use the Text Component including a translation key, I can translate it like this.It's similar for `lore` component
![PixPin_2024-06-28_21-22-05.png](https://s2.loli.net/2024/06/28/TDPsVBn15G6bur9.png)
In fact,it's just like NBT.
I know FTB Quests as a quest mod shouldn't have the ability to modify items like this, but it would be more helpful for translation, and would it be possible to add an optional option?

**Comment by desht** [comment]
The `custom_name` data component is already a text component - https://minecraft.wiki/w/Data_component_format#custom_name

Which means you can define its text as raw json text, as that Wiki link mentions. And raw text already allows for translations: https://minecraft.wiki/w/Raw_JSON_text_format#Translated_Text

So isn't any need for any special support in FTB Quests for this.
