### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by Mihoshika** [FTBTeam/FTB-Mods-Issues#656]
### Mod

FTB Chunks

### Description

Ability to increase max chunks of players/teams based on playtime

### Describe the solution you'd like

In general, new players don't really need as many chunks as established players. On top of that, established players are more likely to move on to make larger builds, due to having both resources and the equipment to expand.

There is also the minor issue of newer players possibly placing a bunch of random claims, and leaving. There's the option to unclaim inactive players' chunks, but that's not really a good thing in modpacks that rely heavily on progression, as you would end up with advanced players' bases being lootable by newer players, which pretty much kills most of the work needed for the modpacks. 

Anyways, an option for reducing newer players' total chunks, and allowing them to get more as they played, would lower the issue of newer players spamming as many claimed chunks. Plus it would incentivize players to spend more time on.

**Comment by desht** [comment]
This is actually already achievable via the use of FTB Ranks.  One of the rank conditions is time played, so you have e.g. a "veteran" rank for long-term players, and give that rank an increased chunk allocation.  Let me know if you need more info on this, and if it can be a workable solution.
