### ISSUE TITLE
[Bug]: Force loaded chunks of random players are loaded when they are offline.

### ISSUE THREAD

**Issue by Shizz00** [FTBTeam/FTB-Mods-Issues#657]
### Mod

FTB chunks

### Mod version

ftb-chunks-forge-1902.3.14-build.218

### Forge / Fabric version

forge-1.19.2-43.2.0

### What issue are you having?

The server has the following options set concerning chunk loading:
-chunk_load_offline: false
-force_load_mode: "never"

With these settings, no chunk should be loaded when the team/player is offline.
But that is not the case. It force loads even when offline, but only for random players.

This issue started when i updated from ftb-chunks-forge-1902.3.13-build.207 to ftb-chunks-forge-1902.3.14-build.218

### Steps to reproduce

1. Make server with ftb-chunks-forge-1902.3.14-build.218
2. Deactivate offline force loading (chunk_load_offline: false, force_load_mode: "never")
3. Invite people.
4. Let them create zones with force loaded chunks.
5. Some players will have their chunks force loaded while offline, some not.

**Comment by desht** [comment]
What are you using to determine that chunks are indeed still force-loaded?

**Comment by Shizz00** [comment]
We tested this with machines and farms.
For example:
- UU-matter from ic2c kept going
- reactors were still on and used up materials (for this to function, pipes needed to be active)
- farms made with create were still going

**Comment by Mihoshika** [comment]
Not 100% sure, since I am not personally the server owner, but this is happening on the ATM8 server I'm currently playing in. Owner says the option is disabled, but I was getting millions of lithium dust while offline.

**Comment by desht** [comment]
Yeah, I think I can see what's going on here.  If I'm right it's an easy fix...

**Comment by Shizz00** [comment]
A bit late, but after 2 days of testing with version 1902.3.15... the chunks are still loaded.

**Comment by desht** [comment]
Really? :(  Going to need see your server logs then, specifically any entries mentioning "cleaned up X stale Forge chunkloading tickets".  These messages should be logged on server startup, where tickets for chunks that shouldn't remain loaded are discarded.

**Comment by Shizz00** [comment]
Log and config files:
[server files.zip](https://github.com/FTBTeam/FTB-Mods-Issues/files/10689130/server.files.zip)

Let me know if you need more files. Can't practically upload the hole world (11GB...)

**Comment by desht** [comment]
That's fine, I don't need the world.  I've been through the configs and data files and everything looks in order.  I tried again this morning with basically the same setup as you, and I still can't reproduce the problem.

* Chunk forcing disabled in server config
* Team has no offline chunkloading perms

Steps I took (this is on a dedicated server so I can inspect the console while not logged in):

* I set up a blast furnace processing some ore, chunkloaded the area
* Went to the Nether for a couple of minutes, and came back - furnace had continued working as expected
* Logged out for a couple of minutes - furnace had processed another 3 or 4 ores then stopped.  Again as expected (chunks unload a few seconds after no forceloading tickets are held for them, so a little extra processing is normal)
* Logged back in, furnace started up again

Another very valuable utility which is worth installing if you don't have it is Crash Utilities - https://www.curseforge.com/minecraft/mc-mods/crash-utilities

While on the server console, run `crashutilities chunks` - you should see output like this when logged in:
```
[10:13:54] [Server thread/INFO] [minecraft/MinecraftServer]: PARTIALLYGENERATED: 422
[10:13:54] [Server thread/INFO] [minecraft/MinecraftServer]: ENTITY_TICKING: 801
[10:13:54] [Server thread/INFO] [minecraft/MinecraftServer]:     forge:entity_ticking: 6
[10:13:54] [Server thread/INFO] [minecraft/MinecraftServer]:     start: 1
[10:13:54] [Server thread/INFO] [minecraft/MinecraftServer]:     player: 441
[10:13:54] [Server thread/INFO] [minecraft/MinecraftServer]:     unknown: 498
[10:13:54] [Server thread/INFO] [minecraft/MinecraftServer]: INACCESSIBLE: 214
[10:13:54] [Server thread/INFO] [minecraft/MinecraftServer]: BORDER: 183
[10:13:54] [Server thread/INFO] [minecraft/MinecraftServer]: TICKING: 167
[10:13:54] [Server thread/INFO] [minecraft/MinecraftServer]:     unknown: 1
[10:13:54] [Server thread/INFO] [minecraft/MinecraftServer]: PRIMED: 1603
[10:13:54] [Server thread/INFO] [minecraft/MinecraftServer]: FULL: 1213
[10:13:54] [Server thread/INFO] [minecraft/MinecraftServer]: Non-Ticking chunks have little to no performance impact. See the GUI and minecraft wiki for what each type represents.
```

Those 6 `forge:entity_ticking` entries are the 6 chunks I have loaded via FTB Chunks, and the `player` chunks are the ones loaded due to me being logged in (they overlap in this case). After logging out, I see:

```
[10:14:31] [Server thread/INFO] [minecraft/MinecraftServer]: PARTIALLYGENERATED: 116
[10:14:31] [Server thread/INFO] [minecraft/MinecraftServer]: ENTITY_TICKING: 360
[10:14:31] [Server thread/INFO] [minecraft/MinecraftServer]:     start: 1
[10:14:31] [Server thread/INFO] [minecraft/MinecraftServer]:     unknown: 68
[10:14:31] [Server thread/INFO] [minecraft/MinecraftServer]: INACCESSIBLE: 308
[10:14:31] [Server thread/INFO] [minecraft/MinecraftServer]: BORDER: 87
[10:14:31] [Server thread/INFO] [minecraft/MinecraftServer]: TICKING: 79
[10:14:31] [Server thread/INFO] [minecraft/MinecraftServer]: PRIMED: 156
[10:14:31] [Server thread/INFO] [minecraft/MinecraftServer]: FULL: 1096
[10:14:31] [Server thread/INFO] [minecraft/MinecraftServer]: Non-Ticking chunks have little to no performance impact. See the GUI and minecraft wiki for what each type represents.
```

The `unknown` entries there are what keeps the chunk loaded for a short time.  At this point, the chunks are still loaded and being ticked. About 10-15 seconds later:

```
[10:14:44] [Server thread/INFO] [minecraft/MinecraftServer]: PARTIALLYGENERATED: 116
[10:14:44] [Server thread/INFO] [minecraft/MinecraftServer]: ENTITY_TICKING: 360
[10:14:44] [Server thread/INFO] [minecraft/MinecraftServer]:     start: 1
[10:14:44] [Server thread/INFO] [minecraft/MinecraftServer]: INACCESSIBLE: 308
[10:14:44] [Server thread/INFO] [minecraft/MinecraftServer]: BORDER: 87
[10:14:44] [Server thread/INFO] [minecraft/MinecraftServer]: TICKING: 79
[10:14:44] [Server thread/INFO] [minecraft/MinecraftServer]: PRIMED: 156
[10:14:44] [Server thread/INFO] [minecraft/MinecraftServer]: FULL: 1096
[10:14:44] [Server thread/INFO] [minecraft/MinecraftServer]: Non-Ticking chunks have little to no performance impact. See the GUI and minecraft wiki for what each type represents.
```

Now only the `start` chunk is loaded, and my furnace and other block entities are no longer ticking.  So yeah... all working as I expect it to.  It would be very useful if you could do the same checks with Crash Utilities - if nothing else it would confirm that you don't have any other unexpected sources of chunk forcing active.  For example, when I first started testing, I realised I'd left a nearby Mekanism Digital Miner with an Anchor upgrade installed which confused my testing initially.  This showed up on the Crash Utilities output as `forge:block: 1`.

**Comment by Shizz00** [comment]
<HTML>
<HEAD>
	
	<META HTTP-EQUIV="CONTENT-TYPE" CONTENT="text/html; charset=utf-8">
	<TITLE></TITLE>
	<META NAME="GENERATOR" CONTENT="OpenOffice 4.1.6  (Win32)">
	<STYLE>
		
	</STYLE>
	
</HEAD>

<BODY TEXT="#000000">
<TABLE FRAME=VOID CELLSPACING=0 COLS=6 RULES=NONE BORDER=0>
	<COLGROUP><COL WIDTH=340><COL WIDTH=101><COL WIDTH=138><COL WIDTH=138><COL WIDTH=163><COL WIDTH=111></COLGROUP>
	<TBODY>
		<TR>
			<TD WIDTH=340 HEIGHT=34 ALIGN=LEFT BGCOLOR="#CCCCCC"><B><BR></B></TD>
			<TD WIDTH=101 ALIGN=LEFT BGCOLOR="#CCCCCC"><B>noone online</B></TD>
			<TD WIDTH=138 ALIGN=LEFT BGCOLOR="#CCCCCC"><B>player A online,<BR>away from his zone</B></TD>
			<TD WIDTH=138 ALIGN=LEFT BGCOLOR="#CCCCCC"><B>player A in his zone</B></TD>
			<TD WIDTH=163 ALIGN=LEFT BGCOLOR="#CCCCCC"><B>player A in his zone<BR>player B not in his zone</B></TD>
			<TD WIDTH=111 ALIGN=LEFT BGCOLOR="#CCCCCC"><B>player A and<BR>B in their zones</B></TD>
		</TR>
		<TR>
			<TD HEIGHT=17 ALIGN=LEFT>ENTITY_TICKING</TD>
			<TD ALIGN=RIGHT SDVAL="524" SDNUM="1031;">524</TD>
			<TD ALIGN=RIGHT SDVAL="645" SDNUM="1031;">645</TD>
			<TD ALIGN=RIGHT SDVAL="912" SDNUM="1031;">912</TD>
			<TD ALIGN=RIGHT SDVAL="1117" SDNUM="1031;">1117</TD>
			<TD ALIGN=RIGHT SDVAL="1382" SDNUM="1031;">1382</TD>
		</TR>
		<TR>
			<TD HEIGHT=17 ALIGN=LEFT BGCOLOR="#CCCCCC">forge:entity_ticking</TD>
			<TD ALIGN=LEFT BGCOLOR="#CCCCCC">-</TD>
			<TD ALIGN=RIGHT BGCOLOR="#CCCCCC" SDVAL="146" SDNUM="1031;">146</TD>
			<TD ALIGN=RIGHT BGCOLOR="#CCCCCC" SDVAL="146" SDNUM="1031;">146</TD>
			<TD ALIGN=RIGHT BGCOLOR="#CCCCCC" SDVAL="271" SDNUM="1031;">271</TD>
			<TD ALIGN=RIGHT BGCOLOR="#CCCCCC" SDVAL="271" SDNUM="1031;">271</TD>
		</TR>
		<TR>
			<TD HEIGHT=17 ALIGN=LEFT>start</TD>
			<TD ALIGN=RIGHT SDVAL="1" SDNUM="1031;">1</TD>
			<TD ALIGN=RIGHT SDVAL="1" SDNUM="1031;">1</TD>
			<TD ALIGN=RIGHT SDVAL="1" SDNUM="1031;">1</TD>
			<TD ALIGN=RIGHT SDVAL="1" SDNUM="1031;">1</TD>
			<TD ALIGN=RIGHT SDVAL="1" SDNUM="1031;">1</TD>
		</TR>
		<TR>
			<TD HEIGHT=17 ALIGN=LEFT BGCOLOR="#CCCCCC">forge:entity</TD>
			<TD ALIGN=RIGHT BGCOLOR="#CCCCCC" SDVAL="164" SDNUM="1031;">164</TD>
			<TD ALIGN=RIGHT BGCOLOR="#CCCCCC" SDVAL="164" SDNUM="1031;">164</TD>
			<TD ALIGN=RIGHT BGCOLOR="#CCCCCC" SDVAL="164" SDNUM="1031;">164</TD>
			<TD ALIGN=RIGHT BGCOLOR="#CCCCCC" SDVAL="164" SDNUM="1031;">164</TD>
			<TD ALIGN=RIGHT BGCOLOR="#CCCCCC" SDVAL="164" SDNUM="1031;">164</TD>
		</TR>
		<TR>
			<TD HEIGHT=17 ALIGN=LEFT>unknown</TD>
			<TD ALIGN=RIGHT SDVAL="108" SDNUM="1031;">108</TD>
			<TD ALIGN=RIGHT SDVAL="304" SDNUM="1031;">304</TD>
			<TD ALIGN=RIGHT SDVAL="394" SDNUM="1031;">394</TD>
			<TD ALIGN=RIGHT SDVAL="630" SDNUM="1031;">630</TD>
			<TD ALIGN=RIGHT SDVAL="649" SDNUM="1031;">649</TD>
		</TR>
		<TR>
			<TD HEIGHT=17 ALIGN=LEFT BGCOLOR="#CCCCCC">player</TD>
			<TD ALIGN=LEFT BGCOLOR="#CCCCCC">-</TD>
			<TD ALIGN=RIGHT BGCOLOR="#CCCCCC" SDVAL="441" SDNUM="1031;">441</TD>
			<TD ALIGN=RIGHT BGCOLOR="#CCCCCC" SDVAL="441" SDNUM="1031;">441</TD>
			<TD ALIGN=RIGHT BGCOLOR="#CCCCCC" SDVAL="882" SDNUM="1031;">882</TD>
			<TD ALIGN=RIGHT BGCOLOR="#CCCCCC" SDVAL="882" SDNUM="1031;">882</TD>
		</TR>
		<TR>
			<TD HEIGHT=17 ALIGN=LEFT>INACCESSIBLE</TD>
			<TD ALIGN=RIGHT SDVAL="561" SDNUM="1031;">561</TD>
			<TD ALIGN=RIGHT SDVAL="401" SDNUM="1031;">401</TD>
			<TD ALIGN=RIGHT SDVAL="183" SDNUM="1031;">183</TD>
			<TD ALIGN=RIGHT SDVAL="87" SDNUM="1031;">87</TD>
			<TD ALIGN=RIGHT SDVAL="207" SDNUM="1031;">207</TD>
		</TR>
		<TR>
			<TD HEIGHT=17 ALIGN=LEFT BGCOLOR="#CCCCCC">BORDER</TD>
			<TD ALIGN=RIGHT BGCOLOR="#CCCCCC" SDVAL="265" SDNUM="1031;">265</TD>
			<TD ALIGN=RIGHT BGCOLOR="#CCCCCC" SDVAL="333" SDNUM="1031;">333</TD>
			<TD ALIGN=RIGHT BGCOLOR="#CCCCCC" SDVAL="305" SDNUM="1031;">305</TD>
			<TD ALIGN=RIGHT BGCOLOR="#CCCCCC" SDVAL="405" SDNUM="1031;">405</TD>
			<TD ALIGN=RIGHT BGCOLOR="#CCCCCC" SDVAL="437" SDNUM="1031;">437</TD>
		</TR>
		<TR>
			<TD HEIGHT=17 ALIGN=LEFT>unknown</TD>
			<TD ALIGN=LEFT>-</TD>
			<TD ALIGN=RIGHT SDVAL="4" SDNUM="1031;">4</TD>
			<TD ALIGN=LEFT>-</TD>
			<TD ALIGN=RIGHT SDVAL="2" SDNUM="1031;">2</TD>
			<TD ALIGN=LEFT>-</TD>
		</TR>
		<TR>
			<TD HEIGHT=17 ALIGN=LEFT BGCOLOR="#CCCCCC">TICKING</TD>
			<TD ALIGN=RIGHT BGCOLOR="#CCCCCC" SDVAL="235" SDNUM="1031;">235</TD>
			<TD ALIGN=RIGHT BGCOLOR="#CCCCCC" SDVAL="287" SDNUM="1031;">287</TD>
			<TD ALIGN=RIGHT BGCOLOR="#CCCCCC" SDVAL="266" SDNUM="1031;">266</TD>
			<TD ALIGN=RIGHT BGCOLOR="#CCCCCC" SDVAL="350" SDNUM="1031;">350</TD>
			<TD ALIGN=RIGHT BGCOLOR="#CCCCCC" SDVAL="382" SDNUM="1031;">382</TD>
		</TR>
		<TR>
			<TD HEIGHT=17 ALIGN=LEFT>unknown</TD>
			<TD ALIGN=RIGHT SDVAL="4" SDNUM="1031;">4</TD>
			<TD ALIGN=RIGHT SDVAL="11" SDNUM="1031;">11</TD>
			<TD ALIGN=RIGHT SDVAL="6" SDNUM="1031;">6</TD>
			<TD ALIGN=RIGHT SDVAL="10" SDNUM="1031;">10</TD>
			<TD ALIGN=RIGHT SDVAL="7" SDNUM="1031;">7</TD>
		</TR>
		<TR>
			<TD HEIGHT=17 ALIGN=LEFT BGCOLOR="#CCCCCC">PRIMED</TD>
			<TD ALIGN=RIGHT BGCOLOR="#CCCCCC" SDVAL="606" SDNUM="1031;">606</TD>
			<TD ALIGN=RIGHT BGCOLOR="#CCCCCC" SDVAL="1566" SDNUM="1031;">1566</TD>
			<TD ALIGN=RIGHT BGCOLOR="#CCCCCC" SDVAL="2034" SDNUM="1031;">2034</TD>
			<TD ALIGN=RIGHT BGCOLOR="#CCCCCC" SDVAL="2931" SDNUM="1031;">2931</TD>
			<TD ALIGN=RIGHT BGCOLOR="#CCCCCC" SDVAL="2986" SDNUM="1031;">2986</TD>
		</TR>
		<TR>
			<TD HEIGHT=17 ALIGN=LEFT BGCOLOR="#CCCCCC">FULL</TD>
			<TD ALIGN=RIGHT BGCOLOR="#CCCCCC" SDVAL="4291" SDNUM="1031;">4291</TD>
			<TD ALIGN=RIGHT BGCOLOR="#CCCCCC" SDVAL="4739" SDNUM="1031;">4739</TD>
			<TD ALIGN=RIGHT BGCOLOR="#CCCCCC" SDVAL="4739" SDNUM="1031;">4739</TD>
			<TD ALIGN=RIGHT BGCOLOR="#CCCCCC" SDVAL="5763" SDNUM="1031;">5763</TD>
			<TD ALIGN=RIGHT BGCOLOR="#CCCCCC" SDVAL="5833" SDNUM="1031;">5833</TD>
		</TR>
	</TBODY>
</TABLE>
</BODY>

</HTML>

Collected some data... it seems this forge:entity is always the same.
The only things that have chunkloaded stuff are mekanism, ic2c and ftb chunks.
The ic2c has it's recipe disabled and noone touched mekanism yet (except me, i just make tons of plastic^^).
There are only 3 dudes (me and two friends) who reallllly go into tech mods and are online... i have asked them and
they do all their chunkloading with ftb chunks.

There's on thing i will try next. When the other two guys are online, we will delete all our chunkloaded chunks in ftb chunks, restart the server and reclaim them.

**Comment by Shizz00** [comment]
More things i found out:
The tickets in my chunks that work correctly are called "forge:entity_ticking" and are unloaded after disconnect
The tickets of my two friends are called "forge:entity" and are even loaded if the zone is completely deleted!!!
My zones, when i'm not there, has only the one "forge:entity_ticking" ticket.
The zones of my two friends have two tickets, "forge:entity_ticking" and "forge:entity". The "forge:entity" remains even if they are offline or decide to delete the zone. That chunk will keep the "forge:entity" ticket and will be loaded.
I checked this with the gui of the crash utilities mod.

**Comment by desht** [comment]
Good information, thanks.  FTB Chunks *only* registers `forge:entity_ticking` tickets, although older releases did at one point register `forge:entity`.  It's a bit of a long shot, but I'll add a little code to ensure any old `forge:entity` tickets registered by Chunks are purged (they do persist across server restarts, so it's not impossible).  Are you in a position to try out a dev build of Chunks on your server?  Should be pretty safe (although of course take a backup first).

**Comment by Shizz00** [comment]
Yeah i can try that dev build. The server in physically located in my home :D
Is this dev build already uploaded somewhere?

**Comment by desht** [comment]
Yep, sorry, you can get it here: https://maven-admin.ftb.dev/repository/maven-public/dev/ftb/mods/ftb-chunks-forge/1902.3.15-build.235/ftb-chunks-forge-1902.3.15-build.235.jar

**Comment by Shizz00** [comment]
Well the server did not crash, but it also didn't fix the problem. Even after deleting the ftb chunks folder (so deleting all zones), the chunks where the zones previously were located, still have been loaded. Rolled everything back for now.

**Comment by desht** [comment]
Well, this is the thing: if that update didn't fix the problem, the problem can't be FTB Chunks anymore.  Check again with Crash Utilities; if the only tickets left are now `forge:entity`, then there are 100% definitely no FTB Chunks chunkloading tickets remaining.  Current version of Chunks *only* uses `forge:entity_ticking` and the update I just gave you ensures any old `forge:entity` tickets that old versions of the mod once used are purged from the system.

So any remaining `forge:entity` tickets are from another mod.  Something else is holding those chunks loaded.

**Comment by desht** [comment]
One other thing we can check is your `data/chunks.dat` file, which is saved in the `world/` folder.  That's what Forge uses to track forced chunks (and why just clearing the ftbchunks/ folder doesn't necessarily clear everything).

Can you send me a copy of that for analysis?  That would provide some useful clues as to which mods have tickets currently.

**Comment by Shizz00** [comment]
The forge:entity tickets are in the exact same shape as the force loaded chunks that were selected in the ftb chunks map. Even in parts where no mod things were used (village or normal fields). And it is correct that new zones work with the _ticking ticket that gets purged like intended.
[chunks.zip](https://github.com/FTBTeam/FTB-Mods-Issues/files/10713730/chunks.zip)
(had to zip, apparently github does not know what .dat files are)

**Comment by desht** [comment]
Huh.  It's all ftbchunks, even the `forge:entity` tickets.  Are you definitely running that dev version I gave you?  It explicitly wipes any of those it finds on server startup.  Also, can you check your server startup log for a message in the form:
```
cleaned up <X> stale Forge chunkloading tickets for team ID <ID> in dimension <D>
```
If all else fails, it might be worth stopping the server, deleting the `chunks.dat` file (keep a copy just in case) and starting again.  Shouldn't break anything by doing that.

**Comment by Shizz00** [comment]
Yes i had the build number 235 that you posted, i the old one i use is 233.

**Comment by Shizz00** [comment]
Ok, i deleted the chunks.dat file and it works! The new tickets remained and the chunks with the old forge:entity ticket had to be reselected for chunkloading.

**Comment by desht** [comment]
Good news that it's working now, but I'm still puzzled that the code I added in that test build didn't purge those `forge:entity` entries.

It might OK just to purge all the Forge chunkloading tickets on every server restart, since Chunks keeps track itself of those chunks which should be loaded.  I'll do some testing with that and see if it helps.
