### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by geesl** [FTBTeam/FTB-Mods-Issues#658]
### Mod

FTB Quests

### Mod version

ftb-quests-forge-1902.4.6-build.176

### Forge / Fabric version

1.19.2 Forge - 43.2.3

### What issue are you having?

Command reward does not have permission to execute most commands. Only when cheats are on then the commands function properly.

### Steps to reproduce

1. Create a quest with a command reward.
2. In commands put a command with permission 3 or higher.
3. Complete the quest and claim the reward. You should get an unknown command output.

**Comment by desht** [comment]
Edit the command reward, and in the config screen, be sure that "Run as Player" is set to false.  Then the command will be executed as if run on the server console, with full permissions.
