### ISSUE TITLE
Automatically increase claiming & loading limits for teams vs players.

### ISSUE THREAD

**Issue by max-dau** [FTBTeam/FTB-Mods-Issues#66]
Hey!
My suggestion should be self explanatory. When players join a team right now, they all appear to have the standard amount of claims & loads together which is actually intended per player. The bigger a team gets, the worse this situation becomes, as one player can statistically only claim a fraction of what he would be able to claim without a team.
I suggest that the amount of chunks a team can claim and load should be equal to the sum of the amounts all of the teams members could claim on their own.

**Comment by mjevans** [comment]
After creating / joining a team the FTB Chunks map (bound to the m key in Enigmatica 6 for 1.16.5) claims chunks as the team.

Chunks are now claimed against that team.

/ftbchunks admin extra_claim_chunks $USER $ACTION $NUMBER

ONLY allows users, which have zero reflection on the team's limits.

Chunks don't appear to be able to be claimed as anyone other than the group, and I can't adjust the group limit as an operator.

Additionally, it would be really nice to have a 'claim' command that accepted ANY sort of range, so I could just claim a big swath for a project, and so the map tools could claim a rectangle.

**Comment by desht** [comment]
This one was actually fixed some time ago, probably as part of a separate issue.  See new `party_limit_mode` (as well as `hard_team_claim_limit` and `hard_team_force_limit`) settings in server config.
