### ISSUE TITLE
[Feature Request]: FTB Quests, dissallow manual turn in

### ISSUE THREAD

**Issue by Saereth** [FTBTeam/FTB-Mods-Issues#661]
### Mod

FTB Quests

### Description

Requestion an option to mark a quest to disallow manual turn in. 

### Describe the solution you'd like

We would like for people to only be able to gain quest progress via the screens instead of manually completing so we can ensure automated logistics lines become a part of the questing process.

**Comment by desht** [comment]
Fixed in latest FTB Quests release
