### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Supermarcel10** [FTBTeam/FTB-Mods-Issues#663]
### Mod

FTB Teams / FTB Chunks

### Mod version

ftb-teams-forge-1605.2.3-build.40.jar / ftb-chunks-forge-1605.3.4-build.220.jar

### Forge / Fabric version

1.12.2

### Modpack & version

Create: Above and Beyond v1.3

### What issue are you having?

A user (e.g. userA) on my server has claimed a few chunks before creating a team. After creating a team and adding a user (userB) to it, the added user(userB) cannot access (build/interact/destroy) those chunks previously claimed by the owning user (userA). Those chunks still show up as owned by the creating user (userA), rather than the team.

I do not have an alt account to test this myself. I have tested solo on a cloned server instance, with the same settings. When claiming chunks and creating a team, those chunks are changed to team chunks - therefore I was unable to reproduce this myself.

Same might be true if a user were to claim chunks and then join a team - however I have not tested this functionality.

### Steps to reproduce

Direct steps to reproduce, according to user:
1) Claim chunk(s).
2) Create team.
3) Claim different chunks.
4) Invite friend to team.
5) Friend can only access newly claimed chunks, but not old chunks.

As previously said, I do not have an alt account to test this myself.
But from my testing I was unable to reporoduce this situation.

**Comment by desht** [comment]
Yes, this is a known limitation in FTB Chunks in 1.16.  The user will need to unclaim and reclaim any chunks that were claimed before they created their party team.

1.16 is in critical-fixes support only, and this is not a critical bug, so won't be fixed, sorry.
