### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ShultzO** [FTBTeam/FTB-Mods-Issues#664]
### Mod

FTB chunks

### Mod version

ftb-teams-forge:1605.3.3-build.200

### Forge / Fabric version

forge 1.16.5 36.2.39

### Modpack & version

Chroma Endless 

### What issue are you having?

when I click on the button to open the map, I open claim chunks and not a huge map as it should be initially

### Steps to reproduce

may not be the correct setting

**Comment by MichaelHillcox** [comment]
Do you have Journey map installed?

**Comment by ShultzO** [comment]
yep

**Comment by MichaelHillcox** [comment]
That's why then, if you have Journey map installed, we default to their map instead of our own.
