### ISSUE TITLE
[Feature Request]: Disable Clicking on Quests with Dependencies

### ISSUE THREAD

**Issue by FooterMan14** [FTBTeam/FTB-Mods-Issues#665]
### Mod

FTB Quests

### Description

Would be cool to have a feature that disables clicking on quests with un-completed dependencies, like BQM. I think part of what made BQM great was the suspense to getting to locked quests, and attempting to prepare for them.

### Describe the solution you'd like

Add a quest/chapter option that disables interaction with Quests that have uncompleted dependencies, until said dependencies are completed.

**Comment by desht** [comment]
So the quest tree would be visible, but not possible to inspect the detailed quest description or the tasks until the quest unlocks?  Sounds reasonable, sure.

**Comment by desht** [comment]
Added a "Hide Details Until Startable" property for quests (and for chapters - default for quests is to check the chapter setting, which is false by default).
