### ISSUE TITLE
[Bug]: [QUILT] [QUESTS] Some popups and base gui are unable to work their intended way

### ISSUE THREAD

**Issue by Qraculum** [FTBTeam/FTB-Mods-Issues#667]
### Mod

FTB Quests

### Mod version

ftb-quests-fabric-1902.4.6-build.176

### Forge / Fabric version

1.19.2 Quilt 0.17.10  

### What issue are you having?

A) Cannot open whole GUI (with any way), as the message seen in the image below happens to be typed as a response. 
Temporary fix to A: need to enable yourself editing mode and reload the files (with commands in-game); this fix stays for as long as I am not relaunching whole minecraft (can rejoin the same world in singleplayer)
![Screenshot_4914](https://user-images.githubusercontent.com/103532026/216762062-e6f6276d-7c41-4aa7-be91-6927387729e9.png)

B) Auto-claim and popups as the quest completion never work, though popups while claiming items yourself do work ("Reward Collected")

### Steps to reproduce

Bug A) Happens with every launch of MC
Bug B) Always, no matter what

**Comment by desht** [comment]
Have you checked for server-side errors, as suggested by the message?

**Comment by Qraculum** [comment]
You mean in the game logs? I don't see any errors, only the lines visible in the image and the chat logs of server typing the response mentioned in main post
![Screenshot_4915](https://user-images.githubusercontent.com/103532026/216764381-9ee21a2c-edd4-42ce-8baa-f651c122fbbf.png)
[latest.log](https://github.com/FTBTeam/FTB-Mods-Issues/files/10608484/latest.log)

**Comment by desht** [comment]
Can you attach your `debug.log` file as well please?

**Comment by Qraculum** [comment]
Oh really sorry for the late response. How could I get the mentioned debug.log? Do I need to enable debug log level somewhere or use other launcher than vanilla?

**Comment by desht** [comment]
You should have a debug.log in your `logs/` folder along with the `latest.log`

**Comment by Qraculum** [comment]
Yeah that's the thing - it isn't getting created automatically for me. I tried googling anything about it and I've come to nothing basically.

**Comment by desht** [comment]
I'm not sure about the vanilla launcher but I believe the Curseforge app disables debug.log by default.  There is a setting for that though:

> Curseforge App: Debug Logging
> To enable debug logging in the Curseforge app, open the app and click the cog/gear icon in the bottom-left of the app. This will open the app settings.
>
> In the app settings, choose Minecraft under Game Specific settings and toggle on the Enable Forge debug log option

![image](https://user-images.githubusercontent.com/736831/217191447-8f132e4d-07c1-4dcf-ad6d-eb318cb1a936.png)

**Comment by desht** [comment]
Yeah, that doesn't contain much. Unfortunately I really need see the debug output from several mods to have a chance of tracking this down. It's not clear right now why the server data isn't getting transferred - my best guess is that some other mod is throwing an exception during the player login process so the FTB Teams login event doesn't get fired, and then FTB Quests doesn't get notified to sync the data to your client.  But without seeing a debug log, it's impossible to know for sure.

**Comment by Qraculum** [comment]
After halving the mods many times and trying them out I finally found the sus guy - in 99% it was Roughly Enough Resources the one making the problems, though they only happened on quilt, not fabric. It's the latest version, 2.6.0, of it as the last update for fabric was in June. 
Here are all the mods if you would want to try to do something with it:
https://drive.google.com/file/d/1SRvh8JVAjWbPtqoQm8cuRDrJmBEsf4ne/view?usp=sharing
