### ISSUE TITLE
[Bug]: Playtime Bug

### ISSUE THREAD

**Issue by Flavoniu00s** [FTBTeam/FTB-Mods-Issues#674]
### Mod

FTB Ranks

### Mod version

ftb-ranks-forge-1902.1.14-build.70

### Forge / Fabric version

1.19.2 43.2.4

### What issue are you having?

I run a Minecraft server with a few mods, and made Custom Ranks. I use in all ranks the "playtime" condition type. But if anybody joins, they get all aviable ranks.
[Mods](https://pste.ch/ahohizoqob.css)
[Ranks](https://pste.ch/moretufisi.bash)

### Steps to reproduce

Use my Ranks on a Server and join it

**Comment by desht** [comment]
None of the ranks in your ranks file are actually using the playtime condition, so I'm not sure what you're trying to achieve here?

**Comment by Flavoniu00s** [comment]
> 

Sorry wrong link, now it should be working

**Comment by desht** [comment]
Your problem  is the `time_units` field, which should be `time_unit`.  Because it was missing, it default to a time unit of ticks, which of course every player would match.

I'll add a warning log message in the next release if it defaults like this, since that's usually not what is wanted.

**Comment by Flavoniu00s** [comment]
> Your problem is the `time_units` field, which should be `time_unit`. Because it was missing, it default to a time unit of ticks, which of course every player would match.
> 
> I'll add a warning log message in the next release if it defaults like this, since that's usually not what is wanted.

Thank You! It works now
