### ISSUE TITLE
[Feature Request]: Locked quests should still be dark in Flexible mode

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-Mods-Issues#675]
### Mod

FTB Quests

### Description

![image](https://user-images.githubusercontent.com/15698722/217647274-587addf4-db0a-45d0-a1bc-7ac3e52ee2c8.png)
Like this, the flow of quests is harder to understand. It should stay dark when locked (and when locked but tasks completed), I think.

**Comment by desht** [comment]
Fixed in latest FTB Quests release
