### ISSUE TITLE
[Feature Request]: FTBQ should refuse to make a chapter if there's already a chapter with that file name

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-Mods-Issues#676]
### Mod

FTB Quests

### Description

I just lost like an hour's work from what I assume is this.

I have a Storage group, so I wanted to make a Misc chapter named `misc` in it, for misc storage things.

I also have another group, which also has a misc chapter, also named `misc`.

The Storage Misc did not save, because the other misc shared its file name and overwrote it.

When making a new chapter, it should check to ensure that that name is free, and refuse if it isn't.

**Comment by desht** [comment]
Yeah, that's quite bad.  The *right* solution would be store the quest book on using chapter group and chapter name, not just chapter name.  But that's risky to change mid-version (too much chance of existing quest book data being trashed trying to reorganise it).  So in the short term disallowing duplicate chapter names is probably the best option.

**Comment by desht** [comment]
Working through the code, I discovered there actually is already a check for clashing chapter names for file storage purposes... but only for the chapters in the same group. Oops.  On the plus side, it's easy to extend this check to look at *all* the chapters in the book, which means duplicate chapter names will be allowed (on file, a `_x` suffix is added to the filename, where `x` is a small integer).

**Comment by desht** [comment]
Fixed in latest FTB Quests release
