### ISSUE TITLE
[Bug]: Entity Interaction quest type not working consistently

### ISSUE THREAD

**Issue by NostalJay** [FTBTeam/FTB-Mods-Issues#678]
### Mod

FTB Quests (Forge)

### Mod version

ftb-quests-forge-1902.4.6-build.176.jar

### Forge / Fabric version

1.19.2 Forge - 43.2.3

### What issue are you having?

Entity Interaction task type is not functioning consistently.  The same player actions will trigger quest progress, then suddenly will not.  For example: Task interact with horse with saddle in hand x1, will function, after deleting that quest, or creating a quest with the same requirements, quest will not progress.

### Steps to reproduce

1. Create a quest with entity interaction task type
2. complete the quest
3. delete the quest
4. create any entity interaction task type
5. task will not progress as expected

**Comment by desht** [comment]
Entity Interaction is a not a task type offered by FTB Quests, so I'm guessing you're using the Quests Additions mod?  That's a third-party addon, and not supported by us.  You'll need to speak with the author of that mod about it.
