### ISSUE TITLE
[Feature Request]: Recursive weak NBT match

### ISSUE THREAD

**Issue by baileyholl** [FTBTeam/FTB-Mods-Issues#680]
### Mod

FTB Quests

### Description

Currently, weak match fails for nested tags if the nested tags do not entirely match. This causes items that store complex NBT in nested tags to be undetectable, especially if they are blockentity tags. 

Example:
Currently, weak match with a tag:
{ blockEntity: {entityTag: {id: "..."} } } 

fails if your actual item is 
{blockEntity: { entityTag: {id: "..." someOtherField: ".." } }} 

### Describe the solution you'd like

Ideally, we would have an option to recursively weak match only the specified tags.

If I want to detect:
{ blockEntity: {entityTag: {id: "..."} } } 

Then it is a successful match IF:
blockEntity exists and contains entityTag
AND entityTag contains ID
AND ID == the value

Ignoring any other tags at other levels.

**Comment by desht** [comment]
Fixed in latest FTB Quests release
