### ISSUE TITLE
[Bug]: FTB Quests NBT Parser Broken for list tags

### ISSUE THREAD

**Issue by baileyholl** [FTBTeam/FTB-Mods-Issues#682]
### Mod

FTB Quests

### Mod version

ftb-quests-forge-1902.4.6-build.176.jar

### Forge / Fabric version

1.19.2 43.2.3

### What issue are you having?

List tags are not parsing lists of doubles correctly, or not being serialized correctly. I have a reward with blocks that store an entity tag as part of the block and item tag, but FTB quests detects this as invalid and will not load the chapter.

Failed to read C:\Users\baile\curseforge\minecraft\Instances\skypack\config\ftbquests\quests\chapters\drygmy_jars.snbt: Unexpected tag '-0.08d' in list @ 2254:31 - can't mix two different tag types in a list!

Quest file here: https://pastebin.com/Pfd2wSLp

### Steps to reproduce

1. Add reward with an item that has a list tag with doubles in it.
2. Reload the game
3. Quests will not load

**Comment by desht** [comment]
Looks like the SNBT parser in FTB Library is wrongly interpreting `1.962601141863566E-4d` as a string instead of double.  Then the next element `-0.08d` as a double, and types can't be mixed in NBT lists.

Should be an easy fix I think (add support for scientific notation to double values).

**Comment by desht** [comment]
Fixed in latest FTB Library release.
