### ISSUE TITLE
[Bug]: Cannot read field "dimension" because "this.this$0.dimension" is null

### ISSUE THREAD

**Issue by Lancelotbronner** [FTBTeam/FTB-Mods-Issues#686]
### Mod

FTB Chunks

### Mod version

ftb-chunks-fabric-1802.3.13-build.234

### Forge / Fabric version

0.14.4

### What issue are you having?

Waypoints don't display in-world, trying to access the world map just crashes the game.

`java.lang.NullPointerException: Cannot read field "dimension" because "this.this$0.dimension" is null`

### Crashlogs

Crashlog: https://pste.ch/emaqasefar.php

### Steps to reproduce

1. Connect to a dedicated server with FTB Chunks
2. Try to open the world map
3. Boom.

### Anything else to note?

Every mods have been updated to their latest versions on Minecraft 1.18.2

**Comment by desht** [comment]
Tracked with #616

**Comment by Lancelotbronner** [comment]
Sorry for bumping, but I see a fix has been made a long time ago however there hasn't been a release for Fabric 1.18.2 with it yet. When will this be shipped?
