### ISSUE TITLE
[Bug]: Invalid distance too far back

### ISSUE THREAD

**Issue by FooterMan14** [FTBTeam/FTB-Mods-Issues#687]
### Mod

FTBQ

### Mod version

1902.4.8

### Forge / Fabric version

43.2.4

### Modpack & version

https://github.com/TheGangModpacks/Fun-in-the-Sky/releases/tag/0.0.5

### What issue are you having?

Got some weird unknown crash here for you. Started debugging and found enabling FTBQ causes it.

### Crashlogs

Crash: https://gist.github.com/FooterMan14/c097f2c0cfacad84ce8e1bd55a08c0ab
Latest: https://gist.github.com/FooterMan14/74ff73b060bda491050d1c8b51483ab0

### Steps to reproduce

Install FTBLib, FTBQuests.
Run the game.

### Anything else to note?

If you require a mod-list, I'll be happy to provide... as long as I can find some way to.

**Comment by FooterMan14** [comment]
Just tested an instance with just FTBLib, Quests, and their dependencies with no crash. I commited my latest quest changes on our repo if you'd like to take a look.

**Comment by desht** [comment]
There's nothing whatsoever here to suggest any problem with an FTB mod. The error suggests a possible corrupted mod JAR file, but it's hard to be certain.  In any case, I don't think there's anything else I can add here, sorry.
