### ISSUE TITLE
[Feature Request]: "max_idle_days_before_unforce" should use a double or float value

### ISSUE THREAD

**Issue by LordNoisy** [FTBTeam/FTB-Mods-Issues#688]
### Mod

FTB Chunks

### Description

To save TPS I would like to set my servers loaders to turn off after 12 hours - enough to generate resources and such through the night, but also enough so that chunks aren't permenantly loaded. Since the value for the "max_idle_days_before_unforce" is a long, and the unit is real-life days, this means you can't set chunk loaders to disable any time less than a day, which is a severe limitation in my opinion. 

### Describe the solution you'd like

The value should allow decimal inputs rather than being a long

**Comment by desht** [comment]
While days are a natural unit for this sort of duration, allowing fractional amounts is a good idea, sure.  Will be in next Chunks release.

**Comment by desht** [comment]
Fixed in latest Chunks release
