### ISSUE TITLE
[Bug]: FTBQuests only allows "Flowing Fluids" to be set

### ISSUE THREAD

**Issue by Speiger** [FTBTeam/FTB-Mods-Issues#689]
### Mod

FTBLibrary/FTBQuests

### Mod version

1.19.2 Latest Most likely a lot of different versions too

### Forge / Fabric version

ForgeAny

### Modpack & version

Custom in progress

### What issue are you having?

FTB Fluids only allows flowing fluids to be selected instead of source fluids.
Which doesn't make sense, since "Flowing Water/Lava" is unobtainable.
And all mods that add Fluids without blocks set their fluids to be source only, meaning all custom piped liquids get filtered out instantly.

Class: SelectFluidScreen (FTBLibrary)
Code that is the issue:
```java
    for (Fluid fluid : Registry.FLUID) {
      if (fluid == Fluids.EMPTY || fluid.defaultFluidState().isSource()) //This second check
        continue;
    }
```

### Steps to reproduce

Install Immersive Engineering or IC2Classic or any mod that is having fluids without blocks and try to select their fluids.

For Immersive Engineering it would be Potion fluid
and for ic2c it would be: Blazing Lava/WoodGas/Steam/BioFuel/Alcohol

**Comment by desht** [comment]
Agreed, this doesn't look right.

**Comment by desht** [comment]
Fixed in latest FTB Lib release

**Comment by Speiger** [comment]
Thank you!
Already noticed by the packdev who uses it :)
