### ISSUE TITLE
[Feature Request]: Additional quest image click features

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-Mods-Issues#691]
### Mod

FTB Quests

### Description

Right now, the quest image click option just opens a URL. It would be nice if it could do the various text json things (without being a json preferably)

**Comment by desht** [comment]
I'm not really clear on what you're looking for in this one.  What does "various text json things" mean?

**Comment by desht** [comment]
These are both actually possible right now (the docs for Quests really need updating - fortunately that's underway)

* To run a command, use `command:<command>`.  Although that runs the command unsigned right now (needs a FTB Library change).  I need to find out why it's currently done that way and if there are any dangers to running the command signed.
* To open a quest, just use `#<quest-id>`, i.e. the quest ID you get from using the "Copy ID" context menu entry, preceded by a `#` mark.

**Comment by aaronhowser1** [comment]
Ahhhh, I tried just the quest id without the # and it caused a crash. Fair enough then!

**Comment by desht** [comment]
Well, it shouldn't crash :)  I'll fix that while I'm at it.

**Comment by desht** [comment]
Fixed in latest Quests release.
