### ISSUE TITLE
[Bug]: Quest image hover text does not support & formatting

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-Mods-Issues#692]
### Mod

FTB Quests

### Mod version

ftb-quests-forge-1902.4.8-build.190

### Forge / Fabric version

1.19.2 43.2.4

### What issue are you having?

![image](https://user-images.githubusercontent.com/15698722/220540484-2cefe1c0-d70b-44e4-8b45-66319240e8c5.png)

### Steps to reproduce

n/a

**Comment by desht** [comment]
Fixed in latest Quests release
