### ISSUE TITLE
[bug] Rare NPE from `MapDimension.getCurrent`

### ISSUE THREAD

**Issue by NielsPilgaard** [FTBTeam/FTB-Mods-Issues#70]
Relayed from: https://github.com/NillerMedDild/Enigmatica6/issues/2922

Crashing when opening the map. The player must have claimed chunks for the crash to have a chance to occur, I believe.

**Mod & Pack version**
ftb-chunks-forge-1605.3.1-build.41

**Forge / Fabric version, if applicable**
Forge

**Modpack (with version), if applicable**
Enigmatica 6 v0.5.9

**If the issue is a crash; An external link to the crash report**

**How to reproduce the issue**
*Please provide use with a step by step description*
I'm afraid I cannot reproduce it, but multiple people have experienced it.

**Comment by DoraTheExploder** [comment]
Dropping in to give you another crash log related to this issue in case the extra info helps: https://crashy.net/2ucU2HtXEmBspHFcmfD3

**Comment by rmccarthy1504** [comment]
Same issue for many users on our server.

I wasn't experiencing the issue yesterday, but have begun to today with no server or client side changes.

https://paste.feed-the-beast.com/view/33c56cda

**Comment by MichaelHillcox** [comment]
I've fixed this on 1.18... well patched, I don't know the root cause yet but I'm working it out... I'll back port the fix soon

**Comment by Jetpack-Cat** [comment]
I'm having this issue on my public server for 1.16.5. Where are the files located on the server? What folder can I delete to fix this say least temporarily?

**Comment by MichaelHillcox** [comment]
Please see #616 as our main tracking issue for this crash
