### ISSUE TITLE
[Bug]: Reward table weights are are input as decimals but save as integers

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-Mods-Issues#701]
### Mod

FTB Quests

### Mod version

ftb-quests-forge-1902.4.9-build.195

### Forge / Fabric version

1.19.2 43.2.4

### What issue are you having?

![image](https://user-images.githubusercontent.com/15698722/222307832-ad6c9c8b-dbe6-42fd-bb4b-c86d60e3166b.png)

This is the default weight. If I set it to 1.5, it actually sets to 1.

### Steps to reproduce

N/A

**Comment by desht** [comment]
This looked like a bug to me too initially, but it's actually intended behaviour, even though really unintuitive...

The idea is that you can set a weight of < 1, which will cause the weight to be adjusted to 1, and the weights of all other rewards to be adjusted upwards proportionally too.  E.g. if you have

Item A - 5
Item B - 1
Item C - 2

and you change Item B to have a weight of 0.5, you end up with

Item A - 10
Item B - 1
Item C - 4

But it only has an effect for weights less than 1 - any fractional weight > 1 is just rounded down.  So yeah, useful but not at all obvious without looking at the code.

Open to suggestions on making this behaviour a bit friendlier...

**Comment by aaronhowser1** [comment]
Yeah fractional weights above 1 would be the most logical I think
