### ISSUE TITLE
[Feature Request]: FTB Chunks add "can see players at xx range" config option

### ISSUE THREAD

**Issue by Grishord** [FTBTeam/FTB-Mods-Issues#702]
### Mod

FTB Chunks

### Description

The ability to set a range (including infinite) at which you can see other players on the big map (not mini map)

### Describe the solution you'd like

Just a config option would be fantastic! 

### Describe alternatives you've considered

I have dynmap but I'd like in game functionality as well.

**Comment by desht** [comment]
Just to note that it's already possible to see players on the map outside the normal vanilla entity tracking range (but only if they are in your team, or their team settings make their location public to all players).  So this is already in-game, with an unlimited range?

Are you requesting an option to limit the range at which you can see players?  On the understanding that this would potentially give you _less_ information than you have now?

**Comment by Grishord** [comment]
I guess I want to be able to override that as the server owner so everyone can see everyone without changing settings.

**Comment by desht** [comment]
Ah OK, a server-side setting that allows admins to override the team visibility preferences?

**Comment by desht** [comment]
Added in 1902.3.21
