### ISSUE TITLE
[Bug]:  \n in quest titles produces a bugged character in the tooltip

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-Mods-Issues#704]
### Mod

FTB Quests

### Mod version

ftb-quests-forge-1902.4.9-build.195

### Forge / Fabric version

1.19.2 43.2.4

### What issue are you having?

![image](https://user-images.githubusercontent.com/15698722/222896915-f9d9e8ea-3d2e-4898-819a-eec20bf00a09.png)

### Steps to reproduce

N/A

**Comment by desht** [comment]
Are you using a literal title here, with embedded `\n` sequences?

From my testing this does fail as you noted, but using a translation key which translates to a string containing `\n` works OK - the lines are split properly.  Do you also see that?

In any case, if it's only happening for literal titles, it's pretty easy to work around (just split the title when building the tooltip).

**Comment by aaronhowser1** [comment]
This was using a lang key that had an \n in it

**Comment by desht** [comment]
OK that's more of a problem then, because I can't reproduce that.

**Comment by aaronhowser1** [comment]
https://user-images.githubusercontent.com/15698722/223692249-c94ff52c-ca80-41cf-920d-63f62f9d7a84.mp4

![image](https://user-images.githubusercontent.com/15698722/223692276-9c30f657-5a95-4803-97fd-cfcaa850456b.png)

**Comment by desht** [comment]
Oh, I believe it's happening to you - I just can't make that happen in my dev instance :smile:
