### ISSUE TITLE
[Bug]: 1.18.2 FTB Chunks/Team Server gamebreaking issue

### ISSUE THREAD

**Issue by Saereth** [FTBTeam/FTB-Mods-Issues#705]
### Mod

FTB Teams + Chunks

### Mod version

ftb-chunks-forge-1802.3.13-build.234; ftb-teams-1802.2.10-build.96.jar

### Forge / Fabric version

40.1.93

### Modpack & version

FTB Inferno

### What issue are you having?

When upgrading to the latest ftb chunks/teams for mc 1.18.2 everything seemed fine in single player but upon running/connecting to a server the player gets disconnected with an invalid playerdata.

### Crashlogs

Not a crash but here is the latest.log 
https://gist.github.com/Saereth/8622e01d27f01729f4dfff3446766715

### Steps to reproduce

Make a 1.18.2 server with the latest version of ftb chunks and teams, try to connect, get booted. Downgrading the mods resolves this.

**Comment by Saereth** [comment]
This also happens in single player on this version for new world creation, existing worlds you upgraded to from previous teams seem to open fine in SP

**Comment by desht** [comment]
The fix was made in dev, but a version wasn't release for 1.18.2.  Just opened a PR for it.

**Comment by desht** [comment]
Fixed in FTB Teams 1802.2.11 (on CF now).
