### ISSUE TITLE
[Bug]: 1.19.2 (Forge) - FTB Chunks and Advanced Compass incompatibility, world crashes.

### ISSUE THREAD

**Issue by NovaLynxie** [FTBTeam/FTB-Mods-Issues#706]
### Mod

FTB Chunks [Forge]

### Mod version

ftb-chunks-forge-1902.3.15-build.233

### Forge / Fabric version

1.19.2 43.2.4

### What issue are you having?

Whenever I load a world, be it generating a new world or an old world, the game will crash right as I am about to load in.
I do not know if this happens on a server since this I have not yet tested it.

### Crashlogs

Crash Logs: 
[crash-2023-03-07_17-40-02-client-txt](https://gist.github.com/NovaLynxie/a7e645483dc62ccb8cd3e99907aa4b95#file-crash-2023-03-07_17-40-02-client-txt) / [hastebin link](https://hastebin.com/share/abilozosuh.php)

_I have uploaded it directly onto gist github incase the hastebin.com link stops working at any time._

### Minimum set of mods to test this (latest versions used at time of post):
architectury-6.5.69-forge
ftb-chunks-forge-1902.3.16-build.240
ftb-library-forge-1902.3.14-build.184
ftb-teams-forge-1902.2.12-build.95
AdvancedCompas-forge-1.19.2-1.2.14
### Steps to reproduce
1. Either: Generate a fresh new world save OR Load up an existing one in single-player mode.
2. Wait for the world to load up, and observe the loading sequence up to when it says 'Joining world' or close to that.
3. Game crashes and will close immediately, you should have a crash report generated in your crash-reports folder

### Anything else to note?

After looking through the logs, I have identified the following mods causing this issue.
I have identified it as a crash caused by the following mods:
Advanced Compasses - forge-1.19.2-1.2.14
Disabling or removing the following mods will allow the world to load properly.

This issue has not been reported before on this issue tracker but has been reported on the mod's own issue tracker page [here](https://www.curseforge.com/minecraft/mc-mods/advanced-compass/issues/53).

**Comment by desht** [comment]
Advanced Compasses is built against an older version of FTB Chunks.  The current FTB Chunks release doesn't have the `getWaypoints()` method; AC should be calling `MapDimension#getWaypointManager()` and iterating over that (the `WaypointManager` class implements `Iterable<Waypoint>`.
