### ISSUE TITLE
[Bug]: FTB chunk block edit / interact mod public = Blocks will still a block is placed.

### ISSUE THREAD

**Issue by sungho955** [FTBTeam/FTB-Mods-Issues#708]
### Mod

ftb-chunks-fabric-

### Mod version

ftb-chunks-fabric-1802.3.14-build.239

### Forge / Fabric version

fabric 1.18.2 - 0.14.12

### Modpack & version

It is in the same condition as previously posted.

### What issue are you having?

#673

The cloning issue has been fixed, but blocks are still installed.

Or are you still fixing it?

### Steps to reproduce

It is in the same condition as previously posted.

**Comment by sungho955** [comment]
![2023-03-09_18 18 06](https://user-images.githubusercontent.com/68801535/223976517-0ade603d-e1e9-4297-bdb1-ec25d1352787.png)
 here

**Comment by desht** [comment]
You didn't say it wasn't possible to break it.

Please, start again, and provide a clear description of your problem.  I can't fix your issue based on guesswork.

**Comment by sungho955** [comment]
Blocks can be placed by anyone not on your team.
It is impossible to break it again.

The modpack is the same modpack as before.
The party setting is as pictured.

The person who puts the block is not a member of the party
People who are not in your party can place blocks.

**Comment by desht** [comment]
OK, now I see the problem, thanks.  I'll get a new Fabric release out today to fix that.

**Comment by desht** [comment]
OK build 1802.3.15 is on Curseforge now, should fix that problem.

**Comment by sungho955** [comment]
thank you
in ftb chunk  mode
Interaction to public
Block edit can't be set to private?

**Comment by sungho955** [comment]
i want
block eddy = private
interaction = public

Is there any way to do it with this setup?

**Comment by desht** [comment]
Sorry, it's not possible on Fabric & Architectury due to the way block interactions are handled.  It's simply not possible to properly distinguish right-clicking a block to interact and right-clicking a block to place something.

**Comment by sungho955** [comment]
Thank you for your kind explanation.
