### ISSUE TITLE
[Bug]: Quest shop does not work

### ISSUE THREAD

**Issue by toster234** [FTBTeam/FTB-Mods-Issues#710]
### Mod

FTBMoney

### Mod version

ftbmoney:1605.1.4-build.9

### Forge / Fabric version

1.16.5-36.2.39

### Modpack & version

RAD 2 - 1.16.5

### What issue are you having?

Quest shop does not work when server is `online-mode=false`
The game is crashing when you try to use a store.

### Crashlogs

https://pste.ch/qeduramiho.rb

### Steps to reproduce

Set `online-mode` to false

**Comment by desht** [comment]
Offline servers are not supported. You should be running in online mode.
