### ISSUE TITLE
[Bug]: FTB Chunks crashes on start-up [FABRIC]

### ISSUE THREAD

**Issue by Poke097** [FTBTeam/FTB-Mods-Issues#715]
### Mod

FTB Chunks

### Mod version

ftb-chunks-fabric-1902.3.17-build.244

### Forge / Fabric version

1.19.2 Fabric 0.14.17

### What issue are you having?

Hello there!

After updating **Traveler's Backpack** to the latest version, it crashes FTB Chunks on start-up possibly due to this:

`Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector getOtherEntities(Lnet/minecraft/class_1937;Lnet/minecraft/class_1297;Lnet/minecraft/class_238;)Ljava/util/List; in travelersbackpack.mixins.json:ExplosionMixin from mod travelersbackpack failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap travelers-backpack-refmap.json`

Again, have no clue whether or not this is the case, but mentioning just in case.

### Crashlogs

https://mclo.gs/68TJxDO

### Steps to reproduce

1. Update Traveler's Backpack
2. Crash on start-up due to FTB Chunks

**Comment by desht** [comment]
In no way an FTB Chunks problem, even if it gets mentioned in the log.  Complain to the Traveler's Backpacks author.
