### ISSUE TITLE
[Bug]: Formation Plane crash in force loaded chunks

### ISSUE THREAD

**Issue by Miku0Sama** [FTBTeam/FTB-Mods-Issues#717]
### Mod

FTB Chunks

### Mod version

ftb-chunks-fabric-1902.3.17-build.244

### Forge / Fabric version

1.19.2 0.14.17

### Modpack & version

All of Fabric 6 AOF6 - 1.4.5

### What issue are you having?

When a Formation Plane from AE2 attempts to place a block inside a force loaded chunk on a dedicated server, it crashes the server.

### Crashlogs

https://gist.github.com/Miku0Sama/686ee998bb034fe1756c1672516246f0

### Steps to reproduce

1. Set-up an isolated sub-network on AE2 with a Formation Plane and Import Bus (No other devices and powered via quartz fiber from another cable)
2. Make sure everything is in the same force loaded chunk
3. Have the Formation Plane attempt to place a block (again, in the same chunk)
4. Behold! Crash!

### Anything else to note?

I haven't done much testing of this yet outside of AE2 but it's possible other block placers might have a similar issue
I already created an issue on the AE2 github and they directed me here.
The issue on AE2 github: https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/6969
The block I was attempting to place with the Formation Plane was specifically a Flawed Budding Certus Quartz Block but the crash may occur with other blocks as well.
Again haven't tested it much as it puts the server into a crash loop if I'm not careful.

**Comment by desht** [comment]
Looks like the AE2 fake player is using a null connection field. While it really should be setting up a dummy connection field, I'll add an extra to FTB Chunks to verify it as well.

**Comment by desht** [comment]
Fixed in latest Chunks release for 1.18 & 1.19
