### ISSUE TITLE
[Bug]: Create Mod can be used for chunks griefing

### ISSUE THREAD

**Issue by sTiKyt** [FTBTeam/FTB-Mods-Issues#719]
### Mod

FTB Chunks

### Mod version

latest

### Forge / Fabric version

any

### What issue are you having?

Create Mod can be used for chunks griefing

### Steps to reproduce

Mechanisms from Create can freely enter claimed chunks and break stuff

**Comment by sTiKyt** [comment]
> If Create contraptions can break blocks in protected chunks, it means that Create isn't firing the relevant block interaction events for Chunks to catch and cancel. There's nothing that Chunks can do to prevent mods which just break blocks.

My friend designed create machine that can mine out entire bases like it's nothing xD

**Comment by desht** [comment]
> My friend designed create machine that can mine out entire bases like it's nothing xD

Good for him?  I would suggest raising an issue with the Create authors and check what events they fire when their contraptions break blocks.  I suspect the drill doesn't fire a break event from looking at the Create code.  As I said before, there's nothing we  can do about that, sorry.
