### ISSUE TITLE
[Bug]: co-dependency bug

### ISSUE THREAD

**Issue by oleg12054** [FTBTeam/FTB-Mods-Issues#721]
### Mod

FTB-qestes

### Mod version

ftb-quests-forge-1802.3.10-build.138

### Forge / Fabric version

Forge 1.18.2

### What issue are you having?

When you put the dependency of another item on the first item, then put the dependency of the first item on the other, it crashes... Make it so that in this case the dependency in one of the quests is reset to zero.
And how can I restore access to this page that crashes?

### Crashlogs

[2023-03-20-3.log.gz](https://github.com/FTBTeam/FTB-Mods-Issues/files/11028083/2023-03-20-3.log.gz)
[crash-2023-03-20_21.21.24-client (1).txt](https://github.com/FTBTeam/FTB-Mods-Issues/files/11028085/crash-2023-03-20_21.21.24-client.1.txt)
[latest (2).log](https://github.com/FTBTeam/FTB-Mods-Issues/files/11028086/latest.2.log)

### Steps to reproduce

1.create a quest
2.create a second quest
3.create a dependency of the first(1) quest with the second(2)
4.create a dependency of the second (2) quest with the first (1)

### Anything else to note?

now there is no access to the page with quests on which such an error occurred. minecraft crashes immediately

**Comment by desht** [comment]
FTB Quests prevents adding quests with circular dependencies when creating quests in the normal way, i.e. via the GUI.  It will pop up an error if you try to do that.  Did you edit the quest files directly?

In any case, repairing the problem will require going through your quest files and identifying the quests with circular dependencies (i.e. where the quest ID appears in another quests dependency list and vice versa), and removing one of the dependencies.

**Comment by oleg12054** [comment]
Разобрался, исправил через .script. Спасибо

**Comment by desht** [comment]
Please, use English.

**Comment by MichaelHillcox** [comment]
Translated: they fixed it, not our issue
