### ISSUE TITLE
[Bug]: Stats Task Issue

### ISSUE THREAD

**Issue by TQCnoARosto** [FTBTeam/FTB-Mods-Issues#724]
### Mod

FTB Quests

### Mod version

ftb-quests-forge-1902.4.9-build.195

### Forge / Fabric version

Forge 1.19.2

### What issue are you having?

It seems the quest does not update for the stats introduced by other mods. I tried to create a quest where you have to activate a waystone's mod altar, but the quest doesn't seem to update even if from the minecraft stats menu the number of activated waystones has increased.
![QuestMenu](https://user-images.githubusercontent.com/43849125/227377384-9c57b3b6-3bcc-46c5-a81f-06868651fd4c.png)
![StatMenu](https://user-images.githubusercontent.com/43849125/227377386-62cb1181-c766-4614-978f-29bc4423052b.png)

FTBQuest mod version : ftb-quests-forge-1902.4.9-build.195
Waystones mod version : waystones-forge-1.19.2-11.3.1

### Steps to reproduce

1. Create a quest with "waystones activated" task.
2. Find a village with a waystone (/locate structure minecraft:village_plains).
3. Activate the waystone with right click.

**Comment by desht** [comment]
Can't see an obvious reason why non-vanilla stats wouldn't work, but I will investigate.

**Comment by desht** [comment]
I got round to testing this; it's actually a bug in Waystone (or more precisely the Balm portability mod that Waystones depends on).  Specifically this line here: https://github.com/TwelveIterationMods/Balm/blob/1.19.x/forge/src/main/java/net/blay09/mods/balm/forge/stats/ForgeBalmStats.java#L28

This registers the `waystones:waystone_activated` stat with just the path, in other words the stat key used is `minecraft:waystone_activated`, with the value of `waystones:waystones_activated`.  But FTB Quests correctly expect the stat to have a key of `waystones:waystones_activated`.

I can add a workaround to check for the stat name in the `minecraft` namespace, but this is ultimately that should be reported to the Waystone author.

**Comment by TQCnoARosto** [comment]
Oh wow this was hard to spot.
I'll forward this inaccuracy of the code to them and ask them to modify it following the standards.
Thanks a lot!
