### ISSUE TITLE
[Bug]: Reward Tables Update

### ISSUE THREAD

**Issue by TQCnoARosto** [FTBTeam/FTB-Mods-Issues#726]
### Mod

FTB Quests

### Mod version

ftb-quests-forge-1902.4.9-build.195

### Forge / Fabric version

Forge - 43.2.8

### What issue are you having?

Once a reward table is created, if you change the attributes such as name, or icon, the changes are saved but are not propagated outside.

### Steps to reproduce

1. I create the "test" reward table and it shows up like this
![RewardTableTestUnmodified](https://user-images.githubusercontent.com/43849125/227788307-2b273164-e389-40b4-830b-c39640e54adf.png)

2. If i want to modify the name to "Tests_test" and set the icon as "Redstone Torch" on the settings tab
![RewardTableTestModifying](https://user-images.githubusercontent.com/43849125/227788546-08ed61be-ea08-4350-9f09-d7279271d190.png)

3. When i click accept by first clicking the button at the top right and then the one under the settings button changes are saved because if i reopen the settings tab it shows me the modified data, but in the screen with all the reward tables the changes are not visible and i still see this
![RewardTableTestModified](https://user-images.githubusercontent.com/43849125/227789075-29313bab-78b9-48ca-915d-a1f8383fbf99.png)

**Comment by desht** [comment]
Confirmed. The changes are getting saved to the server and if you restart the client (or just log out and in again) the changes do appear.  But the reward table GUI isn't getting properly updated when the changes are made.

**Comment by desht** [comment]
Fixed in 1902.4.10 release
