### ISSUE TITLE
[Bug]: Latest ftbessentials build for 1.18.2 has incorrect LuckPerms dependency version

### ISSUE THREAD

**Issue by jacobgranberry** [FTBTeam/FTB-Mods-Issues#728]
### Mod

FTB Essentials

### Mod version

ftb-essentials-1802.2.0-build.61

### Forge / Fabric version

forge-1.18.2-40.2.1

### What issue are you having?

Hey there!  Saw that the latest version of ftb-essentials for forge-1.18 included LuckPerms integration.  Went to test it out and was hit with this error:

`INFO net.minecraftforge.fml.ModLoadingException: Mod ftbessentials only supports luckperms 5.4.30 or above
27.03 14:01:31 [Server] INFO Currently, luckperms is 5.4.26
`

However, there is no version of LuckPerms-Forge above 5.4.26 - thats the latest for 1.18, as far as I'm aware, according to the LuckPerms curseforge page

### Crashlogs

https://hastebin.com/share/hodajizozi.scss

### Steps to reproduce

1. Install the latest versions of ftb-essentials, ftb-library for 1.18
2. Install the latest version of LuckPerms-Forge for 1.18
3. Start the server

**Comment by desht** [comment]
You are correct, that was an error when backporting the integration from 1.19.2.  Will get a fixed release out for 1.18.2 shortly.

**Comment by desht** [comment]
Fixed in latest release (1802.2.1)
