### ISSUE TITLE
[Feature Request]: A "set" button for observation tasks

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-Mods-Issues#731]
### Mod

FTB Quests

### Description

![image](https://user-images.githubusercontent.com/15698722/228384670-ff2e2c39-2358-4ccd-af86-b4fd06ecd1ae.png)

Being able to just click a button here to set the `Observe` field to whatever I'm looking at would be nice.

Doubly so if it did it depending on the Type that's been set, though that would be much harder to do I'm sure.

All in all, fairly low priority. Would save typing though, esp for long ids that have to be typed outside of the game so I can look back and forth

**Comment by desht** [comment]
This would definitely be a good QoL feature, but adding any GUI components to the config screen is actually a lot harder than you'd hope, given the way it's currently coded (it's a rather generic class for editing any config object).  I will try out some ideas here though and see if there's a way to customise this.

**Comment by desht** [comment]
Couldn't do exactly what you wanted, but creating observation tasks now takes the block you're currently looking at into account.  So if you look at (say) an Oak Plank, open the quests gui, and create an observation task, the target block will be 'minecraft:oak_planks` by default.

**Comment by desht** [comment]
Fixed in 1902.4.13
