### ISSUE TITLE
[Feature Request]: Custom tasks with an amount

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-Mods-Issues#732]
### Mod

FTB Quests

### Description

Custom tasks basically work by having a KJS script or whatever force-complete them, right

It It would be useful if you could set an amount in the task, and the script would instead increment that instead.

For example, a quest to kill anything using a specific item, 10 times. The script would grab the kill event, check if the item was used, and if it was, increment the player's custom task by 1. When that reaches 10, quest completes.

This could already be done using persistent data in the player, but the player can't check their progress doing that.

**Comment by desht** [comment]
So the custom task would just have current and target amounts, and expose a method to be called by KJS (or possibly other mods) which increments the current amount?

**Comment by desht** [comment]
Wait, there is already a custom task type in FTBQ with KubeJS integration: https://wiki.latvian.dev/books/kubejs-legacy/page/ftb-quests-integration

The above is KubeJS legacy, but all the integration is still present in FTB Quests for listening to custom task events, and updating custom task progress.  Does this not do what you need?

**Comment by aaronhowser1** [comment]
```js
onEvent('ftbquests.custom_task.75381f79', event => {
  log.info('Custom task!')
  event.checkTimer = 20
  event.check = (task, player) => {
    if (player.world.daytime && player.world.raining) {
      task.progress++
    }
  }
})
```

What does this even do? It looks like, every second it checks if it's daytime and raining, and then increments a custom task's progress thing. But afaik, FTBQ custom tasks don't *have* a progress thing. It's either completed or it isn't.

> So the custom task would just have current and target amounts, and expose a method to be called by KJS (or possibly other mods) which increments the current amount?

Basically, yeah. Being able to set the amount rather than increment would also potentially be useful.

**Comment by aaronhowser1** [comment]
https://github.com/FTBTeam/FTB-Quests/blob/main/common/src/main/java/dev/ftb/mods/ftbquests/integration/kubejs/CustomTaskEventJS.java#L38

*Interesting.* This might already be a thing already then actually.

I'm not sure what half of those actually do though, and I don't see anything in the in-game menu. Maybe it can *only* be set with scripts.
![image](https://user-images.githubusercontent.com/15698722/228800860-543a8a7b-9110-4a47-85e4-0f7d694decc4.png)

**Comment by aaronhowser1** [comment]
Wouldn't it be 1200 seconds, since the checkTimer is 20?

**Comment by desht** [comment]
So does this cover the functionality you need or is anything missing from it?

**Comment by aaronhowser1** [comment]
```js
FTBQuestsEvents.customTask('ftbquests.custom_task.5A74FF4EE62B2BC5', event => {

	log.info('Custom task!')
	event.checkTimer = 20
	event.check = (task, player) => {
	  if (player.world.daytime && player.world.raining) {
		task.progress++
	  }
	}

})
``` does not work in 1.19, nor does anything else I tried. Doesn't even do the log.

**Comment by MichaelHillcox** [comment]
Dealt with privately, correct code would have been 
```javascript
FTBQuestsEvents.customTask('4F98C2CCAEF49BB4', event => {
    console.info('Custom task!')

    event.setCheckTimer(20)
    event.setCheck((task, player) => {
        if (player.level.isDay() && player.level.isRaining()) {
            task.progress++
        }
    })
})
```

For anyone interested
