### ISSUE TITLE
[Bug]: FTB Chunks breaks Occultism's book rendering

### ISSUE THREAD

**Issue by MuteTiefling** [FTBTeam/FTB-Mods-Issues#734]
### Mod

FTB Chunks

### Mod version

1902.3.18-build.248

### Forge / Fabric version

1.19.2 43.2.7

### Modpack & version

Enigmatica 9 inDev

### What issue are you having?

Issue is reproducable with limited mod set (JEI, Occultism, FTB Chunks, and all associated library mods)

Details here: https://github.com/EnigmaticaModpacks/Enigmatica9/issues/286

### Steps to reproduce

1. Install Occultism and FTB Chunks
2. Open the Occultism Book
3. Cry
4. Uninstall FTB Chunks (can leave all other mods)
5. Open Occultism Book
6. Smile

**Comment by desht** [comment]
Well, that's a "wtf" type of issue :)  I'll see if I can reproduce this here, but no idea why FTB Chunks would have any effect on another mod's rendering...

**Comment by desht** [comment]
OK, confirmed the problem.  And it's to do with the minimap display - if I switch off the minimap (Ctrl-M by default), the book icons display correctly.  With the minimap on, they are invisible.

So there's a short-term workaround until I figure out what in the minimap code is messing this up...

**Comment by MuteTiefling** [comment]
This was Klikli's first thought, perhaps it would help?

> Based on the results it looks like mod(s) causing the issue are modifying the blitoffset or posestacks for rendering screens
> usually that happens if you e.g. render an overlay and don't clean up, but could also happen in other render code

**Comment by desht** [comment]
Adding a single call to `RenderSystem.disableDepthTest()` at the end of Chunks' HUD renderer apparently fixes the problem, and the Modonomicon renders the buttons again.

But I'd be a little wary about doing that, since GUI drawing normally does that (looking at vanilla here, primarily) *before* doing any GUI drawing, and enables depth testing at the end.  Tagging @klikli-dev for comment...

**Comment by klikli-dev** [comment]
@desht thanks a lot - it's odd that vanilla rendering does not cause that to happen (because I don't think they consistently disable depth test .. ) but I can just figure out all the places I need to add it on my end, definitely should be there in the first place
