### ISSUE TITLE
[Bug]: Scrolling in FTB Quests

### ISSUE THREAD

**Issue by 5ully** [FTBTeam/FTB-Mods-Issues#735]
### Mod

FTB Quests

### Mod version

ftb-quests-forge-1902.4.10-build.200

### Forge / Fabric version

1.19.2 Forge

### Modpack & version

Any pack with a bunch a chapters

### What issue are you having?

Note, this is generally an issue with ftb quests and not pack specific.
If you collapse all the chapter groups after scrolling down with them open, you can no longer scroll up. You than have to extend every chapter group to be able to scroll back up.

### Crashlogs

n/a

### Steps to reproduce

Open Quests line where all chapters groups are "open".
Scroll down to the bottom in the chapter list.
Close all the chapter groups.
try to scroll back up.

### Anything else to note?

Im guessing scrolling is only possible if the visible chapters are past a point close to the bottom and this function "breaks" when you collapse the group while being scrolled down.

**Comment by desht** [comment]
Fixed in 1902.4.13
