### ISSUE TITLE
[Bug]: Enderman can pickup and place blocks in claimed chunks

### ISSUE THREAD

**Issue by RCertainty** [FTBTeam/FTB-Mods-Issues#737]
### Mod

FTB Chunks (fabric)

### Mod version

ftb-chunks-fabric-1902.3.18-build.248.jar

### Forge / Fabric version

1.19.2 Fabric 0.14.17

### Modpack & version

Medieval MC [FABRIC] - MMC1 - v19.5

### What issue are you having?

On my claims on a minecraft server while creepers explode and damage nothing, endermen are able to come and pick up blocks and place them without restraint lead to blocks ending up everywhere over time causing me to have to spend alot of time fixing my base and builds due to the many blocks they place and holes they make in my claims.

### Steps to reproduce

1. Claim some chunks with pickable blocks like grass
2. Wait for some enderman to spawn
3. Watch them pick up and place blocks in your claim
4. Cry as you will have to be the one to fill the holes and remove blocks constantly from yours builds or whatever.

### Anything else to note?

I honestly didn't expect this to happen since claims already prevent creeper explosions from damaging anything on claims but I guess I can just sick a bunch of enderman on someones base to turn it into a unattractive wasteland of holes.

**Comment by desht** [comment]
Creeper explosions are entirely unrelated to Enderman block griefing, so I'm not sure why you're surprised.

Having said that, protecting from Endermen is something that could easily be added, so will treat this as a feature request, not a bug.

**Comment by desht** [comment]
Added in 1902.3.21

**Comment by Sloid** [comment]
This added features doesn't appear to be working in version 2001.1.3
