### ISSUE TITLE
[Bug]: Worldedit commands Breaks the rank system

### ISSUE THREAD

**Issue by MrMethOG** [FTBTeam/FTB-Mods-Issues#740]
### Mod

FTB Ranks

### Mod version

ftb-ranks-forge-1902.1.14-build.70

### Forge / Fabric version

1.19.2

### Modpack & version

ATM8

### What issue are you having?

I tried to make a rank for worldedit but when i add a command in the permission from a rank the ranks.snbt dosen't load ingame all ranks disappear but when i remove the commands it working again i think its cos of the // commands.
Working: https://pastebin.com/rz7Vxz9F
Dont work: https://pastebin.com/nuWa23uu

my readme.txt from ftbranks: https://pastebin.com/bFsgKvCs

### Steps to reproduce

Having worldedit installed
go in /''world''/serverconfig/ftbranks/ranks.snbt
and add any command./.. from worldedit in a rank

**Comment by desht** [comment]
Confirmed.  There are actually a couple of problems here:

1. The extra "/" character which worldedit likes to add to its commands isn't treated as a valid word character when being read by FTB Library from .snbt files.  There is an easy workaround though - you can quote the permission like this:

```
	member: {
		name: "Member"
		power: 1
		condition: "always_active"
		command.gamemode: true
		command.gamemode.creative: false
		command.gamemode.spectator: true
		command.reload: true
		command.worldedit: true
		command.worldedit.args: true
		"command./": true
		"command./.args": true
		"command./copy": true
		"command./copy.args": true
	}
```

2. FTB Ranks says it loaded the erroring file OK, and loses all its current data, which is wrong.  It should report an error, and leave the current runtime configuration as it is.  I will fix this for the next FTB Ranks release.
