### ISSUE TITLE
[Feature Request]: More Essentials commands

### ISSUE THREAD

**Issue by Sa1ZeR** [FTBTeam/FTB-Mods-Issues#741]
### Mod

FTB Essentials

### Description

Hello. Can you add commands from bukkit essentials:

kit (with nbt support)
feed (set 20 only for food bar)
near
jump
clear
ext
weather
speed

**Comment by desht** [comment]
By "Bukkit Essentials", exactly which plugin are you referring to?  URL please.

**Comment by Sa1ZeR** [comment]
https://essinfo.xeya.me/commands.html

**Comment by desht** [comment]
Thanks.  Most of these look like useful additions, other than /weather, which can already be done with the vanilla command.

**Comment by desht** [comment]
All of the mentioned commands are in the 2001.2.0 release (see https://github.com/FTBTeam/FTB-Essentials/wiki/kits.md for more detailed information on the kit command, which isn't quite the same the EssentialsX version)
