### ISSUE TITLE
[Feature]: Ultimine cocoa bean harvesting 

### ISSUE THREAD

**Issue by The-Forge-Master** [FTBTeam/FTB-Mods-Issues#742]
### Mod

FTB Ultimine

### Mod version

ftb-ultimine-forge-1902.4.0-build.77

### Forge / Fabric version

Forge 43.2.4

### Modpack & version

Valhelsia 5 5.0.16 (manually added)

### What issue are you having?

Right-click harvesting cocoa beans doesn't work like it does for ground-based crops.

### Crashlogs

N/A

### Steps to reproduce

1. Grow a field of wheat
2. Hold Ultimine key
3. Right click
4. Profit

Okay, works with wheat, try with cocoa beans.

1. Grow columns of cocoa beans
2. Hold Ultimine key
3. Right click
4. Nothing happens

Right click on the cocoa beans works fine, but not if I want to get them all at once with Ultimine. There aren't an absurd amount, only 24.

**Comment by desht** [comment]
Added in current releases for 1.19 and 1.20
