### ISSUE TITLE
[Feature Request]: Quick Set Quest Icon

### ISSUE THREAD

**Issue by FooterMan15** [FTBTeam/FTB-Mods-Issues#744]
### Mod

FTBQuests

### Description

It gets annoying having to set the icon for Quests repeatedly. You have to click so many times to get to the setting, and then you have to find the item, etc. Cycling items are ugly, too fast, and not helpful.

So, I'm wondering if in this menu:
![image](https://user-images.githubusercontent.com/71946346/229540217-d4c0c16f-0a20-4607-afb8-71df17006d97.png)
There can be a quick option when right clicking items to set them as the Quest icon.

### Describe the solution you'd like

Add an option to set an item in a Quest as the Icon, without entering the Quest properties.

### Describe alternatives you've considered

Alternatively, don't automatically cycle Quest items on the Icon when multiple items are included in the Quest. Have it automatically set the first item as the Icon, and have cycling a separate option.

**Comment by desht** [comment]
Just so we're clear on terminology here, do you mean the Quest icon or the Task icon?  Your screenshot shows you right-clicking on a task within a quest...

**Comment by FooterMan15** [comment]
Quest icon

**Comment by desht** [comment]
OK, so a menu entry when you right-click a task button in the quest panel that copies that task's icon to the quest icon?

**Comment by FooterMan15** [comment]
> OK, so a menu entry when you right-click a task button in the quest panel that copies that task's icon to the quest icon?

Correct

**Comment by desht** [comment]
Fixed in 1902.4.13
