### ISSUE TITLE
[Bug]: Broken event listener in FTB Chunks causes a server crash when buckets are used in an unowned claim

### ISSUE THREAD

**Issue by TropheusJ** [FTBTeam/FTB-Mods-Issues#746]
### Mod

FTB Chunks

### Mod version

1902.3.18-build.248

### Forge / Fabric version

mc 1.19.2, loader 0.14.18, api 0.76.0

### Modpack & version

AOF6 1.5.1

### What issue are you having?

When a Create Deployer uses a bucket in a claimed chunk, the game will crash. I'm assuming this will apply to any player, not just the Deployer's fake one.
This is caused by [this](https://github.com/FTBTeam/FTB-Chunks/blob/1.18/main/common/src/main/java/dev/ftb/mods/ftbchunks/FTBChunks.java#L325) line. That null replaces the resulting ItemStack of the interaction. It should probably be the currently held item.
Create issue: https://github.com/Fabricators-of-Create/Create/issues/855

### Crashlogs

From Create issue: https://pastebin.com/8GrLKK80

### Steps to reproduce

1. Install AOF6 (Should just require FTB Chunks and Create)
2. Claim a chunk
3. Place a Deployer
4. Give it a water bucket and power it
5. Observe crash

**Comment by desht** [comment]
I agree, that's definitely wrong. It actually doesn't crash when a player does it, however, since the interaction event for the bucket would be reached first, and cancelled. Which explains why this didn't get noticed much sooner :)

I'll get it fixed for the next Chunks release.

**Comment by desht** [comment]
If you're in a position to test a dev build, https://maven-admin.ftb.dev/repository/maven-public/dev/ftb/mods/ftb-chunks-fabric/1902.3.18-build.249/ftb-chunks-fabric-1902.3.18-build.249.jar should fix the bucket problem.

**Comment by TropheusJ** [comment]
threw it into AOF6, working fine

**Comment by desht** [comment]
Fixed in 1902.3.20 release
