### ISSUE TITLE
[feature] square shape minimap, and client-related minimap visibility.

### ISSUE THREAD

**Issue by Wedge1453** [FTBTeam/FTB-Mods-Issues#75]
toggling the minimap is done from the server configs, which means it's either on or off for all players.

**Comment by Jetpack-Cat** [comment]
Feels like this should have been a feature a long time ago. The circle is just ugly

**Comment by MichaelHillcox** [comment]
Shouldn't be super hard to add, just need to find the time. PR's are always welcome

**Comment by Teraphina** [comment]
would love a square minimap in FTBChunks any chance on getting this any time soonish?

**Comment by MichaelHillcox** [comment]
Chunks is the next mod we'll be focusing on. Not sure how high this will be but it should be relatively simple to add

**Comment by Jetpack-Cat** [comment]
What versions will you be working on? Any chance 1.16.5?

**Comment by desht** [comment]
Next release of the mod for 1.18.2 will include a square minimap. 

Undecided about 1.16.5; this version will be getting fixes, but haven't made a decision yet on new features for 1.16.

**Comment by desht** [comment]
Fixed in 1.18/1.19
