### ISSUE TITLE
[Bug]: quests: editing icon causes "mouseClicked event handler  java.lang.NoClassDefFoundError: com/google/common/collect/Iterators$2"

### ISSUE THREAD

**Issue by macks2008** [FTBTeam/FTB-Mods-Issues#750]
### Mod

FTB-Quests (forge)

### Mod version

ftb-quests-forge-1902.4.10-build.202

### Forge / Fabric version

43.2.6

### Modpack & version

All the Mods 8

### What issue are you having?

When in edit mode, attempting to edit the icon for a newly created quest node caused a crash. 

### Crashlogs

https://paste.feed-the-beast.com/view/86f71194

### Steps to reproduce

1. Install and launch the mod, possibly along with the rest of ATM8 (but I'm not sure)
2. enter a world (cheats enabled); technically I was op on a server but I imagine it also happens in single player
3. open the quest book from the inventory icon
4. if cheats are enabled, you should be able to enter edit mode from the icon in the bottom right
5. create a new quest note
6. click the "minecraft:air" value in the icon field
7. crash

### Anything else to note?

not sure how relevant it is, but my goal in this case was to experiment with the mod's capabilities. I was trying to see if the mod had a way to make quests repeatable, as our server owner has been wanting to set up an economy with a server-issued currency of some form, and I thought a repeatable quest would be the best way to ensure that currency could be minted without being farmed infinitely by just throwing more mobs in a grinder. As I recall, there was a 1.7.10 pack that did something similar with HQM so...
Well, I didn't even get far enough to find out: is there a way to do this?

**Comment by desht** [comment]
Looks like something is wrong with your installation. The erroring line is a call to `java.lang.NoClassDefFoundError: com/google/common/collect/Iterators$2`, which is `Iterators.cycle()`, a [Guava library method](https://guava.dev/releases/17.0/api/docs/com/google/common/collect/Iterators.html#cycle(java.lang.Iterable)).  Guava is included as standard in any Minecraft distribution, so the fact that you don't seem to have it suggests something's wrong at your end.

I would suggest a modpack reinstallation initially to see if that helps.

**Comment by macks2008** [comment]
I cannot seem to reproduce the issue now, I will reopen if it happens again but for now...

**Comment by desht** [comment]
Just Java being Java!
