### ISSUE TITLE
[Bug]: Possible memory leak from FTB Chunks

### ISSUE THREAD

**Issue by hgiabao** [FTBTeam/FTB-Mods-Issues#751]
### Mod

FTB Chunks

### Mod version

1902.3.18-build.248

### Forge / Fabric version

1.19.2 43.2.6 

### Modpack & version

ATM 8

### What issue are you having?

After a 1~2 hours of play time, minecraft would fill up my memory and need to be killed with task manager. I made a heapdump with spark when it's start lagging. [Here is a screenshot of MemoryAnalyzer result on said heapdump](https://i.imgur.com/tr7EJDG.png).

### Steps to reproduce

1. Play ATM8 for a few hours
2. MC client lag/non-responsive

**Comment by desht** [comment]
When you encounter these memory starvation issues, has it been playthrough where you've been doing a lot of exploration or otherwise moving around the world (or dimension-hopping), and/or using the map at a high zoom-out level?

I can see some potential for freeing up memory by clearing up data held for regions not recently used in the map, but it would be good to know the conditions that lead to excessive memory usage here.

**Comment by desht** [comment]
Also, can you switch "Debug Info" to true on your client (can be done via "Settings" button in bottom left of the large map screen)?  That will switch on an estimate memory usage display in the top right of the large map.  When you've been playing for a while, what sort of values is that memory usage showing?

**Comment by hgiabao** [comment]
> When you encounter these memory starvation issues, has it been playthrough where you've been doing a lot of exploration or otherwise moving around the world (or dimension-hopping), and/or using the map at a high zoom-out level?

Yeah, I tested and it only happens when I explore a lot, in the same dimension or different dimension. The memory leak doesn't happen when I stay in 1 place.
I thought it was related to the zoom in bug so I unbinded the key for FTB map. The memory leak still happens regardless.

**Comment by hgiabao** [comment]
Tested with debug info. Initial memory usage is ~2875 MB. This value doesn't change much after I did a bunch of exploration & when it started lagging. 2875 MB is quite high though. I had to opened the big map to see the debug value so maybe that caused the high memory usage?

**Comment by desht** [comment]
Yep, opening the large map would probably do it.  And yes 2875MB is far too high. 

There should be a new release out in the next few days which will hopefully help with this problem and greatly reduce ongoing memory usage.

**Comment by desht** [comment]
Added in 1902.3.21 and 1802.3.17.  Memory usage should be a lot lower now, although spikes are still possible if zooming the map out a long way in a well-explored world (although map zoom will be limited if too much memory would be used).

Please give this a go and tell me your thoughts...

**Comment by hgiabao** [comment]
I just tested on the lastest ATM8 version with FTB Chunk 1902.3.21. There seems to be no more memory leaks. Memory usage debug info stays around ~800MB.

**Comment by desht** [comment]
Excellent.  Note that if 800MB is still too high, there are a few new client-side settings which can be tweaked to further reduce memory usage (although at the cost of extra disk access).
