### ISSUE TITLE
[Bug]: Problem when editing tasks with multiple lines in name

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-Mods-Issues#752]
### Mod

FTB Quests

### Mod version

ftb-quests-forge-1902.4.11-build.207

### Forge / Fabric version

Forge 43.2.8

### What issue are you having?

![image](https://user-images.githubusercontent.com/15698722/230735681-4a8b53c8-b47f-42c9-86a8-fd6ff3be9b06.png)
![image](https://user-images.githubusercontent.com/15698722/230735692-5c17aefc-6d2f-4729-8922-5a5b28c0b3ee.png)

### Steps to reproduce

Task name:

Look at a completed Assembler\n\n6x Steel Scaffolding\n2x Redstone Engineering Block\n2x Light Engineering Block\n9x Iron Sheetmetal\n6x Iron Sheetmetal Slab\n2x Conveyor Belt

**Comment by desht** [comment]
Given only quest editors actually see this, I don't think it's a problem at all that the "LF" characters appear in the title of context menu. However, I will add some code to shorten it so the title is massively wide.  Probably take the first line only and append an "..." ellipsis to it.

**Comment by desht** [comment]
Fixed in 1902.4.13
