### ISSUE TITLE
[Bug]: Task names are not being localized

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-Mods-Issues#753]
### Mod

FTB Quests

### Mod version

ftb-quests-forge-1902.4.11-build.207

### Forge / Fabric version

Forge 43.2.8

### What issue are you having?

![image](https://user-images.githubusercontent.com/15698722/230736162-50f3e7cd-b2e6-415e-b89e-0889b6e4a85b.png)
![image](https://user-images.githubusercontent.com/15698722/230736164-6510ee36-11ec-44a9-b153-ae4ce5fcd690.png)

`"university.floatingflowers.task":"Floating functional flower",`

### Steps to reproduce

N/A

**Comment by desht** [comment]
4933ef0bec2555c61408555828329e013afa2d55

**Comment by desht** [comment]
Fixed in 1902.4.13
