### ISSUE TITLE
[Bug]: Error with mod loading 

### ISSUE THREAD

**Issue by Grukki** [FTBTeam/FTB-Mods-Issues#755]
### Mod

FTB Chunks

### Mod version

1902.3.18-build.248

### Forge / Fabric version

43.2.6

### What issue are you having?

The mod is not loading correctly could anyone help with this issue?

### Crashlogs

[crash-2023-04-09_23.23.11-fml.txt](https://github.com/FTBTeam/FTB-Mods-Issues/files/11187418/crash-2023-04-09_23.23.11-fml.txt)

### Steps to reproduce

I open the launcher and im greeted with this error at launch.

**Comment by desht** [comment]
```
Exception message: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector redirectIconDraw(Ldev/ftb/mods/ftbchunks/integration/MapIcon;Ldev/ftb/mods/ftbchunks/client/MapType;Lcom/mojang/blaze3d/vertex/PoseStack;IIIIZ)V in merchantmarkers.mixins.json:FTBChunksClientMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap merchantmarkers.refmap.json
```

Not a FTB Chunks problem.  Complain to the author of Merchant Markers who should not be mixing in to FTB Chunks like this.

**Comment by desht** [comment]
Until the author releases a version of the mod which doesn't break FTB Chunks, we cannot recommend using it.
