### ISSUE TITLE
[Bug]: FTB Chunk mod loading error

### ISSUE THREAD

**Issue by KaiHaruki** [FTBTeam/FTB-Mods-Issues#756]
### Mod

FTB Chunk

### Mod version

1902.3.20-build.257

### Forge / Fabric version

forge-1.19.2-43.2.8 / 43.2.7

### Modpack & version

https://www.curseforge.com/minecraft/modpacks/kyusekai

### What issue are you having?

Unable to launch and display error message 
FTB Chunks (ftbchunks) has failed to load correctly java.lang.reflect.InvocationTargetException: null

### Crashlogs

https://pste.ch/momozedulo.pl

### Steps to reproduce

Update FTB to lastest version latest version launch failed under both 43.2.7 and 43.2.8 FTB other FTB are up to dated

**Comment by desht** [comment]
```
Exception message: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector redirectIconDraw(Ldev/ftb/mods/ftbchunks/integration/MapIcon;Ldev/ftb/mods/ftbchunks/client/MapType;Lcom/mojang/blaze3d/vertex/PoseStack;IIIIZ)V in merchantmarkers.mixins.json:FTBChunksClientMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap merchantmarkers.refmap.json
```

Not a Chunks problem.  Complain to the author of Merchant Markers, who should not be mixing into FTB Chunks like this.
