### ISSUE TITLE
[Feature Request]: Party Warning

### ISSUE THREAD

**Issue by TheBloodSwiper** [FTBTeam/FTB-Mods-Issues#757]
### Mod

FTB Teams/Party

### Description

So I played on Medieval Minecraft 1.19.2 in a server, and left a party due to the leader being inactive.
Nowhere did it say when I joined (nor leaving) that the chunks I claimed would belong to the party and not myself. This made it so I had to wait a week until a Mod could come over and fix the chunks that belonged to me (unlucky cause he was on holyday).
This had me not play the modpack for that time, which was annoying as I was in the middle of base building.

Another issue is that they are still taking the chunks from MY chunk pool, meaning that the server gave me 50 chunks to claim, but now I only have 5 chunks cause the other 45 chunks I claimed still belong to the party? Now this does not make any sense for me, again a good reason to add the feature I'm suggesting below.
Also, the command /chunks unclaim_all did not work, as even if they take from MY chunk pool, they are no longer "mine".

Sorry beforehand if:
1 - I'm being ignorant and this was stated somewhere. Note I've not Created a party, only joined and later left one.
2 - This is fixed in later versions, as 1.19.2 is a earlier version. 

### Describe the solution you'd like

When you leave a party, get a warning that tells you "You have claimed chunks belonging to the party, would you like to give them to the party, unclaim the chunks or convert them to your private chunks?". As I'm jusing 1.19.2 I know I wont be able to make use of such a feature, but I hope this will save a lot of other people trouble.

### Describe alternatives you've considered

The only workaround is to unclaim all chunks before leaving the party, which is a hassle if you have claimed chunks in different spots (mob farm, village, base and private land you want to protect for future plans). Not practical but the only solution.

**Comment by desht** [comment]
In any up-to-date version of FTB Chunks, your claims are returned to you when you leave a party.  What version of the mod (the mod version, not the Minecraft version) are you using?

**Comment by TheBloodSwiper** [comment]
ftb-teams-fabric-1902.2.12-build.95
