### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Tyrapi** [FTBTeam/FTB-Mods-Issues#758]
### Mod

FTB Chunks

### Mod version

ftb-chunks-forge-1802.3.16-build.247

### Forge / Fabric version

Forge 40.2.0

### Modpack & version

Custom Modpack (linked further down)

### What issue are you having?

The modpack fails to load and returns the following error messages:

![image](https://user-images.githubusercontent.com/90660316/231583363-9dd9a75f-1f6b-46cb-8745-8e9ad4c1e893.png)

I'm not sure what to do about the null error message for the mods, so I'd greatly appreciate any help I can get.

The modpack I'm trying to use is a combination of a lot of different mods that I put together: 
https://drive.google.com/drive/u/0/folders/1KnYN0wUvXJ6VF590XyTqaFP74a1aiJcP

### Crashlogs

[crash-2023-04-12_16.48.13-fml.txt](https://github.com/FTBTeam/FTB-Mods-Issues/files/11216004/crash-2023-04-12_16.48.13-fml.txt)

### Steps to reproduce

1. I start loading the mod with the curseforge client.
2. I press play when it get to the minecraft launcher.
3. I wait for a few minutes and the error messages pop up.

**Comment by Jake-E** [comment]
It looks like you're missing dependencies, your crash report leads to you missing Obscure API.

**Comment by Tyrapi** [comment]
I have Obscure API in the modpack: obscure_api-10.jar
[Obscure API 10 (Forge 1.18.2)](https://www.curseforge.com/minecraft/mc-mods/obscure-api/files/4259349)

**Comment by Jake-E** [comment]
The tooltips jar name seems to suggest you need API 9, not 10.

**Comment by Tyrapi** [comment]
Okay, I'll try that.

**Comment by Tyrapi** [comment]
It worked, thanks!

**Comment by Tyrapi** [comment]
Hi, I am having the same error with ftb Chunks again because switching to obscure api to 9 as well as aquamirae for api 9 caused a separate issue resolved an issue with Aquamirae requiring api 10 on that version. 

Currently, the error message is the same as before and the crash report may mention something about architectury api, but I'm not sure if I'm also supposed to switch that's version nor what version I would switch to since there are many 1.18.2 versions for that mod. I'm currently using architectury-4.11.90-forge.jar

Crash Report:

[crash-2023-04-12_18.09.05-fml.txt](https://github.com/FTBTeam/FTB-Mods-Issues/files/11216468/crash-2023-04-12_18.09.05-fml.txt)

**Comment by desht** [comment]
```
Exception message: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector redirectIconDraw(Ldev/ftb/mods/ftbchunks/integration/MapIcon;Ldev/ftb/mods/ftbchunks/client/MapType;Lcom/mojang/blaze3d/vertex/PoseStack;IIIIZ)V in merchantmarkers.mixins.json:FTBChunksClientMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap merchantmarkers.refmap.json
```

Not a FTB Chunks problem.  Complain to the author of Merchant Markers who should not be mixing into FTB Chunks like this.
