### ISSUE TITLE
[Bug]: FTB Chunks 1.18.2 Loading Error

### ISSUE THREAD

**Issue by Tyrapi** [FTBTeam/FTB-Mods-Issues#759]
### Mod

FTB Chunks (Forge)

### Mod version

ftb-chunks-forge-1802.3.15-build.243

### Forge / Fabric version

40.2.0

### Modpack & version

Custom Modpack, listed in linked issue post

### What issue are you having?

Hi, I am having an error with ftb Chunks where it displays the error message: 

![image](https://user-images.githubusercontent.com/90660316/231604229-24be462e-6eed-47be-9b8c-090c9368a905.png)

The crash report mentions something about architectury api, but I'm not sure what exactly I'm supposed to do, if I'm supposed to switch it's version, or what version I would switch to since there are many 1.18.2 versions for that mod. I'm currently using architectury-4.11.90-forge.jar

### Crashlogs

[crash-2023-04-12_18.09.05-fml.txt](https://github.com/FTBTeam/FTB-Mods-Issues/files/11216468/crash-2023-04-12_18.09.05-fml.txt)

### Steps to reproduce

1. I load up the modpack using curseforge
2. I press play on the minecraft launcher
3. The modpack loads most of the way and then has the error

### Anything else to note?

I had a similar error before with this mod not loading, but I got help and was told to switch api versions, which worked temporarily, but I now have a different issue. The link to that post is here: #https://github.com/FTBTeam/FTB-Mods-Issues/issues/758

**Comment by desht** [comment]
```Exception message: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector redirectIconDraw(Ldev/ftb/mods/ftbchunks/integration/MapIcon;Ldev/ftb/mods/ftbchunks/client/MapType;Lcom/mojang/blaze3d/vertex/PoseStack;IIIIZ)V in merchantmarkers.mixins.json:FTBChunksClientMixin failed
```

Not a FTB Chunks issues.  Complain to the author of Merchant Markers, who should not be mixing into our mod.
