### ISSUE TITLE
[Feature Request]: Support to show player arrow when rotation is not locked

### ISSUE THREAD

**Issue by samardzicneo** [FTBTeam/FTB-Mods-Issues#761]
### Mod

FTB Chunks

### Description

Currently, you can either lock the rotation of the minimap, which shows a small arrow in the middle of the minimap which faces whichever way the player is facing, or you can make the minimap rotate with the player, which hides this arrow with no option to enable it.

### Describe the solution you'd like

A toggle in the minimap settings which would make this arrow show even if rotation is not locked. Currently, the player is always in the middle of the map, but it's kind of hard to tell where the middle is without any indicator. The arrow should just always point up in this case.

### Describe alternatives you've considered

Besides drawing a little dot on my display with a sharpie or using another map mod which I don't want to do, none.

**Comment by desht** [comment]
Added in 1902.3.21

**Comment by 0x427279** [comment]
Will this be retrospectively applied to the 1.16.5 branch?

**Comment by desht** [comment]
Sorry, no.
