### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by CraCCMan** [FTBTeam/FTB-Mods-Issues#763]
### Mod

FTB Chunks

### Mod version

ftb-chunks-forge:1802.3.6-build.160

### Forge / Fabric version

forge-40.1.80

### Modpack & version

Hexangle's Tech Bombs Guns and War 1.1.0

### What issue are you having?

Singleplayer world, ever since I died at a certain point a few hundred blocks from spawn point, my minimap and waypoints have vanished, and whenever I hit "m" to open the map, my world crashes. This issue has even carried over to a new world I made.

### Crashlogs

https://bytebin.lucko.me/yMBanJtpVB

### Steps to reproduce

After the death, I: 1. hit m to open the map 2. game crashes

**Comment by CraCCMan** [comment]
The issue has since been resolved through a combination of moving closer to where I died and restarting a few times

**Comment by desht** [comment]
There is an issue where sometimes chunk data doesn't get synchronized from the server, but it's very hard to reproduce and therefore very hard to fix.  That is the ultimate cause of why the map cannot be opened.

However, you're on a very old version of FTB Library, and if you were up to date (1802.3.11 is current), you would not have had this crash.
