### ISSUE TITLE
[Bug]: java.lang.NullPointerException when trying to execute command "ftbquests" in a .mcfunction file in a datapack

### ISSUE THREAD

**Issue by Molioron** [FTBTeam/FTB-Mods-Issues#766]
### Mod

FTB Quests

### Mod version

ftb-quests-forge-1802.3.14-build.191

### Forge / Fabric version

1.18.2 40.2.0

### What issue are you having?

When trying to use the "ftbquests" command in a .mcfunction file, the exception "java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "net.minecraft.server.MinecraftServer.m_129792_()" because the return value of "net.minecraft.commands.CommandSourceStack.m_81377_()" is null" is thrown. (and any command in the .mcfunction file will not be executed)

### Crashlogs

Not exactly a crashlog, but the full error: https://hastebin.com/share/tosifixoyo.css

### Steps to reproduce

1. add the the command "ftbquests change progress @a complete
<quest id>" (originally also used selector "[scores= {looted chests=1..}]" and id
"6509C45E0303740F") to a tick.mcfunction file.
2. add the command "say test" for debugging purposes.
3. register said file in the tick.json file, which is under the namespace "minecraft"
4. run /reload
5. either look in the chat and see that nothing is happening or check the log "latest"

### Anything else to note?

1) a similar problem has been reported with the "ftbrank" in mc 1.16.5 here https://github.com/FTBTeam/FTB-Mods-Issues/issues/165
2) this bug may extend to other ftb related commands (in any ftb related mod).

**Comment by desht** [comment]
Looks like on the first tick, the server is not yet loaded.  From the [wiki](https://minecraft.fandom.com/wiki/Function_(Java_Edition)): 

> Note: The first instance of functions tagged minecraft:tick run before minecraft:load runs. This means that when reloading or loading, the order of execution is tick, load, tick, tick, tick, … 

But the FTB Quests command handler assumes a server is present, which I guess is not the case on the very first tick. Should be an easy fix, though.

**Comment by desht** [comment]
Fixed in 1902.4.13
