### ISSUE TITLE
FTBQuests cause insane TPS issues on ATM8 server

### ISSUE THREAD

**Issue by cXenonz** [FTBTeam/FTB-Mods-Issues#771]
### Modpack

Other...

### Modpack version

ATM 8 1.0.17

### Log Files

https://spark.lucko.me/KtkBeX4I35

### Describe the bug

Basically as the title says. Before I describe further, here are all the current FTB mods installed within this modpack:

ftb-chunks-forge-1902.3.21-build.266.jar
ftb-essentials-1902.1.10-build.47.jar
ftb-industrial-contraptions-1900.1.7-build.212.jar
ftb-library-forge-1902.3.18-build.208.jar
ftb-quests-forge-1902.4.11-build.207.jar
ftb-ranks-forge-1902.1.15-build.77.jar
ftb-teams-forge-1902.2.13-build.100.jar
ftb-ultimine-forge-1902.4.0-build.77.jar

Initially, this problem started when I remembered the quests line mod and opened it to claim all of the rewards. There were DOZENS of rewards from quest lines from different mods that I claimed. I have only fully completed the mekanism mod quest line, other than that at least half of the other quests are still open. After this, the server TPS was drastically impacted. Ranging from 200-400 ticks behind. The only temporary solution I've come up with is locking all quests for all players, or removing the mod from the server. Locking the questlines for all players completely removes the lag the aspired from the mod. Unlocking any quest line IMMEDIATELY causes a huge over all amount of lag and TPS drop.

### Steps to reproduce

1. Go through several different mods and fully complete at least one.
2. Remember that the quest lines are a thing, and claim all of the rewards for dozens of different quests all at once.
3. Inspect other mods quest lines and mark off/complete specific quests that you are able to and have completed.
4. Investigate more mods quest lines that you have not completed or started out of curiosity
5. Let the lag commence.

### Expected behaviour

Did not expect an overall lag spike this huge.

### Screenshots

![image](https://user-images.githubusercontent.com/96469328/234430099-c930ffb0-deca-41e0-803d-50f93ea85392.png)

### Additional information

I have been talking to my server provided support staff for over a full day now, and we cannot find anything to remedy the issue other than the temporary fixe(s) I described above.

The server has 26GB of DDR4 RAM, and is running an Intel(R) Xeon(R) Gold 6134 CPU @ 3.20GHz with 32 threads available.

**Comment by desht** [comment]
`ItemTask#submitTask` appears to be getting continuously called, probably every tick, which would certainly explain the lag you're seeing.  Under normal circumstances, it's only called when a player's inventory changes in some way (via `AbstractContainerMenu#triggerSlotListeners`). So something in some player's inventory is changing rapidly enough to cause this to be called excessively. Without knowing who on your server has what items, it's impossible to tell more.

When the detection code is called, it will iterate over every task which has submittable items, which could be a lot for a large quest book (which I guess ATM 8 has). One possible mitigation here would be to queue up inventory detections per player so they're not done more than once a second (or possible some configurable value).

**Comment by cXenonz** [comment]
> The spark output also shows most of the time being spent in a task which has a relatively complex filter item, including a regex filter. That's also going slow things down. Another potential optimisation here is to focus only on the specific item which changed in the player's inventory rather than scanning the whole inventory, although that will significantly increase the chance of an item not being auto-detected...

That makes a lot of sense, however when I ran the spark profiler I was the only one on the server and had a very minimal inventory. The screenshot I posted was just an example of how high the lag instantly spikes; but knowing that information, my guess is it has something to do with my extremely extensive automatic importing, exporting, and crafting with the QIO storage. I have the wireless QIO crafter in my inventory so maybe the bug is that the quests mod is tying the entire storage system to my inventory, and it’s constantly updating every tick because of that… since I have constant items flowing in and out.

**Comment by desht** [comment]
Yeah, that could do it. Try putting the QIO crafter away, and see if that helps.

If that is the case, then reducing the check interval (to say every 20 ticks, or some server-configurable value) would definitely help, although you'll see more of a delay between picking items up and getting quest auto-completion updates.

**Comment by desht** [comment]
Something else to note is that any item with rapidly changing NBT will also trigger an inventory scan. For example, if you use a Mekasuit, the chestplate flight module updates NBT every tick while flying. Not really Mekanism's fault, plenty of other mods do similar things.  Again, my planned changes should help with this.

Also, are you in a position to test a dev build of FTB Quests on your server?

**Comment by desht** [comment]
1902.4.13 has been released, which *should* be a lot better with regard to inventory checking performance.  Please let me know.

Also, the check interval is configurable (default: 20 ticks).  You can change it from the GUI - in edit mode, click the gear icon, then Edit File.  Setting is "Item Auto-Detection Minimum Interval".  Range is from 1..200.  Higher values check less often, so kinder to server CPU, but a longer delay between picking an item up and getting a quest completed notification.

**Comment by cXenonz** [comment]
I apologize for the long response time, I just downloaded the new build and will be testing it in a minute. Thank you!

**Comment by cXenonz** [comment]
> 1902.4.13 has been released, which _should_ be a lot better with regard to inventory checking performance. Please let me know.
> 
> Also, the check interval is configurable (default: 20 ticks). You can change it from the GUI - in edit mode, click the gear icon, then Edit File. Setting is "Item Auto-Detection Minimum Interval". Range is from 1..200. Higher values check less often, so kinder to server CPU, but a longer delay between picking an item up and getting a quest completed notification.

The updated build completely fixed it, I raised the inventory checking interval a bit, but there is no lag what so ever or hardware over-usage. Thank you so much!
