### ISSUE TITLE
[Bug]: Latest version of essentials missing trash can in player inventory menu

### ISSUE THREAD

**Issue by DelviousCrafts** [FTBTeam/FTB-Mods-Issues#778]
### Mod

FTB Essentials

### Mod version

ftb-essentials-forge-1902.3.1-build.75

### Forge / Fabric version

Forge 1.19.2-43.2.8

### What issue are you having?

FTB Essentials added a trash can icon to the player inventory screen. After updating to the latest version of Essentials, this icon and functionality were missing.

### Steps to reproduce

1. update to the latest version
2. open player inventory
3. See trash can icon on the top-right no longer existing

**Comment by desht** [comment]
Confirmed, a couple of resource files got misplaced during the codebase split to Forge/Fabric builds.  Apologies; will be fixed in next release.

**Comment by desht** [comment]
Fixed in the 1902.3.2 release (back in June)
