### ISSUE TITLE
[Bug]: FTB Quests Hide quests until dependencies visible no default setting option

### ISSUE THREAD

**Issue by SamuelRUM** [FTBTeam/FTB-Mods-Issues#780]
### Mod

FTB Quests

### Mod version

ftb-quests-forge-1902.4.13-build.219.jar

### Forge version

1.19.2 43.2.6

### What issue are you having?

I think it's a bug, basically the setting 'Hide quest until dependencies visible' has a 'default' setting, but I can't seem to find anywhere where I can set the default behavior of this.

**Comment by OssanSharp** [comment]
This also happens in the fabric version.

**Comment by desht** [comment]
Looks like an oversight here; there should be a default setting in the chapter, but there isn't. Will get this added for the next update.

**Comment by desht** [comment]
Fixed in latest release
