### ISSUE TITLE
[Bug]: ”Online mod=false“.   players in online mode cannot invite others to join the team!

### ISSUE THREAD

**Issue by QianMuu** [FTBTeam/FTB-Mods-Issues#782]
### Mod

FTB Teams

### Mod version

ftb-teams-fabric-1902.2.13-build.100

### Forge / Fabric version

1.19.2-1902.2.13

### What issue are you having?

Team data has not been received from the server!
FTB Teams will not function correctly.
Check server log for errors, and ensure your server is in online mode.
====================================================
If the server opens genuine verification, it will function normally, but this will prevent offline players from accessing the server.

Turn off genuine verification, genuine users cannot use it normally, and offline users can use it normally.

Is there a way to avoid this issue? I don't want to open the server online mod.

### Steps to reproduce

Everytime

**Comment by MichaelHillcox** [comment]
I have absolutely no idea what you are trying to say here. If there is a bug in the mode, please attach logs

**Comment by QianMuu** [comment]
> I have absolutely no idea what you are trying to say here. If there is a bug in the mode, please attach logs我完全不知道你想说什么。如果模式中有bug，请附上日志


Its error did not generate a log

Fabric-1.19.2-Server
-----------------------------------------------
“server.properties——online-mode=false"
-----------------------------------------------
After creating a team in online mode, players cannot invite others into the team. There will be an "X" in the upper left corner indicating:

“Team data has not been received from the server!
FTB Teams will not function correctly.
Check server log for errors, and ensure your server is in online mode.”

Players in offline mode can use it normally without such errors.


-----------------------------------------------
“server.properties——online-mode=true"
-----------------------------------------------

If online mode is turned on in the server's configuration file.
Online players can use it normally, but offline players will not be able to access the server.
This is unequal.

**Comment by desht** [comment]
We do not support offline mod in this way. The correct fix is to buy the game and run the server in online mode.

**Comment by SrNadien** [comment]
@desht que mal servicio deberia dejarlo como estaba y admitirlo saben que hay gente que no puede comprar mc no aga esas cagadas
