### ISSUE TITLE
[Bug]: List of issues with FTB teams

### ISSUE THREAD

**Issue by 5ully** [FTBTeam/FTB-Mods-Issues#786]
### Mod

FTB Teams

### Mod version

ftb-teams-forge-1605.2.3-build.40

### Forge / Fabric version

Forge 36.2.34

### Modpack & version

IBP

### What issue are you having?

I was trying to switch around some ftb teams stuff when i was beta testing today and hit some pretty frustrating issues:

- Trying to transfer ownership of a team when the player you want to transfer the ownership to is offline does not work.
- Trying to delete the team as the owner did not work
- Trying to delete the team as OP did not work
- Transferring ownership is not something OP can do for other teams?
- Somehow the team both exists and not at the same time. I can get info on it and change settings for it but trying to delete it returns does not exist.

I was in this case trying to leave the team as the team owner to start a new team, and new session of testing. Unfortunately it doesnt look like the team can be deleted without backend access. 

With upcoming content using this version the ftb teams version might need to get a fix in or a solution.

### Crashlogs

I believe Mikey/Saereth could pull those from the server. The interesting time period is around 2 pm server time and for around an hour. 

### Steps to reproduce

Not sure tbh, as i do not have access to server files/logs

### Anything else to note?

Ping me in discord tester channels. 
And @Saereth asked for a ping.

**Comment by desht** [comment]
I think pretty much all of these issues are resolved in 1.19. I'll look at backporting some of the fixes from there.

**Comment by 5ully** [comment]
Thanks Desht, i knew they where fixed in new versions but with pack in an older version releasing i was hoping that you could help out.

**Comment by 5ully** [comment]
This seems to have been fixed so im closing it.
