### ISSUE TITLE
[Feature Request]:   Strangers can use the function of the item.

### ISSUE THREAD

**Issue by QianMuu** [FTBTeam/FTB-Mods-Issues#788]
### Mod

FTB Teams

### Description

I don't know if this idea has already been realized.

I want strangers to be able to use the functions of the item, such as "Anvil", "Enchantment Table", "Furnace".

But they still cannot open the box.

### Describe the solution you'd like

Allow strangers to use the functionality of the item, but cannot damage, place blocks, or open boxes.

### Describe alternatives you've considered

not have

**Comment by desht** [comment]
This can be done with the `ftbchunks:interact_whitelist` tag.  Add the block ID's of any blocks you want to allow (e.g. `minecraft:furnace`) to that tag, and all players will be able to interact with those blocks.

**Comment by QianMuu** [comment]
I may not be familiar with labels, I am a novice.

Where should I add a whitelist label and what should its format be?

**Comment by QianMuu** [comment]
> 这可以通过`ftbchunks:interact_whitelist`块标记来完成。 添加您想要允许的任何块的块ID（例如`minecraft:furnace`）添加到该标签，并且所有玩家都将能够与这些块进行交互。

I may not be familiar with labels, I am a novice.
Where should I add a whitelist label and what should its format be?

**Comment by QianMuu** [comment]
> 这可以通过`ftbchunks:interact_whitelist`块标记来完成。 添加您想要允许的任何块的块ID（例如`minecraft:furnace`）添加到该标签，并且所有玩家都将能够与这些块进行交互。

Where should I add a whitelist label? I'm a bit confused.

**Comment by QianMuu** [comment]
> 这可以通过`ftbchunks:interact_whitelist`块标记来完成。 添加您想要允许的任何块的块ID（例如`minecraft:furnace`）添加到该标签，并且所有玩家都将能够与这些块进行交互。

Hello, how can I add 'ftbchunks: contact_whitelist'?

I don't know where to add it, nor do I know the format of the label.

I may need help.

**Comment by desht** [comment]
`ftbchunks:interact_whitelist` is a block tag.  Tags are a standard Minecraft feature since 1.13+, and are documented here: https://minecraft.fandom.com/wiki/Tag.

You can modify the tag either by creating a data pack for your instance (see https://minecraft.fandom.com/wiki/Data_pack), or by using a utility mod such as KubeJS to create tags.
