### ISSUE TITLE
[Bug]: Modpack error

### ISSUE THREAD

**Issue by KaitoDestiny** [FTBTeam/FTB-Mods-Issues#789]
### Mod

FTB Chunks

### Mod version

ftb-chunks-forge-1902.3.21-build.266.jar

### Forge / Fabric version

1.19.2 - 43.2.8

### Modpack & version

https://www.curseforge.com/minecraft/modpacks/kaitos-medieval-realm

### What issue are you having?

Game stops loading or server crashes. This is my mod pack i made with my community for streaming. during some mods being updating things are just not wanting to run or work together now.

### Crashlogs

https://gist.github.com/KaitoDestiny/d3391d022bd730fe8e2de028726d22f4

### Steps to reproduce

this is happening when I start the mod pack i made with my friends. and we get this error.
![crash pic 1](https://github.com/FTBTeam/FTB-Mods-Issues/assets/132838617/55ec6eab-0ba2-4117-b606-929e3379f43f)

### Anything else to note?

at this point, my brain has been fried from trying to fix or find a way to fix this.

tries removing some mods and adjusting mods from different verisons too.

got rid of EE and Enigmatic mods, cause that made things crash too.

**Comment by desht** [comment]
The bug is in Merchant Markers, which has a bad mixin into FTB Chunks; see https://github.com/AHilyard/MerchantMarkers/issues/21

The author has ignored our requests to fix his mods, so we can only recommend removing it from your instance.
