### ISSUE TITLE
[Feature Request]: The ability to show a recipe in a quest without making it a requirement of the quest

### ISSUE THREAD

**Issue by MuteTiefling** [FTBTeam/FTB-Mods-Issues#790]
### Mod

FTB Quests

### Description

The heart of the issue here is that I've got recipes that create no tangible items. 

The recipe spawns a Gateway from Gateways to Eternity. The player then kills the mobs and gets the true target of the quest. 

The trouble is, there is no link between the item and the Gateway recipe in JEI. 

The recipes look like this, effectively: 

![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/9543430/dc90f110-e87a-46db-96ce-e4613ccffcbe)

The Gateway Pearl is spawned in by the ritual, but a script immediately removes the pearl and spawns the gateway instead. 

### Describe the solution you'd like

I think the simplest way to do this would be if a task could be flagged as optional. This would allow me to show the Gateway pearl in the quest, but the player wouldn't need to obtain the item (impossible) to finish the quest.

**Comment by Raidobw2** [comment]
I've had a reply from Saereth, which developed on FTB Inferno. Possibly this can help you accomplish what you want:

> Gateways to eternity has a java event that is called when they spawn and when they are completed, [your] best bet would to just hook into that event to trigger the quest properly. [You] would just define a custom task "summon the gateway" and have kube complete the task when the gateway completed event is triggered. I do this in inferno already so I know it works.

I'm guessing the Java event he mentions is among those: https://github.com/Shadows-of-Fire/GatewaysToEternity/blob/1.19/src/main/java/shadows/gateways/event/GateEvent.java

I couldn't find these events being called in Inferno's scripts, but likely there is some correlation in them.

The script in question in FTB Inferno should be located at `kubejs/server_scripts/invasion.js`.

I recall some Java events being used in FTB OceanBlock specifically, at their location `kubejs/server_scripts/player/swimming.js` in the modpack. That is older Kube code however.

e.g.
`const Trinkets = java("owmii.losttrinkets.api.LostTrinketsAPI").get().getTrinkets(mcPlayer);`

I'm guessing you could do a similar way with Gateways to eternity, then have the quest updated in KubeJS:
`event.player.data.ftbquests.addProgress("PUT_QUEST_ID_AS_STRING_HERE", 1);`
https://github.com/FTBTeam/FTB-Quests/blob/7cff8f4c1adf9158f82f96d4a038cca837070a52/common/src/main/java/dev/ftb/mods/ftbquests/integration/kubejs/FTBQuestsKubeJSTeamData.java#L19-L29

**Comment by Saereth** [comment]
You can hook directly into the java event for gateways with a startup script in kubejs, something like this example script should accomplish what you're after

`ForgeEvents.onEvent('shadows.gateways.event.GateEvent.Completed', event => {
    const {entity, level} = event
    player = level.getEntity(entity.summonerId) //translate summoner UUID to entity

    if (!player) //make sure the player is still online when this executes
        return;

    if (entity.id = 'gateways:your_gateway_name'){
        //Gateway was successfully completed, complete the quest in FTB Quests
        player.data.ftbquests.addProgress('51171AC46282699B',1) //replace quest id 
    }
})`

**Comment by MuteTiefling** [comment]
I appreciate the script, sadly it won't work.  :-\

The player is never in contact with the gateway pearl, so they're not listed as the summoner. 

A Kubejs event triggers on the spawn event. If the item spawned is one of these pearls, it deletes the pearl and triggers the gateway via command. The player UUID isn't known, so there's no way to link it back to the quests

**Comment by desht** [comment]
Optional tasks are in the latest release

**Comment by MuteTiefling** [comment]
Thanks!
