### ISSUE TITLE
[Bug]: FTB Essentials Back Command Goes to Spawn After Death

### ISSUE THREAD

**Issue by getBoolean** [FTBTeam/FTB-Mods-Issues#795]
### Mod

FTB Essentials (Forge)

### Mod version

ftb-essentials-forge-1902.3.1-build.75

### Forge / Fabric version

1.19.2 43.2.6

### Modpack & version

Boolean Create v1.2.1 (on Technic Launcher)

### What issue are you having?

After a player death, the `/back` command goes to spawn instead of the death location

### Steps to reproduce

1. Open world, walk away from spawn
2. Player dies
3. Use `/back`
4. Player teleported to spawn instead of death location

### Anything else to note?

The modpack can also be found on CurseForge, but it is an outdated version. I am not updating it anymore since all my server members are using Technic Launcher. The old version does not have this bug, which uses `ftb-essentials-1902.1.10-build.47`

**Comment by WyFryMU** [comment]
I think this can be closed. The latest update has this fixed: ftb-essentials-forge-1902.3.3-build.100.jar , I had this same error and just switched to the newest version and /back is working properly now :) Thank you!

**Comment by desht** [comment]
Yep, closing.
