### ISSUE TITLE
[Bug]: "Building Terrain" stuck screen after opening quest book

### ISSUE THREAD

**Issue by itsdinkd** [FTBTeam/FTB-Mods-Issues#798]
### Mod

FTB Quests

### Mod version

ftb-quests-fabric-1902.4.15-build.228.jar

### Forge / Fabric version

0.76.0

### Modpack & version

Another Quality Modpack 1.5.6.2 (Dev build)

### What issue are you having?

When using the latest FTB Quests for 1.19.2 Fabric, in AQM2 (Haven't tested by itself), and open the quest book, and then exit Via **ESC** key, you will receive a "Building Terrain" screen.

![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/35115304/8658d09d-030b-4766-84a9-bd4508d30646)

### Crashlogs

No crash

### Steps to reproduce

1. update to latest FTB Quests
2. Launch Another Quality Modpack 2
3. Open quest book
4. exit via ESC key
5. viola

### Anything else to note?

You cannot exit this screen and are forced to force quit minecraft.

**Comment by desht** [comment]
Quests certainly doesn't send anyone to that screen.  Are you sure that's the only mod you updated?

**Comment by itsdinkd** [comment]
There were other mods updated however when I downgraded ftb quests to the
prior version used, the issue went away.

**Comment by desht** [comment]
If you'd like to try a dev build, I think https://maven-admin.ftb.dev/repository/maven-public/dev/ftb/mods/ftb-quests-forge/1902.4.16-build.231/ftb-quests-forge-1902.4.16-build.231.jar will fix this problem (as well as the lag issue you also reported). Please let me know if this helps...

**Comment by itsdinkd** [comment]
Testing the lag portion might be difficult. Will I be able to put it on our
official server for our modpack where players wouldn't need that version to
join?

**Comment by desht** [comment]
Probably not, no.  But if you can test at least the fix for this issue in a test world, that would be great.

**Comment by itsdinkd** [comment]
sounds good, ill test to see if that screen stops showing right now

**Comment by itsdinkd** [comment]
oh it looks like it was made for forge? this is a fabric issue

**Comment by desht** [comment]
Oh, sorry - here's a fabric build: https://maven-admin.ftb.dev/repository/maven-public/dev/ftb/mods/ftb-quests-fabric/1902.4.16-build.232/ftb-quests-fabric-1902.4.16-build.232.jar

**Comment by itsdinkd** [comment]
Thanks! So i tested and it works fine (no more building terrain screen). I am unable to test the lag on join though unfortunately. once you release this update on CF though ill push it out in a modpack update and will test in our public servers

**Comment by desht** [comment]
Should be a new release in the next couple of days, with luck.

**Comment by itsdinkd** [comment]
> Should be a new release in the next couple of days, with luck.

🤞 standing by
