### ISSUE TITLE
[Bug]: Major lag when player joins dedicatedf server

### ISSUE THREAD

**Issue by itsdinkd** [FTBTeam/FTB-Mods-Issues#799]
### Mod

FTB Quests and FTB Teams

### Mod version

1

### Forge / Fabric version

0.76.0

### Modpack & version

Another Quality Modpack 2 - v1.5.6.1

### What issue are you having?

When a player joins the official servers for AQM2, there is a massive lag spike for 10-20 seconds.

Players helped me with profiling, and I ran the profiler right after someone left, and stopped 10 seconds after they joined. 

I set a threshold for only ticks over 1000 to make sure I caught the offending mods. 

I have bookmarked both sections that I feel is part of the cause. (I know Roughly Enough Resources also indicates high delays, I have tested this out by removing RER, and the lag still occurs, just not as much)

### Crashlogs

https://spark.lucko.me/cITj7f8U5g?hl=22,2579

https://spark.lucko.me/cITj7f8U5g?hl=22,2579

### Steps to reproduce

1. Launch AQM2 dedicated server
2. Have a player join
3. Lag

### Anything else to note?
![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/35115304/80b8044a-6d0f-42ab-a810-5d988812d79b)

_No response_

**Comment by desht** [comment]
There's a structure task in the quest book, and that's being checked for completion when a player logs in. That involves getting the chunk where the player is to check for structures, which appears to be causing the lag.

Changing the structure task completion check to not check on player login, but only periodically, may help here.

**Comment by desht** [comment]
Fixed in latest release
