### ISSUE TITLE
[Bug]: Minetogether chat shows connected, but no one else is ever in chat

### ISSUE THREAD

**Issue by Yaco-Taco** [FTBTeam/FTB-Mods-Issues#80]
### Mod

Mine Together

### Mod version

minetogether-1.10.2-2.2.5

### Forge / Fabric version

1.12.2-14.23.5.2847

### Modpack & version

FTB Interactions 2.0.9

### What issue are you having?

I can't see anyone else chatting in the Mine Together chat box. I can see the mine together background, I can type things, and it says I'm online. I can also see friends I added in the past in my friends list, but they are not available to try a private chat. I have tried other versions of the mod, and this one is the only one that connects. The other versions say disconnected or eternally stay on connecting. The chat used to work back when the modpack first came out, but it hasn't worked since I installed the latest version. Maybe just nobody is chatting, but I've played for long enough and enough times that I think I would have seen at least someone by now.
![Picture1](https://user-images.githubusercontent.com/92287073/136733720-310a8998-f4b8-49f1-a77e-632b0ee57f2e.png)
![Picture2](https://user-images.githubusercontent.com/92287073/136733725-1af7c592-01c2-4d01-be5e-8ff62894cc89.png)

### Steps to reproduce

Just install FTB Interactions, start a singleplayer world, and open the chat box.

**Comment by Raidobw2** [comment]
Please report this issue to MineTogether's issue tracker which is located at: https://github.com/CreeperHost/MineTogether/issues.

This is not a mod made by the Feed the Beast team.

**Comment by Yaco-Taco** [comment]
Sorry yeah I just found the mine together section, but thanks anyway
