### ISSUE TITLE
[Bug]: <> In the chat

### ISSUE THREAD

**Issue by SheroxGG** [FTBTeam/FTB-Mods-Issues#800]
### Mod

FTB RANKS

### Mod version

ftb-ranks-forge-1902.1.15-build.76

### Forge / Fabric version

1.19.2

### Modpack & version

FTB SKIES 1.0.0

### What issue are you having?

I am having a trouble with FTB Ranks, I have shared my FTB Ranks config downstairs.
The problem is that angled brackets are appearing on the chat when they are not in the config. I am not sure if this brackets are placed by your mod or by minecraft, as Minecraft itselfs uses these brackets by default, but FTB Ranks is supposed to overwrite this. Hope someone can explain me why is this happening 🥰

![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/34599826/ad54337d-681b-479b-8a07-48c6442de039)

Id like to ask another quick question, the Permission chunk_load_offline, is supposed to make loaded chunks work while the user is online right? I am asking this because someusers that have this permission "false" are still loading while offline on their island. 

Thanks a lot for your time and patience! 

### Steps to reproduce

I have shared my config so you can check. Thanks!

### Anything else to note?

{
	imperial: {
		name: "Imperial"
		power: 3
		ftbranks.name_format: "&7&l►&r&#D6D6D6 Imperial&7 | &r&f{name} &7»&r"
		ftbchunks.max_claimed: 200
		ftbchunks.max_force_loaded: 5
		ftbchunks.chunk_load_offline: false
		ftbutilities.chunkloader.load_offline: false
	}
	admin: {
		name: "Admin"
		power: 1000
		command.ftbranks: true
		ftbchunks.max_claimed: 200
		ftbranks.name_format: "&7&l►&r&#ff1c60 Admin&7 | &r&f{name} &7»&r"
		command: true
		ftbchunks.max_force_loaded: 200
		command.ftbteams: true
		ftbchunks.chunk_load_offline: true
	}
	ancestral: {
		name: "Ancestral"
		ftbchunks.max_claimed: 200
		ftbchunks.max_force_loaded: 5
		power: 6
		ftbchunks.chunk_load_offline: true
		ftbranks.name_format: "&7&l►&r&#F76608 Ancestral&7 | &r&f{name} &7»&r"
	}
	amigo: {
		name: "Amigo"
		condition: "always_active"
		power: 1
		ftbranks.name_format: "&7&l►&r&#c4deff Amigo&7 | &r&f{name} &7»&r"
		ftbchunks.max_claimed: 0
		ftbchunks.max_force_loaded: 0
		ftbchunks.chunk_load_offline: false
	}
	celestial: {
		name: "Celestial"
		power: 5
		ftbranks.name_format: "&7&l►&r&#FD5151 Celestial&7 | &r&f{name} &7»&r"
		ftbchunks.max_claimed: 200
		ftbchunks.max_force_loaded: 5
		ftbchunks.chunk_load_offline: false
		ftbutilities.chunkloader.load_offline: false
	}
	dueno: {
		name: "Dueno"
		power: 999
		command.ftbranks: true
		ftbranks.name_format: "&7&l►&r&#3d64ff Dueño&7 | &r&f{name} &7»&r"
		ftbchunks.max_claimed: 200
		ftbchunks.max_force_loaded: 200
		ftbchunks.chunk_load_offline: true
	}
}

**Comment by desht** [comment]
For the angle bracket issue: the way chat is handled by Minecraft in 1.19.2+ has changed a lot, and the old chat reformatting that Ranks used in 1.18 and earlier doesn't work anymore. So only the player name can be reformatted, not the angle brackets. There might be the possibility of more customization in future, but that needs some investigation.

For the offline chunk loading question, what are your `chunk_load_offline` and `force_load_mode` settings set to in your world config file (found in the `serverconfig/ftbchunks-world.snbt` file) ?

**Comment by SheroxGG** [comment]
Thanks a lot for your quick reply! Thanks for letting me know that there is nothing to do on newest versions yet! 😊

About the FTBCHunks config,
chunk_load_offline: true
force_load_mode: default

I had no clue that this config was there. My main language is not english, and I dont fully understand what do I have to change in order to prevent users without the "Offline load permission false" from loading while online.

**Comment by desht** [comment]
OK, so with those settings, offline force-loading is enabled for everyone. If you want to limit it using ranks, then set `chunk_load_offline` to false.

Note: you can also change this in-game, if you're an op user - open the map, and click the purple button bottom-right - that opens the server config screen. The setting you want is "Allow Forceloading for Offline Players".
