### ISSUE TITLE
[Bug]: FTBChunks explosions protection is still not working

### ISSUE THREAD

**Issue by Proxwian** [FTBTeam/FTB-Mods-Issues#801]
### Mod

FTB Chunks

### Mod version

ftb-chunks-forge-1802.3.17-build.265.jar

### Forge / Fabric version

1.18.2 40.2.2

### Modpack & version

OxFORTPACK x256 7.1

### What issue are you having?

Explosion flag is not working at all. No creeper/tnt/wither protection provided at all. Having this issue all time using FTBChunks

### Steps to reproduce

1. Claim a chunk
2. Try to explode creeper/tnt/spawn wither in it
3. Get blocks detroyed

### Anything else to note?

![2023-05-18_13 52 56](https://github.com/FTBTeam/FTB-Mods-Issues/assets/31781674/9e4ff3d3-18c6-4008-a9bc-6962ae3dd4d5)
![2023-05-18_13 53 06](https://github.com/FTBTeam/FTB-Mods-Issues/assets/31781674/3efe9a70-c862-4bff-839f-78c826a96ad5)
![2023-05-18_13 52 45](https://github.com/FTBTeam/FTB-Mods-Issues/assets/31781674/3d12d17c-c305-479d-adfe-9f552d12a5b8)

**Comment by desht** [comment]
It's working fine here.  That doesn't look like vanilla TNT - what is it?

**Comment by Proxwian** [comment]
It is vanilla. Just retextured

**Comment by Proxwian** [comment]
![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/31781674/3832575e-e741-4926-b7cb-ff8e192f056d)

**Comment by Proxwian** [comment]
![2023-05-18_14 12 46](https://github.com/FTBTeam/FTB-Mods-Issues/assets/31781674/640ff7b9-4b14-482f-893f-d6ce0ea69309)
![2023-05-18_14 12 50](https://github.com/FTBTeam/FTB-Mods-Issues/assets/31781674/021cbcc6-a775-400e-b191-e8dd17217d60)
![2023-05-18_14 12 43](https://github.com/FTBTeam/FTB-Mods-Issues/assets/31781674/de644109-1d4c-4a1b-9e74-a3376568d851)

**Comment by desht** [comment]
Then you probably have some other mod messing with explosion events.  I've tested in 1.18 (and 1.19 too), and TNT explosion damage is most definitely prevented.  Have you tested with just FTB Chunks?

**Comment by Proxwian** [comment]
Not yet. OK, i will check possible compatibility issues and update ticket

**Comment by Proxwian** [comment]
Oh, my bad. It seems mod named "Survival Reimagined (former IguanaTweaks Reborn)" makes explosions damage protected chunks. Setting "Enable Explosion Overhaul" in Survival Reimagined config to false solves problem. Maybe someone will reference this issue in future.

Closing for now.

**Comment by desht** [comment]
I'll take a look at the code for that mod and see if their overhaul is something we can detect.

**Comment by Proxwian** [comment]
Found old issue for SurvivalReimagined on its GitHub. You can see my discussion with developer here

https://github.com/Insane96/IguanaTweaksReborn/issues/166

**Comment by desht** [comment]
I opened a new one: https://github.com/Insane96/IguanaTweaksReborn/issues/250
