### ISSUE TITLE
Player unable to access team dimension

### ISSUE THREAD

**Issue by Dulant84** [FTBTeam/FTB-Mods-Issues#804]
### Modpack

FTB Skies

### Modpack version

1.0.4

### Log Files

[crash-2023-04-16_19.22.49-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11243237/crash-2023-04-16_19.22.49-server.txt)

### Describe the bug

One user on our server is unable to log in due to a problem with their team dimension. When the owner of the team/dimension logs on, the server crashes with the crash report attached.  If another user on the server tried to visit their team dimension, the same problem occurs.  Prior to this happening the owner of the affected team/dimension had logged out while inside a compact machine, once clicking on the machine to exit, the server crashed in the same manner described before.

### Steps to reproduce

use /ftbteamdimensions visit (team ID)
Owner logs into the server when player.dat Dimension is set to the problematic team.

### Expected behaviour

User is able to log in and return to their dimension & other players can visit their dimension.

**Comment by desht** [comment]
It's unclear if this is an issue with Team Dimensions, or with Compact Machines.  I cannot reproduce the problem either in SSP or SMP (dedicated server).

What's needed to debug this issue is to disable the server watchdog timer and then run spark (`/spark profile start`) just before someone either logs in or tries to visit the dimension in question. That may provide some clues as to exactly where the server is deadlocking.

**Comment by Saereth** [comment]
@Dulant84 if you could zip up your world folder and throw it on google drive or something it may help us reproduce the issue as well if you're able. As it stands we're having difficulty directly reproducing it

**Comment by Raidobw2** [comment]
To me looks like a Create contraption that's processing items with water is overflowing a lot, there's bout 76000 itemstacks floating around somewhere in `ftbteamdimensions:team/cba3d914-bee3-4c73-ac4e-a758ba1388d8`, I think? That would be dimension player "Radrael" is in at the moment.
![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/17010632/9d7309e6-bf6f-4350-be63-99514f56b417)

In your server files, in the folder at `FTB_Skies_2243413/dimensions/ftbteamdimensions/team/cba3d914-bee3-4c73-ac4e-a758ba1388d8/entities`, there should be a `r.0.0.mca` file that's much bigger than the rest in terms of file size.

If that file is not especially big, then the item farm is in a compact machine. Jump straight to solution \# 2.

2 solutions:

## 1
While the server is offline, delete that file `FTB_Skies_2243413/dimensions/ftbteamdimensions/team/cba3d914-bee3-4c73-ac4e-a758ba1388d8/entities/r.0.0.mca`. It can potentially destroy the following: 76359 items, 108 pigs, 41 chickens, 16 tropical fish, 15 starbuncle (ars nouveau). Then restart the server and ask Radrael to log on. This will only work if the farm is in the player's overworld dimension, so not in a compact machine.

## 2
1. Backup the world immediately and keep in safe storage for now
2. Enable commands blocks in `server.properties`
3. Set `max-tick-time=120000` in `server.properties`
4. Using a player that's not crashing the server and OP in the server, set up a repeating command block with command `/kill @e[type=item]`. This command kills all items that are loaded in the server (only thrown items that are presently lingering on the ground).
5. Make sure command block is loaded (e.g. at spawn) and working (throw one useless item on the ground to test)
6. Have Radrael log on
7. Server should freeze for a few seconds, then have Radrael turn off their Create farm

In both cases after fixing the lag, have Radrael fix their Create farm by adding overflow protection for example, turning off the farm, unloading the farm or dismantling it if it's no longer needed.

I think that might do it considering what I'm seeing in the crash log. Let us know and cheers
