### ISSUE TITLE
[Bug]: FTB Quest  Visit Biome quest type not triggering for modded biomes from BYG or BiomesOPlenty

### ISSUE THREAD

**Issue by Twigstick71** [FTBTeam/FTB-Mods-Issues#805]
### Mod

FTB Quests

### Mod version

ftb-quests-forge 1902.4.15-build.228

### Forge / Fabric version

1.19.2 43.2.6

### What issue are you having?

ftb quest type biome or "visit biome" working for minecraft biomes but not byg or biomesoplenty with same setup  and proper namespace for modded biomes

### Crashlogs

no crash, quest simply doesn't trigger when modded biome visited

### Steps to reproduce

create biome type quest for minecraft (vanilla) biome, BYG biome and BiomesOPlenty biome and visit them.  Behaviour for vanilla biome is  as expected, but not for the modded biomes

**Comment by desht** [comment]
I can't reproduce this problem. I created a visiti-biome quest using `byg:redwood_thicket` as a biome. Then visited a Redwood Thicket, and the quest immediately completed.

**Comment by Twigstick71** [comment]
further tests and  the issue was user skill, not the mod.  I was not seeing a quest complete for coniferous forest  but the quest was for byg version and the version I traveled through was bop version and others seem to have been a result of copyig quests rather than creating new ones for each biome.
