### ISSUE TITLE
[Bug]: "\" is not displayed when using the in-game editor

### ISSUE THREAD

**Issue by BlackAures1** [FTBTeam/FTB-Mods-Issues#810]
### Mod

ftb-quests-forge-1902.4.15-build.228

### Mod version

ftb-quests-forge-1902.4.15-build.228

### Forge / Fabric version

1.19.2 43.2.11

### Modpack & version

Play as dragon Gothic Edition

### What issue are you having?

The `\ `sign is rendered only in edit mode (fast key D), but in the quest itself it is absent.

### Steps to reproduce

Do this
![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/43911230/73932acf-a26e-4aff-9860-e83a81c23ee5)

Take this
![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/43911230/53746e30-b77f-4e77-ba59-1908cdac39ce)

**Comment by BlackAures1** [comment]
![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/43911230/6905658b-5f89-4a9a-afc3-0d11ae11b43d)
![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/43911230/18df4b4e-b241-43e3-a9bf-13db9b262121)
Yes. The double works. I think it's just a minor problem that doesn't affect anything. I can't think of a situation where it's critical to specify `\` and not `/`

**Comment by desht** [comment]
Yep, `\` has special meaning (for example `\n` is a link break).  So to get a literal backlash in, it needs to be doubled like this.
