### ISSUE TITLE
[Feature Request]: More information for "Observable" quests

### ISSUE THREAD

**Issue by BlackAures1** [FTBTeam/FTB-Mods-Issues#812]
### Mod

FTB Quest 1.19.2

### Description

![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/43911230/e5dfdc8c-7cb6-4fa5-9d6b-d6a42a70bc05)
We need to add automatic name generation for "Observable" quests. If you do not manually write what exactly needs to see, the player will never guess from the icon what he needs to watching. 

### Describe the solution you'd like

1. The simplest: just an automatically generated title like for quests like " Kill ". 
![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/43911230/d9ae3c4f-7c99-40e9-b905-8a355ec646df)

2. The hardest: Rendering in place of the Air block or entity to be inspected.
![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/43911230/d7e353fd-1338-4a37-b692-9fd8b8c1ef08)

### Describe alternatives you've considered

Now it's only possible if the creator manually fills it in, but that's inconvenient for several reasons:

1. it's a lot of manual monotonous work that would have to be redone when the quest changes.
2. Complicating the localization work. Additional localization keys will be needed.

**Comment by desht** [comment]
Next version will have a default "Observation: <subject>" title (which can be overridden as normal).

**Comment by desht** [comment]
Added in 1902.4.17
