### ISSUE TITLE
[Feature Request]:  Biggest Reward Table... and 5 more

### ISSUE THREAD

**Issue by BlackAures1** [FTBTeam/FTB-Mods-Issues#814]
### Mod

FTB Quest 1.19.2

### Description

![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/43911230/c29cdbfb-3dac-4ae1-bd58-abb9345f3df5)
For the large Reward Table, there is no way to know the full list of possible items, and what's sad is that they are sorted from rarest to most common.

### Describe the solution you'd like

1. "Press shift" to see the full list of items

or

2. Allow the quest creator to specify how many items from the list will be shown to the player. Also give the ability to choose in what order items will be displayed.

### Describe alternatives you've considered

The only way to make it displayable now is to reduce the number of items in the reward.

**Comment by desht** [comment]
I guess there's a risk in some cases of the full list overflowing the vertical screen height, which was why that was added.  Although a 10-line limit is too small, I agree.

One idea: I could make the list slowly scroll if it's very tall (with pausing by holding Shift). Thoughts?

**Comment by desht** [comment]
Shift-to-pause is actually trickier than I hoped, and really needs a more extensive tooltip rewrite in FTB Library.  So probably for the next major release (1.20).

However, I've adjusted tooltips here to display as many lines as possible based on the screen height, and if there are still too many to fit, then it will slowly cycle through all available rewards in the tooltip.

**Comment by BlackAures1** [comment]
I would love any way to see all the rewards regardless of how it works. It's just really weird that a player can't see what he'll get with a 90% chance, but sees what he'll get with a 0.1% chance

**Comment by desht** [comment]
Added in 1902.4.17
