### ISSUE TITLE
[Feature Request]: FTB Teams/Chunks support for Xaero's Minimap/World Map

### ISSUE THREAD

**Issue by WitherTM** [FTBTeam/FTB-Mods-Issues#815]
### Mod

FTB Teams + FTB Chunks

### Description

Everytime I am using a modpack with Xaero's Minimap and FTB's mods I find it annoying to have to go into the inventory and open the FTB Chunks map just to change your chunks. I wish it could be combined into one place where I can see the map and change my claimed 

### Describe the solution you'd like

Add a way to be able to edit your claimed and forceloaded chunks within Xaero's World Map and see them in Xaero's Minimap.

### Describe alternatives you've considered

Xaero96 has released a mod called Open Parties and Claims, which has Xaero's World Map/Minimap support, but this would cause there to be two teams, one for quests and one for claims, which would be insanely annoying. It is also possible to only have FTB Chunks of course, except Xaero's version has so many more good features that I am not gonna do that.

**Comment by desht** [comment]
Next Chunks release will allow opening the chunk claim screen directly, with a configurable hotkey. This should do what you need, I think?

**Comment by WitherTM** [comment]
well thats very cool, nice! Except I meant that it would be possible if one could do the things in the chunk claim screen (as in (un)claim chunks and (un)forceload chunks) right inside of the Xaero's World Map screen. does that explain my question?

Also, It was more of an accident asking it here, since I was more supposed to ask at Xaero's CF, but I asked it here first and oh well

**Comment by desht** [comment]
Yeah that would be something that Xaero's would need to add support/integration for.

**Comment by WitherTM** [comment]
I'll rephrase it in a different suggestion :)
