### ISSUE TITLE
[Feature Request]: FTB Essentials `/rtp` dimension whitelist/blacklist

### ISSUE THREAD

**Issue by Aiidoneus** [FTBTeam/FTB-Mods-Issues#818]
### Mod

FTB Essentials

### Description

Hello,
I would like to request the ability to add a dimension whitelist or blacklist (maybe both with a config?) to the `/rtp` command. If servers have this on by default, it can cause issues to players in the Twilight Forest for example. As a lot of the Twilight Forest is locked behind advancements and physical barriers. Another example is The End. Players can technically skip defeating the End Dragon and go the end islands by using this command. 

### Describe the solution you'd like

A simple way to blacklist or whitelist which dimensions players `/rtp` in using a config option/change

### Describe alternatives you've considered

Right now I am limiting this with another mod but having this built in would be nice.

**Comment by WitherTM** [comment]
very cool suggestion! (I'm not a dev, I just would like this too

**Comment by desht** [comment]
Yes, good idea.

**Comment by desht** [comment]
Added in 1902.3.2 release
