### ISSUE TITLE
[Bug]: Format Error - KubeJS forwarded the problem to you

### ISSUE THREAD

**Issue by BlackAures1** [FTBTeam/FTB-Mods-Issues#821]
### Mod

ftb-quests-forge-1802.3.14-build.191

### Mod version

ftb-quests-forge-1802.3.14-build.191

### Forge / Fabric version

1.19.2 43.2.11

### Modpack & version

Play as dragon Gothic Edition

### What issue are you having?

**Mods:** ftb-quests-forge-1902.4.16-build.235 + kubejs-forge-1902.6.0-build.142 
**Briefly:** when trying to use localization keys from kubejs you get Format Error
![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/43911230/fad33144-85fc-4056-ba03-67f28fadf1b7)

In detail: to make a modpack in several languages I have to use kubejs, but very often appears Format Error, which spam endlessly in the logs and in general visually spoil the appearance of quests. 
![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/43911230/3328ba50-dba9-4486-905c-1be56d4c10c2)

Here is an example of text from my old modpack, which had the same problem when trying to add this to the localization file: 
> "chapter.1.quest.1.description.1": "▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬\n■ Хочешь пройти по пути настоящих драконов? Тогда тебе сюда. Задания можно проходить в любом порядке. За многие из них вы будете получать награды, но самое важное это информация о модах и изменениях в них.\n▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬\n■ Полный список заданий можно найти в меню слева. Здесь только самые общие задания.\n▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬\n■ Для выполнения некоторых заданий требуется подтверждение прочтения. Для этого нужно просто нажать галочку слева от награды. Прежде чем забирать саму награду, обязательно освободите инвентарь.\n▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬\n■ Если вам что-то не нравится в каком-либо из модов, просто используйте конфиги. У Dragon Survival конфиг доступен без перезагрузки игры. Просто зайдите в инвентарь дракона и нажмите на шестерёнку справа внизу. Многие моды в модпаке являются настраиваемыми. Для этого откройте папку с модпаком (curseforge - minecraft - Instances - Play as Dragon) и найдите там папку config. С помощью Блокнот или Notepad++ откройте и изучите файл нужного вам мода.\n\n■ Не нашли нужную вам настройку? Возможно, она находится тут: Play as Dragon - saves - World Name - serverconfig\n▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬"

### Crashlogs

[debug.log](https://github.com/FTBTeam/FTB-Mods-Issues/files/11593145/debug.log)
[latest.log](https://github.com/FTBTeam/FTB-Mods-Issues/files/11593146/latest.log)

### Steps to reproduce

1. Create a profile in CurseForge, install ftb-quests-forge-1902.4.16-build.235 + kubejs-forge-1902.6.0-build.142 
2. Take these two files and turn them into jsons + snbt (github does not allow me to upload this file type)
- [en_us.txt](https://github.com/FTBTeam/FTB-Mods-Issues/files/11593151/en_us.txt) - \Instances\Play as Dragon Gothic Edition\kubejs\assets\kubejs\lang 
![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/43911230/1f82fe47-2ee1-49fc-999e-83b463205d65)
- [general.txt](https://github.com/FTBTeam/FTB-Mods-Issues/files/11593011/general.txt) - Instances\Play as Dragon Gothic Edition\config\ftbquests\quests\chapters
![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/43911230/aa1db0f4-1c6e-40aa-b697-d6b50f8730f6)

3. Move the files to the specified locations
4. Go into the game, create a world, go into the world and open the rightmost quest (most of the graphics will be broken, but that's not the point)
![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/43911230/518cd9e9-c810-4ded-a46f-4261a7addcb1)
5. Open the quests and see Format Error here
![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/43911230/4aaab6fa-8ab9-4ec0-bf02-891909ab2d7e)

### Anything else to note?

**Addition Info:** https://github.com/KubeJS-Mods/KubeJS/issues/468
I have no idea whose part of the code you two have to blame, but the KubeJS developer has been insisting for a year that you have the problem.

**Comment by desht** [comment]
Actually, the problem here is in your own translation file.  Due to the way Java handles translations, '%' characters have special meaning, e.g. '%s' means 'substitute in a string parameter'.

Your translation in `chapter.1.quest.15.subtitle` contains `99% контента и особенностей модпаков хранятся не в папке модов`. A '%' followed by a space isn't valid, and will cause that `Format error` you've noticed.

The easy fix here is to double up any % symbols in your translation text, e.g. `99%% контента и особенностей модпаков хранятся не в папке модов` (similar to the way you need to double up `\` as discussed in the other issue).

**Comment by desht** [comment]
This isn't something we should be trying to work around - when using translation files, literal '%' should always be escaped as a double '%%' (this applies to all translations in Java, modding and otherwise, not just FTB Quests).

So you will need to go through your translation files and substitute any lone '%' symbols, sorry...
