### ISSUE TITLE
[Feature Request]: FTB Quests support for Open Parties and Claims

### ISSUE THREAD

**Issue by WitherTM** [FTBTeam/FTB-Mods-Issues#822]
### Mod

FTB Quests

### Description

What I would like is that it would be possible to have OPAC Teams as possible replacement for FTB Teams

### Describe the solution you'd like

A possible toggle or a config that I makes it possible to choose which team mod u should use and if OPAC is chosen, to have FTB Teams not be a required mod

### Describe alternatives you've considered

the current system is fine, but OPAC is pretty cool and built into the Xaero's Map mods

**Comment by desht** [comment]
Sorry, we have no plans to add support for OPAC Teams.
