### ISSUE TITLE
[Bug]: Player active while game loads and chunks are generated

### ISSUE THREAD

**Issue by KatrinkaRose** [FTBTeam/FTB-Mods-Issues#831]
### Mod

FTB Chunks

### Mod version

ftb-chunks-fabric-1902.3.21-build.266

### Forge / Fabric version

Fabric 1.19.2 0.14.21

### Modpack & version

StaTech Industry 1.0.0

### What issue are you having?

When loading a save the game displays the targets chunks loading for server and client but while those load the player is active in the world but not visible or controllable.  Game sounds are heard and I've died more than once to the delay between the character load and the actual game starting.

I expect to have control of my character when I load into world, even if it's a bit laggy while the initial chunks load that's preferable to an extended period (10-15 seconds on average) of blind vulnerability every load.  I can only imagine it being more dangerous on a multiplayer server where the world runs while you're away.

### Steps to reproduce

1. Create new world or select to load an existing save.
2. Wait.
3. There's a thump sound at the same time the Building terrain screen appears and game sounds are active during the entire load and the player is vulnerable to any enemies that happen to be around.
4. Wait until the server and client chunks finish building before getting to see the world and actually control the player character.

![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/90729629/3a967a26-3c20-4a28-92aa-bbc6efdc2095)

**Comment by desht** [comment]
That... has nothing to do with FTB Chunks?

The loading screen you posted is generated by some other mod (doesn't look like vanilla), not FTB Chunks.  We don't modify how the player logs into the world in any way.

**Comment by KatrinkaRose** [comment]
Sorry about the confusion, the actual culprit was Fastload.  Thank you for your time!
