### ISSUE TITLE
[Feature Request]: FTB Essentials Config for /back only allowed on death

### ISSUE THREAD

**Issue by theboo** [FTBTeam/FTB-Mods-Issues#836]
### Mod

FTB Essentials

### Description

It would be very nice to be able to restrict the /back command to work only once and only on death. MA essentials has long had this feature and would be great to see it here as it would keep players from having a free trip home and back with /home enabled.

### Describe the solution you'd like

A boolean in the /back section in the FTB essentials server config file to allow /back only on death and only once per death.

**Comment by desht** [comment]
Good idea, yes.

**Comment by desht** [comment]
Added in 1902.3.2 release
