### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by Don77b** [FTBTeam/FTB-Mods-Issues#837]
### Mod

FTB Teams

### Description

I want to be able to let people interact with blocks without being able to break blocks

### Describe the solution you'd like

Currently the only option on FTB Teams allows anyone to interact with blocks but also lets them break and place blocks. I want to have people interact with blocks but not break or place any. Could split these into two different options for this

**Comment by desht** [comment]
This is already an option on Forge (separate interact and place permissions).  It currently cannot be done on Fabric due to lack of API support in Fabric/Architectury, but will be added in future if it becomes possible.
