### ISSUE TITLE
[Bug]: FTB Fabric 1.20.1 Dependency Checking

### ISSUE THREAD

**Issue by tspurr** [FTBTeam/FTB-Mods-Issues#840]
### Mod

FTB Library

### Mod version

ftb-library-fabric-2001.1.1-build.1.jar

### Forge / Fabric version

Fabric - 0.14.21

### Modpack & version

Personal

### What issue are you having?

Incompatible mod set. It is saying I need version 2001.1.1-build.219 instead of 2001.1.1-build.1 for FTB Library only has an alpha version available for build.1 and no build.219.

![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/51808217/977f9364-739c-49c8-a96f-d411f53314d0)

### Crashlogs

Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'FTB Library' (ftblibrary) 2001.1.1-build.1 with version 2001.1.1-build.219 or later.
Unmet dependency listing:
	 - Mod 'FTB Essentials' (ftbessentials) 2001.1.1-build.1 requires version 2001.1.1-build.219 or later of mod 'FTB Library' (ftblibrary), but only the wrong version is present: 2001.1.1-build.1!
	 - Mod 'FTB Ranks' (ftbranks) 2001.1.2-build.1 requires version 2001.1.1-build.219 or later of mod 'FTB Library' (ftblibrary), but only the wrong version is present: 2001.1.1-build.1!
	 - Mod 'FTB Teams' (ftbteams) 2001.1.1-build.1 requires version 2001.1.1-build.219 or later of mod 'FTB Library' (ftblibrary), but only the wrong version is present: 2001.1.1-build.1!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

### Steps to reproduce

Load game with 1.20.1 Fabric launcher and mods in it

### Anything else to note?

Just didn't know if this was an error in the dependency check and the .219 wasn't replaced with the .1

**Comment by desht** [comment]
Confirmed, will be new releases out today to resolve this.

**Comment by desht** [comment]
New versions for 1.20.1 are now published on Curseforge (still marked as "Alpha").   Note that the `-build.X` part has been dropped from the mod versions, including in the JAR filenames.  E.g. FTB Library is now simply `ftb-library-fabric-2001.1.2.jar`.
