### ISSUE TITLE
[Feature Request]: 1.20.1 - Add event for mods to cancel FTB teleport commands

### ISSUE THREAD

**Issue by TelepathicGrunt** [FTBTeam/FTB-Mods-Issues#841]
### Mod

FTB Essentials

### Description

I would like to block teleporting commands from FTB such as /home when players are in an arena event in my mod. Ideally there should be a feedback message to player so then know they can’t escape.

### Describe the solution you'd like

Could an event be fired by Essentials or so that I can cancel if player is disallowed to escape the area?

### Describe alternatives you've considered

The forge and fabric events are not quite sufficient or missing

**Comment by desht** [comment]
Now firing a new `TeleportEvent.TELEPORT` event, which can be cancelled to prevent teleportation based on the current of the passed `ServerPlayer` object.

Example usage:

```java
import dev.ftb.mods.ftbessentials.api.event.TeleportEvent;

// registering during mod construction...
TeleportEvent.TELEPORT.register(this::onPort);

// event handler
private CompoundEventResult<Component> onPort(ServerPlayer serverPlayer) {
    if (notAllowed(serverPlayer)) 
        return CompoundEventResult.interruptFalse(Component.literal("nope"));
    }
}
```

Return a Component, which is the message that will be sent to the player if teleportation is prevented.

A dev build is now available if you'd like to test against it:

https://maven.saps.dev/snapshots/dev/ftb/mods/ftb-essentials-forge/2001.1.3-SNAPSHOT/ftb-essentials-forge-2001.1.3-20230620.091549-1.jar

**Comment by desht** [comment]
Added in 2001.1.3 (although you should get 2001.1.4 at least).
