### ISSUE TITLE
[Bug]: The mod "Carry On" is able to bypass Claims

### ISSUE THREAD

**Issue by Veracis-Eclise** [FTBTeam/FTB-Mods-Issues#843]
### Mod

FTB Teams/CarryOn

### Mod version

 ftb-teams-fabric-1902.2.13-build

### Forge / Fabric version

1.19.2

### Modpack & version

BigChadGuys Plus

### What issue are you having?

- Am unsure how to check fabric version

The mod Carry On allows the player to physically move certain entities and blocks. However, FTB teams doesn't seem to be able to block Carry On from moving mobs around in claims that do not belong to the player. 

### Steps to reproduce

1. Shift right-click when standing next to a mob, lets say a villager. (empty hands)
2. The player will pick up the villager.
3. The player is unable to place down picked up entities in claims

### Anything else to note?

I believe carry on sends a break event when picking up blocks. I'm unsure of the event used for picking up entities

**Comment by Tschipp** [comment]
Unless I'm sending the event wrongly, I think I am breaking the block only after the event is sent.
See here the event is sent: https://github.com/Tschipp/CarryOn/blob/1.19-multiloader/Common/src/main/java/tschipp/carryon/common/carry/PickupHandler.java#L101-L103
but then only here the block is removed: https://github.com/Tschipp/CarryOn/blob/1.19-multiloader/Common/src/main/java/tschipp/carryon/common/carry/PickupHandler.java#L121-L122

**Comment by desht** [comment]
@Tschipp I realise I mentioned a Forge method earlier, but we're talking about Fabric in this case.  As I understand, it's the PickupCallback which is responsible for firing the event, right?

Looking here:
https://github.com/Tschipp/CarryOn/blob/1.19-multiloader/Fabric/src/main/java/tschipp/carryon/events/CommonEvents.java#L45
you pass a null callback, so no event is fired, and the block is removed without question. Which explains why FTB Chunks can't do any protection on Fabric.

Fabric API does provide a `PlayerBlockBreakEvents` class, which you should be able to use to fire a Fabric event for this. Doing that should allow protection mods like this one to work correctly.

**Comment by Tschipp** [comment]
I see, sorry I thought we were talking about forge. Yes, I'll add this.

**Comment by desht** [comment]
Block place events in Fabric a bit of a long sranding topic :)  See https://github.com/FabricMC/fabric/pull/2601

Architectury works around it by mixing in to `BlockItem#placeBlock()`, which is far from ideal but works in most common cases.  See https://github.com/architectury/architectury-api/blob/1.19.2/fabric/src/main/java/dev/architectury/mixin/fabric/MixinBlockItem.java

If you go through Forge's code for handling block place events, you quickly discover that their implementation is complex to say the least!

**Comment by Tschipp** [comment]
Alright great thanks, I've implemented soft compat for architectury placement.
