### ISSUE TITLE
[Bug]: Building wands ignore FTB Chunks protection in Fabric

### ISSUE THREAD

**Issue by Scionoftruth** [FTBTeam/FTB-Mods-Issues#849]
### Mod

FTB Chunks (Fabric)

### Mod version

ftb-chunks-fabric-1902.3.22-build.271.jar

### Forge / Fabric version

1.19.2 0.14.21

### Modpack & version

StaTech - v1.0.4

### What issue are you having?

In this and older versions, Building Wands can ignore claimed chunks. I have tested on a few different packs and versions, but the same issue holds true.

### Steps to reproduce

Have someone else claim a chunk
Go into the chunk and use building wand

**Comment by desht** [comment]
Not a bug in FTB Chunks.  Assuming you're referring to https://www.curseforge.com/minecraft/mc-mods/building-wands, I've checked its source code and confirmed that it's setting blocks in the world without firing any event.  Therefore FTB Chunks (or indeed any protection mod) has no way of knowing that blocks are being changed.

Please speak to the author of Building Wands about this.
