### ISSUE TITLE
[Bug]: Players cannot accept invites to teams, instead get an error message

### ISSUE THREAD

**Issue by Yokiie** [FTBTeam/FTB-Mods-Issues#850]
### Mod

FTB Teams

### Mod version

ftb-teams-forge-2001.1.2

### Forge / Fabric version

Forge 47.0.19

### Modpack & version

N/A

### What issue are you having?

When someone in my self-hosted (the server runs on a Windows Server virtual machine if that matters) gets invited to a team using the FTB Teams mod, they see the "Accept/Deny" prompt in chat, if they click on "Accept", the following error message displays :
![javaw_m4ePzBMpbi](https://github.com/FTBTeam/FTB-Mods-Issues/assets/22001430/37413fc7-2974-41ef-867d-fc462ccefc55)

If they click on "Decline", a different error message displays : 
![javaw_0ET1YY5Ww4](https://github.com/FTBTeam/FTB-Mods-Issues/assets/22001430/23ec6080-7ddd-442c-8aa6-562e0a510ea8)

The error seems connected with with the Team's unique ID because if i try to disband the team :
![javaw_scT8WPfFsP](https://github.com/FTBTeam/FTB-Mods-Issues/assets/22001430/70e70963-f9f5-4273-b6cc-28d6c60f091d)

I get the same error message (hovering the mouse over the error displays "No Value present") :
![javaw_rXyAOZ8sGp](https://github.com/FTBTeam/FTB-Mods-Issues/assets/22001430/a8f917c8-5648-4779-9e4e-979c33033bbf)

The logs on the server show nothing related to that error. The only logs I can see are on the client side, but they say the same things as my previous screenshots.
![notepad_uTBrhzYKQ6](https://github.com/FTBTeam/FTB-Mods-Issues/assets/22001430/786fadd0-febf-4ef8-94e3-f86c0af98cf9)

Both of us tried to disband & create teams ourselves several t imes to invite the other, and in both cases, my friend got the error trying to join my team, and I got the error trying to join his team. So I believe it's not just tied to one person and would happen to everyone.

If I try to use the text command to accept the invitation with the Team's ID :
![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/22001430/817e2e2b-f0eb-4f19-ab1a-64559eb390ac)
I get the same error :
![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/22001430/4d96ceb6-f3eb-42b2-822a-028d4efd7b50)

The only way that works is if I use the username of the person who invited me instead of the Team's ID :
![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/22001430/169d055a-3b05-4fdb-9446-2f4a091392f7)
Then it works correctly :
![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/22001430/c28d60e1-0089-48db-bd77-111cd09928af)

### Steps to reproduce

1. Create a new team in FTB Team
2. Use the "Invite player" button on the GUI of the team menu
3. Have the other player accept or decline by clicking the invite message in chat
4. The error message should appear if you accept or decline.
5.  If the player types the command `/ftbteams party join <TeamID>`, they will get the same error message than if they clicked during step 3. 
6. If the player types the command `/ftbteams party join <UsernameWhoInvitedThem>` this time it will work and they'll be able to join the team without an error message.

### Anything else to note?

Here is a list of all the mods that are installed on the server and/or me and my friend's client. (We both have identical modded Forge launchers with the same mod versions)
![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/22001430/9fddb772-87c7-4904-a515-2ed9909fe6e3)

**Comment by desht** [comment]
Confirmed, there is an issue right now with joining a team by the party team name.  Will fix this for next release, but as  short-term workaround, the invite player should be able to join the team by typing `/ftbteams party join <player>`, where player is the owner of the party.

(Basically looking up teams by party name is currently broken, but parties can be looked up by the owner name)

**Comment by desht** [comment]
Fixed in 2001.1.3 release
