### ISSUE TITLE
Endermen can still grief claimed chunks [Bug]: 

### ISSUE THREAD

**Issue by SoulDusk** [FTBTeam/FTB-Mods-Issues#856]
### Mod

FTB Teams

### Mod version

ftb-teams-forge-2001.1.3

### Forge / Fabric version

47.0.35

### Modpack & version

All The Mods 9

### What issue are you having?

Even though "allow mob griefing actions" is set to false, endermen are still picking up and placing blocks inside my claimed chunks

### Steps to reproduce

1. claim chunks
2. spawn endermen
3. set mentioned setting to false
4. regardless, they still grief

**Comment by desht** [comment]
Confirmed, will be fixed in next release.

**Comment by desht** [comment]
Fixed in current Chunks release
