### ISSUE TITLE
[Bug]: Client Crash on Clicking JEI Quest Task

### ISSUE THREAD

**Issue by StormCountTwo** [FTBTeam/FTB-Mods-Issues#860]
### Mod

FTB Quests

### Mod version

ftb-quests-forge-1902.4.17-build.240.jar

### Forge / Fabric version

1.19.2 43.2.8

### Modpack & version

Cottage Witch-1.15.3fix

### What issue are you having?

Whenever I click the text in JEI that would take you to the quest page, it would crash. E.g. here upon clicking on either of the Kill quests it would crash the client (server still remains up)
![image-3](https://github.com/FTBTeam/FTB-Mods-Issues/assets/69146861/31cd0db8-1eb5-4ca4-bf61-b96b0df7957b)

### Crashlogs

https://pastebin.com/kZTWfuxq

### Steps to reproduce

1. Search for recipe of item which is rewarded in a quest
2. Go to JEI page where it indicates what quest rewards it
3. Click on the text of the task of the quest
4. Crash

**Comment by desht** [comment]
Confirmed, will be fixed in next release.

**Comment by desht** [comment]
Fixed in 1902.4.18
