### ISSUE TITLE
[Bug]: ftb chunks crashes 1.20

### ISSUE THREAD

**Issue by redgoblin88** [FTBTeam/FTB-Mods-Issues#861]
### Mod

FTB Chunks

### Mod version

ftb-chunks-forge-2001.1.2

### Forge / Fabric version

minecraft:1.20.1 forge:47.0.45

### What issue are you having?

upon claiming a large area of chunks, to help protect against "creeper accidents" i got a random crash

looking at the crashlog it seems that an endermen in a cave decided to grab some block, but this "mob griefing" caused the crash

### Crashlogs

https://paste.feed-the-beast.com/view/080fa992

### Steps to reproduce

have FTB Chunks installed for 1.20 (version for both provided in this report)

claim a large area, ensiring "enable mob griefing" is set to false, so in theory creepers and endermen CANT grief

upon a mob griefing, you should crash (in my case it was RNG with an endermen picking up a block

### Anything else to note?

i have browsed other reported issues, and though this one seems to be similar, from the wording and description, this user had endermen greifing their claimed chunk without crashing, whereas if endermen grief with the version i provided, you crash 

https://github.com/FTBTeam/FTB-Mods-Issues/issues/856

**Comment by Meepin** [comment]
I am experiencing the same issue with 1.20.1 version 2001.1.2, not sure if it is the same issue because the game is crashing before full world load

**Comment by desht** [comment]
This is actually fixed in dev already, and a new release will be out pretty soon.

In the meantime you can avoid the crash by setting "Allow Mob Griefing Actions" to true in your team settings. Enderman will be able to steal block, but better than a crash...

**Comment by desht** [comment]
Fixed in current Chunks release
