### ISSUE TITLE
[Bug]: Potions Broken

### ISSUE THREAD

**Issue by SubAtomicCreeper** [FTBTeam/FTB-Mods-Issues#863]
### Mod

unsure

### Mod version

1.20

### Forge / Fabric version

1.20

### Modpack & version

atm9 1.20

### What issue are you having?

Using redstone to increase potion duration removes duration all together rendering the potion useless

### Steps to reproduce

Just add redstone to fire res potion

### Anything else to note?

havent tried other potions except splash fire res and it was happening there aswel

**Comment by MichaelHillcox** [comment]
Please use https://github.com/ftbteam/ftb-modpack-issues
