### ISSUE TITLE
[Bug]: Incompatible with Minecraft 1.20.1

### ISSUE THREAD

**Issue by conetopia** [FTBTeam/FTB-Mods-Issues#869]
### Mod

FTB Quests (Forge)

### Mod version

N/A

### Forge / Fabric version

N/a

### Modpack & version

DarkRpg 7.0.8

### What issue are you having?

Wanted to add FTB Library , teams, and  quests.
FTB Quests is outdated 1.19.2, and won't load with everything else on the 1.20.1 server.

### Steps to reproduce

Install Dark RPG
Then add 3 FTB mods to folder.

**Comment by MichaelHillcox** [comment]
We're aware, it's been worked on.
