### ISSUE TITLE
[Feature Request]: ftb chunks & luckyperms

### ISSUE THREAD

**Issue by Lezers** [FTBTeam/FTB-Mods-Issues#870]
### Mod

ftb chunks

### Description

Is there a way to add more chunks for players using luckyperm permissions?

**Comment by desht** [comment]
The latest FTB Chunks release (1902.3.22) supports luckperms, as long as FTB Ranks is *not* installed.  The permission nodes used are identical to what you would use with FTB Ranks -  `ftbchunks.max_claimed` for max claims, and `ftbchunks.max_force_loaded` for max force loaded chunks.

**Comment by mmouradev** [comment]
how can i change the chunk number if luckperms only accepts boolean?

**Comment by desht** [comment]
What makes you think that luckperms only accepts boolean permission nodes?
