### ISSUE TITLE
[Feature Request]: ftb chunks & luckperms and no_wilderness per world for 1.18.x

### ISSUE THREAD

**Issue by Lezers** [FTBTeam/FTB-Mods-Issues#871]
### Mod

FTB Chunks

### Description

Could you update the mod from version 1.18 by adding support for luckyperms and kjs, so that it has "no_wilderness" configurable per world?

If not, that's fine, thank you.

**Comment by desht** [comment]
Possibly at some point, but feature support for 1.18 mods is very low priority right now, sorry.  1.18 is really in fixes-only mode these days.

**Comment by Lezers** [comment]
if you can consider at least "no_wilderness" per world in 1.18 it would be of great help, I really need it
