### ISSUE TITLE
[Bug]: Server Crash on Enderman taking a block

### ISSUE THREAD

**Issue by manmaed** [FTBTeam/FTB-Mods-Issues#873]
### Mod

Chunks or Teams

### Mod version

ftb-chunks-forge-2001.1.2

### Forge / Fabric version

1.20.1-forge-47.1.0

### Modpack & version

FTB Unstable 1.20: Forge - 1.3.0

### What issue are you having?

erver crash caused by enderman trying to take block from a protected region

### Crashlogs

https://pastebin.com/fCFBbAKR

### Steps to reproduce

  1. Protect a chunk (with FTBTeams)
   2. Allow Enderman to attempt the theft of your protected block (while "ftbchunks:allow_mob_griefing": 0b for protected regions)
   3. Server Crashes with: Exception caught during firing event: Attempted to call Event#setCanceled() on a non-cancelable event of type: net.minecraftforge.event.entity.EntityMobGriefingEvent

### Anything else to note?

https://github.com/FTBTeam/FTB-Modpack-Issues/issues/3656

teams was updated: ftb-teams-forge-2001.1.2.jar` to `ftb-teams-forge-2001.1.4.jar`
forge was also updated 47.0.34 to 47.1.0

**Comment by desht** [comment]
Already fixed in FTB Chunks 2001.1.3
