### ISSUE TITLE
[Bug]: Crash when pressing 'e' or 'esc' in quest window

### ISSUE THREAD

**Issue by vedrit** [FTBTeam/FTB-Mods-Issues#874]
### Mod

FTB Quests

### Mod version

ftb-quests-forge-1902.4.16-build.235

### Forge / Fabric version

Forge 43.2.8 for 1.19.2

### Modpack & version

Create on a Potato Ultimate 1.19.2-4.10

### What issue are you having?

When in the quest window, pressing 'e' will often result in a client crash. This also occasionally happens when pressing 'esc'
Only seems to happen if the inventory was first opened.

### Crashlogs

Pastebin: https://pastebin.com/JsZewawM

### Steps to reproduce

1. Open inventory
2. Open quests
3. Press the 'e' key or 'esc' key

**Comment by desht** [comment]
```
java.lang.ClassCastException: class net.minecraft.world.inventory.InventoryMenu cannot be cast to class tfar.craftingstation.CraftingStationContainer (net.minecraft.world.inventory.InventoryMenu is in module minecraft@1.19.2 of loader 'TRANSFORMER' @5e562067; tfar.craftingstation.CraftingStationContainer is in module craftingstation@1.19.2-6.0.1 of loader 'TRANSFORMER' @5e562067)
	at tfar.craftingstation.client.TabButton.m_6303_(TabButton.java:30) ~[craftingstation-1.19.2-6.0.1.jar%23277!/:1.19.2-6.0.1] {re:classloading}
```

Not a FTB Quests problem, in any way.  Complain to the author of the Crafting Station mod.
