### ISSUE TITLE
[Bug]: Client Side Crashing

### ISSUE THREAD

**Issue by UTCrown** [FTBTeam/FTB-Mods-Issues#875]
### Mod

FTB Chunks

**Comment by desht** [comment]
Please don't post huge stacktraces directly into an issue!  Paste sites like https://paste.feed-the-beast.com/ exist for a reason, please use them.

**Comment by desht** [comment]
Anyway, the problem is Optifine, which for some bizarre reason is causing a Forge mob griefing event to be fired _on the client_.

I can work around this in the next release of FTB Chunks, but the best fix is to uninstall Optifine, and use better mods like Rubidium/Oculus.

**Comment by desht** [comment]
Fixed in 2001.1.4 release
https://www.curseforge.com/minecraft/mc-mods/ftb-chunks-forge/files/4654814
