### ISSUE TITLE
[Bug]: crash wheel scrolling/zooming on ftb quests

### ISSUE THREAD

**Issue by Abalieno** [FTBTeam/FTB-Mods-Issues#878]
### Mod

FTB Quests

### Mod version

ftb-quests-fabric-1902.5.0-build.248

### Forge / Fabric version

1.19.2 fabric 14.21

### Modpack & version

mine

### What issue are you having?

Random crash using the scroll wheel on a quest page.

### Crashlogs

https://paste.feed-the-beast.com/view/71ee9a38

### Steps to reproduce

I can reproduce it this way:

open questbook, use scrollwheel > it zooms in/out normally, no problem
click/open a quest, press ESC to exit, zoom out > crash

The quest opened doesn't seem to matter.

**Comment by Abalieno** [comment]
Seems to be doing it only on a certain page, it's weird...

**Comment by Abalieno** [comment]
Since this can could be hard to track, you can test directly this version:
https://legacy.curseforge.com/minecraft/modpacks/gregorian-nightmares/files/4651787

Only certain quests in a specific area seem to cause the crash:

![yukyiki](https://github.com/FTBTeam/FTB-Mods-Issues/assets/4656436/8b936bf9-0374-4297-abe3-dba281d260ea)

The quests themselves are fine, but if I open one of those, press ESC to go back at the quest page, then zoom in the page, and then zoom out. As soon I zoom out the client crashes immediately.

**Comment by Abalieno** [comment]
So.

Rolling back to ftb-quests-fabric-1902.4.18-build.244 works perfectly.

I thought I was stuck this side of kubejs 6.1, but apparently Max patch works well enough I can use ftb quests old version without the built-in support of xmod-compat. That's enough for me. I'm didn't especially like the waiting game of the past few days :)

You should fix your stuff, tho.

**Comment by desht** [comment]
Fixed in 1902.5.1
