### ISSUE TITLE
[Bug]: FPS lag spikes every 1 minute with FTB Chunks

### ISSUE THREAD

**Issue by csdivad** [FTBTeam/FTB-Mods-Issues#88]
### Mod

FTB Chunks

### Mod version

ftb-chunks-forge-1605.3.2-build.65

### Forge / Fabric version

1.16.5 36.2.8

### What issue are you having?

Hello,

I have a weird FPS lag spike exactly every 1 minute with FTB Chunks.
The spikes are ~400-500ms on my machine.
It looks like the culprit is around: dev.ftb.mods.ftbchunks.client.map.MapRegionData.write

JProfiler pic: [https://imgur.com/a/5ntKKxg](https://imgur.com/a/5ntKKxg)
Overall profiling time was 3869 ms. This timeframe contained one such lag spike.

Logs: [latest](https://pste.ch/kebedipuxu.md), [debug](https://pste.ch/ajevitebup.md)
(there are no log entries made during the spikes)

### Steps to reproduce

1. Add FTB Chunks to the modpack
2. Walk around for 1 minute

**Comment by algorythm** [comment]
I'm experiencing this too. I noticed while playing [Enigmatica 6](https://github.com/NillerMedDild/Enigmatica6). I had this issue on the latest version, so I started testing different versions, and concluded, that this was introduced in v0.5.12 of the modpack. According to their [changelog](https://github.com/NillerMedDild/Enigmatica6/blob/master/changelogs/changelog_mods_0.5.12.md), FTB Chunks was updated from [ftb-chunks-forge-1605.3.1-build.41.jar](https://www.curseforge.com/minecraft/mc-mods/ftb-chunks-forge/files/3409573) to [ftb-chunks-forge-1605.3.2-build.57.jar](https://www.curseforge.com/minecraft/mc-mods/ftb-chunks-forge/files/3466965).

**Comment by MichaelHillcox** [comment]
@MaxNeedsSnacks @LatvianModder any insight into this?

**Comment by LatvianModder** [comment]
FPS issues have been solved a while back, currently latest version is ftb-chunks:1605.3.2-build.79
