### ISSUE TITLE
[Bug]: NPE at ViewQuestPanel.java:782

### ISSUE THREAD

**Issue by leagris** [FTBTeam/FTB-Mods-Issues#881]
### Mod

FTB-Quest

### Mod version

ftb-quests-forge:1902.4.18-build.244

### Forge / Fabric version

1.19.2 43.2.14

### Modpack & version

Allthemods 8-1.0.22

### What issue are you having?

Right-clicked on a quest icon and it crashed with this:

### Crashlogs

https://paste.feed-the-beast.com/view/cdd5fc3e

### Steps to reproduce

Cannot reproduce. Right-clicked bookmarked de-bookmarked the Productive Bees quests glowing bee step icon. Sometimes a blank haze covers the screen like an empty bugged window, but no crash.

Sound like a race condition to be traced with the crash log I pasted.

**Comment by desht** [comment]
Interesting. That _should_ be an impossible crash (rendering code called before widgets are created), but apparently not.  I'll get a fix together for it.

**Comment by desht** [comment]
Fixed in 1902.5.3
