### ISSUE TITLE
[Feature Request]: Be able to switch which team mod is connected 

### ISSUE THREAD

**Issue by WitherTM** [FTBTeam/FTB-Mods-Issues#882]
### Mod

FTB Quests/Chunks?

### Description

What I would like added is the ability (probably somwhere within the configs) to switch which team mod, like FTB Teams, Open Parties and Claims or even the Lightman's Currency teams, is connected to the progress of the quests/to the claimed chunks

### Describe the solution you'd like

Have a option or a config to pick which mod handles the quest/ chunk teams

### Describe alternatives you've considered

Just having FTB Teams is possible, but if you play with a lot of mods in a big modpack and a few different teams, it would be really nice to have this option

**Comment by WitherTM** [comment]
I added a question mark to FTB Chunks since that one is not that big of an issue for me

**Comment by desht** [comment]
Sorry, but this is not on our roadmap.  FTB Teams is too integral to FTB Quests and FTB Chunks.
