### ISSUE TITLE
[Feature Request]: Add right-click bypass for blocks

### ISSUE THREAD

**Issue by manmaed** [FTBTeam/FTB-Mods-Issues#883]
### Mod

FTB Chunks

### Description

Add a way for a block to be able to be right-clicked on when in a claimed chunk, ex. to be able to right-click on a grave form Flanks Grave mod

Maybe via a config or and api call to chunks?

**Comment by desht** [comment]
Already possible: add the block to the `ftbchunks:interact_whitelist` block tag to always allow right-clicking.

There's also `ftbchunks:edit_whitelist` to always allow blocks to be placed or broken.

**Comment by desht** [comment]
What's the block ID or tag for Flanks grave block?  I could add it to the default values for the tag for the next 1.19/1.20 releases.

**Comment by manmaed** [comment]
Ok flanks is going to do it his side :)

**Comment by Flanks255** [comment]
I was at work so i couldn't see if the tag already existed, glad it does 👍tagged the graves in 1.0.5
