### ISSUE TITLE
[Bug]: MC-1.19.2 Wrong method called for gamestages integration

### ISSUE THREAD

**Issue by winnetrie83** [FTBTeam/FTB-Mods-Issues#884]
### Mod

FTB Chunks

### Mod version

ftb-chunks-forge-1902.3.22-build.271

### Forge / Fabric version

Forge 43.2.21

### What issue are you having?

I have setup a testing environment with minimal required mods.
Wich is basically : Lobby, FTBChunks (and dependencies), Gamestages
When teleporting to another dimension with command: "/lobby, /spawn", the game crashes due to a class references that is non-existent.
The same happens when teleporting to the nether via ingame portal (no command)
I checked within ftbchunks and indeed the method "syncStages" does not exists. It should be "sync"
I'm very sure it is an issue between FTBchunks and Gamagestages, because the issue persists even without Lobby.
By removing/disabling FTBChunks or Gamestages the issue is not present.

### Crashlogs

https://pastebin.com/veq5tbiG

### Steps to reproduce

-Have FTBChunks + Gamestages installed ( eventually Lobby)
-Start game
-Teleport to another dimension (for example netherportal)
-OR use Commands when Lobby is installed

### Anything else to note?

I have also reported this at Gamestages dev: https://github.com/Darkhax-Minecraft/Game-Stages/issues/81

**Comment by desht** [comment]
Fixed in latest chunks release
