### ISSUE TITLE
[Bug]: Crash when placing enchanted QuarryPlus in claimed/loaded chunk

### ISSUE THREAD

**Issue by trevorjd** [FTBTeam/FTB-Mods-Issues#886]
### Mod

FTB Chunks

### Mod version

ftb-chunks-forge-2001.1.4.jar

### Forge / Fabric version

1.20.1-47.1.28

### Modpack & version

FTB Unstable 1.20 v1.4.0 (updated chunks due to enderman crash)

### What issue are you having?

I got a QuarryPlus quarry running and then claimed and chunkloaded the chunk it's in.
Just now, I broke the quarry, upgraded it to Efficiency IV.
I placed a QuarryPlus marker, expanded it to max size in all 6 directions, then re-placed the quarry.
Game crashed immediately with the attached error.

Reloaded the game, found the quarry and marker in world and I still have an Eff4 quarry in my inventory.  Foolishly, I placed the duped quarry in the same chunk and it immediately crashed with the same error.  

I placed the duped (I have 2 now!) quarry in a different chunk but within the area of the active quarry.  Crashed a few seconds later vs immediately.

Reloaded... I have 3 now.  Placed a quarry in a different chunk outside the area of the active quarry and it crashed pretty much immediately.  Have verified that it's the same crash each time.

fake_players: allow
force_load_mode: "always"
others are default

gamerule mobgriefing = false

AdditionalEnchantedMiner-1.20.1-1201.0.9-SNAPSHOT.jar

### Crashlogs

https://pastebin.com/bQyDP7Vp

### Steps to reproduce

Have covered this above.

**Comment by desht** [comment]
You're using a broken version of Additional Enchanted Miner.  

`java.lang.NoClassDefFoundError: dev/ftb/mods/ftbchunks/data/FTBChunksAPI` is correct - there is indeed no such class, so I don't know where you got this mod from, or how it even compiled, but it's definitely broken.

I just downloaded Additional Enchanted Miner from CF, and checked what it's doing.  It refers to the correct FTBChunksAPI class, at `dev.ftb.mods.ftbchunks.api.FTBChunksAPI`.

**Comment by trevorjd** [comment]
Thanks for the snappy response! Seems that my launcher didn't update mods when I told it to update.

**Comment by desht** [comment]
Yeah on checking again, the version of AEM you had was one release out of date.  Latest AEM works fine with Chunks.
