### ISSUE TITLE
[Bug]: forceloaded chunks are not loaded

### ISSUE THREAD

**Issue by techiend** [FTBTeam/FTB-Mods-Issues#887]
### Mod

FTB Chunks (Forge)

### Mod version

ftb-chunks-forge-2001.1.4

### Forge / Fabric version

Forge 1.20.1 - 47.1.3

### Modpack & version

TheAVD Forge - 1.0.4

### What issue are you having?

I have a hosted server with the modpack "TheAVD Forge" (personal modpack). 

I forceload a 3x3 grid yesterday and keep a furnace working with kelp on it and logout, when I log in today the furnace still burning

![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/19810065/af7e5b56-abf1-4709-a32d-5890343d94fb)

In other test, I forceload a 2x2 grid with a villager breeder with some babies on it and go far away of it, some hours later I go back and the villagers still being babies

I dont know if I need to do something to keep the chunks forceload or what.

The client and the server config are default config, we dont change any config mods.

### Steps to reproduce

1. Download the "TheAVD Force" modpack
2. Login on the server
3. Forceload chunks
4. Put some kelp in a furnace with coal
5. Logout and login some hours later
6. The kelp still undone

**Comment by desht** [comment]
Have you verified that offline chunk loading is in enabled in the server config?  Ensure that "Force Load Mode" is either set to Always, or if set to Default, that you have FTB Ranks installed with the `ftbchunks.chunk_load_offline` permission enabled for a rank you're in.

**Comment by techiend** [comment]
Thanks, in this case was the value set to default and the server doesn't have FTB Ranks. Set to "always" works
