### ISSUE TITLE
[Bug]: FTB Quests no longer shows REI recipe, only "valid items for x"

### ISSUE THREAD

**Issue by IanMoroney** [FTBTeam/FTB-Mods-Issues#888]
### Mod

FTB Quests

### Mod version

ftb-quests-forge-1902.5.1-build.250

### Forge / Fabric version

1.19.2-forge-43.2.10

### Modpack & version

UniversIO-R-5.0

### What issue are you having?

When looking at a quest in the quest book, and clicking on an item to view its recipe, instead of showing you the recipe in REI, it now shows you "valid items for <name of item>".
It used to show you the recipe for the item in the previous version of the pack, but not anymore.

Same as this issue here:
https://www.reddit.com/r/feedthebeast/comments/156jws3/ftb_quests_and_jei_how_do_i_make_it_so_i_can/

### Steps to reproduce

1. Install UniversIO version 5.0
2. Open the quest book
3. Click on a quest that requires you to have an item
4. Click on the image of the item to view the recipe
5. You are presented with a "valid items for <name of item>" dialog instead of linking to JEI/REI to see the item recipe.

**Comment by desht** [comment]
Do you have FTB XMod Compat installed?

**Comment by IanMoroney** [comment]
Can confirm adding this makes it work.
I've also just seen the updated warning on the mod page indicating the compat requirement 👍 
Thank you!
