### ISSUE TITLE
[Bug]: Client Crashes when atempting to open map on server, no issues in singleplayer

### ISSUE THREAD

**Issue by asgsdfgrthtr** [FTBTeam/FTB-Mods-Issues#89]
### Mod

FTB Chunks

### Mod version

ftb-chunks-forge-1605.3.2-build.67

### Forge / Fabric version

1.16.5-36.2.6

### Modpack & version

ATM6 v1.8.6

### What issue are you having?

it seems to have happened when i was loading in "chunks" on the minimap/map, i was in spectator fastest speed flying around and it just crashed and now everytime i try load the mao  with "M" it crashes. Minimap doesnt show up either. Everything works in single player no problems, but when i connect to server and press "M" my instance crashes minimap not showing either. server stays up and in server logs it just shows as if i "disconnected" I tried to remove the cache in the "local\ftbchunks\" folder and same issue. I havent yet tried to reinstall my client but thats my next attempt. version on server and client was 65 so updated to 67 to try fix it to no avail same problem with both versions.

### Crashlogs

https://pste.ch/cikinarexa.rb

https://pste.ch/alunepagox.rb

https://pste.ch/umagiliyuy.rb

### Steps to reproduce

literally try to open the map and crash, also "CTRL+M" doesnt do anything the minimap doesnt toggle on or off, but it doesnt crash when i try. Only when oppening map does it crash

### Anything else to note?

hope you guys can help me out, it would be nice to play again, ty for hard work

**Comment by asgsdfgrthtr** [comment]
changed to txt format but this is the file that was causing the issue, server file. thanks for the pointer that tip helped me get back up :)

[c7ba1211-78f1-4f69-84e9-b05cb1c3fd95.snbt.txt](https://github.com/FTBTeam/FTB-Mods-Issues/files/7370678/c7ba1211-78f1-4f69-84e9-b05cb1c3fd95.snbt.txt)

**Comment by Brycey92** [comment]
I also have this issue

**Comment by Hi-ImKyle** [comment]
Still seems to persist on 1.18

**Comment by RCPhysics** [comment]
I'm having this issue with the FTB Presents Direwolf20 1.18.

**Comment by MichaelHillcox** [comment]
> I'm having this issue with the FTB Presents Direwolf20 1.18.

Can you attach a crash log please

**Comment by Raidobw2** [comment]
I'll close this issue to avoid redundancy since the crash mentioned by the OP is the same as #70, so we'll only keep the other one for tracking
