### ISSUE TITLE
[Feature Request]: Add ability to search questbook when not in edit mode

### ISSUE THREAD

**Issue by lupusagax** [FTBTeam/FTB-Mods-Issues#892]
### Mod

FTB Quests

### Description

The mod currently supports searching via ctrl-f when in edit mode, but this does not seem to work outside of it.

 I have found myself repeatedly wanting the ability to search the quests for large modpacks with a significant number of quests to find one that has some extra information in its description that I cannot quite recall.

### Describe the solution you'd like

Expose the same search that is already present in edit mode, with modification to hide results from currently hidden quests.

**Comment by desht** [comment]
Agreed, Ctrl-F should work outside edit mode.

**Comment by desht** [comment]
Fixed in 1902.5.2 release
