### ISSUE TITLE
[Crash]:

### ISSUE THREAD

**Issue by Phinies2** [FTBTeam/FTB-Mods-Issues#893]
### Mod

FTB XMod Compat

### Mod version

ftb-xmod-compat-fabric-1.2.0

### Forge / Fabric version

1.19.2 Fabric 0.14.21

### What issue are you having?

When i open/create a world i get this crash. It happens at the last part of loading.

### Crashlogs

https://hastebin.com/share/usugaveqir.yaml

### Steps to reproduce

dont know how to reproduce it

**Comment by desht** [comment]
Fixed in FTB XMod Compat 1.2.1
