### ISSUE TITLE
[Bug]: Game crashes when right then left clicking quest

### ISSUE THREAD

**Issue by NitroNinja79** [FTBTeam/FTB-Mods-Issues#894]
### Mod

FTB Quests

### Mod version

ftb-quests-forge-1902.5.2-build.256.jar

### Forge / Fabric version

1.19.2 43.2.21

### What issue are you having?

The game crashes when I right click then left click a quest for some reason.

### Crashlogs

[crash-2023-07-27_19.39.20-client.txt](https://github.com/FTBTeam/FTB-Mods-Issues/files/12181814/crash-2023-07-27_19.39.20-client.txt)

### Steps to reproduce

Right click then left click a quest (this was done on a game stage quest, however may not matter)

**Comment by desht** [comment]
Fixed in 1902.5.3 release
