### ISSUE TITLE
[Feature Request]: FTBRanks API

### ISSUE THREAD

**Issue by Artucuno** [FTBTeam/FTB-Mods-Issues#895]
### Mod

FTBRanks

### Description

API for FTBRanks that allows for checking user permissions & adding/removing ranks.

**Comment by Artucuno** [comment]
https://github.com/FTBTeam/FTB-Ranks/blob/main/forge/src/main/java/dev/ftb/mods/ftbranks/forge/PermissionAPIWrapper.java

**Comment by desht** [comment]
Creating/removing/modifying ranks is already in the mod API, in 1.19.2, and in a more cleaned-up documented form in 1.20.1.

E.g.  (1.19.2):
```java
Rank rank = FTBRanksAPI.INSTANCE.getManager().createRank("new_rank");
rank.addPermission("some.perm.node", NumberPermissionValue.of(10));
rank.add(somePlayer.getGameProfile());
```

Very similar in 1.20.1, but see `FTBRanksAPI` for more comprehensive Javadocs.

What exactly do you mean by "checking user permissions" ?
