### ISSUE TITLE
[Bug]: Rewards don't show up in the JEI as a "recipe"

### ISSUE THREAD

**Issue by PinkLasagna03** [FTBTeam/FTB-Mods-Issues#896]
### Mod

FTB Quests

### Mod version

ftb-quests-forge-1902.5.3-build.258

### Forge / Fabric version

1.19.2 Forge 43.2.21

### What issue are you having?

When using JEI to check the recipes of certain items, the FTB Quests tab doesn't appear when one of those items are the rewards of a certain quest. I've seen them appear in other modpacks and people telling in other posts here. 

![2023-07-28_19 07 04](https://github.com/FTBTeam/FTB-Mods-Issues/assets/139581723/c937b088-f73a-46cf-9c7c-46762b84bced)
![2023-07-28_19 07 46](https://github.com/FTBTeam/FTB-Mods-Issues/assets/139581723/cee04333-f7df-411c-81f0-5f59ccd65491)
![2023-07-28_19 07 49](https://github.com/FTBTeam/FTB-Mods-Issues/assets/139581723/8c46632f-a93b-44a0-9a42-f01fb2d6abf4)

### Steps to reproduce

1. Installed FTB Quests (and its dependecies) + JEI
2. started minecraft, made a simple linear quest
3. Checking in the JEI the items that I've had as rewards
4. the FTB quests tab didn't show up

**Comment by MichaelHillcox** [comment]
Do you have FTB XMod Compat?

**Comment by PinkLasagna03** [comment]
> Do you have FTB XMod Compat?

I do now, but now it only shows the "recipe" for the quests that aren't locked behind any dependencies. 

![2023-07-28_20 33 45](https://github.com/FTBTeam/FTB-Mods-Issues/assets/139581723/7caea99d-4234-43d2-8b6a-880b3df33343)
![2023-07-28_20 33 50](https://github.com/FTBTeam/FTB-Mods-Issues/assets/139581723/d66b5d4c-1a52-46ec-ac70-6cb74fde6ed7)
![2023-07-28_20 33 53](https://github.com/FTBTeam/FTB-Mods-Issues/assets/139581723/da3cf0f5-0702-4fa4-97c4-b6399272ac98)
![2023-07-28_20 34 01](https://github.com/FTBTeam/FTB-Mods-Issues/assets/139581723/bfc87bee-e18e-4d09-b457-9fc5fada59a0)
![2023-07-28_20 34 02](https://github.com/FTBTeam/FTB-Mods-Issues/assets/139581723/34ce0f38-3161-41ce-8dcc-4d5e1d387d41)
![2023-07-28_20 34 05](https://github.com/FTBTeam/FTB-Mods-Issues/assets/139581723/68339694-951c-4c66-9eb2-b3e525b2a33f)

**Comment by desht** [comment]
That's working as intended.  If a quest is locked behind dependencies, it shouldn't really be visible to the player yet, and that includes seeing the rewards for it via JEI.
