### ISSUE TITLE
[Bug]: Moving quest images behaves strangely

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-Mods-Issues#897]
### Mod

FTB Quests

### Mod version

ftb-quests-forge-1902.5.3-build.258

### Forge / Fabric version

Forge 1.19.2 43.2.21

### What issue are you having?

https://github.com/FTBTeam/FTB-Mods-Issues/assets/15698722/ca5fcc19-39fd-42fe-b06c-a72f3a25e93a

### Steps to reproduce

n

**Comment by desht** [comment]
I think a bit more explanation is required here - it's not clear from just the video.  I've tried moving images around in my dev instance and it works as I would expect.

**Comment by aaronhowser1** [comment]
The minimum distance it jumps is massive, rather than for every whole coordinate

**Comment by desht** [comment]
Sorry, missed your response.  I'm guessing the image has been scaled up in this case?  The movement grid snap is scaled by the scaling of the object (quests, quest links, images all the same), so a scaled-up object does have a larger snap grid.

Easy workaround is to hold Shift while moving, which disables the snap grid entirely.  I guess images could always use a non-scaled grid though, so I can probably get that into the next FTBQ release.

**Comment by desht** [comment]
Fixed in latest 1.19/1.20 releases
