### ISSUE TITLE
[Bug]: Strange issue when right-clicking then left-clicking a quest outside of editing mode

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-Mods-Issues#899]
### Mod

FTB Quests

### Mod version

ftb-quests-forge-1902.5.3-build.258

### Forge / Fabric version

Forge 1.19.2 43.2.21

### What issue are you having?

https://github.com/FTBTeam/FTB-Mods-Issues/assets/15698722/7a8c720d-2199-4d05-9342-49270a88823c

### Steps to reproduce

.

**Comment by desht** [comment]
Fixed in 1902.5.4 release
