### ISSUE TITLE
[Bug]: FTBChunk Permissions not working in ranks.snbt

### ISSUE THREAD

**Issue by Airfirewall** [FTBTeam/FTB-Mods-Issues#902]
### Mod

FTBChunks

### Mod version

ftb-chunks-forge-1902.4.1-build.290

### Forge / Fabric version

Forge 43.2.21

### Modpack & version

TNP Limitless 6 1.31.0

### What issue are you having?

I cant get FTBChunks chunk permissions to work, I am pretty sure the permissions are correct but maybe they changed in 1.19.2?
ftbchunks.max_claimed:
ftbchunks.max_force_loaded:

The FTBChunks file in serverconfig is named ftbchunks-world.snbt, is it suppose to be named like that? In other modpacks its just ftbchunks.snbt, I tried deleting it and it recreates it as ftbchunks-world.snbt. In the default config folder it has it as ftbchunks.snbt so not sure what is wrong.

All the other permissions work its just all the ftbchunks.max_claimed: and ftbchunks.max_force_loaded: dont work at all.
pastebin of ranks.snbt file below.

### Crashlogs

https://pastebin.com/LHbL0Urz

### Steps to reproduce

edit ranks.snbt and use /ftbranks reload

also tried restarting server

**Comment by Airfirewall** [comment]
So there is a issue with ftb-chunks-forge-1902.4.1-build.290, reverted back to ftb-chunks-forge-1902.3.22-build.271 and it works fine

**Comment by desht** [comment]
FTB Chunks 1902.4.0 and later also need FTB XMod Compat installed for any cross-mod compat.  Do you have FTB XMod Compat installed?

**Comment by Airfirewall** [comment]
No currently not installed, Ill try it with the mod installed.

**Comment by Airfirewall** [comment]
tried to add the FTB XMod Compat mod but its just breaking other mods. First needed to update kubejs and ftbquest as modpack wouldent even start, didn't even crash just loading in background forever until I ended java process. Looked in log and seen that those needed updating to a minimum version. Now it actually loads but crashes every time. First mod it didn't like was tempad and tried relaunching and then having a issues with the model of a minecraft:pufferfish. 

If I get time ill look into it further but ATM ftb-chunks-forge-1902.3.22-build.271 works without any issues.

**Comment by desht** [comment]
Yeah, there's a fair bit of dependency hell going on unfortunately, mainly related to KubeJS 6.1 changing its API so a lot of mods built against KJS 6.0 will not work.  In your position you're best off sticking with 1902.3.22.
