### ISSUE TITLE
[Bug]: Cannot invoke "dev.ftb.mods.ftbchunks.client.map.MapDimension.getLoadedRegions()" because "this.dimension" is null

### ISSUE THREAD

**Issue by dolphin-cat** [FTBTeam/FTB-Mods-Issues#903]
### Mod

FTB-Chunks

### Mod version

ftb-chunks-forge-1802.3.17-build.265.jar

### Forge / Fabric version

1.18.2 40.2.8

### Modpack & version

CogCraft 

### What issue are you having?

open the map with M and you get the error

### Crashlogs

https://paste.ee/p/FHljM

### Steps to reproduce

open map

**Comment by dolphin-cat** [comment]
pack: https://cdn.discordapp.com/attachments/1121934071237451811/1134710529575886878/CogCraft-3.5.zip

**Comment by dolphin-cat** [comment]
idk why but it works now

**Comment by trimcorn** [comment]
Did you do anithign to make it work? bcs it crashes my game

**Comment by TheFlash787** [comment]
From my experience, this occurs when FTB Chunks is installed client-side, but not server-side.
