### ISSUE TITLE
[Bug]: repeatable quests are not working properly

### ISSUE THREAD

**Issue by yurannado** [FTBTeam/FTB-Mods-Issues#906]
### Mod

FTB quests

### Mod version

ftb-quests-forge-1802.3.14-build.191

### Forge / Fabric version

1.18.2 40.2.10

### What issue are you having?

repeatable quests can't be submitted properly for more than twice if there're more than two rewards when at least one of them are manually-claimed.

### Steps to reproduce

set a repeatable quest,and add two or more rewards, make sure there's one or more manual-claimed rewards.

**Comment by desht** [comment]
I believe this is the same problem as #807 which is fixed in 1.19.  I'll backport that fix to 1.18, hopefully will resolve this problem too.

**Comment by desht** [comment]
Fixed in 1802.3.15
