### ISSUE TITLE
[Bug]: Infinitely Repeatable Quests After 1 Completion

### ISSUE THREAD

**Issue by sharkweekthings** [FTBTeam/FTB-Mods-Issues#907]
### Mod

FTB Quests

### Mod version

ftb-quests-forge-1902.5.3-build.258

### Forge / Fabric version

1.19.2 43.2.21

### Modpack & version

Plastek v1.12+

### What issue are you having?

In my pack I've set up several repeatable quests for simple things (Kill X amount of Mobs, Loot X amount of Chests, etc etc etc). 

Each of these quests are infinitely repeatable after 1 completion.

![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/134178249/32113bad-abfe-4513-97c1-5170e2ea3c42)

For instance, this Kill 1000 mobs quest (reduced to 2 kills for the example) -- once completed, you can just keep accepting the reward infinitely without having to kill 1000 mobs again.  The actual progress for the quest never resets, but the reward does. 

### Crashlogs

N/A

### Steps to reproduce

1. Make a repeatable quest (Mob Kills, Barrel/Chest Loots, Breed Animals, etc)
2. Add a reward
3. Complete repeatable quest
4. Continuously accept the reward an infinite amount of times

**Comment by desht** [comment]
I can't reproduce this. 

* I set up a repeatable quest to kill 2 zombies, with 1 wood plank as a reward.
* Killed 2 zombies, quest completed
* Claimed the plank, the quest reset, including the reward
* Can't claim any more planks until I killed another 2 zombies

**Comment by sharkweekthings** [comment]
Is it possible something with my FTB Quests file itself: 
[for_fun.zip](https://github.com/FTBTeam/FTB-Mods-Issues/files/12334582/for_fun.zip)

Alternatively: 
https://www.curseforge.com/minecraft/modpacks/plastek any version of the pack 1.12 and lower seems to have the problem. In 1.13 I disabled the Repeatable aspect of the quests to prevent further infinite recyling. 

![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/134178249/907076f5-3b05-464a-86a6-05fe6ae86b0e)

![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/134178249/0a9aa2e5-18b2-4e68-a569-b546dde61483)

![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/134178249/02199ba5-974f-4962-9724-fa6919e2ab87)

**Comment by WyFryMU** [comment]
It's not a bug. You're misunderstanding how you setup your quest.
Your quest is a repeatable quest based off the Mob Kills stats. So you will get infinite rewards because the Mob Kill stat never resets because that's just vanilla MC. (I just tested this on v1.12 to find out that info)
What you want is the Kill Entity quest type, not the Stat quest time.

**Comment by desht** [comment]
Yep, repeatable quests don't make sense with minecraft stats, since as @WyFryMU pointed out, they never reset.  So as soon as the quest repeats, it effectively is complete again.

**Comment by sharkweekthings** [comment]
Ahh, that makes a lot of sense. Okay. Thank you for clarification!
