### ISSUE TITLE
[Bug]: FTB Chunks ignoring FTB Ranks chunk claim limit (ftbchunks.max_claimed node)

### ISSUE THREAD

**Issue by WyFryMU** [FTBTeam/FTB-Mods-Issues#908]
### Mod

FTB Chunks

### Mod version

ftb-chunks-fabric-1902.4.1-build.290.jar

### Forge / Fabric version

1.19.2 0.14.22

### Modpack & version

BigChadGuys Plus v3.9.2

### What issue are you having?

After updating FTB Chunks from ftb-chunks-fabric-1902.3.22-build.271.jar to ftb-chunks-fabric-1902.4.1-build.290.jar, no one has the correct FTB Chunks claim limit as specified by various ranks in FTB Ranks. They all have the default 500 claims as set by the FTB Chunks serverconfig.

### Crashlogs

N/A

### Steps to reproduce

1. Using FTB chunks (build 271) and ftbranks, make a rank that has "ftbchunks.max_claimed: 25"
2. Apply that rank to yourself
3. Notice that you have 25 claims now instead of the default 500.
4. Now upgrade ftbchunks to build 290, and load back in
5. Notice that the rank is now ignored and you have the default 500.

### Anything else to note?

All I had to was downgrade from 290 back to 271 and everything worked again, so something is up with chunks.
The FTB rank node I am using is "ftbchunks.max_claimed" (example 'ftbchunks.max_claimed: 25').

**Comment by WyFryMU** [comment]
> Do you have FTB XMod Compat installed?

No, but after installing it and updating Chunks back to build 290. It's all good now. Thanks :)

**Comment by WyFryMU** [comment]
Is there any reason I should have known to add it? FTB Chunks doesnt mention any dependencies, neither does FTB Ranks. You can close this if you're done with it, but I would maybe suggest mentioning FTB Xmod compat somewhere on those mod pages.

**Comment by WyFryMU** [comment]
Ahhhh, gotcha. Thanks for the help and your responses!

**Comment by desht** [comment]
No worries, closing now.  CF page will updated shortly.
