### ISSUE TITLE
[Bug]:  invitation to team

### ISSUE THREAD

**Issue by Lezers** [FTBTeam/FTB-Mods-Issues#911]
### Mod

ftbteams

### Mod version

ftb-teams-forge-1802.2.11-build.107

### Forge / Fabric version

1.18.2 - 40.2.10

### What issue are you having?

after the player executes the command: /ftbteams party invite <player>, the guest player already gains permission on the ftbchunks lands, even before accepting the invitation, even if he declines the invitation, he continues with the permission to modify the lands, the permission continues without the player being on the team, and continues even after being killed or logged out

### Steps to reproduce

login with two accounts simultaneously, with one you create the team and claim the chunk, then send a team request to the other account, in the other account you can already see that you will be able to modify the chunk of the other player even without accepting the request, you can until you refuse the request to join the team, which will still have access to the chunk

**Comment by Lezers** [comment]
when we are going to invite someone, we usually use the tab to complete the player's name, in case there is another player with a similar name and by accident we invite him, he will have access to the chunks forever, being able to find out and change it at some point, causing vulnerability in the security of chunks, wouldn't it be ideal to remove this from all versions?

**Comment by Lezers** [comment]
this is not a made up situation, after all that's how the bug got to me

**Comment by Lezers** [comment]
it wouldn't be a problem if the player refused and could no longer modify it, but after making the mistake of inviting someone by accident, the players are left without the possibility of expelling him from the team, after all the other player did not accept this, so the other player continued with access to the chunks with nothing the player victim could do

**Comment by desht** [comment]
Yeah, that's a fair comment.  I'll take a look.

**Comment by desht** [comment]
I just tested on a 1.18.2 server, and I can't reproduce the problem (and looking at the code, it does indeed check for a team level of "member", not just "invited").

With private team settings, I invited another player.  The other player didn't accept the invitation, but was still unable to break or place any block in my claims, as expected.

**Comment by Lezers** [comment]
this is showing in the game: https://prnt.sc/OJVNEDvyujo-

the mod can only be used in online mode?


I zipped a video demonstrating the error: https://www.dropbox.com/scl/fi/2zqzp9uw1xu0bla1s1l84/video.zip?rlkey=0ee0csjt46jj860a0ve6gg91d&dl=0

yes i am on the latest version of all mods

there are no mod errors in the log
