### ISSUE TITLE
[Bug]: Latest FTB Quests update breaks JEI and crashes

### ISSUE THREAD

**Issue by AstraKurai** [FTBTeam/FTB-Mods-Issues#912]
### Mod

FTB Quests/JEI

### Mod version

ftb-quests-forge-1902.5.3-build.268

### Forge / Fabric version

43.2.14

### What issue are you having?

crash when looking for recipe / JEI not even showing up

### Crashlogs

https://hastebin.com/share/uyapecobak.scss

### Steps to reproduce

get JEI, get ftb quests

### Anything else to note?

e

**Comment by desht** [comment]
Same issue as #913, an update to FTB XMod Compat is coming.
