### ISSUE TITLE
[Bug]: REI freeze when looking at recipes

### ISSUE THREAD

**Issue by Zenthae** [FTBTeam/FTB-Mods-Issues#913]
### Mod

FTB Quests

### Mod version

ftb-quests-fabric-1902.5.3-build.268

### Forge / Fabric version

1.19.2 0.14.22

### Modpack & version

Statech Industry 1.1.7

### What issue are you having?

Game freeze when opening a recipe with REI, an error is thrown in the logs and roll backing to a previous rev (258 instead of 268) of FTB Quests fixed the issue

### Crashlogs

https://mclo.gs/iniyhi9

### Steps to reproduce

Click on any items to show its recipe

### Anything else to note?

I opened an issue on REI side too as I don't know exactly wish side is at the root of the issue.
https://github.com/shedaniel/RoughlyEnoughItems/issues/1481

**Comment by desht** [comment]
Fixed in FTB XMod Compat 1.2.2
