### ISSUE TITLE
Allow Distribution via CurseForge API

### ISSUE THREAD

**Issue by coryjreid** [FTBTeam/FTB-Mods-Issues#916]
### Mod

FTB XMod Compat

### Description

Currently this mod is unavailable via the CurseForge API. This prevents installation through the CurseForge Launcher or other tools which use the CurseForge API (such as Packwiz) to automatically download and install this mod. 

### Describe the solution you'd like

Check the box in the settings page of the mod on CurseForge to allow it to be available over the API.

### Describe alternatives you've considered

Manually downloading and distributing the JAR, which is not ideal for all parties.

**Comment by desht** [comment]
Sorry, but it's not FTB policy to make FTB mods available to third parties via the API.

**Comment by coryjreid** [comment]
@desht since when? 

Literally every other FTB mod (Ranks, Chunks, Teams, Library, …) are available this way.

**Comment by MichaelHillcox** [comment]
This was an oversight on my part, and des was going off information I provided. I do apologise. This has been fixed, sorry for the delayed response. @coryjreid

**Comment by coryjreid** [comment]
@MichaelHillcox understandable. Thanks for taking care of it!
