### ISSUE TITLE
[Bug]: Null pointer exception crashes server

### ISSUE THREAD

**Issue by hconhegg** [FTBTeam/FTB-Mods-Issues#920]
### Mod

FTB Chunks

### Mod version

ftb-chunks-forge:1902.4.1-build.290

### Forge / Fabric version

Forge 43.2.21

### Modpack & version

JCSMP Pack-1.3.3

### What issue are you having?

Ars novaeou spell turrets give a null value as player name. When you have ftbchunks set to allow certain fake users, it does not validate that the player name is not null leading to a null pointer exception crashing the server. So there is a missing null check in the `dev.ftb.mods.ftbchunks.data.ChunkTeamDataImpl#canFakePlayerUse`. One could argue that you should not set null as a value here in any mod, but there is also no reason to fail on a null pointer here instead of just denying the fake user access.

### Crashlogs

https://paste.feed-the-beast.com/view/d81f2fe8

### Steps to reproduce

1. create an ars novaeou spell turret with a breaking spell.
2. create a team and claim the chunk with the turret in
3. set 1 or more fake users in the team config "allow fake players by  Player ID"
4. give the turret redstone signal and watch it break something
5. ????
6. crash (see supplied logs).

### Anything else to note?

Do you accept pull requests? i could sumbit a fix instead of an issue.

**Comment by desht** [comment]
No need to do a PR, this will be fixed in the next release of Chunks...

**Comment by hconhegg** [comment]
Thank you :)
