### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by jaynotgay** [FTBTeam/FTB-Mods-Issues#923]
### Mod

FTBChunks

### Mod version

ftb-chunks-forge-2001.2.1.jar

### Forge / Fabric version

ftb-chunks-forge-2001.2.1.jar

### Modpack & version

ATM9

### What issue are you having?

Hi there.

Permission nodes no longer work with FTBranks with this version with FTBranks for claim chunk ammounts. They worked in the previous version ftb-chunks-forge-2001.1.5

Also the mod Create can be used to bypass FTBchunks claims to grief inside other claims.

### Steps to reproduce

Anything that moves can grief inside claims from the Create mod.

**Comment by jaynotgay** [comment]
Also some handheld items too. Like: "create:wand_of_symmetry"

**Comment by jaynotgay** [comment]
https://youtu.be/qReHE36gVIM

**Comment by desht** [comment]
As of 2001.2.0, you need to have the FTB XMod Compat mod installed for all cross-mod compat, same as in newer 1.19.2 releases of the mod.

If Create contraptions are able to grief FTB Chunks claims, that's something you need to raise with that mod.

**Comment by desht** [comment]
I should also note that FTB XMod Compat is part of ATM 9 as of 0.0.59: https://www.curseforge.com/minecraft/modpacks/all-the-mods-9/files/4724754

So I guess you tried to drop FTB Chunks into an older version of the pack?
