### ISSUE TITLE
[Bug]: FTB Quests Cannot Read Field_3944

### ISSUE THREAD

**Issue by greglor** [FTBTeam/FTB-Mods-Issues#924]
### Mod

FTB Quests

### Mod version

ftb-quests-fabric-2001.1.1

### Forge / Fabric version

1.20.1

### What issue are you having?

Whenever I open a world it says this-
![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/68510665/52268ba6-32a5-4305-bcac-d253fd8b4615)

And it's a singleplayer world so I don't really know. There's no crash report so I really can't get much more information.

### Steps to reproduce

1. Open a World
2. That's it

**Comment by DMJaxun** [comment]
Since this is already made I will not make a new thread but same issue on Forge.
![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/66274985/8c1dc591-b07c-4db1-83d6-08e8d79ecaee)

**Comment by MichaelHillcox** [comment]
Please attach your debug.log file

**Comment by greglor** [comment]
[latest.log](https://github.com/FTBTeam/FTB-Mods-Issues/files/12506235/latest.log)

this maybe

**Comment by DoubleAxeray** [comment]
same error....XD

**Comment by desht** [comment]
This one's hard to reproduce, but I think I see what's going on.  The quest book sync can come in before the local client player is fully initialised (yay multithreading), so deferring the creative tab rebuild following a sync should resolve the problem. Will make this change today, but testing is tricky due to the unpredictable nature of the problem.

**Comment by greglor** [comment]
Sounds good! Will there be a new release on curseforge with the fix or will we have to wait until another update comes out in the future?

**Comment by ukmcplyr** [comment]
In case it helps, I have a small instance (41 mods) where I can reproduce the forge version of this crash very reliably.

**Comment by desht** [comment]
There will be a new release very soon.

**Comment by desht** [comment]
New 2001.1.2 release out, should fix the issue:

Forge: https://legacy.curseforge.com/minecraft/mc-mods/ftb-quests-forge/files/4737935
Fabric: https://legacy.curseforge.com/minecraft/mc-mods/ftb-quests-fabric/files/4737934

**Comment by greglor** [comment]
Seems like it works! Tysm!
