### ISSUE TITLE
[Bug]: Cannot read field "field_3944" because "player" is null

### ISSUE THREAD

**Issue by DoubleAxeray** [FTBTeam/FTB-Mods-Issues#926]
### Mod

Ftb Team

### Mod version

fabric 2001.1.4

### Forge / Fabric version

0.14.22

### What issue are you having?

Some errors occurred which caused me to fail to connect when entering a single player game? maybe

java.lang.NullPointerException: Cannot read field "field_3944" because "player" is null

Thank u so much to whoever can provide any answer.

### Crashlogs

https://pste.ch/disoxesifu.md

### Steps to reproduce

1.Join single player game 
2.then ....

**Comment by MichaelHillcox** [comment]
Duplicate of #924

**Comment by DoubleAxeray** [comment]
> 
okey
maybe this log will help you to fine something
