### ISSUE TITLE
[Bug]: Jar Connection to Cobble Gen causes jar crafting to fail

### ISSUE THREAD

**Issue by coledamon** [FTBTeam/FTB-Mods-Issues#93]
### Mod

FTB Jar Mod

### Mod version

ftb-jar-mod-1605.1.0-build.31

### Forge / Fabric version

1.16.5-36.2.8

### Modpack & version

FTB Oceanblock 1.4.1

### What issue are you having?

When attempting to craft a cobble gen (Cobble for Days mod) using a jar (gens tier 3&4) in Oceanblock, if there is a cobble gen directly next to an output chest, and some form of connection to the jar system (even if it doesn't show connection(see pics below in reproduction)) of that cobble gen, the newly crafted cobble gen will not be placed in the chest, but materials will be consumed.

### Steps to reproduce

![Screenshot (300)](https://user-images.githubusercontent.com/44043262/138310815-52d56ac8-8ae8-4825-8d53-3804e6b4a452.png)
![Screenshot (299)](https://user-images.githubusercontent.com/44043262/138310883-ff7885fa-d527-4e23-8a28-e2fb3d56af86.png)

1. Set up the jar system as seen in either picture
2. Place items needed for crafting either tier 3 or 4 cobble gen in the chest
3. Click on the jar and attempt to craft the item
4. Check the chest and see there is no output

If the connection to the cobble gen is removed (see pic below), the crafting will now work
![Screenshot (301)](https://user-images.githubusercontent.com/44043262/138311134-791c1af3-2721-46f8-a709-589a6dc1e19e.png)

### Anything else to note?

Not sure if this is an issue with this mod or Cobble For Days, but I assumed here would be better because it looks like an issue with the pipe connectivity.

**Comment by Raidobw2** [comment]
I believe this was fixed in https://github.com/LexManos/CobbleForDays/pull/17 so I will close this issue since it should be resolved now
