### ISSUE TITLE
[Bug]: FTB Quests barrier block tooltip crash

### ISSUE THREAD

**Issue by LamaraFPS** [FTBTeam/FTB-Mods-Issues#930]
### Mod

ftb quests

### Mod version

ftb-quests-fabric-2001.1.3

### Forge / Fabric version

fabric 0.14.22

### Modpack & version

fabric 1.20.1

### What issue are you having?

game randomly crashed while rejoining my world

### Crashlogs

https://hastebin.com/share/xevedibojo.yaml

### Steps to reproduce

1. create a world
2. create some quests/change stuff etc
3. leave
4. rejoin

**Comment by desht** [comment]
https://github.com/FTBTeam/FTB-Quests/commit/42fb718aed0ed733c1252ff75155329e969382fe

**Comment by desht** [comment]
Fixed in 2001.1.4
