### ISSUE TITLE
[Bug]: Chunks crashing on world creation

### ISSUE THREAD

**Issue by Xplodin** [FTBTeam/FTB-Mods-Issues#932]
### Mod

FTB CHUNKS

### Mod version

ftb-chunks-forge-2001.2.1

### Forge / Fabric version

forge 47.1.3

### Modpack & version

custom modpack ft Connector mod

### What issue are you having?

create world with ftbchunks and connector mod w dependency 
crash while creating via ticking memory connection

### Crashlogs

https://gist.github.com/Xplodin/5bffe219c7315afe95ea1c4c38f252aa

### Steps to reproduce

above describes the steps and issue

### Anything else to note?

not really, besides that the pack boots fine but wont create a world

**Comment by desht** [comment]
This is a normally impossible situation - could only happen if the player logging out has no team (FTB Teams), and that should never happen (players are always assigned a team when they log in, a new team created if necessary).  I could work around the crash, but that would just mask the underlying problem.

* Does this happen when the server starts, or when someone logs out?
* Try it without the Connector mod.  Bridging Fabric plugins via mixins is a great way to destabilise your server.
* I need to see a copy of your server's debug.log, ideally when a new player (who hasn't connected to the server before) logs in.

**Comment by Xplodin** [comment]
[debug.log](https://github.com/FTBTeam/FTB-Mods-Issues/files/12591862/debug.log)
sorry for the wait, this is in singleplayer when the crash happens. Right when I create a new world

**Comment by desht** [comment]
This is a symptom of another problem, then. The "player logged out" event is being fired as you're trying to log in (on SSP world creation), meaning something has already gone wrong, and before your player could be added to a team.

I will fix the crash in FTB Chunks, but I don't believe it'll fix your entire problem.

**Comment by Xplodin** [comment]
thank you for the info and the crashfix.
Ill keep looking around to see how that event is being fired

**Comment by Xplodin** [comment]
After removing ftbchunks from the modpack for further testing I got invalid player data error.
that came from a payload being larger error which was solved with connectivity mod 

Hope this info helps

**Comment by desht** [comment]
Yeah, that would trigger the crash you saw in FTB Chunks. Glad you tracked the problem down.

There will be a new release of FTB Chunks today (just awaiting CF approval now) which fixes the crash (although if you've fixed the root cause of the problem, you won't see the crash anyway).
