### ISSUE TITLE
[Feature Request]: FTB Quests - Additional Command to Open/Switch to specific Quest (Id)

### ISSUE THREAD

**Issue by TheonlyTazz** [FTBTeam/FTB-Mods-Issues#936]
### Mod

FTB Quests

### Description

As discussed, a command (`/ftbquests open_book <quest_id>`) to open a specific quest

**potential Edge-Cases**
if no Questbook open, opengui and focus on that specific quest (potentially move chapter aswell?)
if Questbook open, close current quest if 1 is open and focus on specific quest

**Use-Cases**
Being able to open a Quest on interacting with something (Entity, Block etc)
Being able to bind in the command as an onClickEvent() inside the questbook description

**Comment by desht** [comment]
Added in latest 1.18/1.19/1.20 releases
