### ISSUE TITLE
[Feature Request]: Pause while reading quests

### ISSUE THREAD

**Issue by nageih** [FTBTeam/FTB-Mods-Issues#938]
### Mod

FTB Quests

### Description

The game pauses while the player who is in single player reads the quest.This gives players plenty of time to read the quests.

### Describe the solution you'd like

I think this is a simple, practical and easy to implement feature.This code might be useful for reference.
https://github.com/TeamMoegMC/FrostedHeart/blob/master/src/main/java/com/teammoeg/frostedheart/mixin/ftb/QuestScreenMixin.java

**Comment by desht** [comment]
Sure, I could get a feature like this into the 1.20 release.

**Comment by desht** [comment]
Added in 2001.1.4

**Comment by Turokirill** [comment]
Please add this function in 1.19.2. If it already exists, then it is strange that it does not work. I saw that there is a line "pause_game:" I set true, but the game is not paused.

**Comment by nageih** [comment]
@desht Maybe it's better to have this feature enabled by default? I think it's only beneficial for the players.
