### ISSUE TITLE
[Feature Request]: FTB Quests - Clickable links to quests by ID inside quest descriptions

### ISSUE THREAD

**Issue by loving2** [FTBTeam/FTB-Mods-Issues#940]
### Mod

FTB Quests

### Description

I'm writing quests and want to reference a previous quest in a different chapter as a reminder for how certain mechanics work. I think it would be nice for the player to be able to see that there is some text in the description like "See the `<Referenced Quest>` for a reminder!" that is a clickable link that opens that quest's view.

### Describe the solution you'd like

A clickable link with some optional hover text (to indicate that it is a clickable link or just add extra info) and display text so it doesn't look like a quest ID would be ideal. Snooping around the code I found [ClientTextComponentUtils](https://github.com/FTBTeam/FTB-Library/blob/dev/common/src/main/java/dev/ftb/mods/ftblibrary/util/client/ClientTextComponentUtils.java) which is where the open_url and image tags get turned into components, so I imagine it would get added here. What that code would look like I'm not sure though. Perhaps when writing the description it could look like `{open_quest:<id> text:<text> hoverText:<hoverText>}`

### Describe alternatives you've considered

The alternative I'm using in the meantime is to just be redundant and state the information again - this is not ideal for me as this particular piece of info applies in many scenarios

I also thought about trying to learn how to use KubeJS to write my own custom parser, but I'm not versed in using KubeJS enough to know how to really approach such a task.

**Comment by desht** [comment]
This is actually already possible, although not very well-documented (better documentation is something we're aware we need to get sorted).  You can do something like
```json
{ "text": "click me!", "clickEvent": { "action": "change_page", "value": "<quest_id>" } }
```
The `change_page` action is normally only used by vanilla in written books, but FTB Quests uses it for jumping to quests within the quest GUI.  The <quest_id> is the hexadecimal quest ID of the target quest; you can get this by right-clicking on the quest and selecting "Copy ID".

**Comment by loving2** [comment]
Interesting, it looks like if there is any other text on that line you get the `Invalid formatting! Can't nest multiple substitutes!` error. 

This works great, thank you! I can make the quest link just be on one line by itself no problem

**Comment by desht** [comment]
The line is a standard raw text JSON as used by vanilla, so you can append other elements or use a list of elements, e.g. 

`[ "text" : "hello - ", "text": "click me!", "color": "yellow" :"clickEvent": { "action": "change_page", "value": "<quest_id>" }, "text": " and some more text" ]`

https://minecraft.fandom.com/wiki/Raw_JSON_text_format

**Comment by christopherwalkerml** [comment]
> The line is a standard raw text JSON as used by vanilla, so you can append other elements or use a list of elements, e.g.
> 
> `[ { "text" : "hello - " } , { "text": "click me!", "color": "yellow" :"clickEvent": { "action": "change_page", "value": "<quest_id>" } }, { "text": " and some more text" } ]`
> 
> https://minecraft.fandom.com/wiki/Raw_JSON_text_format

Sorry to bring this back.. I'm actually trying to do exactly this, but it's still giving the invalid formatting error mentioned above.

I've pasted exactly this: `[ {  "text" : "hello - " }, { "text": "click me!", "color": "yellow" :"clickEvent": { "action": "change_page", "value": "<quest_id>" } }, { "text": " and some more text" } ]`

but no luck. Any ideas?

Thanks

**Comment by TomPlop** [comment]
That doesn't seem to work for me I get the same error even with your example.

**Comment by katubug** [comment]
Sorry for the necromancy, but I also can't get this to work. I'm on 1.21 though - does this no longer work? it says cannot nest multiple substitutes

**Comment by katubug** [comment]
Okay so I did manage to get it working by using ONLY this:

`[{"text": "Link Text", "clickEvent": {"action": "change_page", "value": "<QUEST ID>"}}]`

If I add ANY other arguments, such as color or other formatting, it breaks. If I add anything else to the line, it breaks. But if I do this and ONLY this, it works.
