### ISSUE TITLE
[Bug]: FTB Quests Edit_Mode Command ERROR

### ISSUE THREAD

**Issue by tenshi97** [FTBTeam/FTB-Mods-Issues#942]
### Mod

FTB Quest

### Mod version

ftb-quests-forge-2001.1.3

### Forge / Fabric version

1.20.1-47.1.47

### What issue are you having?

When I type in "/ftbquests edit_mode" it shows an error message
and when i replace the mod with older verion(2001.1.2) it just works
![QQ图片20230919011037](https://github.com/FTBTeam/FTB-Mods-Issues/assets/47095775/bac824db-f724-471e-bb85-4bc0ac2b16b9)

![QQ图片20230919011041](https://github.com/FTBTeam/FTB-Mods-Issues/assets/47095775/055b009d-2afe-4823-86ad-84591dd2ad73)

### Steps to reproduce

just command /ftbquests edit_mode

**Comment by MichaelHillcox** [comment]
Please attach logs
