### ISSUE TITLE
[Feature Request]: Mod compat with Ars Nouveau so ftb can protect entities better

### ISSUE THREAD

**Issue by HenrikoMagnifico** [FTBTeam/FTB-Mods-Issues#947]
### Mod

FTB Chunks

### Description

FTB cannot currently protect chunks from magic from ars nouveau, which makes it possible to players to grief and steal from protected chunks using ars spells and magic. Compat to fix this would be great!

### Describe the solution you'd like

Compatibility with Ars Nouveau so griefing is no longer possible using that mod

### Describe alternatives you've considered

Compat added either to FTB or to Ars Nouveau

**Comment by desht** [comment]
It's on Ars Nouveau to fire the appropriate Forge events when it's about to break blocks.
