### ISSUE TITLE
[Bug]: Server Crash after using /rtp command

### ISSUE THREAD

**Issue by Periphera** [FTBTeam/FTB-Mods-Issues#949]
### Mod

FTB Essentials

### Mod version

ftb-essentials-1802.2.2-build.83.jar

### Forge / Fabric version

1.18.2 40.2.9

### Modpack & version

Create:Arcane Engineering

### What issue are you having?

Added FTB Essentials to this pack. Default config settings. All commands work except /rtp. as soon as a player uses the command, the server times out.

### Crashlogs

[crash-2023-09-22_18.24.45-server.txt](https://github.com/FTBTeam/FTB-Mods-Issues/files/12703904/crash-2023-09-22_18.24.45-server.txt)

### Steps to reproduce

Bug is reproduced every time /rtp is executed by a player. 

Have played on another server with the same pack that includes FTB Essentials, and /rtp works fine. All other mods are the same.

**Comment by desht** [comment]
The servercore mod is known to break the /rtp command.  See #941 for an equivalent problem on 1.19.2.  Please try without this mod installed.

**Comment by desht** [comment]
Closing due to lack of response.
