### ISSUE TITLE
[Bug]: FTB Essentials : /home makes you look down

### ISSUE THREAD

**Issue by jinkhya** [FTBTeam/FTB-Mods-Issues#951]
### Mod

FTB essentials

### Mod version

ftb-essentials-forge-2001.1.2

### Forge / Fabric version

47.1.3

### What issue are you having?

When you run /home your character systematically looks down.

### Steps to reproduce

- Make an instance with ftb essentials and dependancies
- run /sethome
- run /home
You'll be looking at your feet :)

**Comment by desht** [comment]
Fixed in 2001.2.0 release
