### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by XenoPatrick** [FTBTeam/FTB-Mods-Issues#953]
### Mod

Forgematica

### Mod version

Forgematica-0.1.2-mc1.20.1.jar

### Forge / Fabric version

Forge 47.1.3

### Modpack & version

FTB Unstable 1.20: Forge

### What issue are you having?

Hello, first of all thanks for the FTB Unstable modpack ; it's been a lot of fun playing it. My goal was to add an litematica equivalent (so any other option you think might work better would be perfect) so i tried implementing Forgematica. After adding Forgematica-0.1.2-mc1.20.1.jar the game cannot launch anymore both with the beta and release file (even after removing the modfile).  The game needs to be backed up to an instance previous the mod installation. I've added some custom mods to the modpack but even disposing of those do not fix the crash. I figured Forgematica i quite experimental so it's probably a mod side problem. Thanks anyway for investing, have a good day.

Ps: i'm not an english native so please excuse the eventual mistakes.

### Crashlogs

https://pste.ch/isewocalis.md

### Steps to reproduce

1. Install the following custom mod i've added on my modpack (as said theire presence do not seem to impact the bug occuring)
2. Install Forgematica-0.1.2-mc1.20.1.jar (both beta and release file crashs the game)
3. Start the game and see it crash :/ (btw i'm only running 16Go but i don't think it matters)

### Anything else to note?

Thanks for the modpack and have a good day.

**Comment by MichaelHillcox** [comment]
Hi, this is not the correct place for modpack support. Upon this, sorry to say but we do not support modified versions of our modpacks.
