### ISSUE TITLE
[Bug]: Ftbessentials homes are not saving properly after a server restart

### ISSUE THREAD

**Issue by manugame** [FTBTeam/FTB-Mods-Issues#954]
### Mod

Ftbessentials

### Mod version

ftb-essentials-forge:1902.3.3-build.100

### Forge / Fabric version

1.19.2-43.3.0

### What issue are you having?

After restarting the server, homes add/delete are not saving properly.

### Steps to reproduce

- add a home
- restart the server
- add / delete a home
- disconnect then reconnect
- check if home was properly added/removed

**Comment by desht** [comment]
Confirmed, but actually already fixed in dev.  Will look to get a 1902.3.4 release out today.

**Comment by desht** [comment]
1902.3.4 released
