### ISSUE TITLE
[Bug]: FTB Essentials `/rtp` findblockpos() Server Performance Issue

### ISSUE THREAD

**Issue by Aiidoneus** [FTBTeam/FTB-Mods-Issues#957]
### Mod

FTB Essentials

### Mod version

ftb-essentials-forge-1902.3.2-build.85

### Forge / Fabric version

1.19.2-43.2.14

### Modpack & version

FTB AbePack 1.0.9

### What issue are you having?

Hello,
I am running several servers that use FTB Essential's `/rtp` command. Whenever someone runs this command, the server struggles a lot causing severe TPS dips. After running some profiles with spark, it looks like something weird is going on. Not sure exactly what is going on but maybe we can work together to solve this? 

![](https://i.imgur.com/vXxH59p.png)

If you need anymore information, I can provide it. 

### Crashlogs

N/A

### Steps to reproduce

Setup FTB AbePack and run `/rtp` and run profiles or see if the TPS dips?

**Comment by desht** [comment]
The `/rtp` command can cause a lot of worldgen to happen, by its very nature - it's searching for a random spot to teleport players, potentially thousands of blocks away, and potentially lag-inducing worldgen is triggered when it does that.  When it picks a random spot that can't be used, it will try again (recursively calling itself up to 100 times - but see `rtp_max_tries` config setting).

Reasons the spot can't be used:
* It's outside the world border radius
* It's an ocean biome of some kind
* It's in a chunk already claimed by someone using FTB Chunks, or some other mod is cancelling the RTP_EVENT that FTB Essentials fires when looking for a spot

Could any of these things be happening a lot on this server?

**Comment by desht** [comment]
What is your world border radius?

**Comment by desht** [comment]
While it might not solve your problem, I would recommend editing the config (`serverconfig/ftbessentials.snbt`) to reduce the max RTP radius to match your world border - look at the `min_distance` and `max_distance` values in the `rtp` section.

Looking again at the stacktrace, it appears the server CPU time is mostly within chunk generation itself (the call to the vanilla `getChunkBlocking()` method.  I'm honestly not sure what's happening on your server to make chunk generation so expensive, though.
