### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ThatsAsh** [FTBTeam/FTB-Mods-Issues#958]
### Mod

FTB Teams

### Mod version

ftb-teams-forge-1802.2.11-build.107

### Forge / Fabric version

1.18.2 40.2.10

### Modpack & version

Custom Modpack

### What issue are you having?

It seams with the mod Draconic Evolution, the game will crash while it starts. No other FTB mods seam to have this issue, as with FTB Teams and Chunks disabled, the modpack loads just fine.

### Crashlogs

https://pste.ch/aveyoripuw.php

### Steps to reproduce

1. Install mods, FTB Library, FTB Teams, FTB Chunks and Draconic Evolution
2. Launch game

**Comment by desht** [comment]
```
Failure message: Mod draconicadditions requires brandonscore 3.1.8.+ or above
		Currently, brandonscore is not installed
```

**Comment by ThatsAsh** [comment]
Even tho this is closed, I want to correct myself, as this does not actually produce a crash report. So I will give the log for my instance

https://pste.ch/seqoxowiri.pl

**Comment by desht** [comment]
That's the JVM itself crashing, and not relevant to FTB mods in any way.

**Comment by Natemo2625** [comment]
I get the same thing, with both FTB Chunks and Draconic Evolution enabled it'll crash. Asked about it on Draconic/Brandon's Core github, and they don't know why it's happening. They worked fine together in 1.16.5 so I'm not quite sure either.
