### ISSUE TITLE
[Bug]: Can't claim stage rewards

### ISSUE THREAD

**Issue by vizthex123** [FTBTeam/FTB-Mods-Issues#959]
### Mod

FTB Quests

### Mod version

ftb-quests-forge-1902.5.5-build.297

### Forge / Fabric version

43.3.2

### Modpack & version

Minecraft 1.19.2, custom modpack.

### What issue are you having?

I've added stage rewards using Game Stages to my modpack using the built-in "stage" reward the mod has, but it doesn't grant the stage.

It was a team reward, so I set it to be a normal one and that didn't fix it, and I directly copy/pasted the name from the CraftTweaker scripts that stage items so it can't be misspelled. Running the game stages info command says that I have no stages.

Screenshot of the reward's settings is attached.
![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/31721920/a25c8e96-2437-4ffe-bcfc-97f572c01ed0)

### Steps to reproduce

1. Set a quest reward to "stage" and have it grant whatever stage
2. Complete the quest and claim the reward

**Comment by desht** [comment]
Do you have the FTB XMod Compat mod installed?

**Comment by vizthex123** [comment]
> Do you have the FTB XMod Compat mod installed?

Didn't even know that was a thing. Odd that it didn't auto-install (I use the CurseForge app). Added it and it works fine.

Would be nice if FTB Quests told you that it was required. The mod page says it (so I guess it's technically my fault, lol), but I've never checked that since I've used FTB Quests so many times.

Why'd integration get split into its own mod though? Some kind of technical bugs?

**Comment by desht** [comment]
Yeah, there was a Discord announcement when it came out, and the CF page suggests it (and FTBQ logs a message if it's not installed).  But I appreciate it's not always possible to reach everyone.  I do see that it's a not a suggested dependency on CF right now, so I'll fix that for the next release.

We made the decision to split 3rd-party mod integration from FTB Quests and FTB Chunks to isolate API changes that we have no control over (like the KubeJS 6.0 -> 6.1 change) into one place.
