### ISSUE TITLE
[Bug]: Issue with Task Screen in FTB Quests (Version 1.19.2)

### ISSUE THREAD

**Issue by iFuuka** [FTBTeam/FTB-Mods-Issues#961]
### Mod

FTB Quests

### Mod version

1.19.2

### Forge / Fabric version

43.3.0

### What issue are you having?

Brief Description: The Task Screen lacks the ability to select quests that require specific items.

Full Description: In the quest selection menu within the Task Screen settings, there is an absence of any quests that require items such as cobblestone, a sword, saplings, or any other materials. Despite this, quests that require fluids or FE energy are accessible. Changing the game language did not yield any results. Reinstalling the mod with a clean game slate also failed to resolve the issue. Turning editing mode on and off likewise does not solve the problem. According to Discord chat logs, it appears that some players are experiencing a similar issue, and as of now, no solution has been found.

[Screen 1 Add quest](https://i.imgur.com/wm8zMuf.png)
[Screen 2 Trying to choose a quest](https://i.imgur.com/2D7VzwT.png)

[Creating a liquid quest](https://i.imgur.com/R7lGCoz.png)
[Choosing a liquid quest](https://i.imgur.com/s3V0FgO.png)

### Crashlogs

Not available as the bug does not cause the game to crash

### Steps to reproduce

Quest Creation: When attempting to create a quest for resource gathering, such as cobblestone or any other material.

Task Screen Settings: Navigate to the Task Screen settings to configure the created quest.

Quest Selection: Attempt to select the newly created quest.

Missing Quest: The quest is not present in the available options.

### Anything else to note?

The following mods are connected:
https://www.curseforge.com/minecraft/mc-mods/ftb-xmod-compat
https://www.curseforge.com/minecraft/mc-mods/ftb-quests-optimizer
https://www.curseforge.com/minecraft/mc-mods/teams-stages

**Comment by desht** [comment]
In your item task, make sure the "Consume Items" property is also set to true.  Ideally this would be true by default when "Only From Task Screen" is true, but at present it's necessary to set both of those to true.

**Comment by ajioe1111** [comment]
> In your item task, make sure the "Consume Items" property is also set to true. Ideally this would be true by default when "Only From Task Screen" is true, but at present it's necessary to set both of those to true.
> 
> Tasks must consume items to be eligible for Task Screen usage.

Setting Switching Consume Items to true indeed resolves the issue. Apparently, the default setting is False. This parameter is not very intuitive.

**Comment by desht** [comment]
The "default" setting means "use the chapter default".  And the default setting in chapters is false.  This allows configurability per-chapter if needed; I'm open to suggestions on making this more intuitive.

Forcing it to true for tasks which are marked as Task Screen Only is one thing I will investigate doing.

**Comment by ajioe1111** [comment]
There aren't clear instructions available. You have to memorize everything or rely on outdated guides. Perhaps some form of training, like a book, could help? Certain mechanics are quite perplexing, and a thorough study is necessary to grasp them.

**Comment by desht** [comment]
It's true documentation is lacking. There is an initiative to greatly overhaul the docs to all of our mods, so the situation will improve in the future.

**Comment by ajioe1111** [comment]
> It's true documentation is lacking. There is an initiative to greatly overhaul the docs to all of our mods, so the situation will improve in the future.

Another temporary solution is to post answers to questions on a website or discord server. 
It won't replace documentation, but in my case it would help a lot.
