### ISSUE TITLE
[Feature Request]: FTB Quests - /ftbquests change_progress Instruction optimization, add silent parameters (output does not indicate that a player's task has been completed)

### ISSUE THREAD

**Issue by luoxiawuchen** [FTBTeam/FTB-Mods-Issues#963]
### Mod

FTB Quests

### Description

**Example：**

/ftbquests change_progress @s complete 2063017B63797013 --silent

In silent mode, the player completes the task without sending a message prompt to the administrator.

**Comment by desht** [comment]
Where are running this command from?  It's possible there is a already a way of suppressing the command output...

**Comment by ShiYan2022** [comment]
> Where are running this command from? It's possible there is a already a way of suppressing the command output...

Console.  How to suppress it?

**Comment by ShiYan2022** [comment]
Not console output. When run this command, OP account will receive [Progress has been changed!] like below
![图片](https://github.com/FTBTeam/FTB-Mods-Issues/assets/116441541/86a20ddc-d1a4-47cd-9235-7aeb5cec0f03)

**Comment by desht** [comment]
Ah, I see.  The progress message is copied to all admins on the server right now.  I can see how that would be a problem - I will take a look at the best way to suppress this (it might be best just to suppress it completely, and not even require an extra command option - it isn't very useful to anyone other than the originator of the command).

**Comment by ShiYan2022** [comment]
Thank you for your patience.

**Comment by desht** [comment]
Fixed in 2001.1.6
