### ISSUE TITLE
[Bug]: FTB Essentials requires FTB Ranks version which does not exist

### ISSUE THREAD

**Issue by LlubNek** [FTBTeam/FTB-Mods-Issues#964]
### Mod

FTB Essentials

### Mod version

ftb-essentials-forge-1902.3.4-build.109

### Forge / Fabric version

mc 1.19.2 forge 43.2.23

### Modpack & version

ATM8 modified/updated

### What issue are you having?

FTB Essentials 1902.3.4-build.109 depends on a version of FTB Ranks which is not generally available (not on Curseforge).
It requires 1902.1.16-build.79
The latest version available is 1902.1.15-build.77

### Crashlogs

[latest.log](https://github.com/FTBTeam/FTB-Mods-Issues/files/12795044/latest.log)
[crash-2023-10-03_12.39.48-fml.txt](https://github.com/FTBTeam/FTB-Mods-Issues/files/12795051/crash-2023-10-03_12.39.48-fml.txt)

### Steps to reproduce

install FTB essentials and it's dependencies from curseforge.  Start minecraft. Observe errors.

**Comment by desht** [comment]
There was a CF publication problem for the updated FTB Ranks, sorry.  Getting that sorted now.

**Comment by desht** [comment]
Ranks 1902.1.16 is now published, which will work fine with the latest Essentials.
