### ISSUE TITLE
[Bug]: Items vanishing when right clicking claims

### ISSUE THREAD

**Issue by Flnchie** [FTBTeam/FTB-Mods-Issues#965]
### Mod

FTB Chunks

### Mod version

 2001.1.4

### Forge / Fabric version

Fabric 1.20.1

### What issue are you having?

When right clicking blocks within a claim (including the ground) the item(s) vanish from my inventory.

### Steps to reproduce

Holding any item and right clicking within a claim makes the item vanish from your inventory.

**Comment by desht** [comment]
Confirmed, although it's just a client desync - the item isn't really gone (opening your inventory and clicking on the item will pick it up).
