### ISSUE TITLE
[Bug]: FTB Quests - Task Screen + Energy Quest Crashes Game Repeatedly

### ISSUE THREAD

**Issue by Viking790** [FTBTeam/FTB-Mods-Issues#967]
### Mod

FTB Quests

### Mod version

ftb-quests-forge-2001.1.5

### Forge / Fabric version

1.20.1 47.1.3 

### Modpack & version

ATM9 0.1.12

### What issue are you having?

When placing down a Task Screen attached to an energy providing pipe, then trying to submit energy to a quest, the game crashes repeatedly for the user who's interacting with the Task Screen. Issue is repeatable, as other users on the server have had the same issue happened. Solved by world edit deleting the block(s) on a server, or loading a backup in singleplayer for now.

### Crashlogs

https://pste.ch/joneroroke.pl

### Steps to reproduce

Place down a task screen, connect an energy providing pipe (I used Mekanism, I believe another player used Pipez). Open the task screen, and click a quest that requires energy. Game crashes, and upon re-logging user crashes again in less than 10 seconds.

**Comment by desht** [comment]
Fixed in 2001.1.6 release
