### ISSUE TITLE
[Feature Request]: FTB Quests - Quest Favorites Bar feature (quickly locate frequently used tasks)

### ISSUE THREAD

**Issue by luoxiawuchen** [FTBTeam/FTB-Mods-Issues#968]
### Mod

FTB Quests

### Description

This is mainly for some repeatable tasks, or when there are too many goals in the current branch, you can choose a quest/task according to the player's own preferences, add it to favorites (similar to JEI mod), click it to quickly jump to the current task (or open the corresponding task interface)

Feature Request Summary:
Add a Quest favorites that users can bookmark tasks they use frequently or want to complete.

Thank you for your patience in reading.

**Comment by desht** [comment]
That's what the pinned quests feature is for.  Players can already pin quests that they want to track.
![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/736831/7befcda2-51a0-4e2e-9a09-bb35ab2d5369)

**Comment by luoxiawuchen** [comment]
> That's what the pinned quests feature is for. Players can already pin quests that they want to track.
> 
> ![image](https://user-images.githubusercontent.com/736831/272893980-7befcda2-51a0-4e2e-9a09-bb35ab2d5369.png)

Thank you for your patience.
