### ISSUE TITLE
[Bug]: FTB Ranks Does not handle permission nodes properly.

### ISSUE THREAD

**Issue by SilverScythe64** [FTBTeam/FTB-Mods-Issues#974]
### Mod

FTB Ranks

### Mod version

ftb-ranks-forge-2001.1.3.jar

### Forge / Fabric version

1.20.1 Forge - 47.1.3

### What issue are you having?

For example, I am trying to make a rank that has the permission to use:
"/gamemode survival" & "/gamemode "spectator"

I only want the rank to be able to use these two commands, and only be able to target themselves with it.
These are the possible nodes for the command:

command.gamemode
command.gamemode.adventure
command.gamemode.adventure.target
command.gamemode.creative
command.gamemode.creative.target
command.gamemode.spectator
command.gamemode.spectator.target
command.gamemode.survival
command.gamemode.survival.target

If I make a "test" rank and give it the permissions:
"command.gamemode.spectator true" & "command.gamemode.survival true"

I expect the rank to be able to use "/gamemode survival" & "/gamemode spectator" and nothing else, because I excluded every other node, and specified exactly which nodes I wanted.

However, this does not work.

It seems that the only node that actually functions is "command.gamemode" 

If it is excluded from the permissions, you have access to nothing.
If it is included in the permissions, then you have access to every node that stems from it.

None of the other nodes seem to matter when being added as FTB Rank permissions.

### Steps to reproduce

Do:

/ftbranks create test 100

/ftbranks add YourUsername test

/ftbranks node add test command.gamemode.survival true

/ftbranks node add test command.gamemode.spectator true

De-op yourself, and relog.

Try using the gamemode commands you just gave yourself access to.
You will find that they do not work...

Re-op yourself, and do:

/ftbranks node add test command.gamemode true

De-op / relog / try the gamemode commands again.
You will find that you have access to everything, including the nodes you did not want access to.

Re-op yourself and do:

/ftbranks node add test command.gamemode.adventure false

/ftbranks node add test command.gamemode.adventure.target false

/ftbranks node add test command.gamemode.creative false

/ftbranks node add test command.gamemode.creative.target false

/ftbranks node add test command.gamemode.spectator.target false

/ftbranks node add test command.gamemode.survival.target false

De-op / relog / try the gamemode commands again.
You will find that you still have access to every node, even though you specified which nodes you do not want.

Re-op yourself and do:

/ftbranks node remove test command.gamemode

De-op / relog / try the gamemode commands again.
You will find that you no longer have access to any of the nodes.

**Comment by desht** [comment]
`command.gamemode.survival` and `command.gamemode.spectator` are not command nodes at all.

The only relevant command nodes here are `command.gamemode` and `command.gamemode.target`; `survival` and `spectator` are arguments to the `/gamemode` command, not nodes in their own right.  So what you're trying to do here isn't workable, sorry.
