### ISSUE TITLE
[Bug]: Item tooltip is not displayed

### ISSUE THREAD

**Issue by MrHimera** [FTBTeam/FTB-Mods-Issues#988]
### Mod

FTB Quests

### Mod version

ftb-quests-forge-2001.1.7

### Forge / Fabric version

Forge 1.20.1 47.2.1

### What issue are you having?

The item tooltip is not displayed in quest rewards if you do not specify a name for the reward (there is just an empty tooltip).

### Steps to reproduce

1. Create any quest
2. Select a reward any item
3. Look at the item tooltip in the quest

**Comment by MrHimera** [comment]
Can you also add a description of the item to the tooltip?

**Comment by desht** [comment]
Fixed in 2001.2.0 release
