### ISSUE TITLE
[Feature Request]: Quest Dependencies "OR" condition

### ISSUE THREAD

**Issue by blsimpson** [FTBTeam/FTB-Mods-Issues#989]
### Mod

FTB Quests

### Description

To my knowledge, there is no way to have a quest line unlocked by completing one of multiple dependencies.

What I am trying to create is a way for the player to select one of two quest lines at the start, but then also unlock the second when the first quest line is complete.

### Describe the solution you'd like

Allow an OR condition in dependencies that allows the player to unlock quest lines by completing one or the other

### Describe alternatives you've considered

Using outside mods, including Game Stages, to kind of create a "hacky" solution

**Comment by desht** [comment]
This is already a feature: set the "Min Required Dependencies" property of the quest to a number other than 0. As per the tooltip on the property in the quest config screen:

```
If you set this to anything more than 0, it becomes an OR quest, where only certain amount of dependencies is required for it to unlock
```

**Comment by blsimpson** [comment]
You're awesome. Thank you for this. I guess I wasn't looking hard enough.
