### ISSUE TITLE
[Bug]: Deletion doesn't work

### ISSUE THREAD

**Issue by MrHimera** [FTBTeam/FTB-Mods-Issues#990]
### Mod

FTB Quests

### Mod version

ftb-quests-forge-2001.1.7

### Forge / Fabric version

Forge 1.20.1 47.2.1

### What issue are you having?

Deleting a chapter and a group of chapters in the list on the left does not work. Visually they are deleted, but when you reboot they return.

### Steps to reproduce

1. Create a chapter on the left in the list
2. Delete chapter 
3. Re-enter the world
4. See that nothing has been deleted

**Comment by desht** [comment]
Fixed in 2001.2.0 release
