### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by BluberryPlay** [FTBTeam/FTB-Mods-Issues#991]
### Mod

FTB C

### Mod version

ftb-chunks-forge-1902.4.2-build.302.jar

### Forge / Fabric version

1.19.2 40.3.0

### Modpack & version

N/A 

### What issue are you having?

Hi. Ive noticed players on my server, are able to unclaim other peoples chunks, allowing them to claim that chunk for themselves. which something I don't like happening, as it opens up to pvp. and grieving purposes of happening on my server. 

by any chance is this able to be resolved.

the log below, is a test server of me and my friend testing to see if we can fix it. 

### Crashlogs

https://pste.ch/aqisobajan.sql

### Steps to reproduce

so I claim a chunk. and then an other player, (my friend in this instance) is able to unclaim the chunk I claimed. and then claim it for herself. Im unsure if im doing something else, or doing something wrong.

**Comment by desht** [comment]
Is your friend a server op, i.e. has permission level >= 2?

FTB Chunks does not normally allow players to unclaim each other's claims, unless the player is a server admin.

**Comment by BluberryPlay** [comment]
no players are at the regular, which I believe a permission level 0 or 1. myself and the owner, are permission levels 4 and 5. so I know we are able to. but members are able to though. being at a low level as a 0 and 1. 

Ive
