### ISSUE TITLE
[Bug]: Crash on clicking chunks on inventory UI

### ISSUE THREAD

**Issue by kurtramone** [FTBTeam/FTB-Mods-Issues#999]
### Mod

FTB Chunk?

### Mod version

ftb-chunks-forge-1902.4.2-build.302

### Forge / Fabric version

Forge 43.3.2

### Modpack & version

Custom

### What issue are you having?

Any idea on what could cause a crash when you click chunk in your inventory UI?

### Crashlogs

https://paste.feed-the-beast.com/view/32bb98dc

### Steps to reproduce

Open Inventory UI
Click FTB Chunk on top left

### Anything else to note?

Nope

**Comment by Prilychnuy** [comment]
I have the same problem

**Comment by UnRealDinnerbone** [comment]
Please upload a new crash report if this issues still exists

**Comment by kurtramone** [comment]
Hello. I just logged in, could not make it crash anymore. But since then updated the mod, forge itself, and I even changed my hardware, so I don't know what to say.

**Comment by desht** [comment]
OK, closing for now. Please reopen or raise a new issue if you see a repeat of the problem.
